### ISSUE TITLE
[BUG]Bottomless Trap Hole Bug

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#1049]
1. When "Convulsion of Nature" is on the field and you summon "Evilswarm Salamandra". Right after you summon it, you actiavte "Infestation Infection" and send that monster for cost. The monster send to the deck and u Chain the "Bottomless Trap Hole". The monster in your deck is destroyed and banished.

2. Same goes on Pendulum monster. You nomal summon Pendulum monster, activate "Turnover Soul", the monster would be send to Extra deck in face-up, Chain, "Bottomless Trap Hole", Pendulum monster in extra deck would be destroyed and banished.

**Comment by salix5** [comment]
45d20023fbde7655b2c622d30dd969ce4b2d5c7d
fixed
