### ISSUE TITLE
CXyz Barian Hope + Number 86: Heroic Champion - Rhongomiant

### ISSUE THREAD

**Issue by Steeldarkeagel** [Fluorohydride/ygopro#1067]
If CXyz has taken 86's effect, during your opponents End Phase you should be able to resolve CXyz's effect stealing before 86's detach effect. At the moment CXyz will always detach and then lose it's extra effects.

Ｑ：このカードが《Ｎｏ.８６ Ｈ－Ｃ ロンゴミアント》をコピーした場合、相手エンドフェイズ時にどちらの効果が優先されますか？
Ａ：このカードの効果を先に処理する事ができます。
　　先にこのカードの効果を処理した場合、《Ｎｏ.８６ Ｈ－Ｃ ロンゴミアント》の効果を得ていない状態になりエクシーズ素材を取り除く必要はありません。(14/09/22)
Taken from: http://yugioh-wiki.net/?%A1%D4%A3%C3%A3%D8%20%D1%C3%CB%BE%B9%C4%A5%D0%A5%EA%A5%A2%A5%F3%A1%D5

**Comment by salix5** [comment]
fc97dc3cf9f0816a8954714595409b755b3d6e49
7e9657c9f1a5a08e64914c2878424a2ea25b81c0
Basically fixed.
