### ISSUE TITLE
Ygo file

### ISSUE THREAD

**Issue by Chahine2** [Fluorohydride/ygopro#1068]
Where can i find this file?i don't seem to find it anywhere in the source

**Comment by Zayelion** [comment]
Can you be more specific to what you are looking for, and why?

**Comment by Chahine2** [comment]
i was following this https://gist.github.com/adrianojn/68b6f48ac5b2377ab1c2
to compile a ygopro exe file, it says: Open the file ygo with Visual Studio, the file is on build folder
i can't seem to load ygo folder in this open source

**Comment by salix5** [comment]
https://github.com/soarqin/ygopro
First you need premake4 or cmake.

**Comment by Zayelion** [comment]
put premake4.exe in your `c:\windows` directory, then go to the `ygopro` directory, `premake4 vs2010` it will create a folder at `ygopro\build\` you then want to open `ygopro\build\ygo.sln`.

**Comment by Chahine2** [comment]
do i launch it from windows directory? i can't find premake4 vs2010

**Comment by Zayelion** [comment]
**Adds this line of conversation to a case study in the importances of accurate and idiot-proof documentation*

No Press `[winkey-r]` (aka Run) type `CMD` then `[enter]`, a black console will pop up. I suggest you get intimately familiar with this application. Go back to the `ygopro` folder and COPY the directory location. 

C:\blah\blah\blah\la-blah\ygopro. 

Go back to CMD type `cd ` note the space; right click click paste then press `enter`, type `premake4 vs2010` then press `enter`

**Comment by Chahine2** [comment]
ah, it worked, thanks
