### ISSUE TITLE
This keeps appearing when i try to compile Ygo's files

### ISSUE THREAD

**Issue by Chahine2** [Fluorohydride/ygopro#1069]
![887](https://cloud.githubusercontent.com/assets/6339408/5686447/24619820-9843-11e4-8e1f-3cbf9843af33.PNG)
Whenever i try to compile the files within ygopro's engine, this prudently shows up
any help?

**Comment by anshkumar** [comment]
Are you using visual studio 2010 ?

**Comment by Buttys** [comment]
Looks like you might be missing the dependencies(freetype, lua ect) since this git dosnt supply them for you but are included in the premake file, this project should be able to compile on any visual studio version 2010++ i rember compiling it on 2012 a few times.

**Comment by anshkumar** [comment]
v100 means Visual C++ 2010
v110 means Visual C++ 2012
v120 means Visual C++ 2013
So either you change the project settings to use toolset v100, or you install Visual Studio 2010 on this machine.

**Comment by Chahine2** [comment]
That solved, but i got 6 other errors after the compile operation.
![szqqz](https://cloud.githubusercontent.com/assets/6339408/5695329/e00aae22-999c-11e4-9de2-b4dc7afa5e4d.PNG)

**Comment by salix5** [comment]
Irrlicht needs DirectX SDK, and you can download this from Microsoft website.

**Comment by Chahine2** [comment]
I downloaded that already, it's version 2010

**Comment by salix5** [comment]
Try to check the include directory of Irrlicht then. Maybe you need to add the path of DirectX SDK manually.

**Comment by Zayelion** [comment]
^_^ The SDK needs to be included properly into the project. http://takinginitiative.wordpress.com/2010/07/02/setting-up-the-directx-sdk-with-visual-studio-2010/

There is a lib directory, and something else I forget that needs to be included into the project.

You know it would be polite to have the system automaticly try to include this stuff via premake or something,... or have formal instructions somewhere.

**Comment by Chahine2** [comment]
Okay, i Followed them step by step, and i'm still having the same errors.
![szaq](https://cloud.githubusercontent.com/assets/6339408/5695876/31e4bbde-99b6-11e4-894b-a350c99af58d.PNG)

**Comment by Buttys** [comment]
make sure you add the directx include and libs to the irrlicht project and not the ygopro one

**Comment by Chahine2** [comment]
I've done that, and it still listing these errors.
![7784](https://cloud.githubusercontent.com/assets/6339408/5703102/332a1244-9a62-11e4-890b-c3e50c6f3871.PNG)

**Comment by Buttys** [comment]
can you drop us a screenshot of your include and lib dirs, them files are apart of directx

**Comment by Chahine2** [comment]
![zeaz](https://cloud.githubusercontent.com/assets/6339408/5705227/f0bdc1ba-9a77-11e4-9d8c-b704550e48d7.PNG)
![ezzez](https://cloud.githubusercontent.com/assets/6339408/5705235/041b0f38-9a78-11e4-95a2-9381b3955b41.PNG)
![dee](https://cloud.githubusercontent.com/assets/6339408/5705242/13c89e5a-9a78-11e4-864d-ba90acf66258.PNG)
![yyyyyyyyy](https://cloud.githubusercontent.com/assets/6339408/5705250/22f81b3a-9a78-11e4-906a-bb4e751833aa.PNG)
![Uploading 8e7z.PNG . . .]()

**Comment by Buttys** [comment]
was refering to the part you change in visual studio sorry about that :x

**Comment by Chahine2** [comment]
ah
![az](https://cloud.githubusercontent.com/assets/6339408/5705654/3b9eb524-9a7b-11e4-8da2-e5c3bbc4ae36.PNG)
![aazzz](https://cloud.githubusercontent.com/assets/6339408/5705657/3ecf80fc-9a7b-11e4-853e-f81b14b99927.PNG)
No problem ;)

**Comment by Buttys** [comment]
in the lib dir select the x86 folder since you'll be compiling it in 32bit and give it another try

**Comment by Chahine2** [comment]
Same
![zeza](https://cloud.githubusercontent.com/assets/6339408/5706002/a80ee02e-9a7d-11e4-99a5-11ae6992627d.PNG)

**Comment by Buttys** [comment]
I think i understand where you are going wrong now, looks like you might of been editing the wrong properties, make sure you right click Irrlicht in the solution explorer and not the property manager and add them directx includes and libs(using x86 dir) to the VC++ Directories like you've been doing

just compiled it myself using vs2012 to double check

http://i.imgur.com/H1L6mIv.png

**Comment by anshkumar** [comment]
Why don't you use Fedora or Ubuntu, if you want to develop?

**Comment by Zayelion** [comment]
Because they are developing for users not developers.

**Comment by Chahine2** [comment]
![deeez](https://cloud.githubusercontent.com/assets/6339408/5709496/ac2f6fb2-9a9a-11e4-9f72-2e99bc489dbe.PNG)
More errors, Geez!

**Comment by Buttys** [comment]
have you tryed rebuilding the project again using premake4? to remove all them changes you added to the project that might effect the build?

Small run down on what i did to compile the project 
- Clone git
- Copy Dependencies files to the ygopro folder
- Use cmd to run premake4 vs2010
- Open up ygo file in the build folder with vs2012 and upgrade the project
- Add directx include and libs to the irrlicht poject
-(Optional) Set ygopro as the start up project
- Compile

**Comment by Chahine2** [comment]
Git and Dependencies, where do i find them?

**Comment by Zayelion** [comment]
https://github.com/Buttys/ygopro

**Comment by Chahine2** [comment]
Thank You Guys :)
It's also weird when it worked only with Buttys' Engine.

**Comment by Zayelion** [comment]
What are you developing anyway?

**Comment by Chahine2** [comment]
An independent Ygopro that Features More than just Custom cards, it would also include other Custom frames and races..

**Comment by Zayelion** [comment]
This cant be accomplished by editing strings.conf and cards.cdb along with the lua scripts?

**Comment by Chahine2** [comment]
Wait, isn't by editing Card.h file?

**Comment by Buttys** [comment]
You must edit ygopro to have custom frames and stuff, adding custom races is abit more complex than simply adding them to the strings.conf and cdb.

For the record my version is 4 months out of date since i stopped working on ygopro tho you can proberly just copy ocgcore from this project to bring it up to date depending on changes made to the cards and stuff.

**Comment by Chahine2** [comment]
I just edited card.h from ogcore, how to make them visible that way?

**Comment by Chahine2** [comment]
![eza](https://cloud.githubusercontent.com/assets/6339408/5712872/56dac720-9ab6-11e4-969f-e4c451f2e1c7.PNG)
Sorry for Double Post, But Is this how it go when i add a custom race? i mean, i edited the file card.h in ogcore's directory.

**Comment by Zayelion** [comment]
I was thinking more along the lines of renaming the races to replace existing ones. Not extend the current types.

**Comment by Chahine2** [comment]
but, i they are treated as the old race :o

**Comment by Zayelion** [comment]
Thats not really what I was getting at but good luck to you.

**Comment by Chahine2** [comment]
Ah, thanks
