### ISSUE TITLE
Miracle Synchro Fusion and Noden Bug

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#1070]
This card[Elder God Noden] can be Fusion Summoned with "Miracle Synchro Fusion". In this case, you must have at least 1 Synchro Monster in your Graveyard or your side of the field to perform the Fusion Summon. Therefore, if you Fusion Summon "Elder God Noden" with "Miracle Synchro Fusion", you can use either 2 Synchro Monsters or 1 Synchro Monster and 1 Xyz Monster. (You cannot Fusion Summon "Elder God Noden" with "Miracle Synchro Fusion" using 2 Xyz Monsters.)[7]

But in Ygopro, you can Fusion Summon "Elder God Noden" with "Miracle Synchro Fusion" using 2 Xyz Monsters.

**Comment by salix5** [comment]
45d20023fbde7655b2c622d30dd969ce4b2d5c7d
fixed
