### ISSUE TITLE
[BUG]Artifact Durendal Critical Bug!

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#1075]
When monster effect is activated, change its effect with "Artifact Durendal". After that, monster is destroyed and revived with "monster reborn". while your opponent controls spell/trap card, that monster's effect is still "Destroy 1 Spell/Trap Card your opponent controls".

**Comment by salix5** [comment]
Do you have a replay file?

**Comment by salix5** [comment]
d26fd7479438173ff9b04c57a7b7ac5f6a6a1479
fixed

**Comment by treepiece** [comment]
ty

**Comment by salix5** [comment]
No, thank you

**Comment by treepiece** [comment]
please check out the other bugs that i have reported~
