### ISSUE TITLE
Checking for Special summons in the turn doesn't work

### ISSUE THREAD

**Issue by ChibiChanNya** [Fluorohydride/ygopro#1092]
Using your script for Core, Pot of Duality from here. Allowed to special summon and THEN play Duality. Error affects other similar cards, such as "Cards for Black Feathers" and "Cardcar D"

**Comment by Zayelion** [comment]
Configuration used :
- ocgcore as ocgcore.dll with Buttys/YGOCore, server side client with other ygopro's connecting. Server side ocgcore renders bug after updating to current codebase here at fluorohydride/ygopro

**Comment by Tianchenglipu** [comment]
Script is updated but programme has not. Unupdated programme does not support the new codes for such effects. It will do after updated.

**Comment by Zayelion** [comment]
We always build from current source code for our servers before adding bugs. It seems to be resolved now.
