### ISSUE TITLE
[Bug?] Fusion and checking hand

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#1093]
-効果解決時に融合可能な組み合わせが存在しない場合、不発となる。
この時、相手が要求したならば手札とエクストラデッキを公開し、自分が融合召喚を行えないことを証明しなくてはならない。

which means that, 
1. You activate "Shaddoll Fusion" while your opp controls monster that was Special Summoned from the Extra Deck
2. Chain "Compulsory Evacuation Device" to return that monster,
3. As a result, you cannot fusion summon any monster
4. In that case, your opp can check your hand and Extra in order to prove that you cannot fusion summon any monster.

But in ygopro, cannot check the hand or extra......

**Comment by salix5** [comment]
c9d2a1a0bae49080396e81037091927b026fe4fc
fixed
Thank you.
