### ISSUE TITLE
[Bug?] [string"./script/c21007444.lua"]:62: attempt to indec local 'g' (a nil value)

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#1094]
Activate "Double-Edged Sword Technique", and syncro summon "Legendary Six Samurai - Shi En" using that monsters. At the end of this turn, this massage is shows up  [string"./script/c21007444.lua"]:62: attempt to indec local 'g' (a nil value)
Everything is working find but that red massage seems not natural for me.

Situation: Activate "Heavy Strom" -> Chain "Starlight Road" -> Chian "Double-Edged Sword Technique" -> summon 2 "Six Samurai" monsters -> "Heavy Strom" is negated and "Stardust" comes up -> Syncro summmon "Legendary Six Samurai - Shi En" -> during end phase, that red massage pops up

(nothing wrong but seems not good)

**Comment by salix5** [comment]
Do you have a replay file?

**Comment by treepiece** [comment]
https://drive.google.com/file/d/0B5eVShx7b140QlpIQTZVZzM4MG8/view?usp=sharing

Starts at turn 9

**Comment by salix5** [comment]
05427e083484c084930f972f9702913bd2ebc4f1
fixed
Thank you.
