### ISSUE TITLE
[Bug] Nekroz Cycle

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#1095]
遊戯王OCG事務局です。

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。

Q.
フィールド上に《王家の眠る谷－ネクロバレー》が存在するときに、《影霊衣の反魂術》の効果で 墓地の儀式モンスターを儀式召喚できますか？
A.
「王家の眠る谷－ネクロバレー」の効果が適用されている限り、『墓地のカードに効果が及ぶ魔法・罠・効果モンスターの効果は無効化』されます。
したがって、墓地にしか儀式召喚できる儀式モンスターしか存在しなければ、「王家の眠る谷－ネクロバレー」の効果がある限り、「影霊衣の反魂術」の『①』の効果の発動自体ができません。

!You cannot ritual summon "Nekroz" monster in graveyard while there are "Necrovalley" is on the field.

**Comment by nekrozar** [comment]
fixed 17c11ecdb70104c4acf5d9e58c6a8845ac88ccb6
