### ISSUE TITLE
Remove Brainwashing vs Forbidden Lance(And other trap immunity)

### ISSUE THREAD

**Issue by Steeldarkeagel** [Fluorohydride/ygopro#1138]
If a card such as Volcanic Queen is Special Summoned to my opponents side of the field and then later Remove Brainwashing is activated and Forbidden Lance is chained to it. Volcanic Queen will change control after Remove Brainwashing resolves, but it should wait until the End Phase when Forbidden Lance wears off.

《禁じられた聖槍》の効果を受けたモンスターは、このカードの効果で元々の持ち主のフィールドに戻りますか？
エンドフェイズまではコントロールは戻りません。

Google Translate:
Monster that has received the effect of "forbidden Holy Lance", or return to the field of the original owner by the effect of this card?
Until the End Phase is does not return control.

**Comment by nekrozar** [comment]
In the case of such a situation, Volcanic Queen, Lava Golem, Santa Claws, and so on does not return control.

Mail:
遊戯王OCG事務局です。

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。

Q.
「サタンクロース」を相手フィールドに特殊召喚した後に「洗脳解除」を発動、それにチェーンして「サタンクロース」を対象に「禁じられた聖槍」を発動しました。
この場合、「サタンクロース」のコントローラーは自分に移りますか？
A.
ご質問の状況の場合、「禁じられた聖槍」の効果が先に適用されますので、「洗脳解除」の効果は受けません。
したがって、コントロールは戻りません。

これからも遊戯王オフィシャルカードゲームをはじめ、コナミの商品をよろしくお願い申し上げます。
