### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1143]
The thumbnails for the system are redundant. High resolution pictures are provided with variants of this software, why not remove them?

**Comment by Zayelion** [comment]
Bumping, @Fluorohydride @salix5 @IceYGO @woodee @VanillaSalt can we remove thumbnails now, or can I get an update on the difficulty, or even why this is in the system?

**Comment by IceYGO** [comment]
Loading 7000 thumbnails is faster and requires less memory than loading 7000 high-resolution cards.
It's especially useful for the deck editor where one can easily scroll though a thousands of pictures in a few seconds.

**Comment by Zayelion** [comment]
I dont feel it justifies the additional disk space used, especially in production. It basically increases by 33%  the number of files that need to be created, and bandwidth used by end users and server owners. It isnt a "noticeable" performance increase, and does more harm than good.

**Comment by mercury233** [comment]
If window sizing is added, thumbnails may be useless.
