### ISSUE TITLE
Some CROS card bug (Zefra saber and Snatch Steal)

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1147]
there's 2 bugs in your scripts....

1. About Zefra Saber and Nekroz of sophia...
Zefra Saber ca't SSed Sophia bi treat him asa a Ritual Effect (I can;t Tribute it from Hand OR Field to Ritual Summon Sophia) Although I already has 3 monster on the field with 3 different Types and total level 11...
post by steeldarkeagle :

Q.
剣聖の影霊衣－セフィラセイバー 特殊召喚に ｓｏｐｈｉａの影霊衣?
A.
「剣聖の影霊衣－セフィラセイバー」の効果で、「sophiaの影霊衣」を儀式召喚する事はできます。
ただし、『それぞれ種族の異なる自分フィールドのモンスター３体を使用』して、手札から儀式召喚します。

Q.
KenKiyoshi of Kagereikoromo - Sefira Saber and Kagereikoromo of sophia to special summon?
A.
"KenKiyoshi of Kagereikoromo - Sefira Saber" in effect, you can be summoned ritual to "Kagereikoromo of sophia".
However, by "using a monster three-body of your field of different races each," and then ritual summoned from your hand.

http://www.ygopro.co/Forum/tabid/95/g/posts/t/17685/Zefra-Saber-and-Nekroz-of-Sophia

2. About Snatch Steal and Caiser Colloseum
Was not able to take opponent's monster via Snatch Steal nor Falling Down while Kaiser Colosseum was active.
I've checked the OCG rulings, and this isn't mentioned.
An old TCG rulings says "Your opponent cannot use "Monster Reborn", "Scapegoat", etc. while "Kaiser Colosseum" prevents him from placing new monsters. However, your opponent CAN use "Change of Heart", "Snatch Steal", etc."
And, to me, "place a monster on the field" does not apply to monsters which are... already on the field.

Post by steel :

Q.
自分の「カイザーコロシアム」の効果が適用中、お互いにモンスターが1体ずつ存在する状態で、モンスターのコントロールを得られますか？
A.
「カイザーコロシアム」の効果が適用中でも、お互いに対戦相手のモンスターのコントロールを得る事はできます。

Q.
In effect his "Kaiser Colosseum" is applied, in the presence by monster 1 body to each other, can I get the control of monsters?
A.
Also in effect the application of "Kaiser Colosseum", you be able to get control of the monster of each other opponent.

http://www.ygopro.co/Forum/tabid/95/g/posts/t/17687/Kaiser-Colosseum---Snatch-Steal#post93906

hope it can be fixed :)

**Comment by salix5** [comment]
1.
merged
2.
5b6f198f4bec06d087f8f6b79e3fa544da45daa1
fixed
Thank you.
