### ISSUE TITLE
Nekroz Sophia's Banishing Effect...

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1151]
When I successfully Summoning Nekroz Sophia, it banishing Effect won't active ( no pop-up window appear and it won't triggered to banish any cards on the Fiels, and both player Graveyards)...

please fix it...

**Comment by nekrozar** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=15077&keyword=&tag=-1
Q.自分が既に他のモンスターを通常召喚・特殊召喚しているターンに、「sophiaの影霊衣」の『②：このカードが儀式召喚に成功した時に発動できる。このカード以外のお互いのフィールド・墓地のカードを全て除外する。この効果を発動するターン、自分は他のモンスターを通常召喚・特殊召喚できない』効果を発動する事はできますか？
A.自分が既に他のモンスターを通常召喚・特殊召喚しているターンには、「sophiaの影霊衣」の儀式召喚に成功した時の効果を発動する事はできません。

Did you Special Summon other monsters that turn?

**Comment by marikisthar** [comment]
yup, thats my bad...

sorry 

btw how about Zefra Savber??? it'is already fixed???

**Comment by salix5** [comment]
merged
Thank you.
