### ISSUE TITLE
Scripting Request...

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1177]
could someone scripting this following cards????
http://yugioh.wikia.com/wiki/Odd-Eyes_Rebellion_Dragon
http://yugioh.wikia.com/wiki/Destruction_Magician
http://yugioh.wikia.com/wiki/Creation_Magician

**Comment by Zayelion** [comment]
This is the main repo for the system internationally. They only fix/make/take in cards that have been printed. Similar to DN's card add policy. These are anime cards.... When they are announced for printing Im sure that they will be added to Salvation, Percy, or DevPro. Wait 1 month then request them in the Salvation Anime section or Percy Anime section.

**Comment by salix5** [comment]
added
