### ISSUE TITLE
Odd-Eyes Rebellion Dragon and Destruction Magician

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#1185]
Japanese Source: http://blog.livedoor.jp/maxut/archives/43178838.html

![85f7bec3](https://cloud.githubusercontent.com/assets/10573786/6664265/91f44bec-cc11-11e4-9272-bd182028bd7a.jpg)
覇王黒竜オッドアイズ・リベリオン・ドラゴン　ランク7　闇属性
ドラゴン族・エクシーズ・ペンデュラム　ATK/3000 DEF/2500
ドラゴン族レベル7モンスター×2
【Pスケール：青4/赤4】
①：1ターンに1度、もう片方の自分のPゾーンにカードが存在しない場合に発動できる。
デッキからPモンスター1体を選び、自分のPゾーンに置く。
【モンスター効果】
レベル7がP召喚可能な場合にエクストラデッキの表側表示のこのカードはP召喚できる。 ①：このカードがXモンスターを素材としてX召喚に成功した場合に発動する。 相手フィールドのレベル7以下のモンスターを全て破壊し、破壊した数×1000ダメージを相手に与える。このターンこのカードは
1度のバトルフェイズ中に3回攻撃できる。 ②：モンスターゾーンのこのカードが戦闘・効果で破壊
された場合に発動できる。自分のPゾーンのカードを全て破壊し、このカードを自分のPゾーンに置く。
English Translation: http://yugioh.wikia.com/wiki/Odd-Eyes_Rebellion_Dragon

![aa084a10](https://cloud.githubusercontent.com/assets/10573786/6664266/927edafa-cc11-11e4-916c-191dee016351.jpg)
相克の魔術師　星7　闇属性
魔法使い族・ペンデュラム　ATK/2500 DEF/500
【Pスケール：青3/赤3】 
①：1ターンに1度、自分フィールドのXモンスター1体を対象
として発動できる。このターンそのモンスターは、そのランクと
同じ数値のレベルのモンスターとしてX召喚の素材にできる。
【モンスター効果】 
①：1ターンに1度、フィールドの光属性モンスター1体を対象として発動できる。
そのモンスターの効果をターン終了時まで無効にする。この効果は相手ターン
でも発動できる。 
English Translation: http://yugioh.wikia.com/wiki/Destruction_Magician

Odd-Eyes Rebellion Dragon is Xyz Pendulum Monster. But, You cannot Pendulum Summon Xyz Monster is now version.
Destruction Magician has a "you can treat it as a monster with the same Level as its Rank" effect. But, EFFECT_XYZ_LEVEL doesn't work if you use the Xyz Monster.
How do you take the measures?

**Comment by salix5** [comment]
b35f8671303fb80ed12676120049fd12085117b1
Now xyz monsters may have EFFECT_XYZ_LEVEL.

**Comment by nekrozar** [comment]
Oh, thank you!!

**Comment by Zayelion** [comment]
Woot!

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro/pull/1186
This is my idea.

**Comment by sidschingis** [comment]
I think you should just add an effect to ODRD to have it treated as level for pendulum summoning, since its not clear if all Pendulum XYZs will be able to be pendulum summoned.

**Comment by nekrozar** [comment]
Either way this is better to decide after the sale.

**Comment by salix5** [comment]
4238ca5505af961caa6f13aeb39111bc1350ae09
Now each monster can have its own pendulum level

58e6b9a24be1ba81ffecec4aed8f6625bb6bf6d1
Now xyz monsters can be xyz material by default

**Comment by nekrozar** [comment]
Oh, thank you!!!
