### ISSUE TITLE
Dark Magician of Chaos (Eratta)

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1187]
Dark Magician of Chaos
Level 8 DARK Spellcaster-Type Effect Monster
ATK 2800
DEF 2600
You can only use the (1) effect of “Dark Magician of Chaos” once per turn. (1) During the End Phase, if this card was Normal or Special Summoned this turn: You can target 1 Spell Card in your Graveyard; add it to your hand. (2) At the end of the Damage Calculations, if this card destroyed an opponent’s monster by battle: Banish that monster. (3) If this card would leave the field, banish it instead.

http://ygorganization.com/vj-april-2015-v-jump-promo-news/

could the script updated???

**Comment by salix5** [comment]
done
