### ISSUE TITLE
[BUG]Number 39: Utopia Beyond

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#1192]
Ｑ：《ヒーロー・マスク》の効果によりカード名を《Ｅ・ＨＥＲＯ フェザーマン》に変更した場合、このカードは「希望皇ホープ」と名のついたカードとして扱いますか？
Ａ：はい、「希望皇ホープ」と名のついたカードとして扱います。(15/01/07)

Which means that, even if you activate "Hero Mask" on "Number 39: Utopia Beyond" so that its name becomes other "Hero" monster, it is still treated as "Utopia" monster.
But in Ygopro, it does not treated as "Utopia" monster........

**Comment by salix5** [comment]
3c81ab617649ed24ab61dca2e48abd1320cdb541
a78e0dd1c44c025b5d853d250761f1a416209b5b
fixed
Thank you.
