### ISSUE TITLE
what is install the game in the archlinux

### ISSUE THREAD

**Issue by behind1231** [Fluorohydride/ygopro#1207]
what is install the game in the archlinux 64???

**Comment by anshkumar** [comment]
sudo pacman -S gcc make premake freetype2 libevent sqlite irrlicht lua git
git clone https://github.com/Fluorohydride/ygopro.git
cd ygopro
premake4 gmake
make -Cbuild

**Comment by behind1231** [comment]
ygopro.make:149: recipe for target '../obj/Debug/ygopro/menu_handler.o' failed
make[1]: *** [../obj/Debug/ygopro/menu_handler.o] Error 1
Makefile:24: recipe for target 'ygopro' failed
make: *** [ygopro] Error 2
make: Leaving directory '/home/behind/ygopro/build'
behind@localhost:~/ygopro$ make -Cbuild
make: Entering directory '/home/behind/ygopro/build'
==== Building ocgcore (debug) ====
==== Building clzma (debug) ====
==== Building ygopro (debug) ====
menu_handler.cpp
In file included from ../gframe/menu_handler.cpp:1:0:
../gframe/config.h:49:22: 致命错误：irrlicht.h：没有那个文件或目录
 #include <irrlicht.h>
                      ^
编译中断。
ygopro.make:149: recipe for target '../obj/Debug/ygopro/menu_handler.o' failed
make[1]: *** [../obj/Debug/ygopro/menu_handler.o] Error 1
Makefile:24: recipe for target 'ygopro' failed
make: *** [ygopro] Error 2
make: Leaving directory '/home/behind/ygopro/build'

**Comment by anshkumar** [comment]
what's the output of " ls /usr/include/irrlicht/irrlicht* " ?

**Comment by behind1231** [comment]
behind@localhost:~$ ls /usr/include/irrlicht/irrlicht*
/usr/include/irrlicht/irrlicht.h

**Comment by behind1231** [comment]
behind@localhost:~$ ls /usr/include/irrlicht/irrlicht*
/usr/include/irrlicht/irrlicht.h

**Comment by behind1231** [comment]
cp /usr/include/irrlicht/irrlicht.h /gframe/???

**Comment by anshkumar** [comment]
No that won't work. Try "rm -r obj bin" and then "make -Cbuild". If it still fails show me the file build/ygopro.make

**Comment by behind1231** [comment]
behind@localhost:~/ygopro/bin/debug$ ./ygopro
Irrlicht Engine version 1.8.1
Linux 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:21:02 CET 2015 x86_64
Using renderer: OpenGL 2.1.2
GeForce Go 6150/integrated/SSE2: NVIDIA Corporation
OpenGL driver version is 1.2 or better.
GLSL version: 1.2
Could not open file of texture: textures/cover.jpg
Could not open file of texture: textures/unknown.jpg
Could not open file of texture: textures/act.png
Could not open file of texture: textures/attack.png
Could not open file of texture: textures/chain.png
Could not open file of texture: textures/negated.png
Could not open file of texture: textures/number.png
Could not open file of texture: textures/lp.png
Could not open file of texture: textures/lpf.png
Could not open file of texture: textures/mask.png
Could not open file of texture: textures/equip.png
Could not open file of texture: textures/target.png
Could not open file of texture: textures/lim.png
Could not open file of texture: textures/f1.jpg
Could not open file of texture: textures/f2.jpg
Could not open file of texture: textures/f3.jpg
Could not open file of texture: textures/bg.jpg
Could not open file of texture: textures/field2.png

**Comment by anshkumar** [comment]
If you want to play the game download it from http://www.ygopro.co/

**Comment by behind1231** [comment]
what is to install?

**Comment by anshkumar** [comment]
http://files.gruntmods.com/Flelf/Linux/ygopro-1.033.3%20Percy-full.tar.gz

**Comment by behind1231** [comment]
Direct decompression operation line?

**Comment by behind1231** [comment]
Thank you for your guidance

**Comment by anshkumar** [comment]
You're welcome.

**Comment by behind1231** [comment]
Direct decompression operation line?

**Comment by behind1231** [comment]
I come from China, do you have QQ? Add a friend ~!

**Comment by anshkumar** [comment]
I do not understand what you are saying.

**Comment by anshkumar** [comment]
Let me see if I can get QQ on pidgin. Wait.

**Comment by anshkumar** [comment]
Sorry, I was unable to get QQ working for linux. Use google translator.

**Comment by Zayelion** [comment]
There is an additional self updating (linux, win) version at http://ygopro.us based off a deep fork of this repo.

**Comment by behind1231** [comment]
@anshkumar 
How to put the software language localization into Chinese?

**Comment by Zayelion** [comment]
https://github.com/Fluorohydride/ygopro/blob/25bdab4c6d0000f841aee80c11cbf2e95ee54047/gframe/menu_handler.cpp#L364

Press the 'r' key, also this functionality needs to be extrapolated to a check control in settings because it causes signifigant issues for Latin based languages. Especially english with 'r' being the 8th most common letter. Being "highly annoying" is an understatement, it is removed in every other variant.

**Comment by anshkumar** [comment]
I don't think it has any such option. I've seen string.conf and cards.cdb file. Everything is in English.

**Comment by behind1231** [comment]
@Zayelion 
How to install the  http://ygopro.us/setups/client.tar.gz to the game?

**Comment by Zayelion** [comment]
Unzip/tar it, run launcher file.
