### ISSUE TITLE
ygopro.make:149

### ISSUE THREAD

**Issue by behind1231** [Fluorohydride/ygopro#1217]
behind@localhost:~/ygopro$ make -Cbuild
make: Entering directory '/home/behind/ygopro/build'
==== Building ocgcore (debug) ====
==== Building clzma (debug) ====
==== Building ygopro (debug) ====
menu_handler.cpp
In file included from ../gframe/menu_handler.cpp:1:0:
../gframe/config.h:49:22: 致命错误：irrlicht.h：没有那个文件或目录
 #include <irrlicht.h>
                      ^
编译中断。
ygopro.make:149: recipe for target '../obj/Debug/ygopro/menu_handler.o' failed
make[1]: **\* [../obj/Debug/ygopro/menu_handler.o] Error 1
Makefile:24: recipe for target 'ygopro' failed
make: **\* [ygopro] Error 2
make: Leaving directory '/home/behind/ygopro/build'

**Comment by salix5** [comment]
https://github.com/soarqin/ygopro
需要的檔案這裡應該都有
不過linux下的編譯我個人沒試過

**Comment by behind1231** [comment]
你是linux系统？

**Comment by salix5** [comment]
不是
所以linux下的編譯細節我不清楚
