### ISSUE TITLE
Could not open file of texture

### ISSUE THREAD

**Issue by behind1231** [Fluorohydride/ygopro#1218]
behind@localhost:~/ygopro/bin/debug$ ./ygopro
Irrlicht Engine version 1.8.1
Linux 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:21:02 CET 2015 x86_64
Using renderer: OpenGL 2.1.2
GeForce Go 6150/integrated/SSE2: NVIDIA Corporation
OpenGL driver version is 1.2 or better.
GLSL version: 1.2
Could not open file of texture: textures/cover.jpg
Could not open file of texture: textures/unknown.jpg
Could not open file of texture: textures/act.png
Could not open file of texture: textures/attack.png
Could not open file of texture: textures/chain.png
Could not open file of texture: textures/negated.png
Could not open file of texture: textures/number.png
Could not open file of texture: textures/lp.png
Could not open file of texture: textures/lpf.png
Could not open file of texture: textures/mask.png
Could not open file of texture: textures/equip.png
Could not open file of texture: textures/target.png
Could not open file of texture: textures/lim.png
Could not open file of texture: textures/f1.jpg
Could not open file of texture: textures/f2.jpg
Could not open file of texture: textures/f3.jpg
Could not open file of texture: textures/bg.jpg
Could not open file of texture: textures/field2.png

**Comment by Zayelion** [comment]
You are missing assets. Copy https://github.com/Fluorohydride/ygopro/tree/master/textures folder into your binary directory on file system level to ygopro.exe

Make sense?
