### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1220]
I have some question about ruling/cards script.
1. about Odd-Eyes Rebellion Dragon ft Destruction Magician :
can I Xyz summon Odd-Eyes Rebellion Dragon using ANY non-Dragon Xyz monster as a Zyz materal (in this case, the non-dragon Xyz monster is already affected by effect of Destruction magician)????

Destruction Magician Pendulum Effect
Once per turn: You can target 1 Xyz Monster you control; this turn, for an Xyz Summon, you can treat it as a monster with a Level equal to its Rank. 

OERD Monster Effect
2 Level 7 Dragon-Type monsters
If you can Pendulum Summon Level 7 monsters, you can Pendulum Summon this face-up card from your Extra Deck. If this card is Xyz Summoned by using an Xyz Monster as any of its Materials: This card can make up to 3 attacks during each Battle Phase this turn, also destroy as many Level 7 or lower monsters your opponent controls as possible, and if you do, inflict 1000 damage to your opponent for each monster destroyed by this effect. If this card in the Monster Zone is destroyed by battle or card effect: You can destroy all cards in your Pendulum Zones, and if you do, place this card in your Pendulum Zone.
1. about Legendary Knight Critias:
   Can I atcivate immediately traps that has beed set by the effect of critias (like mirror force, Cilinder, draining shield) at the damage step???
   
   Cannot be Normal Summoned/Set. Must be Special Summoned with "Legend of Heart", and cannot be Special Summoned by other ways. When this card is Special Summoned: You can target 1 face-up Spell/Trap Card on the field; banish that target. When this card is targeted for an attack: You can target 1 Trap Card in your Graveyard; Set that target. That Set card can be activated this turn.

tnx in advance :)

**Comment by Zayelion** [comment]
This card isnt even in the game yet, the monsters they will summon haven even been announced. No one has a way of answering this till after the card is printed and rulings have been placed on the official databases.
