### ISSUE TITLE
No font causes crash

### ISSUE THREAD

**Issue by anshkumar** [Fluorohydride/ygopro#1221]
The git version does not provide any Font, which causes ygopro to crash. A font folder like in devpro version should be uploaded.

**Comment by salix5** [comment]
It uses fonts included in Windows by default.

**Comment by anshkumar** [comment]
It might be working on windows but it is definitely crashing on Linux.

**Comment by IceYGO** [comment]
The default fonts are copyrighted, we cannot legally redistribute them on GitHub.
We can still use some open-source fonts instead though, if anyone is willing to find two similar ones.

**Comment by Zayelion** [comment]
Im game, Im rather fond of `noto` which with distribute with Salvation : https://www.google.com/get/noto/

**Comment by IceYGO** [comment]
*Noto Sans CJK SC Regular* looks great, but weighs 16 MB.
If everyone is OK with increasing the weight of the repository, we can use it.

We can probably use the lightweight *Noto Sans Bold* for the numbers (~300 KB).

**Comment by Zayelion** [comment]
Are we really going to have a conversation about efficiency of data in this repository? Even though `ygopro-core` and ygopro-script` are separate, there is still the image system which has redundancy issues and lacks a templating system. The DB also has issues.

I'll keep looking around for something that can be used as a sub module.

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro/wiki#running
