### ISSUE TITLE
card::get_attack() returning 0 on Monsters with ??? ATK while not on the field.

### ISSUE THREAD

**Issue by sidschingis** [Fluorohydride/ygopro#1227]
as of 
https://github.com/Fluorohydride/ygopro/commit/986b1e9ba9ce614496348b7961041b7ac1d1595f
card::get_attack() is returning 0 on Monsters with ??? ATK even when not on the field, allowing them to be Special Summoned via Giant Rat, etc.
Was there a Ruling change?

**Comment by salix5** [comment]
0abc13c3bb6f77f8408a10e84a4d652bb0d2b232
It's my mistake.
Thamk you very much.
