### ISSUE TITLE
GetOriginalAttribute of trap monsters

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro#1244]
トランスターン/Transmodify(5288597)
According to this [FAQ](http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=216&keyword=&tag=-1), this card cannot be activated by sending trap monster to grave.
If we record attribute for trap monsters as ce6a96546e23b109c9b8cdd0ba2b8e5f8f3385f4, the script of トランスターン/Transmodify will contradict that FAQ.
Maybe there are some other cards like トランスターン/Transmodify. I don't know which ways to resolve this problem, fixing the scripts of these cards, changing Card.GetOriginalAttribute or some other method?

**Comment by salix5** [comment]
8b9f8c64ec11e11a18cebded8f405c57d7860c49
陷阱怪獸在場上取原屬性應該傳回效果敘述欄()裡面的資料，這部份沒有問題
トランスターン不能選陷阱怪獸我認為可以把它當作特例處理

**Comment by DailyShana** [comment]
好的
