### ISSUE TITLE
[Bug] Djinn Presider of Rituals

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#1319]
Need [Star Blast / Djinn Presider of Rituals / Nekroz Kaleidoscope / any two Nekroz Ritual]

1. Summon "Djinn Presider of Rituals" first
2. Activate "Star Blast" to make "Nekroz of Trishula"'s level 1
3. Activate "Nekroz Kaleidoscope" and Ritual Summon level 1 "Nekroz of Trishula" and level 3 "Nekroz of Clausolas", using "Djinn Presider of Rituals" on field.
4. Only one Nekroz monster has Drawing effect.

**Comment by salix5** [comment]
34e283aefc18ae300065c15e2e47161dedac1e13
fixed
Thank you.
