### ISSUE TITLE
Arch: the app doesn't start, but shows no errors

### ISSUE THREAD

**Issue by mhelvens** [Fluorohydride/ygopro#1408]
Hi there,

I've installed ygopro on Arch linux without much trouble. When I start the app like this:

```
./bin/debug/ygopro
```

It only shows a window for a very brief moment - then it goes poof (like #809). I get the following output in my terminal:

```
Irrlicht Engine version 1.8.1
Linux 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64
Using renderer: OpenGL 4.5.0
GeForce GTX 770/PCIe/SSE2: NVIDIA Corporation
OpenGL driver version is 1.2 or better.
GLSL version: 4.5
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/cover.jpg
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/unknown.jpg
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/act.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/attack.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/chain.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/negated.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/number.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/lp.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/lpf.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/mask.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/equip.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/target.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/lim.png
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/f1.jpg
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/f2.jpg
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/f3.jpg
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/bg.jpg
Loaded texture: /home/mhelvens/Projects/(external)/ygopro/textures/field2.png
```

No errors. Please let me know how I can help debug this.

**Comment by Shadey** [comment]
You probably just don't have a cards.cdb file.
http://a.1339.cf/gtrmmi.cdb
Download mine to your ygopro folder and rename to it cards.cdb and it should start work.

**Comment by mhelvens** [comment]
I had a cards.cdb file, but it was empty. You're right, though. Using your file, the app starts.

But it seems the buttons of the main menu have no text on them. Some font issue, probably.

**Comment by Shadey** [comment]
It is a font issue because the strings.conf in the repo is in Japanese.
You can use mine which is in English 
http://a.1339.cf/lvfrkl.conf
Just replace the old strings.conf with this one.

**Comment by mhelvens** [comment]
So far so good. :-) Am I going to need more files from you?

Because when I click on Deck Edit, I get a segfault.

**Comment by Zayelion** [comment]
It does that on MacOS also.

**Comment by jacksonrayhamilton** [comment]
I have the same issue when compiling on Debian 8. Is there any version of GNU/Linux that YGOPro works on? Do the maintainers know what's causing this?

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro/wiki#running
