### ISSUE TITLE
Disable field of Ghostrick Socuteboss when rank up to Ghostrick Angel of Mischief

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro#1425]
If there is only a Ghostrick Socuteboss and Xyz summon Ghostrick Angel of Mischief by using this Ghostrick Socuteboss as the Xyz Material, then the effect of Ghostrick Socuteboss that disable monster zone will not apply.
http://yugioh-wiki.net/index.php?%A1%D4%A5%B4%A1%BC%A5%B9%A5%C8%A5%EA%A5%C3%A5%AF%A1%A6%A5%B5%A5%AD%A5%E5%A5%D0%A5%B9%A1%D5#faq
Ｑ：自分のフィールドのモンスターが《ゴーストリック・サキュバス》１体のみ存在する状態で、この《ゴーストリック・サキュバス》の上に《ゴーストリックの駄天使》を重ねてエクシーズ召喚しました。
　この場合、この《ゴーストリック・サキュバス》の効果で使用不可となっていたモンスターカードゾーンは使用可能となりますか？
Ａ：その場合、自分のフィールドにゴーストリックと名のついたモンスターが一旦存在しなくなるため、効果の適用が終了となります。(14/09/01)

**Comment by DailyShana** [comment]
not solved perfectly

**Comment by salix5** [comment]
只是暫時性的修正而已
現在的刷新機制有些部分可能需要重新檢討

**Comment by mercury233** [comment]
似乎相关：
https://github.com/Fluorohydride/ygopro/issues/1639

**Comment by DailyShana** [comment]
最近也在考虑这方面, 大体上是希望引入adjust_flag(ADJUST_LOCATION_INFO, ADJUST_SELFDESTROY等等)
以便在不同的地方可以精细的控制刷新那些内容
