### ISSUE TITLE
Spellbook of Power -> Pendulum Monster.

### ISSUE THREAD

**Issue by Steeldarkeagel** [Fluorohydride/ygopro#1462]
If you use Spellbook of Power on a Spellcaster Pendulum monster and it destroys a monster and is destroyed by that battle, for example both monsters have 2000 ATK, then Spellbook of Power will not search. Spellbook of Power should search in this situation.

**Comment by salix5** [comment]
Can you upload a replay file?
Thank you.

**Comment by Steeldarkeagel** [comment]
Here you go, could not upload straight here so used Google Drive.
https://drive.google.com/file/d/0B2VHOL0DTPQyMjdJR05NbVprdTQ

**Comment by salix5** [comment]
3d9dafcb83bfb6db7038cc344c51a90618db78b5
fixed
Thank you.
