### ISSUE TITLE
Apoqliphort Towers (アポクリフォート・キラー) vs D/D/D Kali Yuga the Twin Dawn Overlord (ＤＤＤ双暁王カリ・ユガ)

### ISSUE THREAD

**Issue by sidschingis** [Fluorohydride/ygopro#1469]
When Kali Yuga is XYZ Summoned while Apoqliphort Towers is face-up on the field,
Apoqliphort Towers will not be negated by Kali Yuga.
This should not be the case, since the negation effect of Kali Yuga is not an activated effect.

This behaviour is caused by the following part of Apoqliphort Towers' code:

line  75: "... te:IsHasProperty(EFFECT_FLAG_FIELD_ONLY) ..."
There should be a way to distinguish field only effects that were activated (Psi-Blocker)
and those that were not activated (Kali Yuga)

**Comment by salix5** [comment]
b8d9a11f1903d934c3430f0f0028511f7658994b
fixed
Thank you.
