### ISSUE TITLE
Lose 1 Turn and immune effect

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro#1480]
When the effect of Lose 1 Turn is applying, similar to Skill Drain, if one summon/special summon monsters that are immune to the effect of trap cards, these monsters should still be disabled in that turn.
Also, I want to know the reason that using global check in the current script of Lose 1 Turn.

**Comment by VanillaSalt** [comment]
reason for 5b0719c9cb0e6080e1764246b0d02f9da291dc21

c = Gemini monster
turn 1. Special Summon c
turn 2. Summon c
c:IsStatus(STATUS_SUMMON_TURN) and bit.band(c:GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL will be true for the rest of turn 2

**Comment by DailyShana** [comment]
I see. So maybe it is necessary to introduce STATUS_SPSUMMON_TURN to distinguish
