### ISSUE TITLE
Synchro Summoning become invalid

### ISSUE THREAD

**Issue by Stanshiki246** [Fluorohydride/ygopro#1501]
I cannot send Synchro Materials to the Graveyard to Synchro Summon any Synchro Monsters. If i have Synchro Materials on my field, I Synchro Summon a Synchro Monster without sending its materials to the Graveyard. Please fix it.

**Comment by salix5** [comment]
The Synchro Summon system is modified, so Percival's version cannot interpret current script correctly.
Maybe you can try the Japanese version?

**Comment by Stanshiki246** [comment]
i have tried the japanese version. The result is stil same. There is something wrong in utility script. Please fix it.

**Comment by salix5** [comment]
It can work in current 1033.7
