### ISSUE TITLE
PSY骨架王·Ω (74586817)②效果返回墓地的突破技能(78474168)无法在当前回合发动

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1523]
> Ｑ：除外されている自分の《スキル・プリズナー》を自分の墓地に戻した場合、墓地に戻した《スキル・プリズナー》をそのターンに発動できますか？
> Ａ：はい、発動できます。(15/08/27)

http://yugioh-wiki.net/?%A1%D4%A3%D0%A3%D3%A3%D9%A5%D5%A5%EC%A1%BC%A5%E0%A5%ED%A1%BC%A5%C9%A1%A6%A6%B8%A1%D5

目前的处理是，在我方回合的准备阶段，对方发动PSY骨架王·Ω的②效果将我方除外的突破技能返回墓地，这张突破技能不能在本回合发动。

**Comment by mercury233** [comment]
PSY骨架超载(36970611)也有同样的问题

**Comment by salix5** [comment]
e59d9dc201e3051075a62721ec84f41f690c91a1
已修正
謝謝
