### ISSUE TITLE
Not Issue but questions

### ISSUE THREAD

**Issue by Tic-Tac-Toc** [Fluorohydride/ygopro#1531]
I don't know if it's here i've to post that but i've a question :)

Can someone show me where the display of the listbox ( of the filter cards ) is coded.
Where is coded the 
Name
Level
ATK/Def
display :)
 This : http://puu.sh/jXAmn/694ebc1f89.jpg

Tic-Tac-Toc

**Comment by salix5** [comment]
I think this part is in drawing.cpp

**Comment by IceYGO** [comment]
Indeed, this is drawn in the function `Game::DrawDeckBd()` which is in the file `drawing.cpp`

The loop starts here:

https://github.com/Fluorohydride/ygopro/blob/0e853ab93558407543945b9b6a10119e6bad63f7/gframe/drawing.cpp#L917
