### ISSUE TITLE
ddd issue and question

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1539]
I can't fusion summoning wave ragnarok using 1 d/d swirlal slime and 1 D/D/D monster (in this case Kaiser the Concueror).

Nb : this bug may affect necro slime to because they have similar eff.

Is this a bug or ruling (since wave condition needs 2 DDD monsters)?

Tnx in advance.

**Comment by nekrozar** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=11955
「DD」と名のついたモンスター2体を融合素材とする「DDD烈火王テムジン」や「DDD神託王ダルク」を融合召喚する事はできますが、「DDD」と名のついたモンスター2体を融合素材とする「DDD怒濤壊薙王カエサル・ラグナロク」は融合召喚する事はできません。
Swirlal Slime is not D/D/D monster. Swirlal Slime cannot use to Caesar Ragnarok's Fusion Material.
