### ISSUE TITLE
RESET_DRAW这类的东西

### ISSUE THREAD

**Issue by Tianchenglipu** [Fluorohydride/ygopro#1546]
RESET_DRAW			=PHASE_DRAW			--抽卡阶段重置
RESET_STANDBY		=PHASE_STANDBY		--准备阶段重置
RESET_MAIN1			=PHASE_MAIN1		--主要阶段1重置
RESET_BATTLE		=PHASE_BATTLE		--战斗阶段重置
RESET_DAMAGE		=PHASE_DAMAGE		--伤害计算前重置
RESET_DAMAGE_CAL	=PHASE_DAMAGE_CAL	--伤害计算时重置
RESET_MAIN2			=PHASE_MAIN2		--主要阶段2重置
RESET_END			=PHASE_END			--结束阶段重置

我觉得这几个完全可以撤掉了，或者让这几个的设置自带一个RESET_PHASE，即让RESET_DRAW成为=RESET_PHASE+PHASE_DRAW。

这个批量替换一下就行了，关键字【RESET_PHASE+RESET_】替换为【RESET_】，再把utility.lua的这里改一改。

**Comment by salix5** [comment]
dcd2d4f1180fa9411caa14c12d77805506eba0e9
目前把RESET_移除，之後應該會統一使用RESET_PHASE+...
謝謝
