### ISSUE TITLE
影雾女郎等送去墓地发动的诱发效果的bug

### ISSUE THREAD

**Issue by Lsty** [Fluorohydride/ygopro#1564]
c1发动“暴君的暴饮暴食”将自己场上的“元素英雄 影雾女郎”解放
c2发动“活死人的呼声”以自己墓地的“元素英雄 影雾女郎”为对象
逆处理，“元素英雄 影雾女郎”特殊召唤成功
c1发动“元素英雄 影雾女郎”的“从卡组把1只‘英雄’怪兽加入手卡”的效果
c2发动“禁忌的圣杯”以“元素英雄 影雾女郎”为对象
逆处理，“元素英雄 影雾女郎”的“从卡组把1只‘英雄’怪兽加入手卡”的效果被无效

同样的处理步骤，用“技能抽取”则不会无效。

**Comment by salix5** [comment]
dfb7ba856d21dc53807915543179c3a745910d3b
已修正
謝謝

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@b46cf15
