### ISSUE TITLE
Help merging in Salvations & DevPro's gframe

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1570]
I'll link the conversation on Salvations forum later

@VanillaSalt
@salix5
@sidschingis
@IceYGO
@Fluorohydride 
@woodee
@DailyShana 

The Salvation team is curious if we could get help merging the graphical enhancements from https://github.com/SalvationDevelopment/ygopro-salvation-custom's gframe into the main code base, and @sidschingis and @IceYGO willing the DevPro and TDOANE enhancements also. There are about 50000 people using YGOPro and each has created special extra features to enhance the experience and longevity of our systems. I feel they should all be merged back if possible to make life easier for everyone. 

Salvation promises to help out more going forward.
## Salvation, DevPro, Dawn
- disabling the `r-key press` via `system.conf` keypress so system can be internationalized (these systems have it disabled it needs to be a configuration setting with the default being on to support Chinese players properly)
- Sound Effects
- Themes
- Background Music
- Re-sizing of the screen
- Forced Join ( `-j` parameter function with deck select disabled )
## Salvation
- Configuration of location of `pics`, `scripts`, `strings.conf` and `cards.cdb` files/folders to allow internationalization of gameplay.
## DevPro
- Using a configured server to show Ranking (Salvation and Dawn dont want this feature, so make it on and off)
- Using a configured server to get a custom card cover image to display for users
## Dawn of a New Era
- Using a configured server to get an custom avatar image to display for users

**Comment by ChibiChanNya** [comment]
Would definitely be good if it was equally fair for everyone. YGOPro still has a lot of potential and each system is trying to push it in different ways. This would be extremely helpful.

**Comment by BlackBallista** [comment]
I believe that at this point merging is the best option we have. Stability should always be prioritized over secondary features (After all, why would these be worth anything if you cant play in the first place).

**Comment by Bromantic** [comment]
This is best for those who don't know the core or the system itself. Having different clients promotes competitiveness and self-sustainability. As demonstrated by history, most of the clients do not want to share source, but will give credit were due, because of this exact reason. If Fluorohydride wants to personally get involved with a client, i can see that, but just "requesting" that everyone merge is not fair to the developers and maintainers. Either you learn the system or you work with someone who does. That's how it works.

**Comment by Zayelion** [comment]
That results in a squeezing out of ideas and is kinda against the idea of open source. In our community one of two things happen. People do not share or when they do share they do not accept the commits and contributions of others causing the projects to fracture. It is not that people have not learned or are willing to learn how and where to code to make the changes that they need, it is more so that once those changes are made and they are for the better they are ignore and there is little to no communication about why.

The @soarquin fork has 3 projects dangling from it. DevPro, YGOProX, and Salvation. Dawn and Percy are not open source. None of the five fall under the newly posted GPL2 license, which requires any other forks to opensource their code to, going forward the code base. This is not true for the ygopro-core which is MIT.

Your argument about sustainability is hallow. Konami has license of the product line so the server owners can not make any money off ygopro without being sued. Each of us work on this project by paying from our own wallets. With the exception of Dawn all the projects link to each other, or have at some point. There is contention but not bad blood between each of us. Each going as far as to develop software distinct for the other like DevPro building Salvations minicore, and its AI, Mycard helping assist in its launcher. Percy and Checkmate helping DevPro build its Server, and DevPro repairing Dawns servers.

I agree that we all should be unique and we each are very unique but there are common features that we all have by this point and we need to get them into baseline.
