### ISSUE TITLE
元素英雄 新宇骑士(72926163)攻击力异常

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1571]
使用棱镜侠丢新宇侠，然后用奇迹融合将场上棱镜侠与墓地新宇侠融合新宇骑士，攻击力显示为2499
![image](https://cloud.githubusercontent.com/assets/13391795/10120976/0b2cb69e-6509-11e5-82d7-50f8de31975d.png)

**Comment by salix5** [comment]
可否提供錄像
謝謝

**Comment by mercury233** [comment]
抱歉，我没有仔细测试，这个问题只发生在部分服务器上（比如122.0.65.73 端口1998或233），本地测试时会有这个问题的录像会报错。
等我能单机重现这个问题再来反馈。

**Comment by Lsty** [comment]
服务器的录像也可以啊。。

**Comment by mercury233** [comment]
@Lsty 保存下的录像播放时会报错。比如用2500的怪打了2499的新宇骑士，决斗时是1伤害，新宇骑士死，看录像时新宇骑士是正常2500，两方都死，然后error occur了

**Comment by Lsty** [comment]
确实录像无法重现。比较迷。。
