### ISSUE TITLE
神影依·米德拉什(94977269)会被娱乐法师 秋千魔术家(17016362)的②效果破坏

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1574]
我方米德拉什在主要阶段1被**对方**秋千魔术家2效果指定了，战斗阶段结束时米德拉什被破坏。

**Comment by DailyShana** [comment]
米德拉什在秋千魔术家之后出场？

**Comment by mercury233** [comment]
@DailyShana 与出场顺序无关
replay:http://mercury233.me/ygosrv233/BUG%20El%20Shaddoll%20Winda%20destroyed%20by%20the%20effect%20of%20Performage%20Trapeze%20Magician.zip

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/41ae586dbd01fb1b733cd6d0b51a096c12b48851
已修复

**Comment by salix5** [comment]
51693962c2b33886cd376090c9eee1fd7ddba3df
裁定變更後已回復成原本的處理
謝謝
