### ISSUE TITLE
“深渊唤雨”和“水精鳞-深渊昆德”的墓地诱发效果的bug

### ISSUE THREAD

**Issue by Lsty** [Fluorohydride/ygopro#1578]
c1“雷破”丢弃“水精鳞-深渊昆德”
c2“深渊唤雨”以“水精鳞-深渊昆德”为对象
逆处理苏生“水精鳞-深渊昆德”
c1发动“水精鳞-深渊昆德”墓地的效果以“水精鳞”怪兽为对象，“水精鳞-深渊昆德”的效果被无效。

**Comment by Lsty** [comment]
正确情况“水精鳞-深渊昆德”的效果不会被无效。

**Comment by Lsty** [comment]
@salix5

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/5589807f4f3a262ff458246f259e3c0edb7172f7
已修复
