### ISSUE TITLE
真帝王领域的攻击力上升bug

### ISSUE THREAD

**Issue by Lsty** [Fluorohydride/ygopro#1581]
“真帝王领域”在场，“冥帝”向里侧表示的“娱乐法师 镜子指挥”攻击的场合，反转“娱乐法师 镜子指挥”，发动“娱乐法师 镜子指挥”的效果选择“冥帝”，之后伤害计算时，“冥帝”的攻击力守备力变成1000/3600。

**Comment by salix5** [comment]
a0859045ab8b8af6ecd62cb521d027661de67c08
已修正
謝謝
