### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by Tic-Tac-Toc** [Fluorohydride/ygopro#1589]
How compile libocgcore.so ?

**Comment by mercury233** [comment]
https://github.com/garymabin/YGOMobile/tree/master/Classes/ocgcore

Are you looking for this?

**Comment by Tic-Tac-Toc** [comment]
Hmm it's the source code like ygopro-core.
I look for the lua who can compile the dll i don't know how compile it..

**Comment by Zayelion** [comment]
https://github.com/SalvationDevelopment/ygopro-core/blob/master/README.md

**Comment by IceYGO** [comment]
Closing this since Tic-Tac-Toc managed to compile it.
