### ISSUE TITLE
unscriptable cards

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1592]
Dear Fluoro.

Lots of new cards has been released recently from BOSH. And some of them is impossible/difficult to be scripted. If you don't mind could you scripting this 2 cards?
1. yugioh.wikia.com/wiki/Ariadne_the_Absolver
2. yugioh.wikia.com/wiki/Arbiter_of_the_Seal

tnx in advance..

**Comment by marikisthar** [comment]
2. yugioh.wikia.com/wiki/Arbiter_of_the_Seal

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/pull/45/files
https://github.com/Fluorohydride/ygopro-scripts/pull/37/files
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c98301564.lua
