### ISSUE TITLE
Tag Dueling Broken in Regression Testing by Userbase

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1595]
The C# based server side systems are breaking when they do tag duels. Was there a change to the structure of network packets for tag duels to accomidate the new indicator for face up and face down cards in the extra deck?

@DailyShana 
@salix5

**Comment by Tic-Tac-Toc** [comment]
https://github.com/IceYGO/ygosharp/commit/23e42412a776d3526341aa44767017a5273928c0 :)

**Comment by IceYGO** [comment]
Indeed, it was caused by a change to the `TAG_SWAP` message. See the commit above for a quick fix.

**Comment by Zayelion** [comment]
Thanks!
