### ISSUE TITLE
Different effects not working with certain circumstances

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1601]
I recently noticed some weird bugs on Devpro since the last update ~2-3 days ago. I've already checked the affected scripts with those and they are unchanged by the update (also I didn't notice any errors), thus it should be something with recent core updates I guess.
I'm not sure if any of this has already been fixed or is at work (or did I miss a major ruling change the past days/weeks? Oo ...) thus please point it out if that's the case and I may be just blind...

1. Star Seraph Scepter / Sovereignty combo. You summon Scepter, activate it, chain a Sovereignty in your hand, summon that, add another Sovereignty. This one should trigger and summon itself.
The issue now is, that the added Sovereignty triggers, but it isn't summoned. It stays in the hand, the hand is shuffled.
Following a suspition I had I also tested the Fire King / Generation Shift combo. Basicly, destroying the Yaksha/Barong doesn't trigger the added Yaksha/Barong at all.
Likewise, I've faced an opponent that tried to trigger Kozmo Dark Destroyer with Generation Shift. Dark Destroyer didn't trigger in the grave. I haven't found any ruling for this, but according to the text it should trigger (If [...] you can)

2. That same opponent of mine managed to successfully resolve the effect to special summon of Kozmo Farmgirl which was summoned by Kozmo Strawman. The effect negation should work like Breakthrough Skill / Veiler, thus negate the effect even if the monster is off-field at resolution.
Another example I encountered was U.A. Perfect Ace, already negated by Breakthrough Skill. He activated the effect, chained Midfielder to return him to the hand and the effect successfully negated my action. (shouldn't work either, or is there any ruling?)
After that I quickly tried out a Breakthrough Skilled Stardust, and yes, this one is also successfully able to negate effects which he shouldn't.

**Comment by mercury233** [comment]
After reverting
https://github.com/Fluorohydride/ygopro-core/commit/5589807f4f3a262ff458246f259e3c0edb7172f7
and
https://github.com/Fluorohydride/ygopro-core/commit/f456857ef2580a4451e1d26db527b8800939e38f
everything work well.

@Fluorohydride

**Comment by destdev** [comment]
after updating on Sunday #1 seems to be fixed and is working fine again

#2 should have been solved with this commit if I see that correctly?
https://github.com/Fluorohydride/ygopro-core/commit/c221464baf87a3680d0747c3e5233a5981cb33c2
at least it doesn't seem to be working too well, users are still reporting that cards that tribute for a cost are not negated and after a quick test I can confirm that

@Fluorohydride

**Comment by salix5** [comment]
Does this problem happen in the current version
Fluorohydride/ygopro-core:fa84a630f0c455b6cb6733e97645d6c2f8ef962f

**Comment by destdev** [comment]
a quick test with Cardcar was a success, it's negated now with this
thank you

**Comment by destdev** [comment]
we've just updated ygopro on our server only and there is some strange behaviour on another side now

also I don't know if this is caused by this commit or another change within the past week (at least to my knowledge there wasn't any change from our side, only changes commited here were put into this update)

If you attack with a monster that can special summon itself when being destroyed it can't be special summoned. Asuming the monster being attacked is the same, that one can be special summoned.
I tested this with Colossal Fighter and Trick Clown crashing into each other.
http://imgur.com/a/TbQqi
The first image is from the select screen of the attacker, the second one from the select screen of the one being attacked. As you can see, the attacking Colossal Fighter can't be selected by either side, the one being attacked can be selected normally.
So far I only noticed this with (special summon?) effects that can target themselves in the event of being destroyed by battle. Being destroyed by a card effect works fine (Trick Clown).

**Comment by mercury233** [comment]
@destdev It works for me on my computer. Had you tried to test it on a new complied exe on local computer?

**Comment by Zayelion** [comment]
Is it breaking when going LAN to LAN or Client to dev-Server?

**Comment by destdev** [comment]
as said, the update is only server side, the next local update is scheduled for next week, the upcomming Sunday.
LAN mode with the old core from a week ago still works fine, the problem only exists when testing on the server
I didn't have the chance to test it on a local machine with a new exe yet

**Comment by destdev** [comment]
I have no idea what could have been done to our servers to cause this, at least I have confirmation now that it is server only...
I'll close this now, everything that could be done from fluoro has been done if I see this correctly
thanks for the support everyone
