### ISSUE TITLE
change the way to config please 

### ISSUE THREAD

**Issue by fduxiao** [Fluorohydride/ygopro#1602]
Header files of several shared libs can't be included and I change the Makefile solving the problem. Package management system is applied more on unix-like systems but is different from each other, about which you can find more details on http://linuxfromscratch.org/lfs/view/stable/chapter06/pkgmgt.html. The pattern to link and configure and install packages varies from one operating system to another, even under the same distribution of linux. Most of time /usr/include can meet the need but not always. The package manager of my OS X is homebrew and it install freetype2 and irrlicht with prefix /usr/local and X11 OpenGL under /opt/X11/, making your config mistake, but maybe under a quite different path with macports. You'd better still turn to some auto tools such as autoconf to find the available library instead of writing the configuring script manually making it more cross-systemable.

**Comment by Zayelion** [comment]
@Fluorohydride

**Comment by DailyShana** [comment]
this is done via cmake `find_package`
