### ISSUE TITLE
yokoshiamauma's bug(?) and question. 

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1604]
Dear Fluoro.

I have a question related to yokoshiamuma's eff. 
Could shimauma block opponent's P zone? Because P zöne ís also treated as (extra) s/t zöne and yokoshimauma eff says that it can blocked 1 opponent's mönster OR s/t zone.

I already tried in percy's ygopro and it can't block opp P zone. It's a bug or ruling?

Tnx in advance.

**Comment by salix5** [comment]
http://yugioh.wikia.com/wiki/Spell_%26_Trap_Zone
Spell & Trap Zones are the 5 boxes behind monster zones, which do not include pendulum zones.
