### ISSUE TITLE
bug executing lingering effects

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1606]
this issue occours with psy-framegear cards (and also at least 1 other, can't find or remember which one though)

to make this happen you have to turn off auto chain order and also make sure to have at least any 1 other effect that can be activated in the end phase

picture of the result in the end phase
http://imgur.com/NAhLgpY
you can't continue from here, you are stuck
this does not happen if you don't have anything else to be executed in the end phase

this is reproducable and happens every time
if there is a way to solve this via the scripts I don't know or find anything about that, that's most like a core issue isn't it?
Well, any way, this needs to be fixed and I have no idea how :/

**Comment by salix5** [comment]
https://www.sendspace.com/file/p6ptga
It seems that this bug does not occur in the original version.
Maybe you can contact devpro team.

**Comment by Zayelion** [comment]
http://forum.ygodevpro.com/bugs/index.php/

**Comment by destdev** [comment]
I know where to find that on Devpro, I'm one of the bug staff there^^
I wrote this because of: http://forum.ygodevpro.com/bugs/index.php/Issue/7-Unable-to-banish-Psy-Framegear-s-in-EP/
problem is I've already asked and our lead programmer doesn't know why this happens or how to fix that, thus I thought it should be a general bug... 

as said, looking at the scripts alone I can't find any solution and I'm not really experienced into anything outside of those :/

btw, I was just pointed to this
https://github.com/Fluorohydride/ygopro/commit/1fc19d84d7bc603cbd0d8cd81825938f9cc3e286
though not sure what this actually does. What I can see from that is, that it most propably does something with the display of cards on the select screen, could it be the solution for this issue here?
(or I'm granting myself false hope and this is just a coincidence, wouldn't surprise me >.>)

**Comment by Zayelion** [comment]
@salix5 this is why we at the other variants like Dawn, DevPro, and Salvation want you to pay more attention to our code contributions so there is consistency. @IceYGO has a commit for adding needed translation settings that needs approval or denial with feedback.

@destdev I'll check with my team and see if we are having a similar issue and if we are not, compare your script for the card to ours.
