### ISSUE TITLE
BUG：白龙忍者在场时，自己的魔法陷阱被“无效并破坏”时，不会被破坏

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1607]
自己场上有白龙忍者(99212922)，发动古遗物的神智(12444060)，被对方用神之宣告(41420027)无效并破坏。
因为发动被无效的魔法陷阱卡不视为在场上，不受白龙忍者影响，故神智会被破坏，应可以发动炸卡效果。
目前的处理是白龙忍者有效，神智不能发动效果。

目前发现刚龙剑士(22638495)也有同样的问题，灵摆卡的发动被神宣，也会适用刚龙剑士的效果。

**Comment by salix5** [comment]
這部份有必要確認
發動無效的魔法陷阱卡不算是「從場上送去墓地」，但在發動的連鎖串中仍然算是在場上
Ex.
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=10698&keyword=&tag=-1
天空的聖域發動的連鎖串上可以發動神罰

如果是這樣的話，白龍忍者存在時
C1 神智
C2 神的宣告
解連鎖
C2 發動無效 但因為白龍忍者的效果無法破壞
C1 發動無效，處理跳過
之後按照規則把發動無效的卡送去墓地

http://yugioh-wiki.net/index.php?%A1%D4%A3%CE%A3%EF.%A3%B6%A3%B6%20%C7%C6%B8%B0%B9%C3%C3%EE%A5%DE%A5%B9%A5%BF%A1%BC%A1%A6%A5%AD%A1%BC%A1%A6%A5%D3%A1%BC%A5%C8%A5%EB%A1%D5
Ｑ：裏側表示の《マクロコスモス》を対象に効果を発動し、破壊されない状態にしました。
その《マクロコスモス》の発動に対し《コアキメイル・サンドマン》の効果が発動された場合、《マクロコスモス》は破壊されますか？
Ａ：破壊はされませんが、発動を無効にされたため墓地へ送られます。(13/04/24)

wiki也有找到類似的紀錄

**Comment by DailyShana** [comment]
有人确认过类似的：

Q. 
「ペンデュラム・コール 」の効果を発动した后に， 「贱竜の魔术师」の発动が「神星なる因子」で无効になった场合、処理はどうなりますか？ 
A. 
「ペンデュラム・コール」の『このカードの発动后、次の相手ターン终了时まで自分のPゾーンの「魔术师」カードは効果では破壊されない』効果が适用されていても、ペンデュラムゾーンに魔法カードとして発动する时に、魔法カードの発动を无効にして破壊する事はできます。 


したがって、「神星なる因子」の効果で発动が无効になって破壊された「贱竜の魔术师」は墓地へ送られ、「神星なる因子」の効果で「贱竜の魔术师」を破壊したプレイヤーはカードをドローします。

**Comment by mercury233** [comment]
已向事务局询问，等待回复

**Comment by mercury233** [comment]
Q. 
自分の《白竜の忍者》の効果の適用中に、自分は《アーティファクトの神智》を発動しました。相手はそれに対して《神の宣告》を発動できますか？《アーティファクトの神智》の「このカードが相手によって破壊された場合、フィールド上のカード１枚を選択して破壊できる」効果は発動できますか？ 
A. 
ご質問の状況の場合でも、相手は「アーティファクトの神智」のカードの発動を、「神の宣告」で無効にして破壊できます。 
また、相手の「神の宣告」の効果によって破壊されたため、「アーティファクトの神智」の墓地で発動する効果は発動できます。 

事务局的回复

**Comment by DailyShana** [comment]
No.66的效果是，【选择的卡】不会被卡的效果破坏，白龙忍者和灵摆呼唤说的是【场上的卡】不会被破坏，两者并不矛盾

**Comment by DailyShana** [comment]
刚收到的邮件回复：No.66选择覆盖的古遗物的神智，这张卡的发动被神之宣告无效送去墓地，但不是被破坏。

Q. 
魔法＆罠ゾーンにセットされている「アーティファクトの神智」を対象に「No.66 覇鍵甲虫マスター・キー・ビートル」の効果が発動し、適用されています。その後、その「アーティファクトの神智」をセットされた状態から表側にして発動が相手の「神の宣告」によって無効になった場合、「アーティファクトの神智」の「このカードが相手によって破壊された場合、フィールド上のカード１枚を選択して破壊できる」効果は発動できますか？ 
A. 
ご質問の状況の場合、「アーティファクトの神智」の発動は無効になって墓地へ送られますが、「No.66 覇鍵甲虫マスター・キー・ビートル」の効果で破壊はされません。 
よって、相手に破壊されていない「アーティファクトの神智」の『また、このカードが相手によって破壊された場合、フィールド上のカード１枚を選択して破壊できる』効果は発動できません。

**Comment by salix5** [comment]
已修正
非常感謝！
