### ISSUE TITLE
How to compile ygopro2

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1609]
can I get **exact** steps on how to setup an ygopro2 branch development environment?

**Comment by salix5** [comment]
I don't know much about ygopro2 branch.
Maybe you can ask @Fluorohydride .

**Comment by Zayelion** [comment]
@Fluorohydride

**Comment by Fluorohydride** [comment]
the project need following libraries:
libevent, lua5.2, sqlite3, opengl, glew, glfw3, glm, freetype2
on linux and osx, just install these libs by package manager, and then generate the project file using cmake.
on windows, i think you have to build and link these libs manually.

**Comment by Zayelion** [comment]
I'm on windows using Visual Studio, please walk me through it like I am a complete moron ^_^; the sub-teams around YGOPro use compiling it as a hazing technique for joining up. Its not eactly staightforward for people that are not programmers, and I've found that many people use their passion for YuGiOh to become programmers.

I understand what you said, and it answers my question fully, I am just asking for clarification for the sake of others.

**Comment by Moonlightsorrow** [comment]
How do i exactly compiler ygopro2.

**Comment by meijieru** [comment]
@Fluorohydride lacking CMakeLists.txt at directory `netc` and `ocgcore`

**Comment by blakat360** [comment]
I am having the same issue. I am on Arch Linux. I can't seem to get premake4, so I tried premake5 but ran into issues as the install command couldn't open ocgcore.

I then tried cmake. It complained about the add_subdirectory(ocgcore) call as it contained no CmakeLists.txt file. 

I then subbed this out for an include_directories call, and cmake terminated fine. However, when I call make, I get the following errors.

```bash
n file included from /home/sigkill/src/ygopro/gframe/deck_con.cpp:1:
/home/sigkill/src/ygopro/gframe/config.h:79:10: fatal error: ../ocgcore/ocgapi.h: No such file or directory
   79 | #include "../ocgcore/ocgapi.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [gframe/CMakeFiles/ygopro.dir/build.make:161: gframe/CMakeFiles/ygopro.dir/deck_con.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/sigkill/src/ygopro/gframe/client_field.h:4,
                 from /home/sigkill/src/ygopro/gframe/client_field.cpp:2:
/home/sigkill/src/ygopro/gframe/config.h:79:10: fatal error: ../ocgcore/ocgapi.h: No such file or directory
   79 | #include "../ocgcore/ocgapi.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [gframe/CMakeFiles/ygopro.dir/build.make:135: gframe/CMakeFiles/ygopro.dir/client_field.cpp.o] Error 1
In file included from /home/sigkill/src/ygopro/gframe/deck_manager.h:4,
                 from /home/sigkill/src/ygopro/gframe/deck_manager.cpp:1:
/home/sigkill/src/ygopro/gframe/config.h:79:10: fatal error: ../ocgcore/ocgapi.h: No such file or directory
   79 | #include "../ocgcore/ocgapi.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/sigkill/src/ygopro/gframe/client_card.h:4,
                 from /home/sigkill/src/ygopro/gframe/client_card.cpp:1:
/home/sigkill/src/ygopro/gframe/config.h:79:10: fatal error: ../ocgcore/ocgapi.h: No such file or directory
   79 | #include "../ocgcore/ocgapi.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [gframe/CMakeFiles/ygopro.dir/build.make:174: gframe/CMakeFiles/ygopro.dir/deck_manager.cpp.o] Error 1
In file included from /home/sigkill/src/ygopro/gframe/data_manager.h:4,
                 from /home/sigkill/src/ygopro/gframe/data_manager.cpp:1:
/home/sigkill/src/ygopro/gframe/config.h:79:10: fatal error: ../ocgcore/ocgapi.h: No such file or directory
   79 | #include "../ocgcore/ocgapi.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [gframe/CMakeFiles/ygopro.dir/build.make:122: gframe/CMakeFiles/ygopro.dir/client_card.cpp.o] Error 1
make[2]: *** [gframe/CMakeFiles/ygopro.dir/build.make:148: gframe/CMakeFiles/ygopro.dir/data_manager.cpp.o] Error 1
In file included from /home/sigkill/src/ygopro/gframe/game.h:4,
                 from /home/sigkill/src/ygopro/gframe/drawing.cpp:1:
/home/sigkill/src/ygopro/gframe/config.h:79:10: fatal error: ../ocgcore/ocgapi.h: No such file or directory
   79 | #include "../ocgcore/ocgapi.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [gframe/CMakeFiles/ygopro.dir/build.make:187: gframe/CMakeFiles/ygopro.dir/drawing.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:134: gframe/CMakeFiles/ygopro.dir/all] Error 2
make: *** [Makefile:104: all] Error 2
```

**Comment by ygodueltech** [comment]
@blakat360  did you run `git submodule update --init --recursive` ?

I use arch and I have gotten it to build.

I encountered linking issues and had to follow these instructions to build lua:
  
https://github.com/Fluorohydride/ygopro/issues/2298
```
wget -O - https://www.lua.org/ftp/lua-5.3.5.tar.gz | tar zfx -
cd lua-5.3.5
sed -i '9c CC= g++' src/Makefile
sed -i '22c MYCFLAGS=-x c++' src/Makefile
sed -i '31c LUA_A=	liblua5.3-c++.a' src/Makefile
sed -i '44c TO_LIB= liblua5.3-c++.a' Makefile
sudo make linux install
```

(Instead of the sed I manually edited to prevent it from overwriting system lua)


then I needed edits for new cjk font paths, my PR has already been merged to fix that! So just make sure you have latest master
https://github.com/Fluorohydride/ygopro/pull/2346
