### ISSUE TITLE
Expanding documentation on ygopro-core

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1613]
As I work on another project I want to expand the documentation on ygopro-core, if anyone has somethings that they want more information on regarding how the core works or they feel should be written down to help others Please note it here and I'll get on it.

If there is any inaccuracies let me know.

**Comment by anshkumar** [comment]
I'm building a new front-end for ygopro https://github.com/anshkumar/yugioh-glaze
I've also uploaded a screenshot there. Actually the current README on ygopro-core does not provide much of the information, I've to go through the ygopro sample gui everytime I've understand a new concept.  There are many features I would like to see in  the documentation. I think the exposed functions in the documentation should have a basic example with them. Also I would like to see a block diagram about the working of the core, I will be really helpful.

**Comment by Zayelion** [comment]
We should have a team working on the lua documentation also, Im gonna push for a separate set of documents and put some of my team on writing things up. I'll look over the code you have there.

Im building a back end at https://github.com/Zayelion/exodius-core and @IceYGO has https://github.com/IceYGO/ygosharp @garymabin has https://github.com/garymabin/JYGOServer

All are farther along in understanding the core Im documenting as I build.

**Comment by anshkumar** [comment]
I appreciate your efforts. Feel free to ask question on my repository.  Yes, we should've someone working on the Lua documentation, with some examples of creating complex cards.

**Comment by Zayelion** [comment]
how to compile it would be a good start, my team is excited to test it.

**Comment by anshkumar** [comment]
It's made in Qt( http://www.qt.io/ )
If your on a Linux platform, you can find it in your repository or else download it from the website above. Then compile it in the IDE of the Qt. Copy /pics, /single, /script, cards.cdb and strings.conf to the compiled directory. You will be needing two more folder which I can send you by email when you've done these steps.
Who is in your team ?

**Comment by Zayelion** [comment]
There are 25 people in my team room including myself, this isnt the full list, others help.
    @0mniMage
	@7Se7eN7
	@adrianojn
	@AlexHoQuan
	@ChibiChanNya
	@CollateralDamage
	@GuybrushThreepwoodSD
	@HelixReactor
	@IrateGod
	@Laughing-Luna
	@LordVyro
	@MistressMele
	@OneShot119
	@ParryDox
	@RagnaEdge
	@Raynard-Jordan
	@StormWulf
	@Tragoedia
	@westcoastkiwi
	@Xtremeenigma

**Comment by azispratama92** [comment]
Can i join the team ?
i'll can share all my knowledge in *.lua scripting ^ ^.
