### ISSUE TITLE
BUG：彼岸怪兽在控制权转移时存在问题

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1616]
![image](https://cloud.githubusercontent.com/assets/13391795/11318928/3c96a064-90a1-11e5-83d1-37505babd5f7.png)
我场上有彼岸怪兽1只，对方有非彼岸怪兽若干

我发动强制转移

![image](https://cloud.githubusercontent.com/assets/13391795/11318933/5fec8b8c-90a1-11e5-864a-4a9ebde06989.png)
彼岸怪兽自爆进了墓地，但被转移过来的对方怪兽的数值变成了和那只彼岸一样，变成守备表示，能发动原有的效果

**Comment by salix5** [comment]
可否提供錄像
