### ISSUE TITLE
Request to modify CalculateDamage function

### ISSUE THREAD

**Issue by MichaelLawrenceDee** [Fluorohydride/ygopro#1618]
I've been noticing this function and it doesn't allow nil values for the attack target. Thus, allowing direct attacks. Can you please allow this?
Duel.CalculateDamage(a,d)

**Comment by MichaelLawrenceDee** [comment]
So, anything?

**Comment by salix5** [comment]
Damage Calculation is used in effects that directly jumps to damage calculation between a and d, such as Gagaga Samurai.

If you just want to change battle target, maybe you should try another function.

**Comment by MichaelLawrenceDee** [comment]
I'm not trying to change battle target. I'm trying to perform a direct attack outside the Battle Phase. And Inflicting Damage with an effect equal to its ATK performs a different outcome.
