### ISSUE TITLE
其实应该在某些地方标明苏生限制状态

### ISSUE THREAD

**Issue by ghost** [Fluorohydride/ygopro#1626]
满足以下的全部条件的怪兽我认为需要标注苏生限制未满足的状态。
1、具有EFFECT_REVIVE_LIMIT，且不是STATUS_PROC_COMPLETE的状态
2、不存在于LOCATION_DECK或者LOCATION_HAND
3、不存在于LOCATION_EXTRA，或者表示形式是POS_FACEUP

具有EFFECT_REVIVE_LIMIT，但已是STATUS_PROC_COMPLETE的状态，且满足上述的2与3条件的怪兽，也可以去标注苏生限制已满足的状态，但这一部分其实是可选的。

方案1：显示符号。
怪兽区［?］× → 苏生限制未满
墓地［?］○ → 苏生限制满足
怪兽区［?］(?)○ → 苏生限制满足

方案2：颜色
墓地［?］ (0xffff0000，红色) → 苏生限制未满
墓地［?］ (颜色不设) → 苏生限制满足
怪兽区［?］(?) (颜色不设) → 苏生限制满足 + 控制者与持有者相同
怪兽区［?］(?) (0xffff0000，红色) → 苏生限制未满 + 控制者与持有者相同
怪兽区［?］(?) (0xff0000ff，蓝色) → 苏生限制满足 + 控制者与持有者不同
怪兽区［?］(?) (0xffff00ff，紫红) → 苏生限制未满 + 控制者与持有者不同

以上的两个方案其实有个共同的难点，那就是在前台的部分，如何判断一张卡是否受到EFFECT_REVIVE_LIMIT的影响，如何判断一张卡是不是STATUS_PROC_COMPLETE。

ClientCard\* 是没有这两个属性的，必须要在前台设置某种方式，能够把 ClientCard\* 转化为 Card\* ，这样就可以判断了。

标注苏生限制状态也是为了玩家方便的举动，如果可以的话，也能在卡图上作特殊记号来表示，比如添加一个新的icon，贴到场上的所有苏生限制未满的卡片上，同时在所有地方的【怪兽区[3]】部分的背景贴上那张图。

**Comment by Tianchenglipu** [comment]
@salix5  我自己不会实现，你知道怎么把 ClientCard* 转化为 Card* 吗╮(╯▽╰)╭如果会的话，我就能做出上述的方案2了

**Comment by mercury233** [comment]
done
