### ISSUE TITLE
Scripting request : fusion tag

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1630]
Dear Fluoro,

i have a request about scripting card. Could you help me to scripting "Fusion Tag"?

yugioh.wikia.com/wiki/Fusion_Tag

**Comment by destdev** [comment]
I'm quite sure everybody has seen that card by now and is aware, that it's currently impossible (at least I've found no way so far) to script that, thus just wait until a solution is pushed...
just go for a normal name change prisma like as a workaround for now, there's not too much stuff out there that could be abused with fusion specific names atm outside of fusion summoning anyway
...
it's not like we wouldn't have to use not 100% working workarounds for other prereleased cards as well (looks at Blue-Eyes Spirit Dragon ...) but waiting patiently until the official release of those usually helps, fluoro usually has a solution by then ... or at least not too much later

**Comment by mercury233** [comment]
VanillaSalt added(https://github.com/Fluorohydride/ygopro-core/commit/e0f00fd5b6ccde16b0bb3153177cfd8a6fd38673) `EFFECT_ADD_FUSION_CODE` already, so it is very easy to script it now.
https://github.com/Daniel17173/ygopro/blob/master/unofficial/script/c5866.lua

**Comment by destdev** [comment]
oh, so that's what this code is for^^
kinda drowned in other things last week...
@mercury233 what is this flag effect doing there, I fail to see the reason for its existance ...
and a minor thing, there's a tp parameter at the end of your fusion selection, which shouldn't be there

**Comment by mercury233** [comment]
@destdev Thanks, fixed. I copied the script from Djinn Releaser of Rituals to make the target card show a hint, but it seems that it isn't necessary...

**Comment by salix5** [comment]
Done.
