### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1633]
Themes 
--
@IceYGO has the code done already here :
- https://github.com/IceYGO/ygopro/commit/b7075985e44da5ce6bccfab68e1c74f135b4130c
- https://github.com/IceYGO/ygopro/commit/9df6b558b1a1eca05d0d69003a4e03a78a8f7b81
- https://github.com/IceYGO/ygopro/commit/8a28b8dd919d75a684de7a031e5d35b44fd16d86
- https://github.com/IceYGO/ygopro/commit/8bb96e3ac3e8b85b582214eda28cdbcb44f43134
- https://github.com/IceYGO/ygopro/commit/6cebb7d4d67bfc3ec88b23b9cf6fdcad289015fe

It needs to be reviewed and added to the source 
@adrianojn
@sidschingis

**Comment by IceYGO** [comment]
I may create a Pull Request in the next few hours. I will merge with the latest version and try to clean as much as I can first.

**Comment by Zayelion** [comment]
When you do be sure to provide visual assets, and screenshots of what it renders as (in Japanese/Chinese)
