### ISSUE TITLE
Sounds and Music

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1634]
## Music
- https://github.com/sidschingis/Dev_ygopro/commit/dca13aeab3ff7df536b8ea313652ecdfce1508b7
- https://github.com/sidschingis/Dev_ygopro/commit/3dc2c474de67c75cf8e8f7148ef4c7caacdcb0b9
## Sounds
- https://github.com/Buttys/ygopro/commit/7f86c719598c2e3d04bd95968c4bcd1db0898daf
- General massive change worth reviewing [ https://github.com/Buttys/ygopro/commit/3f98f645bb874e4b306b727d2a05eea5ca36bfc6 ]
## Controls
- https://github.com/Buttys/ygopro/commit/a8a30be6779238a70cd58df84f7155c19d2c96b9
- https://github.com/Buttys/ygopro/commit/ad65b336fe39d181c9beff29b85be347a8f0f752

**Comment by Zayelion** [comment]
I remember there being some contention on the use of the `PlaySound` function because it was proprietary or something of that nature?

**Comment by Zayelion** [comment]
Update : http://www.ambiera.com/irrklang/license.html
@Fluorohydride
@VanillaSalt
@salix5 

Are you guys ok with this license?

**Comment by IceYGO** [comment]
Personally, I am against irrKlang because they are not open-source. All the libraries used by YGOPro are open-source and should remain so.

**Comment by Zayelion** [comment]
I found a way of doing it using windows' built in headers but the sounds dont overlap and its ofcourse windows specific which Im against.

**Comment by DailyShana** [comment]
It seems has been done?

**Comment by mercury233** [comment]
it will be better to add another sound engine support
