### ISSUE TITLE
BUG - Dodger Dragon effect is not working

### ISSUE THREAD

**Issue by elmargomez** [Fluorohydride/ygopro#1636]
I played an AI game then I normal summoned "Dodger Dragon" as said in the effect
```
The normal summon of this card cannot be negated. Your opponents cannot activate a counter trap cards...
```
But still the AI is able to activate Bottomless Trap Hole.

**Comment by mercury233** [comment]
But "Bottomless Trap Hole" isn't a COUNTER trap card.

**Comment by elmargomez** [comment]
Oh I see.
