### ISSUE TITLE
Issue with SetUniqueOnField and Kaiju

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1642]
Kaiju state, that there is can only be 1 Kaiju MONSTER. SetUniqueOnField checks the whole field, but according to the wording you should be able to control both, a Kaiju Monster and a Kaiju monster equipped by something (for example Relinquished).

Thus I'd like to ask for a function similar to SetUniqueOnField that only checks monster zones (or add a parameter to that function that does so). That would also help to provide a solution for that ugly effect chaos in Malefic monster scripts, which I'd like to avoid seeing in Kaiju ...

**Comment by nekrozar** [comment]
Konami has answered, "If Earthbound Immortal and Malefic are equipped, Earthbound Immortal and Malefic can be Normal or Special Summoned."
So, you need something to replace the SetUniqueOnField.

Konami's Answer.
遊戯王OCG事務局です。

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。

Q.
「D-HERO Bloo-D」の効果で装備されている「Sin 青眼の白龍」がフィールドに既に存在する場合、手札から「Sin レインボー・ドラゴン」を特殊召喚できますか？
また、「D-HERO Bloo-D」の効果で装備されている「地縛神 Ccapac Apu」がフィールドに既に存在する場合、手札から「地縛神 Uru」を通常召喚できますか？
A.
ご質問の場合、「Sin レインボー・ドラゴン」「地縛神 Uru」どちらも特殊召喚する事ができます。

**Comment by destdev** [comment]
Thank you for searching out that Konami Q&A.
Yes, this is exactly what I have in mind. "something to replace SetUniqueOnField".
So far we can only make a copy of that Malefic code chaos to fix that (for both Earthbound Immortals and Kaiju), but with all the monsters already out there that needs this one it would make sense to have a function like "SetUniqueMZone" or whatever you want to call that.

**Comment by salix5** [comment]
@nekrozar 
What about cards like 六武衆の師範? (「六武衆の師範」は自分フィールド上に１枚しか表側表示で存在できない。)
Can you help us check this part?

**Comment by destdev** [comment]
According to the current english card text you can only control 1 on your side of the field (thus SetUniqueOnField works just fine for that one)

**Comment by nekrozar** [comment]
Confiming about Grandmaster of the Six Samurai's rule.
In Konami's Data Bese, if Unicorn Spear is equipped, Unicorn Spear cannot be Normal or Special Summoned.
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12595
Q.装備カード扱いとして自分のフィールド上に「ZW－一角獣皇槍」が存在している場合、モンスターとして「ZW－一角獣皇槍」を召喚する事はできますか？
A.装備カード扱いとして「ZW－一角獣皇槍」が自分フィールド上に存在している場合、手札から表側表示で「ZW－一角獣皇槍」を召喚する事はできません。

なお、手札からセットする事はできますが、後からセットしたその「ZW－一角獣皇槍」は、表側表示になった場合にはその時点でただちに破壊されます。

**Comment by destdev** [comment]
This is exactly what SetUniqueOnField does, and this is why I said that the function as it currently exists works just fine for Grandmaster.

**Comment by destdev** [comment]
this is fixed with the reworked uniqueonfield function now, thank you
