### ISSUE TITLE
Problem with chain attacks and attack negation

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1643]
If you negate any chain attack you can simply perform that negated attack again.

To reproduce this:
1. Perform your usual attack with BLS or any other card that uses the ChainAttack() command. Do NOT negate that attack.
2. Trigger and perform the chain attack. Negate that attack with Necro Gardna / Tri-Eyed Dice / any other attack negation that doesn't end the battle phase.
3. You are now able to attack again, this should not happen.

**Comment by salix5** [comment]
ygo-core@9ffc3d60f3748c92f7c0cfe1d52cd3d20b392e61
fixed
Thank you.
