### ISSUE TITLE
Cannot select another monster in some case when ritural summoning using Shurit Nekroz

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1644]
I have one "Shurit, Strategist of the Nekroz" in hand, another Shurit in grave.
I active "Nekroz Mirror" to spsummon "Nekroz of Brionac".
I want to use both Shurit as material, but when i select one Shurit, the selection is over.

The same thing happens when i active "Nekroz Cycle" when one Shurit in hand, and one "Djinn Releaser of Rituals" in graveyard.

**Comment by salix5** [comment]
@VanillaSalt 
Can you help to check this problem?

**Comment by salix5** [comment]
fixed
