### ISSUE TITLE
Cannot know chain order when there are same name cards in a chain

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1645]
Tribute "Super Quantum Mecha Pilot Red Layer" to summon another Red Layer, active effect of both cards, and you'll got:
![image](https://cloud.githubusercontent.com/assets/13391795/12085947/6582e10a-b300-11e5-845c-492c39eeb801.png)

The same problem happens when synchro summoning "Metaphys Horus" using a pendulum monster.

**Comment by salix5** [comment]
目前想到的方式有在下面新增一個欄位顯示那張卡目前的位置
或是你有什麼建議?

**Comment by mercury233** [comment]
我的想法是，询问是否发动卡片时，选择要发动的效果时，和选择顺序时，都显示卡片位置和卡片的效果描述（通过e1:SetDescription设定的那个）
