### ISSUE TITLE
The effect of "T.G. Hyper Librarian" and "Battlin' Boxer Lead Yoke" don't work after update

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1646]
T.G. Hyper Librarian don't draw card when syn summoning, Battlin' Boxer Lead Yoke don't add attack when xyz material was detached.
After reverting https://github.com/Fluorohydride/ygopro-core/commit/85d2b687cdbb4a3bb925a06cf66f0a46c1f08e08, everything return to normal.

**Comment by salix5** [comment]
@VanillaSalt

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/5ba3e29848fc62f470da12d2ff99dc50b8babaa8
seems fixed.
