### ISSUE TITLE
Store .yrp-files without compressing them

### ISSUE THREAD

**Issue by IrateGod** [Fluorohydride/ygopro#1650]
I am currently going through the entire specification of the LZMA SDK just to find a way to decompress the Replay Files stored in ygopro/replay with a language that hasn't implemented the decompression algorithm (yet).

I would love to hear the reasoning behind compressing these files (memory space can no longer be a valid reason), and would propose to store them in a legible format.

**Comment by IceYGO** [comment]
I don't think there is any valid reason to compress them other than saving some bytes.
I'm not against removing the compression but I'm not against keeping it either.

What language that does not have LZMA-support are you using, out of curiosity?

**Comment by Zayelion** [comment]
We are working on JavaScript implementations (ofcourse) the modules dont expose all the ways of compressing or decompressing information. LZMA isnt used in the JavaScript community that much, ZIP is which is built into the nodejs core via zlib.

https://www.npmjs.com/package/lzma
