### ISSUE TITLE
Commit rights for IceYGO

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1652]
@Fluorohydride could you give @IceYGO commit access to `ygopro` and `ygopro-core`. He has expertise and a few years experience making edits to the gframe. The international groups outside of Asia for all our disagreements and all the infighting we have had he has helped all groups and maintained our clients and servers allowing our existence at all. Please view him the same way as @Zh99998.

**Comment by IceYGO** [comment]
Closing this. Thanks!
