### ISSUE TITLE
Illegal Move

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1653]
https://www.youtube.com/watch?v=W0KmWa35Cb8

**Comment by DailyShana** [comment]
>●３体：相手が発動したカードの効果は無効化される。
http://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=6485&request_locale=ja

The effect of Cyber Blader has been modified, so this infinite loop will not occur.
