### ISSUE TITLE
BUG: 用怪兽 + 效果搜索不到反转或调整或同调或超量怪兽

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1655]
Cannot found Flip/Tuner/SYN/XYZ monster when searching with Monster + Effect

![image](https://cloud.githubusercontent.com/assets/13391795/12324213/0c30da0e-bafc-11e5-9ab6-1a9a07d6f4be.png)
![image](https://cloud.githubusercontent.com/assets/13391795/12324217/1420f5d2-bafc-11e5-9077-26c1af62fb6c.png)

**Comment by salix5** [comment]
3966279c6858b5c54ce43a62de9340caa11be638
目前改成會搜尋所有類型包含效果怪獸的卡
