### ISSUE TITLE
Case Sensitivity : Cards that Require Name Declaration Broken Fail Seach

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1658]
In cases of cards like Archfiend Oath, in English atleast the case sensitivity is bugged.

If capitalization is off:
![http://puu.sh/mmcZA/a730533dbb.jpg](http://puu.sh/mmcZA/a730533dbb.jpg)

If spelled and cased correctly
![http://puu.sh/mzL5h/105022ae2a.jpg](http://puu.sh/mzL5h/105022ae2a.jpg)

a fix can be found here :
https://github.com/Buttys/ygopro/commit/e117936e24ebcd091a68d1c5f6b492bd7df4d970#diff-249012b053d63d10e4cc07838658c267

**Comment by Zayelion** [comment]
From a user:
> When I activate mind crush, the list and search bars are extremely limited.

From a user :
> I believe this might be a problem with other card declaration effects .. i couldn't declare any of the sylvan monsters, tried with capital letters but could only declare the spells.. couldn't find lonefire either
![https://i.gyazo.com/9022f799deab2ea06cfe31edfce7ff0d.jpg](https://i.gyazo.com/9022f799deab2ea06cfe31edfce7ff0d.jpg)

**Comment by Zayelion** [comment]
https://github.com/Fluorohydride/ygopro/pull/1663

**Comment by salix5** [comment]
My opinion:
Case sensitive is not a bug, since the card names in the official database do have uppercase and lowercase letters, and  the names are case sensitive.
I believe that XYZ-Dragon Cannon is not an "Xyz" card without further mention is an example.
