### ISSUE TITLE
BUG: Face-down "Yang Zing Creation" cannot use effect when monster destroyed in chain 2.

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1665]
I have face-down "Yang Zing Creation", face-down "Monster Reborn", and a monster on field, in oppent's turn.
Oppent use "Mystical Space Typhoon" to destroy my "Monster Reborn", and chain "Offerings to the Doomed" to destroy my monster.
After the chain is resolved, I got a message to active "Yang Zing Creation", but after I actived it, nothing happens.

If the oppent active "Offerings to the Doomed" in chain 1, everything goes fine, I can spsummon Yang Zing from deck.

**Comment by salix5** [comment]
aa35d60ecfbbcba10c06eb7bd9ddad98643f44f9
已修正
謝謝
