### ISSUE TITLE
Attack lock vs unaffected cards

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1667]
Have any attack lock (2x Watthopper, 2x Marauding Captain, 2x Gentlemander, etc). Then have any Monster on the other side of the field that is unaffected (Vennominaga, Raidraptor - Ultimate Falcon, etc).
When looking for an answer I can't find any statement from Konami to that issue, the closest thing to that I could find was an e-mailed ruling from somewhere in the TCG area:
"Vennominaga the Deity of Poisonous Snakes" cannot target an "Earthbound Immortal" for an attack. The attack restriction is placed on the player, not the monster."
The reason stated (and also from the logical side when looking at the card text) is, that the player is targeted, not the monster.
Unaffected monsters are currently able to attack through a lock like that, which contradicts this.
I also find contradicting statements regarding that question.

Is there any official answer from OCG Konami regarding that matter that says othervise? If yes, what's the reason?

I'd side with the statement, that those unaffected monsters still can't attack, but I'm quite unsure if a fix for that is even necassary because of all those contradicting statements ...

**Comment by mercury233** [comment]
> Ｑ：《ジェントルーパー》が相手フィールドに２体存在する時でも、このカードは相手の《ジェントルーパー》や他のモンスターを攻撃することはできますか？
> Ａ：はい、攻撃できます。(14/10/17)
http://yugioh-wiki.net/index.php?%A1%D4%C6%C7%BC%D8%BF%C0%A5%F4%A5%A7%A5%CE%A5%DF%A5%CA%A1%BC%A5%AC%A1%D5=

wiki says that Vennominaga can attack when two Gentlemander in effect.

**Comment by nekrozar** [comment]
FAQ 1:
> http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8050&keyword=&tag=-1
> Question
> 自分ターンにて、相手が「カバーカーニバル」を発動し、「カバートークン」を特殊召喚しました。
> 
> その際、自分フィールドに「禁じられた聖槍」の効果が適用され、魔法カードの効果を受けないモンスターが存在する場合、そのモンスターで「カバートークン」を攻撃対象に選択する事はできますか？
> Answer
> 相手が「カバーカーニバル」を発動したターン、自分フィールドのモンスターには、『このカードの発動後、ターン終了時まで相手は「カバートークン」以外のモンスターを攻撃対象にできない』効果が適用されます。
> 
> 「禁じられた聖槍」の効果が適用されたモンスターは、他の魔法カードの効果を受けませんので、『このカードの発動後、ターン終了時まで相手は「カバートークン」以外のモンスターを攻撃対象にできない』効果の影響を受けず、「カバートークン」以外のモンスターを攻撃対象に選択する事ができます。 

FAQ 2:
> http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8033&keyword=&tag
> Question
> 相手のモンスターゾーンに「ゴーストリック・デュラハン」と「ゴーストリック・サキュバス」が表側表示で存在しています。
> 
> この場合、「ゴーストリック・サキュバス」の『自分フィールド上にこのカード以外の「ゴーストリック」と名のついたモンスターが存在する場合、相手はこのカードを攻撃対象にできない』効果が適用されますが、「神竜騎士フェルグラント」の『①：１ターンに１度、このカードのX素材を１つ取り除き、フィールドの表側表示モンスター１体を対象として発動できる。このターン、対象のモンスターは効果が無効になり、このカード以外の効果を受けない。この効果は相手ターンでも発動できる』効果が適用されている自分のモンスターは「ゴーストリック・サキュバス」を攻撃対象に選択できますか？
> Answer
> 「ゴーストリック・サキュバス」の『相手はこのカードを攻撃対象にできない』効果はモンスターに適用される効果となります。
> 
> したがって、「神竜騎士フェルグラント」の効果が適用され、カードの効果を受けない状態のモンスターであれば、「ゴーストリック・サキュバス」を攻撃対象に選択する事ができます。 

"Your opponent cannot target" effect applies to monster.
Therefore unaffected monster(Vennominaga etc) can attack Hippo Token, Ghostrick Socuteboss or other monsters when Hippo Carnival, Ghostrick Socuteboss in effect.
This is also true for two Marauding Captain, Watthopper, Gentlemander etc.

Maybe TCG rule is different from OCG rule.

**Comment by destdev** [comment]
ok, thanks for that, we'll stick with ocg then
