### ISSUE TITLE
Bug: changing control of a trap monster with full s/t zone

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1671]
Situation:
You control 4 s/t, destroy Graydle Alligator with a spell while the opponent controls a trap monster.
![trapmonster1](https://cloud.githubusercontent.com/assets/12686731/12827057/36e6825c-cb7e-11e5-95af-7110a7def99f.jpg)
now you can take control of the trap monster with Alligator (and thus a full s/t zone)
![trapmonster2](https://cloud.githubusercontent.com/assets/12686731/12827122/7929586a-cb7e-11e5-8d19-f0d8105ff5ae.jpg)
the required s/t zone will get occupied once any of the s/t leaves the field

I've only managed to find old rulings from UDE for this, but that should still apply now:
If you have a full s/t zone you should be unable to take control of an opponents trap monster, since you require an empty s/t zone for that.

**Comment by DailyShana** [comment]
fixed in https://github.com/Fluorohydride/ygopro-scripts/commit/43b31de37bff2462b1f410e37b148ca884775bc5
