### ISSUE TITLE
Is there a way to set monster's "Normal summoned"/"Special summoned" status in single mode lua?

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1672]
`Debug.AddCard` seems don't have a param for setting this.
It is needed by cards like Apoqliphort Towers.

**Comment by DailyShana** [comment]
```
c1=Debug.AddCard(...)
c1:SetStatus(...)
```

**Comment by mercury233** [comment]
@DailyShana Which status code should I use? I tried `STATUS_SPSUMMON_TURN` and it doesn't work.

**Comment by DailyShana** [comment]
<del>STATUS_SUMMON_TURN</del>
sorry, there is no way to change summon type in lua
it seems that the initial summon type for cards in puzzle mode is something like `0xffffffff`

**Comment by mercury233** [comment]
In fact, when I test this single lua, the spsummon status seems random..

`--
Debug.SetAIName("尸体")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)
Debug.AddCard(52068432,0,0,LOCATION_MZONE,0,POS_FACEUP_ATTACK) --三叉龙之影灵衣
--local c=Debug.AddCard(52068432,0,0,LOCATION_MZONE,0,POS_FACEUP_ATTACK) --三叉龙之影灵衣
--c:SetStatus(STATUS_SPSUMMON_TURN,true)
Debug.AddCard(27279764,0,0,LOCATION_MZONE,1,POS_FACEUP_ATTACK) --物质主义
Debug.AddCard(52687916,0,0,LOCATION_MZONE,2,POS_FACEUP_ATTACK) --三叉龙
Debug.AddCard(82944432,0,0,LOCATION_MZONE,3,POS_FACEUP_ATTACK) --机甲忍者
Debug.AddCard(4335427,0,0,LOCATION_HAND,0,POS_FACEUP_ATTACK) --创星神
Debug.AddCard(9373534,0,0,LOCATION_HAND,1,POS_FACEUP_ATTACK) --风魔手里剑
Debug.AddCard(4392470,1,1,LOCATION_MZONE,2,POS_FACEUP_ATTACK) --狮子男巫
Debug.ReloadFieldEnd()
aux.BeginPuzzle()
`

**Comment by DailyShana** [comment]
`STATUS_SPSUMMON_TURN` does not mean the card is spcecial summoned, it only emphasis it is spsummoned in this turn

**Comment by DailyShana** [comment]
the `summon_info` is not initialized in the constructor of a `card` type variable, so when a card is put on the field at the beginning, the summon type(`=summon_info & 0xff00ffff`) is not 0 but something like `0xcd00cdcd`, which contains `SUMMON_TYPE_SPECIAL`.
