### ISSUE TITLE
Exodius the Ultimate Forbidden Lord 's "win" shouldn't by copied by Phantom of Chaos

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1673]
> ■『このカードの②の効果で「封印されし」モンスター５種類が自分の墓地へ送られ全て揃った時、自分はデュエルに勝利する』はモンスターの効果の扱いではありません。カードによって定められた勝利条件となります。（テキストに記された方法で「封印されし」と名のついたモンスター5種類が全て揃った際にチェーンブロックが作られる事はありません。）
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=7392

Now it's win effect is along with send to grave effect, I don't know how to separate it.

**Comment by salix5** [comment]
已修正
非常感謝
