### ISSUE TITLE
SummonType seems shouldn't be reset when a monster become face-down and flip again

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1676]
FAQs say:
> シンクロ召喚された「幻竜星－チョウホウ」が裏側守備表示になった後に戦闘や効果で破壊され墓地へ送られた場合でも、『デッキからチューナー１体を手札に加える』効果を発動する事ができます。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=15149

and

> 既に1度効果を発動している「レッド・ワイバーン」が、その後に裏側守備表示になった場合、再び表側表示に戻った際には、もう1度効果を発動できるようになります。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=16839

It seems that SYN/XYZ summoned status shouldn't be reset when a monster become face-down.

**Comment by salix5** [comment]
已修正
謝謝
