### ISSUE TITLE
The dialog is confusing when using Nekroz Mirror with Shurit in grave

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1677]
I have a Nekroz Shurit in grave, Brionac and Trishula in hand. I want to use the effect of Shurit to summon Trishula with Shurit only. After I active Nekroz Mirror and select Shurit to "release", I got
![image](https://cloud.githubusercontent.com/assets/13391795/12937778/170ceb3e-cfe7-11e5-8f85-d27d8b1dcfbb.png)
It was confusing, I don't know I can just click OK to finish the selecting.

Can we add a dialog like Shurit is in hand?
![image](https://cloud.githubusercontent.com/assets/13391795/12937853/f6f55718-cfe7-11e5-9b6f-9826064a2240.png)

**Comment by Zayelion** [comment]
Reword the text in the DB?

**Comment by mercury233** [comment]
That will be the last choice.

**Comment by Zayelion** [comment]
Its like this to for Qliphorts, and Mega Monarchs if I recall correctly. Its worded/coded negatively for some reason

**Comment by DailyShana** [comment]
Maybe we can change the name of that button to "Cancel", which indicates that the player can click this button to cancel the selection

**Comment by Zayelion** [comment]
Its more of a "Done?" question,...

**Comment by mercury233** [comment]
Well, a tmp fix here
https://github.com/mercury233/ygopro-scripts/commit/76e5821c5172eaf54a92c1182ef702a5ad43e1e4
