### ISSUE TITLE
Bug: cannot declare Legendary Dragon

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#1679]
Konami's answer, you can declare "Legendary Dragon Timaeus".
But, I cannot declare "Legendary Dragon Timaeus", "Legendary Dragon Hermos" or "Legendary Dragon Critias".
(Legendary Dragon's type are 16384.)
> http://yugioh-wiki.net/index.php?%A1%D4%A5%C6%A5%A3%A5%DE%A5%A4%A5%AA%A5%B9%A4%CE%B4%E3%A1%D5#faq
> Ｑ：《森羅の守神 アルセイ》の効果で《伝説の竜 ティマイオス》と宣言できますか？
> Ａ：はい、宣言できます。(14/06/22)

**Comment by VanillaSalt** [comment]
type=16386

**Comment by nekrozar** [comment]
Sorry, I made a mistake.
Thank you!
