### ISSUE TITLE
Bug: The effect 1 of "Ruins of the Great Divine Dragon" shouldn't active when the monster zone was empty and one level 8 dragon is spsummoned.

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1680]
> Question
自分のモンスターゾーンにレベル7・8のドラゴン族モンスターが存在せず、「巨神竜の遺跡」が自分の魔法＆罠ゾーンに表側表示で存在しています。
「青眼の亜白龍」が『手札の「青眼の白龍」１体を相手に見せた場合に特殊召喚できる』方法によって手札から特殊召喚された場合、「巨神竜の遺跡」の『①：自分フィールドにレベル７・８のドラゴン族モンスターが存在し、墓地以外からモンスターが特殊召喚された場合に発動する。そのモンスターの効果はターン終了時まで無効化される』効果は発動しますか？
Answer
「巨神竜の遺跡」の『そのモンスターの効果はターン終了時まで無効化される』効果は、自分のモンスターゾーンにレベル7か8のドラゴン族モンスターが表側表示で既に存在している状態で、墓地以外からモンスターが特殊召喚された場合に発動する効果です。
質問の状況の場合、「青眼の亜白龍」が特殊召喚される際には、自分のモンスターゾーンにレベル7・8のドラゴン族モンスターが存在していない状態ですので、「巨神竜の遺跡」の効果は発動しません。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=18439&keyword=&tag=-1

But now it will active.

**Comment by destdev** [comment]
no it doesn't, at least with the latest script you can summon something like Blue-Eyes Alternate on an emty field without Ruins being triggered
it was fixed with this update https://github.com/Fluorohydride/ygopro-scripts/commit/0d3c7096f082dd6463e4d593c3f1b91268be519f

**Comment by mercury233** [comment]
sorry i forgot to check the latest fix
