### ISSUE TITLE
Bug: The effect of "Djinn Releaser of Rituals" applys to player himself in certain situations

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1681]
Replay:
http://mercury233.me/ygosrv233/Djinn%20Releaser%20BUG.zip

TO REPRODUCE THIS BUG, YOU CAN'T CHANGE ANY CARD IN THE OPERATION. It seems any change, such as change Scarm to Cir,  will prevent this bug to show.

After check, I found the `rp` become 2 here, which should be 0.
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c8903700.lua#L33

Edit: Another replay here
http://mercury233.me/ygosrv233/Djinn%20Releaser%20BUG%202.zip

**Comment by salix5** [comment]
ec0026c40706926bcb11ecc8d29dad4be176336e
目前暫定把EVENT_BE_MATERIAL事件reason effect/player的設定比照EVENT_SPSUMMON_SUCCESS
目前的設定：
reason effect：執行特召的效果
reason player；該效果發動時的控制者
event player：特召該怪獸的玩家

如果有類似融合之門等可以用對方的卡融合召喚/儀式召喚的效果
這兩個可能會不是同一個玩家
解放者目前改成使用event player
