### ISSUE TITLE
Bug: 特定场景下的内存访问违规

### ISSUE THREAD

**Issue by InvisibleMoon** [Fluorohydride/ygopro#1682]
在调试环境下运行时会抛出异常 —— HEAP: Free Heap block xxxxxxxx modified at xxxxxxxx after it was freed.

猜测野指针相关。使用 gflags 测试，千刀兵起效由墓地特招时，会触发内存访问异常。

![tmp](https://cloud.githubusercontent.com/assets/1255460/13151733/773dff78-d6a6-11e5-8e47-38719592cb2d.png)

还没进一步调试，估计和某个函数的实现有关。

**Comment by salix5** [comment]
這部分我不怎麼懂
可否詳細的解釋一下?
非常感謝！

**Comment by InvisibleMoon** [comment]
@salix5 
在以调试模式运行游戏时，程序开启一段时间后，会抛出此种形式的异常，“HEAP: Free Heap block xxxxxxxx modified at xxxxxxxx after it was freed”，其中 xxxxxxxx 为内存地址。
个人猜测，某处存在不正常的内存分配或使用，破坏了堆结构的完整性导致的。虽然不正确的地址写入未必导致崩溃，却是游戏崩溃的原因之一。
测试时个人临时编译了一个版本，此版使用 gflags 调试时，在千刀兵发效时必定触发断点，即相关流程中访问到不合法的位置。不过比较奇怪的是，官方编译的版本崩溃时机不同且随机，不知道是否与ASLR等机制有关。
（有关 gflags 的作用机理与用法，可参考 [http://advdbg.org/forums/3299/ShowPost.aspx](url)）
