### ISSUE TITLE
magician's rod/dark magic circle and the eye of timaeus

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1684]
Could I search "The Eye of Timaeus" with the effect of "Magician's Rod" or "Dark Magic Circle"?

Tnx in advance

**Comment by mercury233** [comment]
I think you should [ask KONAMI](http://www.yugioh-card.com/japan/support/) instead.

**Comment by destdev** [comment]
Definitly ask Konami about that one.
However I think you shouldn't be able to. The Eye of Timaeus mentions a "Dark Magician monster". The way "Dark Magic Circle" is worded in the translation atm I think the card in question has to address "Dark Magician" directly as a card, not just "Dark Magician" in its description. Else it would also work with several other cards that don't make any sense atm...

**Comment by salix5** [comment]
We do not have certain answer about unreleased cards.
Maybe you can ask Konami after they are released.
