### ISSUE TITLE
BUG: 天帝アイテール(Ehther the Heavenly Monarch) has a wrong count limit

### ISSUE THREAD

**Issue by MobiusMei** [Fluorohydride/ygopro#1685]
The 「'天帝 埃忒耳',96570609,'天帝アイテール','Ehther the Heavenly Monarch'」, currently in ygopro-scripts folder, has a count limit as "Once per turn per card", as "SetCountLimit(1)", for its self-summon effect.

However, the only limitation of the effect is "Once per chain per card", therefore should have a limit similarly with「'励辉士 入魔蝇王',46772449,'励輝士 ヴェルズビュート','Evilswarm Exciton Knight'」. In this case, the "SetCountLimit(1)" may cause a wrong operation in the duel. 
*e.g. When the self-summon effect is negated without destroyed, the player cannot activate the effect again later.

**Comment by salix5** [comment]
fixed
Thank you.
