### ISSUE TITLE
Cant purposely select certain level combinations for Ritual Summons

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#1690]
When summoning Black Luster Solider with Black Luster Ritual, you cant select combinations of monsters that exceed eight if one of the only two monsters in your hand is level eight. Black Luster Ritual and other older ritual cards do not limit the number of monsters used for the ritual.

**Comment by mercury233** [comment]
> •The number of Tributed monsters cannot be higher than necessary.
Example: If “Ritual of Destruction” is activated and its effect that says “You must also Tribute monsters whose total Levels equal 7 or more” resolves, you cannot Tribute a Level 7 and a Level 2 monster, as the Levels already add up to 7 or more with only 1 monster. You can Tribute a Level 5 and a Level 4 monster.

https://ygorganization.com/perfectrulebook/ 
Page 69
