### ISSUE TITLE
request : odd-eyes persona dragon

### ISSUE THREAD

**Issue by marikisthar** [Fluorohydride/ygopro#1692]
Dear fluoro team

could you scripting pre-released script of odd-eyes persona dragon?

yugioh.wikia.com/wiki/Odd-Eyes_Persona_Dragon

tnx in advance

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/blob/master/scripts/VJMP-JP/c100200114.lua
