### ISSUE TITLE
Black Garden issue

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1694]
Since we updated Devpro last sunday the effect of  Black Garden to halfe the attack and summon a token works only once per turn ... and I'm unable to see why :/
After the first summon:
![bg1](https://cloud.githubusercontent.com/assets/12686731/13766207/27d21172-ea60-11e5-9dc2-17a3637b4e83.jpg)
After 2 more summons:
![bg2](https://cloud.githubusercontent.com/assets/12686731/13766214/36e57852-ea60-11e5-8f6b-ae1fab3949e5.jpg)
Same with the opponents turn. It works only once, as you see, the deskbots and naturia beast didn't get halfed and no further token has been summoned.
It works perfectly fine with the update from a week before, so I asume it must be something done during last week. My best guess would be this https://github.com/Fluorohydride/ygopro-core/commit/8a91d4213a2e4b13ded21ec1f02e64deed68dc6a but it shouldn't affect Black Garden, or do I miss something?

The error report along with the replay is found here:
http://forum.ygodevpro.com/bugs/index.php/Issue/746-Black-garden-Bug/

**Comment by DailyShana** [comment]
line 14 `e4:SetCode(71645242)`
but `71645242 & EVENT_PHASE = 0x445383A & 0x1000~=0`

**Comment by salix5** [comment]
Fluorohydride/ygopro-core@75ba9362eac712dd30cabf8f1fb0fc262baacdcd
 Fluorohydride/ygopro-core@001540771ed77a522ee4b6e551f2f4edee108e17
Now EVENT_CARD+.... means that it is a special event named by card ID.
