### ISSUE TITLE
Bug: If confirmed the added card by Graverobber, player doesn't take damage.

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#1698]
Konami's answer, "If confirmed the added card by Graverobber, player take damage."
But I does't take damage.

> http://yugioh-wiki.net/index.php?%A1%D4%CA%E8%B9%D3%A4%E9%A4%B7%A1%D5#faq
> Ｑ：このカード効果で手札に加えた魔導書を相手に見せて手札の《魔導法士 ジュノン》の効果を発動した場合、ダメージを受けますか？
> Ａ：はい、自分は2000のダメージを受けます。(16/03/10)

Maybe we need something EVENT in order to solve this problem.

**Comment by nekrozar** [comment]
Konami doesn't know whether player takes damage if reveal the Iron Core of Koa'ki Meiru to add Graverobber by Iron Core Specimen Lab...

Mail:
遊戯王OCG事務局です。 

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。

Q. 
「鋼核合成獣研究所」の『このカードのコントローラーは自分のエンドフェイズ毎に、手札から「コアキメイルの鋼核」１枚を相手に見せる。または、見せずにこのカードを破壊する。』効果で「墓荒らし」の効果で手札に加えた「コアキメイルの鋼核」を相手に見せた場合、自分はダメージを受けますか？ 
A. 
この度頂きましたゲームルールに関するお問い合わせの件につきましては、ご案内する事のできる回答をご用意差し上げるまで、お時間を頂く場合がございます。
誠に恐縮ではございますが、お時間を空けて再度、お問い合わせ頂けますようお願い申し上げます。

**Comment by nekrozar** [comment]
I confirmed it once again.
Konami's answer, "If reveal the Iron Core of Koa'ki Meiru to add Graverobber by Iron Core Specimen Lab, player take damage."

Mail:
遊戯王OCG事務局です。 

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。 

Q. 
「鋼核合成獣研究所」の『このカードのコントローラーは自分のエンドフェイズ毎に、手札から「コアキメイルの鋼核」１枚を相手に見せる。または、見せずにこのカードを破壊する。』で 
「墓荒らし」の効果で手札に加えた「コアキメイルの鋼核」を相手に見せた場合、自分はダメージを受けますか？ 
A. 
ご質問の状況の場合、「墓荒らし」の効果でダメージ受ける事になります。

**Comment by DailyShana** [comment]
According to this, I think if the spell added to hand is revealed, player will not take damage.

**Comment by nekrozar** [comment]
> http://yugioh-wiki.net/index.php?%A1%D4%CA%E8%B9%D3%A4%E9%A4%B7%A1%D5
> Ｑ：《鋼核合成獣研究所》のエンドフェイズ時の維持コストとして、このカードの効果で手札に加えた《コアキメイルの鋼核》を相手に見せた場合、自分はダメージを受けますか？
> Ａ：いいえ、受けません。(16/10/31)
