### ISSUE TITLE
Bug: Kaiser Colosseum will limit LV7+ monster to summon with The Monarchs Stormforth at some condition

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1703]
Oppent have a monster and Kaiser Colosseum on field, I have a monster on field.
I active The Monarchs Stormforth, as ruling I should be able to summon LV7+ monster, but I can't do it.

**Comment by DailyShana** [comment]
>また、「クロス・ソウル」の効果が適用されている相手のモンスター1体と、自分のモンスター1体をリリースして、レベル7以上のモンスターをアドバンス召喚する事もできません。

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12157&keyword=&tag=-1
