### ISSUE TITLE
Bug: extra tribute summon + Stormforth + opponent summon

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1707]
If you gain an extra tribute summon due to a normal summoned Eidos, if the opponent tribute summons (due to Escalation), then you tribute summon by tributing the opponents tribute summoned monster you can perform another normal summon + the extra tribute summon.
Consufing? Yes, here a step by step.
This bug can be reproduced by following these steps:
1. The opponent has Escalation and Stormforth. Normal summon Eidos (note: normal summon happened), opponent activates both.
![monarch1](https://cloud.githubusercontent.com/assets/12686731/14113382/055c323e-f5d3-11e5-8163-98a254de4301.jpg)
2. Turn player does anything, opponent activates the effect of Escalation and tributes your Eidos and his monster.
![monarch2](https://cloud.githubusercontent.com/assets/12686731/14113434/342cbc00-f5d3-11e5-9ca6-29a60d969881.jpg)
3. Turn player proceeds to special summon Idea + another Eidos
![monarch3](https://cloud.githubusercontent.com/assets/12686731/14113536/bdd7bfcc-f5d3-11e5-88b0-b0e4645060a9.jpg)
then activates Stormforth and tributes the opponents tribute summoned monster.
However this is threated as a regular tribute summon (a normal summon, which has already been performed above), not the extra tribute summon of Eidos. You are then able to tribute summon again since the extra tribute summon is still available.
![monarch4](https://cloud.githubusercontent.com/assets/12686731/14113619/08c15278-f5d4-11e5-8d7c-e2637763a000.jpg)
I hope you have an idea how to fix this, not sure where to find the error here.

**Comment by salix5** [comment]
Do you have a replay file for this?
Or can you test if this bug is fixed after 10b62ad945c8854819f3fa7984f65c0c9470de27

**Comment by destdev** [comment]
here is a replay (turn 5)
[Double normal summon plus tribute bug.zip](https://github.com/Fluorohydride/ygopro/files/201002/Double.normal.summon.plus.tribute.bug.zip)
we'll update tomorrow, I can test it then

**Comment by destdev** [comment]
I tested it now and it seems to be fixed. Thanks you.
