### ISSUE TITLE
Bug with IsAbleToRemoveAsCost()

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1708]
Seems like you are still able to perform effects, even if the IsAbleToRemoveAsCost() check should fail.
Example:
Opponent controls any high level Kozmo, System Down is played, then Kozmojo is chained.
Chain Resolves, Kozmojo destroys the Kozmo monster, then System down banishes the Kozmo monster. The monster is still able to trigger and also successfully able to summon a monster, even if it was already banished and could not pay the cost (and shouldn't be able to trigger in the first place).

**Comment by destdev** [comment]
if you want to solve it this way
https://github.com/Fluorohydride/ygopro-scripts/commit/d5c11f4568068751064e4506aa514b955b435268
it's fine too, I'm just not sure if (or what) other cards are also affected by this
btw, you should also fix all the other kozmo machines then, Dark Destroyer (64063868), Dog Fighter (29491334), Sliprider (94454495) and Delta Shuttle (37679169) are also affected

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@d778cc3 If a card is already removed, it cannot be removed as cost now. 

The effect of those Kozmo monsters is "You can banish this card from your Graveyard.." so `e:GetHandler():IsLocation(LOCATION_GRAVE)` is still necessary

**Comment by destdev** [comment]
thanks for the quick response and fix
