### ISSUE TITLE
Setcodes for 'Metalphosis' and 'Tramid'

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1709]
Two new card series will come out in TDIL tomorrow.
Now https://github.com/Fluorohydride/ygopro-pre-script are using 

> !setcode 0xe1 Celtic Guard
!setcode 0xe2 Metalphosis
!setcode 0xe3 Cardian
!setcode 0xe4 Tramid
!setcode 0xe5 Houkai

Should we keep it, or use the below?

> !setname 0xe1 炼装	メタルフォーゼ
> !setname 0xe2 变形金字塔	トラミッド

As the discussion in https://github.com/Fluorohydride/ygopro-pre-script/issues/11 , I prefer to keep the order in ygopro-pre-script.

**Comment by DailyShana** [comment]
It's unnatural to skip or occupy a positon for nonexisting scripts
so using the following
```
!setname 0xe1 炼装 メタルフォーゼ
!setname 0xe2 变形金字塔 トラミッド
!setname 0xe3 方界
```

**Comment by Zayelion** [comment]
Its best not to move cards over into `ygopro-script` until the whole set is released in Japan and all cards are known to allow a moment for refactoring.
