### ISSUE TITLE
BUG: When Clear Vice Dragon attack Crystal Wing Synchro Dragon

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1712]
It should be
Vice attack Crystal Wing
Vice atk become 6000
Crystal Wing atk become 3000+6000=9000
Vice atk become 18000

Now, Crystal Wing active its effect before Vice, so Crystal Wing got 3000 atk, Vice got 6000 atk only.

**Comment by DailyShana** [comment]
fixed in Fluorohydride/ygopro-scripts@b21cad8
