### ISSUE TITLE
Bug: If Interrupted Kaiju Slumber is chained by Gozen Match

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1716]
It will be able to spsummon monster, with the attribute which was previous on field, only.
For example: I have a water monster on field, I active Interrupted Kaiju Slumber, opponent chain Gozen Match, then I can select only the water Kaiju to spsummon to my field.
![image](https://cloud.githubusercontent.com/assets/13391795/14419769/9eb8436a-fffa-11e5-9b6a-6b86bcca170c.png)

https://github.com/Fluorohydride/ygopro-scripts/pull/328 seems did't fix it.

**Comment by DailyShana** [comment]
It is only the logic in the script is right.
Similar reason as in #1695
