### ISSUE TITLE
Bug: If one monster equips Tyrant Burst Dragon and Twin Swords of Flashing Light - Tryce, it can only attack twice

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1717]
> 質問の状況のように、1体のモンスターが「閃光の双剣－トライス」と「タイラント・バースト・ドラゴン」を装備カード扱いとして装備している場合でも、『装備モンスターは１度のバトルフェイズ中に３回攻撃できる』効果によって、攻撃できる回数は最大で3回です。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=16012&keyword=&tag=-1

**Comment by salix5** [comment]
ygo-core@8804e8c6ebceaaf450ba3aa12b01911f309d71be
多個"多次攻擊"的效果現在會取最大值

**Comment by mercury233** [comment]
谢谢，不过你的链接打不开

**Comment by salix5** [comment]
改好了，不好意思
