### ISSUE TITLE
Fusion spells can active when the only suitable monster is affected by Forbidden Lance

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1718]
![image](https://cloud.githubusercontent.com/assets/13391795/14424488/e9cde3fa-0013-11e6-99ff-235eecb6a08a.png)

![image](https://cloud.githubusercontent.com/assets/13391795/14424447/af90edcc-0013-11e6-9b7f-f03a3aafbb0b.png)

And it will show your extra and hand to opponent, then do nothing.
I've tested Polymerization and Overload Fusion.
Is this a bug..?

**Comment by salix5** [comment]
15/2/26

遊戯王OCG事務局です。

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。

Q.
自分の手札：青眼の白龍、青眼の白龍、融合
自分のフィールド：「禁じられた聖槍」の効果が適用されている「青眼の白龍」
自分のエクストラデッキ：青眼の究極竜
自分の「融合」を発動できますか？
A.
ご質問の状況の場合でも、「融合」を発動する事はできます。

Q.
自分の手札：シャドール・ビースト
自分のフィールド：「禁じられた聖槍」の効果が適用されている「シャドール・ドラゴン」、魂写しの同化（対象：シャドール・ドラゴン、光属性を宣言）
自分のエクストラデッキ：エルシャドール・ミドラーシュ、エルシャドール・ネフィリム
自分の「魂写しの同化」の（2）の効果を発動できますか？
A.
ご質問の状況の場合でも、「魂写しの同化」の『②』の効果を発動する事はできます。


これからも遊戯王オフィシャルカードゲームをはじめ、コナミの商品をよろしくお願い申し上げます。

**Comment by mercury233** [comment]
谢谢
