### ISSUE TITLE
Bug (?) - Nightmare Wheel loosing its target when the target is flipped face down

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1723]
Have a successfully resolved Nightmare Wheel. Then flip the targeted monster face down -> Nightmare Wheel no longer targets that monster.
I'm not 100% sure on this, but since Nightmare Wheel can target face up and face down monsters it shouldn't loose the target in this case and still be able to inflict damage since the monster is still on the field.
If there is a ruling saying othervise I haven't found it. I'm also not sure how to solve this :/

**Comment by DailyShana** [comment]
![image](https://cloud.githubusercontent.com/assets/8469304/21748841/9d609cdc-d5ca-11e6-8472-0c779a6955d5.png)
If the target become face down after havinig resolved the activation of _Nightmare Wheel_, it will not treated as the target of _Nightmare Wheel_.

**Comment by destdev** [comment]
kk, thanks
