### ISSUE TITLE
Bug: Ojama Token don't burn if Fiendish Chain is on the field

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1724]
Situation:
1. Have any number of Ojama Tokens from Ojama Trio on the field. Also have a monster equipped with Fiendish Chain anywhere on the field.
2. Destroy all monsters (Dark Hole/Torrential/etc).
=> Error: You take no burn damage from the Token(s).
Replay:
[OjamaBug.zip](https://github.com/Fluorohydride/ygopro/files/222463/OjamaBug.zip)
The Error is found on turn 11.

**Comment by destdev** [comment]
fixed now, thanks

**Comment by salix5** [comment]
My opinion is that maybe this problem is not totally solved.
The event group in EVENT_DESTROYED may be incorrect when self-destroy is involved.

**Comment by DailyShana** [comment]
No such problem.
In the situation, two `EVENT_DESTROYED` are raised, first for `Fiendish Chain` and second for monsters.
The damage effect in the old script detects the first event and find that `Ojama Token` are not on field, then the damage effect is reseted, miss the right event.
