### ISSUE TITLE
Bug: Dark Magician with Eternal Soul not banished with Macro/Dark Law when destroyed

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1732]
So far I didn't have time to test this further. Here the original bug report:
https://forum.ygodevpro.com/bugs/index.php/Issue/968-Eternal-soul-and-dark-magician-vs-banish-effects/
In the replay there (turn 9) it is shown that DM doesn't get banished when destroyed by battle while Dark Law is on the field. This should not happen, since
1. even immune monsters should get banished by Macro/Dark Law/etc (I think there's a ruling for that for Wildheart vs Macro) and
2. DM should no longer be affected by Eternal Soul after damage calculation.

**Comment by mercury233** [comment]
C-Crush Wyvern have the same issue.

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-scripts@ed765b2

**Comment by destdev** [comment]
Tested and seems to works fine, thanks for that :)
