### ISSUE TITLE
Kaiju Interrupted Slumber vs a face-up Kaiju

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro#1733]
Slumber currently cannot activate if either player controls a Kaiju monster. However, since it's destroying all monsters before Special Summoning, it should be allowed to activate, but resolve without effect if it fails to destroy a face-up Kaiju monster. 

https://www.facebook.com/groups/248499755248/permalink/10156750219050249/?comment_id=10156751654640249&comment_tracking={%252%202tn%22%3A%22R%22}

^ Since this card is exclusive to the TCG, the ruling provided by Julia, the head TCG judge, is as official as it gets.

**Comment by destdev** [comment]
Nobody in that whole discussion ever brought up the most obvious ruling that would prove Julia's statement as being nonesense.
Swallows Nest + EB
There's an official ruling stating, that you can't use Swallows Nest on an EB if the only other vialble target in your Deck is another EB.
Same applies here.
I'd bring that up myself there, but I don't have a FB account, so whoever feels like it ... do it^^

**Comment by StormWulf** [comment]
According to Swallow's Nest's current PSCT text, it's an activation cost and would therefore would be an invalid example to compare with Slumber, which is part of its to destroy all monsters.

**Comment by destdev** [comment]
how is that an invalid example if the one card preventing you from getting the other on the field is gone for sure upon activation (and according to rule not allowed) vs a card where said removal can easily be prevented by 5475683474+-2 possible other cards...

**Comment by StormWulf** [comment]
In your example, you cannot activate Swallow's Nest because there are no legal monsters to summon from the deck, therefore you cannot attempt to pay the activation cost.

However, for a card like Slumber that lacks an activation cost, it just needs to be able to do something, in which case it's destroying monsters and having Kaiju monsters in the deck. Since the Kaiju monster can be destroyed by Slumber, the player can activate it to attempt to destroy it. Once the Kaiju monster is destroyed, the card will then proceed to summon Kaiju monsters from the deck. If you want another suitable example refer to the scenario where a player can activate Artifact Ignition to target one of their own Spell/Traps if all of their Spell/Trap Zones are all occupied.

**Comment by destdev** [comment]
I can't believe I forgot Ignition this whole time >.<
thanks for clearing that up

**Comment by mercury233** [comment]
The set card of Artifact Ignition should be like normal summon, it should be different from spsummon by card.

In OCG rule and ruling, Kaiju Interrupted Slumber shouldn't be able to activate in that stituation, and The Kaiju Files will never be able to work, if there isn't any Kaiju who don't require only 1 on field.

But TCG make this card, so I think TCG may have different rule. Since those cards are exclusive to the TCG now, I think them should be able to activate now, and when they come to OCG, let us see the ruling then.

**Comment by mercury233** [comment]
Is there any progress of this issue, after The Kaiju Files was released?
