### ISSUE TITLE
Daunting Stance Issue

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#1735]
Issue1:
When a monster me control is targeted for an attack, I activated Daunting Stance's effect and targets other monster me control.
But that attack was canceled.
Konami's answer, that attack isn't cancel.
Mail:
遊戯王OCG事務局です。 
いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。 
Q. 
自分フィールドに「ガガガマジシャン」と「ゴゴゴゴーレム」が存在する状況で、相手が「ガガガマジシャン」を攻撃対象として「オッドアイズ・ペンデュラム・ドラゴン」で攻撃宣言した際に、墓地の「仁王立ち」の②の効果を「ゴゴゴゴーレム」を対象に発動した場合、「オッドアイズ・ペンデュラム・ドラゴン」の攻撃はどうなりますか？ 
A. 
ご質問の状況の場合、「オッドアイズ・ペンデュラム・ドラゴン」は「ゴゴゴゴーレム」しか攻撃できなくなり、戦闘の巻き戻しが発生します。 
その後、「オッドアイズ・ペンデュラム・ドラゴン」で「ゴゴゴゴーレム」に攻撃対象を選び直すか、攻撃を取りやめるか、どちらかを選びます。

Issue2:
If Magician Girl activated effect while a Magician Girl that applied Daunting Stance's effect me control is targeted for an attack, that attack change the attack target to that summoned monster.
Konami's answer, "then change the attack target to that monster, and if you do, halve the attacking monster's ATK" isn't resolve.
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=11853&keyword=&tag=-1
Q.自分のモンスターゾーンに表側表示で存在する「アップル・マジシャン・ガール」を対象として、「仁王立ち」の『②：墓地のこのカードを除外し、自分フィールドのモンスター１体を対象として発動できる。このターン、相手は対象のモンスターしか攻撃できない』効果が適用されている相手のターンです。
このターンのバトルフェイズに相手が「アップル・マジシャン・ガール」を攻撃対象に選択した場合、「アップル・マジシャン・ガール」の『①：１ターンに１度、このカードが攻撃対象に選択された場合に発動できる。手札からレベル５以下の魔法使い族モンスター１体を特殊召喚する。その後、攻撃対象をそのモンスターに移し替え、攻撃モンスターの攻撃力を半分にする』モンスター効果を発動する事はできますか？
A.質問の状況の場合でも、「アップル・マジシャン・ガール」が攻撃対象に選択されていますので、そのモンスター効果を発動する事はできます。
その場合、『手札からレベル５以下の魔法使い族モンスター１体を特殊召喚する』処理は適用されますが、「仁王立ち」の効果が適用されているため、『その後、攻撃対象をそのモンスターに移し替え、攻撃モンスターの攻撃力を半分にする』処理を適用する事はできません。
この場合、「アップル・マジシャン・ガール」のモンスター効果は、『手札からレベル５以下の魔法使い族モンスター１体を特殊召喚する』処理にて完了した扱いとなり、戦闘の巻き戻しが発生します。
しかしながら、「仁王立ち」の効果が適用されていますので、相手は手札から特殊召喚された魔法使い族モンスターを攻撃する事はできず、その「アップル・マジシャン・ガール」を攻撃するか、攻撃を取り止めるかを選ぶ事になります。

**Comment by DailyShana** [comment]
It seems that if the attack target become "cannot be attacked", a replay(戦闘の巻き戻し) should occurs.
Maybe as long as the status of "whether can be attacked" of some monster(not necessary the attack target) changed("can be attacked" become "cannot be attacked", or conversely), a replay should occurs then.

**Comment by DailyShana** [comment]
Issue1 is fixed. Issue2 needs some work on Duel.ChangeTarget

**Comment by nekrozar** [comment]
Issue 1: Confirmed. Thank you for fixed!
Issue 2: We should fix Roulette Spider, White Night Dragon etc.
Mail:
遊戯王OCG事務局です。 

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。 

Q. 
自分の「ブラック・マジシャン」を対象に「仁王立ち」の②の効果が適用されている状態です。その「ブラック・マジシャン」を攻撃対象として相手が「青眼の白龍」で攻撃宣言を行った時に、自分が「ルーレット・スパイダー」を発動し、サイコロの2の目が出た場合、攻撃はどうなりますか？ 
A. 
ご質問の状況の場合、『２・その攻撃を自分への直接攻撃にする』の効果は適用されず、相手モンスターと「ブラック・マジシャン」が戦闘を行います。 

Q. 
自分の「白夜の女王」を対象に「仁王立ち」の②の効果が適用されている状態です。その「白夜の女王」を攻撃対象として相手が「E・HERO ネオス」で攻撃宣言を行った時に、自分は「青氷の白夜龍」の②の効果を発動できますか？発動できる場合攻撃はどうなりますか？ 
A. 
ご質問の状況の場合、自分は「青氷の白夜龍」の『②』の効果を発動する事はできません。

**Comment by DailyShana** [comment]
Compliment:
According to http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=19127&keyword=&tag=-1, if two Choco Magician Girl in hand, two Apple Magician Girl in grave and an Apple Magic Girl is attcked, the effects of special summoning and changing attack target can be activated until monster zone is full.

During the second attack of Nitro Warrior, the effect of Apple Magician Girl can be activated and resolved normally.
>Q.
「ニトロ・ウォリアー」の効果によって、2回目の攻撃を行う際に、表示形式を攻撃表示に変更する効果の対象として、「アップル・マジシャン・ガール」を選択した場合、「アップル・マジシャン・ガール」の『①』モンスター効果を発動する事はできますか？効果処理はどうなりますか？
A.
ご質問の状況の場合でも、攻撃対象に選択された事で、「アップル・マジシャン・ガール」は『①』の効果を発動する事ができます。
また、「アップル・マジシャン・ガール」の『手札からレベル５以下の魔法使い族モンスター１体を特殊召喚する。その後、攻撃対象をそのモンスターに移し替え、攻撃モンスターの攻撃力を半分にする』効果も通常通り適用され、「ニトロ・ウォリアー」の攻撃対象は、「アップル・マジシャン・ガール」の効果で手札から特殊召喚された魔法使い族モンスターへ移り、「ニトロ・ウォリアー」の攻撃力は半分になります。

**Comment by nekrozar** [comment]
Issue 2: Confirmed. Thank you for fixed.
But, you forget Shift and Mermail Abysstrite...

**Comment by DailyShana** [comment]
The scripts of Shift and Mermail Abysstrite is right.

**Comment by salix5** [comment]
About the attack target
攻擊對象的部分
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8386&keyword=&tag=-1
The effect of 磁力の指輪/Ring of Magnetism has a higher priority than "must be attacked "
The opponent monsters still have to attack, but they will attack the target of Ring of Magnetism.
Ring of Magnetism has an almost exactly the same text as Daunting Stance
磁力的指輪/仁王立的"不能攻擊此卡以外的目標"優先度比"必須攻擊X"更高
受到"必須攻擊X"的怪獸仍然必須攻擊，但攻擊的會是磁力的指輪裝備的怪獸

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=9795&keyword=&tag=-1
The effect of Ring of Magnetism will ignore 'cannot be attack target'.
磁力的指輪的"不能攻擊此卡以外"的效果會無視"不能當作攻擊對象"的效果

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=6089&keyword=&tag=-1
Similar for Staunch Defender
必須攻擊X也一樣

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=16099&keyword=&tag=-1
If multiple アース・グラビティ/Terra Firma Gravity are applied, the attack target is chosen by the player who activate Terra Firma Gravity.
多個地球重力讓場上產生多個"必須被攻擊的目標"時，攻擊對象會由發動地球重力的玩家決定

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=18026&keyword=%E6%94%BB%E6%92%83+%E4%BB%81%E7%8E%8B&tag=-1
If multiple Daunting Stance are applied, the opponent monster cannot attack.
多個仁王立適用後，對手怪獸不能攻擊

About 'affected by effect'
影響怪獸的效果
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=6808&keyword=&tag=-1
Monsters not affected by effect are immune to "must attack X" .
必須攻擊X是影響怪獸的效果

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=18030&keyword=%E6%94%BB%E6%92%83+%E4%BB%81%E7%8E%8B&tag=-1
Similar for Daunting Stance
仁王立也是影響怪獸的效果

**Comment by DailyShana** [comment]
Another point must be noticed: 
the effect of _Daunting Stance_ is a lingering effect, "...cannot attack for the rest of this turn, except to attack **that** monster" and the effect of _Ring of Magnetism_ is a continue effect.

**Comment by nekrozar** [comment]
Konami has answered, "Shift and Mermail Abysstrite can change attack target."

Mail:
遊戯王OCG事務局です。 

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。 

Q. 
自分の「水精鱗－メガロアビス」を対象に「仁王立ち」の②の効果が適用されている状態です。 
その「水精鱗－メガロアビス」を攻撃対象として相手が「青眼の亜白龍」で攻撃宣言を行った時に、自分は「水精鱗－ガイオアビス」を対象として「シフトチェンジ」「水精鱗－アビストリーテ」の効果を発動できますか？ 
発動できる場合攻撃はどうなりますか？ 
A. 
ご質問の場合、既に「仁王立ち」の『②』の効果が適用されている「水精鱗－メガロアビス」が存在する為、相手の「青眼の亜白龍」による攻撃宣言時に「シフトチェンジ」や「水精鱗－アビストリーテ」の攻撃対象を別のモンスターに移し替える効果を発動する事はできません。

However, Konami doesn't know whether Daunting Stance be able to activate in some situation...

Mail:
Q. 
自分の「ブラック・マジシャン」を対象に「仁王立ち」の②の効果が適用されている状態です。 
その「ブラック・マジシャン」を攻撃対象として相手が「青眼の白龍」で攻撃宣言を行った時に、自分は「チョコ・マジシャン・ガール」を対象に「立ちはだかる強敵」を発動できますか？ 
発動できる場合攻撃はどうなりますか？ 
Q. 
自分の「地縛神 Cusillu」を対象に「仁王立ち」の②の効果を発動できますか？ 
Q. 
自分フィールドに「磁力の指輪」を装備している「竜胆ブルーム」が存在する場合に「ナイト・ドラゴリッチ」を対象として「仁王立ち」の②の効果を発動できますか？発動できる場合どのモンスターを攻撃しなければなりませんか？ 
A. 
この度いただきましたご質問の件につきましては、誠に恐れ入りますが、現時点では具体的な回答をご案内を差し上げる事ができない状況でございます。 
本件、大変お手数をおかけいたしますが、日をあらためて、当事務局までお問い合わせ頂けますようお願い申し上げます。 
もし、ご質問の状況がデュエル中に発生した際には、対戦相手の方と話し合って進めていただいたり、大会中であれば審判の判断で進めていただけました幸いでございます。

**Comment by DailyShana** [comment]
>攻撃対象を別のモンスターに移し替える効果を発動する事はできません

the effect of changing attack target to other monster cannot be activated?

**Comment by nekrozar** [comment]
Sorry, I mistook.

**Comment by salix5** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=5130
シフトチェンジ
自分フィールド上のモンスター１体が相手の魔法・罠カードの効果の対象になった時、または相手モンスターの攻撃対象になった時に発動できる。その対象を、自分フィールド上の正しい対象となる他のモンスター１体に移し替える。

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=16169&keyword=&tag=-1
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=6287&keyword=&tag=-1
正しい対象->不能選擇不能成為攻擊對象的卡、必須符合攻擊怪獸的限制

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=15667&keyword=%E6%94%BB%E6%92%83%E5%AF%BE%E8%B1%A1%E3%80%80%E7%A7%BB%E3%81%97%E6%9B%BF&tag=-1
一般的"攻擊對象轉移到X進行傷害計算"無視不能選擇為攻擊對象的限制

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=15827&keyword=%E6%94%BB%E6%92%83%E5%AF%BE%E8%B1%A1%E3%80%80%E7%A7%BB%E3%81%97%E6%9B%BF&tag=-1
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=13550&keyword=%E6%94%BB%E6%92%83%E5%AF%BE%E8%B1%A1%E3%80%80%E7%A7%BB%E3%81%97%E6%9B%BF&tag=-1
把A的攻擊對象轉移到X->影響A、不影響X

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=10214&keyword=%E6%94%BB%E6%92%83%E5%AF%BE%E8%B1%A1%E3%80%80%E7%A7%BB%E3%81%97%E6%9B%BF&tag=-1
把A的攻擊對象轉移到X->A、X都判定成被全體攻擊過

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=14724&keyword=%E6%94%BB%E6%92%83%E5%AF%BE%E8%B1%A1%E3%80%80%E7%A7%BB%E3%81%97%E6%9B%BF&tag=-1
如果轉移攻擊對象之前發生怪獸數量減少，在轉移之後不回捲

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=7440&keyword=%E6%94%BB%E6%92%83%E5%AF%BE%E8%B1%A1%E3%80%80%E7%A7%BB%E3%81%97%E6%9B%BF&tag=-1
轉移之後發生怪獸數量變化仍然照常回捲

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=19065&keyword=%E6%94%BB%E6%92%83%E5%AF%BE%E8%B1%A1%E3%80%80%E7%A7%BB%E3%81%97%E6%9B%BF&tag=-1
轉移攻擊對象處理時攻擊已無效則不處理



http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=14724&keyword=%E6%94%BB%E6%92%83%E5%AF%BE%E8%B1%A1%E3%80%80%E7%A7%BB%E3%81%97%E6%9B%BF&tag=-1

**Comment by nekrozar** [comment]
Maybe this issue was fixed completed.
Thank you for fix!

**Comment by nekrozar** [comment]
yugioh-wiki was added _Rise to Full Height_'s new FAQ.
In yugioh-wiki, "_Rise to Full Height_ give priority to after target monster."
And, "_Rise to Full Height_ cannot target monster that applied _Rise to Full Height_'s effect."
We should fix these problem.
http://yugioh-wiki.net/index.php?%A1%D4%BF%CE%B2%A6%CE%A9%A4%C1%A1%D5
Ｑ：《仁王立ち》が２枚墓地にある時、同一ターンに(2)の効果を別々の２体のモンスターにそれぞれ発動できますか？
Ａ：はい、発動できます。
　　この場合、後に適用された方の《仁王立ち》が有効となります。(16/07/14)

Ｑ：《仁王立ち》が２枚墓地にある時、同一ターンに(2)の効果を同一の１体のモンスターに発動できますか？
Ａ：いいえ、発動できません。(16/07/14)

**Comment by salix5** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=18026&keyword=%E6%94%BB%E6%92%83+%E4%BB%81%E7%8E%8B&tag=-1
The FAQ in Konami database has a higher priority.

**Comment by nekrozar** [comment]
> And, "Rise to Full Height cannot target monster that applied Rise to Full Height's effect."
> Ｑ：《仁王立ち》が２枚墓地にある時、同一ターンに(2)の効果を同一の１体のモンスターに発動できますか？
> Ａ：いいえ、**発動できません**。(16/07/14)

@mercury233 This problem don't solve.
