### ISSUE TITLE
[Not yet fixed] Card Question[38723936]

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1736]
This is a old card and has unique interactions , 
so if you Activate Question your Opponent cannot look in your Graveyard , 
but in Ygopro if you Activate Question , your opponent can just hold the A button on their keyboard or "left-click" , to look at the Field , and they will be able to look in your Graveyard too , and cheat

Here says the Rulings :  
http://yugioh.wikia.com/wiki/Card_Rulings:Question

> During the resolution of this card, "your opponent cannot check cards in your Graveyard" is also applied, and your opponent cannot check cards
> 
> Your opponent cannot check your Graveyard from the activation of "Question" onwards. Your opponent cannot check your Graveyard even if he activates "D.D. Crow"/"Disappear"/etc

Hopefully someone can add something to the source code in the future to get this card fixed
Ill leave this issue open so we dont forget about it
Thank you !

**Comment by Hello23-Ygopro** [comment]
Can I bump this Issue somehow ? Its still unsolved , i think it needs some core changes to take to get it to work

Thank You!

**Comment by Hello23-Ygopro** [comment]
It says "Effect not implemented" in the script , so that shud be a constant reminder that its not fully implemented yet , so this issue doesnt need to be open

**Comment by Zayelion** [comment]
Thats absurd, a feature enhancement should be closed when it is implemented or explicitly denied with an explanation. Closing a issue because there is a `TODO` comment in the code is bad practice.
