### ISSUE TITLE
BUG: Two issues about The Monarchs Stormforth

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1737]
1. I activate Monster Reborn to spsummon a fusion monster from graveyard, opponent use D/D/D Hexblood King Siegfried to negate it, then I won't be able to activate The Monarchs Stormforth.

2.

> Question
> 自分の発動した「融合」にチェーンして相手が「破壊輪」を発動しました。
> 「破壊輪」の効果によって、自分フィールドのモンスターが破壊された事によって、自分の手札・フィールドに融合素材モンスターとなる一組が揃っていない状態となった場合、「融合」の効果処理にて融合召喚は行われませんが、その後、同一ターンにて自分は「帝王の烈旋」を発動する事はできますか？
> Answer
> 「帝王の烈旋」を発動するターンには、自分はエクストラデッキからモンスターを特殊召喚する事はできません。
> 質問の状況の場合、結果的に「融合」の処理は行われていませんが、エクストラデッキからモンスターを融合召喚するために、「融合」の発動自体は行われています。
> したがって、そのターンに自分は「帝王の烈旋」を発動する事はできません。
> http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=10972&keyword=&tag=-1

Now it will be able to activate in this situation.

**Comment by DailyShana** [comment]
The effect of D/D/D Hexblood King Siegfried is disable effect, not negate activation.

**Comment by mercury233** [comment]
But I was spsummoning from grave.

**Comment by DailyShana** [comment]
tested for issue 1, no problem on D/D/D Hexblood King Siegfried and Monster Reborn

**Comment by mercury233** [comment]
融合召唤贞德，用那个贞德同调咒血王，对面死苏那个贞德

**Comment by salix5** [comment]
調查中

**Comment by DailyShana** [comment]
not bug now (2020-04)
