### ISSUE TITLE
BUG: Muti forced EFFECT_DESTROY_SUBSTITUTE cards should be all destroyed

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1738]
> Ｑ：《六武衆の御霊代》１枚と《漆黒の名馬》３枚が装備された六武衆がいます。
　この六武衆が破壊される場合、《六武衆の御霊代》と《漆黒の名馬》は、どれか１枚だけ破壊されるのですか？
　それとも同時に全て破壊されますか？
Ａ：同時に全て破壊されます。（07/08/18）
http://yugioh-wiki.net/index.php?%A1%D4%BC%BF%B9%F5%A4%CE%CC%BE%C7%CF%A1%D5

Now only one card is destroyed.

**Comment by nekrozar** [comment]
Konami's answer, "If Shien equipped Legendary Ebon Steed and Spirit of the Six Samurai would be destroyed, Legendary Ebon Steed and Spirit of the Six Samurai destroy."

Mail:
Q.
「真六武衆－シエン」に「漆黒の名馬」3枚と「六武衆の御霊代」1枚が装備されている場合に相手の「SNo.39 希望皇ホープ・ザ・ライトニング」に戦闘で破壊される場合、代わりに「漆黒の名馬」3枚と「六武衆の御霊代」1枚の内いずれか1枚を破壊しますか？それとも「漆黒の名馬」3枚と「六武衆の御霊代」1枚の全てを代わりに破壊しますか？
A.
ご質問の場合、「真六武衆－シエン」に装備されているカードである「漆黒の名馬」「六武衆の御霊代」は、全て破壊されます。

**Comment by mercury233** [comment]
Thank you!

So the same thing will happen when A, B and C is equipped to a monster and the monster is destroyed.
