### ISSUE TITLE
添加错误日志输出功能？

### ISSUE THREAD

**Issue by rebiu** [Fluorohydride/ygopro#1740]
能不能添加出错的时候输出错误日志的功能？

现在的版本有几率开局点击任意一张卡都会崩溃，而且是不能重现，十分蛋疼

另外能不能添加二维码功能？例如：Q群约战不用其他平台，直连，如果发二维码就不用手动输入，手机用也感觉不错

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro/commit/a9414e51c18914dfb17c1a1ad64339f51737e6bc#diff-90667b1ce7a22c15d1a4d1c05a370817R6
