### ISSUE TITLE
Bug: Magician Girls don't halve attack

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1746]
Since the last change here
https://github.com/Fluorohydride/ygopro-scripts/commit/b4f2969f47bac10032fbb607b66e9ff7c79c1651
Magician Girl cards don't halve the attack anymore. I'm not 100% sure if I read that correctly, but that might be due to the attack target change being checked, the function scriptlib::duel_change_attack_target always returns 0 and thus always fails?

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@416b733
The return value of Duel.ChangeAttackTarget means it is able to change attack target.

**Comment by destdev** [comment]
of course, happens if I open an old an outdated version of that file, now it makes sense ... what doesn't make sense is something else with our update 2 days ago, sorry for the inconvenience
