### ISSUE TITLE
Bug and issues about get and return control of multiple monsters

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1749]
1.If one card use `Duel.GetControl` to temporarily get control of multiple monsters, when return, it will show selectbox, but the player can't see which card to return.
![image](https://cloud.githubusercontent.com/assets/13391795/15291316/c4479cae-1baf-11e6-913d-220e6bf6916d.png)
![image](https://cloud.githubusercontent.com/assets/13391795/15291334/e32911ac-1baf-11e6-99e4-ec531ea35238.png)

2.If I use Possessed Dark Soul to get control of multiple monsters, but I don't have enough space when the effect solving, the game will show a dialog to let me select which monster to destroy.
I hope it should let me select which monster to get.

**Comment by salix5** [comment]
這個問題現在還存在嗎？

**Comment by mercury233** [comment]
图上的问题仍然存在
