### ISSUE TITLE
Red Nova Issue

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#1751]
If Red Nova and Hydride are sent to the Graveyard as a Synchro Material for a Synchro Summon, Red Nova can activate effect.
Konami's answer, "if Red Nova and Hydride are sent to the Graveyard as a Synchro Material for a Synchro Summon, Red Nova cannot activate effect."
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=19280&keyword=&tag=-1
Q.「レッド・ノヴァ」と「幻影王 ハイド・ライド」で、「アームズ・エイド」をシンクロ召喚した場合、「レッド・ノヴァ」の『②：このカードがチューナー２体以上を素材とするS召喚に使用され墓地へ送られた場合に発動できる。デッキから悪魔族・炎属性モンスター１体を守備表示で特殊召喚する』モンスター効果を発動する事はできますか？
A.質問の状況の場合、「アームズ・エイド」をシンクロ召喚するためには、「幻影王 ハイド・ライド」の『自分フィールド上に表側表示で存在するこのカードをシンクロ召喚に使用する場合、このカードをチューナー以外のモンスターとして扱う事ができる』モンスター効果を適用し、チューナー以外のモンスターとして扱ってシンクロ召喚を行う事になります。
この場合には、チューナー2体以上を素材とするシンクロ召喚に使用された扱いにはなりませんので、「レッド・ノヴァ」のモンスター効果を発動する事はできません。

**Comment by salix5** [comment]
@VanillaSalt 
Can you help us solve this problem?

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/12041f672b6dbc11c06c4e36b3537a73d245c9a5
This has been fixed.
Thank you!
