### ISSUE TITLE
Issue about auto chain order

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1752]
Use Emergency Teleport to spsummon Kozmo Tincan, if auto chain order is enabled, Tincan will be banished before it can activate effect.

**Comment by Hello23-Ygopro** [comment]
> Use Emergency Teleport to spsummon Kozmo Tincan, if auto chain order is enabled, Tincan will be banished before it can activate effect.

I can affirm this , but it only occurs if you Activate Emergency Teleport in the End Phase , atleast for me ;
if Emergency Teleport is Activated in any other Phase , with Chain Order Enabled , this is not an issue

Thank You for bringing it to light, its impossible to explain/resolve in a forum;

**Comment by destdev** [comment]
You should be able to activate the search effect, just not directly after the summon, this is the summon response window. You have to pass this, then you should be able to select the search effect with the next activation request.

**Comment by salix5** [comment]
Now "Auto Chain Order" is default off since it is NOT recommended.
If it is turned on, then all legal results are possible.

In this example,there are 2 things in End Phase:
1. Banish the sp_summoned monster(Emergency Teleport)
2. Trigger effect(Tincan)
The order seems to be 1->2, which is one of the legal results.

**Comment by DailyShana** [comment]
BTW, I want to know why player has to select effect to activate when there is only 1 mandatory trigger effect in the End Phase.

**Comment by salix5** [comment]
My opinion is that:
1. The effects in end phase is resolved one by one, so the steps should be the same regardless of the number of mandatory trigger effects.
2. The system activated the only 1 mandatory trigger effect will make the fact "There is only 1 available effect for the current player."  extremely obvious even if latency is added, which should be avoided.

我的想法是：
1. 結束階段的效果是由玩家決定發動順序後逐項發動，也就是說必發效果只是代表"必須處理完此效果才可以結束目前的階段"，必發效果本身並沒有固定的處理順序。
以這個意義來說，玩家應該對目前的發動順序有清楚的意識，而我相信無論有幾個必發效果都讓玩家自己手動操作會比讓系統介入要好。

2. 原本在只有1個必發效果時系統會自動發動，即使加入延遲後仍會導致對手輕易得知"回合玩家沒有其他可以發動的二速效果"，而系統做出這類可能違反公平性的舉動是應該避免的。
