### ISSUE TITLE
BUG: If the target monster become equip, it will still be destroyed by "destroy monster" effect

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1756]
Similar to https://github.com/Fluorohydride/ygopro-scripts/pull/390
Should we change all those scripts, add `IsLocation`, or change `c:IsRelateToEffect(e)` to `c:IsRelateToEffect(e,true)` for cards which don't require the target is monster when destroy?

**Comment by DailyShana** [comment]
We should use `IsLocation`.
When the target monster become equip cards, they are still be destroy by _Raigeki Break_.
It means it is related to the effect.
"destroy monster" is the condition that also most be satisfied when resolving effects.

**Comment by salix5** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=17936&keyword=&tag=-1
C1 雷破
C2 布面甲
解連鎖
C2 布面甲特召到怪獸區
C1 特召後的布面甲不視為雷破的對象，因此不處理

"對象怪獸變成裝備卡之後，仍然會被破壞"這點是否有相關的資料

**Comment by mercury233** [comment]
> Ｑ：「甲虫装機」と名のついたモンスターを対象に《サンダー・ブレイク》を発動されました。このカードをチェーンして対象にされた「甲虫装機」を装備カードにした場合、その「甲虫装機」は破壊されてしまいますか？
Ａ：破壊されます。(13/02/04)
http://yugioh-wiki.net/index.php?%A1%D4%A5%F4%A5%A1%A5%EA%A5%E5%A5%A2%A5%D6%A5%EB%A1%A6%A5%D5%A5%A9%A1%BC%A5%E0%A1%D5=

怪兽被可变形态变成装备，仍然会被雷破破坏

**Comment by salix5** [comment]
我的想法是因為官方資料庫有記載完全相反的答案
有必要重新調查這幾個問題以後再修改：
1. C1 雷破 、C2 阿波畢斯，C1是否破壞？
2. C1 旋風 、C2 阿波畢斯，C1是否破壞？
3. 上面的問題
