### ISSUE TITLE
BUG: Eternal Soul will be effective for Dark Magician if Dark Magician is destroyed, be tribute, be cost

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1757]
The opponent control Macro Cosmos, I control Eternal Soul and Dark Magician.
If my Dark Magician is destroyed, or be tribute, or be cost, it will be sent to grave.

**Comment by destdev** [comment]
same as https://github.com/Fluorohydride/ygopro/issues/1732
