### ISSUE TITLE
Request: Duel.ConfirmCardsUnlessLflist or Card.IsLflisted

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1758]
I use Chain Disappearance to banish Effect Veiler, but opponent banish 1 card from deck only. I should be able to confirm his deck and hand.
But if the card is Qliphort Scout, I can't confirm because it is semi-limit card.

So we need a function to let the script know if the card is limited.

**Comment by DailyShana** [comment]
#1465

**Comment by mercury233** [comment]
> 「連鎖除外」の効果処理時に、自分から相手プレイヤーに手札を見せる事はありません。
ただし、「連鎖除外」の効果により、フィールド上に召喚・反転召喚・特殊召喚したモンスターと同名のモンスターを手札とデッキから除外しなければなりませんが、その効果処理を行う際に、デッキを構築するうえでの上限枚数まで確認できない場合、「連鎖除外」を発動したプレイヤーは、相手に対して手札とデッキの確認を求める事ができます。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=10739&keyword=&tag=-1

这里说展示手牌不是必须，但如果除外的卡数量不到上限，连锁除外发动方可以要求确认
我想我们应该再问一下事务局

**Comment by DailyShana** [comment]
>服从天声、暗之指名者、扰乱魔术、传说的白石、地狱的暴走召唤等在卡组里没有对应的卡时是否要公开卡组的裁定同时出现了表述变化：
在规则上没有规定一定要公开，但对手可以要求公开，然后双方玩家讨论解决。如果双方不能达成一致，则按照在场裁判的判断。
也就是说事务局刻意将决定权交给裁判，裁判若想照顾被要求公开卡组的玩家，可裁定为由裁判确认卡组内容。
心灵崩坏、王家的牲祭等能否确认对手手牌也出现了类似的表述变化。没有明确记载着公开·确认的卡的情报获取能力全部变得依赖裁判。
http://tieba.baidu.com/p/4617596090

The ruling link above is deleated from officail database now.

**Comment by DailyShana** [comment]
>ルール上の処理は決まっていないが、トラブル回避のため、大会以外なら何らかの方法で確認を取り、大会なら審判に判断を仰ぐべきである。
大会以外で公開する以外に証明する手段がないなら、ゲームの進行のために公開すべきであり、
虚偽の申告をしたり、いわゆるゴネ得を許すためのルールではないという点に注意したい。
http://yugioh-wiki.net/index.php?%B8%F8%B3%AB

**Comment by mercury233** [comment]
So we need to remove confirms like Mind Crush?

**Comment by salix5** [comment]
@mercury233 
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=10739&keyword=&tag=-1
這個連結顯示的是黑魔術的繼承
目前(7/5)搜尋"連鎖除外 確認"找不到任何內容
有正確的出處嗎?

**Comment by mercury233** [comment]
看起来相关的裁定都改了
