### ISSUE TITLE
BUG: EFFECT_CHANGE_CODE seem don't work in LOCATION_HAND

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1759]
https://github.com/Fluorohydride/ygopro-pre-script/blob/9fb467a0a122e6b9ffb7e94c02ce1809feba5b52/scripts/INOV-JP/c100910029.lua

It work in grave, but not in hand.

**Comment by salix5** [comment]
Fluorohydride/ygopro-core@7059fdaede394163a2f718ce6a50bafb151fe5f4
fixed
