### ISSUE TITLE
Bug: Must attack

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1762]
In this commit
https://github.com/Fluorohydride/ygopro-scripts/commit/5a093cc88a8f97e5f76949b5f7371d9f78823692
every EFFECT_CANNOT_EP seems to be replaced by EFFECT_MUST_ATTACK_MONSTER.
However, if you apply that effect in a phase other then BP (e.g. activate number 13 or 31 during your opponents M1) the opponent can simply go to the end phase without attacking. If you activate the effect in BP it works fine, you can't leave BP without attacking.

**Comment by salix5** [comment]
Fluorohydride/ygopro-core@989261c2d44d03fac246b373a12b67fd7eda419e
Now the player cannot enter EP in such situation by default.
