### ISSUE TITLE
跪求在卡组、除外的卡的信息小窗口上显示卡的表里状态

### ISSUE THREAD

**Issue by ghost** [Fluorohydride/ygopro#1764]
比方说，对方混进我卡组一个「寄生虫」，我希望用「愚蠢的埋葬」除掉那个「寄生虫」，但我的卡组本来就投入了「寄生虫」，所以不知道哪个是对手的。
比方说，我用「强欲而贪欲之壶」里侧除外了10张卡，又被对方除外了几张卡，我希望用「PSY骨架王·Ω」的效果优先把里侧除外的卡送回墓地，但我不知道哪些是里侧除外的。

**Comment by Tianchenglipu** [comment]
我没试过前者的情况，也许已经有对策了，但后者的情况是确实的。里侧除外的卡和表侧除外的卡混在一起，这时候他是表侧还是里侧在有些情况下会起到作用。

**Comment by Tianchenglipu** [comment]
在卡图的左下角放一个小图标其实就可以了。如果我知道那卡是什么，而且那卡是里侧，就放一个小图标。同样的方法，也可以给正规手续未满的怪兽放一个小图标。

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro#color-in-card-list
