### ISSUE TITLE
BUG: The second attack of EFFECT_ATTACK_ALL will be canceled

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1772]
The second attack to a monster will be canceled.
![image](https://cloud.githubusercontent.com/assets/13391795/15811010/d3dbf5de-2bd6-11e6-8e90-e52e1f971115.png)

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/15982694/ab359b46-2fc1-11e6-9f0f-fc9a1cf25b83.png)
对方场上有若干个怪兽，使用攻击全体的怪兽进行攻击，第一次攻击正常，第二次会被取消，提示战斗回卷

@salix5

**Comment by mercury233** [comment]
I think it is fixed after reverting https://github.com/Fluorohydride/ygopro-core/commit/b8f08756f8dded93db3fbcc28d935aba48230227

**Comment by qitz** [comment]
Yes. It seems the bug of ygocore.
http://tieba.baidu.com/p/3611170889?pn=41
floor 1362, 1363.
