### ISSUE TITLE
BUG: Performapal Thunderhino will be able to use its destroy replace effect if Performapal Dramatic Theater is going to be destroyed by Solemn Judgment

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1773]
Performapal Dramatic Theater isn't on the field, but Thunderhino will be able to use its effect.
And Performapal Dramatic Theater will be destroyed as usual.

**Comment by salix5** [comment]
Do you have a replay file?
Thank you in advance!

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@4e1021b

**Comment by salix5** [comment]
魔法、陷阱卡發動無效後破壞/送去墓地不視為從場上送去墓地
但還沒送去墓地之前視為場上的卡看起來並沒有問題
有參考資料能確認這是bug嗎？

**Comment by DailyShana** [comment]
灵摆呼唤适用后，发动灵摆卡被神星因子，灵摆卡被无效后被破坏，说明被无效的瞬间就不视为场上的卡
