### ISSUE TITLE
BUG: If you use Tribute Burial to set a monster, you can use Endless Trap Hole against its flip summon

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1777]
![image](https://cloud.githubusercontent.com/assets/13391795/15982808/f664adb6-2fc4-11e6-9b7e-c4e9c144954e.png)

1. Active Tribute Burial
2. Set Amaterasu with Tribute Burial
3. Set Endless Trap Hole
4. Next your turn, flip Amaterasu

**Comment by DailyShana** [comment]
fixed in Fluorohydride/ygopro-scripts@f20004747bd913cd569a713c4048d1cca3a78072
GetSummonPlayer is not available for flip summon.
