### ISSUE TITLE
lflist.conf , generation duel format

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1779]
你好
很多人可能知道：http://www.yugioh-card.com/en/events/generationduel.html
這是1舊格式5 名單，但它真的很好落實到Ygopro，但只有1個問題：
在它說：“所有的怪物效果”等，這是每個卡類型至少1000+卡，段，因此，包括他們都分別在lflist文件Ygopro將需要很長的時間
我在想，如果有一個快捷方式或另一種方式來使用lflist文件，包括所有那些卡，而不必鍵入複製他們的數字
我想另一種方法可以是使用單獨的數據庫，只是包括刪除那些不使用的尋找自己的代碼（32=效果怪獸），（64 =融合怪獸）等，但在我看來，這是更好地使用名單

謝謝。

hi ,
Many of you may know of : http://www.yugioh-card.com/en/events/generationduel.html
It is 5 banlists in 1 for older formats , but it would really nice to implement it into Ygopro , but there is only 1 problem :
In the section it says "All Effect Monsters" , etc, that is at least 1000+ cards on each card type, so including them all individually in the lflist file Ygopro will take a long time
I was wondering if there is a shortcut, or another way to use the lflist file to include all those cards, without having to type copy their numbers
I suppose another way could be to use separate databases, and just include delete those that are not used by looking for their code (32 = Effect Monster), (64 = Fusion Monster), etc but in my opinion it is better to use banlists

Thank You.

**Comment by mercury233** [comment]
Maybe you can make a script to generate the lflist.

**Comment by Zayelion** [comment]
At this time I dont believe it is a good idea to implement the list. Its essentially an unlimited format, also the general idea is for these decks to do cross banlist duels. Each newly released card will require a banlist edit.

Its basically a mess.

I think this is something best dynamically handled by the launchers and server configurations.

> I suppose another way could be to use separate databases, and just include delete those that are not used by looking for their code (32 = Effect Monster), (64 = Fusion Monster), etc but in my opinion it is better to use banlists

This is actually easier for some of the servers.

**Comment by Zayelion** [comment]
**Update**

after talking with the other developers I feel it might be better to rework the OT field to hold the necessary information. While we are at it adding in world, and pre-release tags.
