### ISSUE TITLE
ERROR on Debug 2065

### ISSUE THREAD

**Issue by nogard230** [Fluorohydride/ygopro#1782]
Hi, I don't know solved this problem:
"error C2065: 'POS_FACEDOWN_DEFENSE' : undeclared identifier    c:\users\pc\documents\ygo\ygopro-master\gframe\tag_duel.cpp"
help me please!
thanks

**Comment by mercury233** [comment]
You should update your ocgcore code.

**Comment by nogard230** [comment]
Thanks so much,
new error C1033: cannot open program database 'c:\users\pc\documents\ygo\ygopro-master\bin\debug\ocgcore.pdb'	c:\users\pc\documents\ygo\ygopro-master\ocgcore\processor.cpp	
error C1033: cannot open program database 'c:\users\pc\documents\ygo\ygopro-master\bin\debug\irrlicht.pdb'	c:\users\pc\documents\ygo\ygopro-master\irrlicht\src\c3dsmeshfileloader.cpp

Some idea?
thanks

**Comment by mercury233** [comment]
I don't know too much about how to build ygopro too.
You can try https://github.com/DailyShana/ygopro/tree/build
