### ISSUE TITLE
Union Monster Issue 

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#1783]
If XY-Dragon Cannon equipped Oilman, XY-Dragon Cannon can equip Heavy Mech Support Platform.
Konami's answer, "if XY-Dragon Cannon equipped Oilman, XY-Dragon Cannon cannot equip Heavy Mech Support Platform."
Mail:
遊戯王OCG事務局です。 

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。 

Q.
「オイルメン」を装備カード扱いとして装備している「XY－ドラゴン・キャノン」に、さらに「強化支援メカ・ヘビーウェポン」を装備できますか？
A.
今回「STRUCTURE DECK－ 海馬瀬人 －」に収録されたユニオンモンスター以外については、ルールの変更はございません。
よって、これまで通り、同時に装備できるのは1体までとなります。

したがって、「XY－ドラゴン・キャノン」に「オイルメン」が装備されている状況で、「強化支援メカ・ヘビーウェポン」を装備する事はできません。

なお、「XY－ドラゴン・キャノン」に「強化支援メカ・ヘビーウェポン」が装備されている状況で、「オイルメン」を装備する事もできません。

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro/issues/1738
Did anybody confirmed this to konami?

**Comment by DailyShana** [comment]
Conversely, if _XY-Dragon Cannon_ equipped _Heavy Mech Support Platform_, _XY-Dragon Cannon_ cannot equip _Oilman_ as well.

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@37aa259

**Comment by nekrozar** [comment]
Sorry, I forgot to close this commit.
