### ISSUE TITLE
change "script" directory

### ISSUE THREAD

**Issue by anshkumar** [Fluorohydride/ygopro#1790]
I want to change the script directory to something else. I'm not able to find the part of the code where to specify the change. Please help.

@Fluorohydride @IceYGO @mercury233

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-core/blob/master/interpreter.cpp#L678

**Comment by anshkumar** [comment]
Thank you.
That is what I was looking for.

**Comment by Zayelion** [comment]
Make it configurable.....
