### ISSUE TITLE
BUG: Legendary Dragon cards count for every setcode

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro#1792]
I have observed that all three of the Legendary Dragon cards can be banished for the cost of Ronintoadin, discarded to activate Pantheism of the Monarchs, and searched by Sky Iris. Based on this observation, it appears that they are counted as every setcode when they should not. Is this an issue with the current setcode `0xa1`, or something else?

**Comment by destdev** [comment]
should be something you have changed, at least what you describe doesn't work in Devpro and I don't think we run anything that would change something at that mechanic... unless I'm missing something^^

**Comment by destdev** [comment]
However, this reminds me of bug reports we get that The claw of Hermos can be searched by Black Metal Dragon or Dark Dragon Ritual... and I don't understand why this is happening, I'm never able to reproduce that.
We just got one that finally has a replay^^
Problem being, I get an "Error occours" and I don't know why ... there's no script on the server different from the client in this situation...
you can look at that yourself if you want (turn 2 in the replay)
https://ygodevpro.com/forum/bugs/index.php/Issue/1323-Searching-The-Claw-of-Hermos/
I always thought that it might be the fault of something on the checkmate server, but this one is vs DevBot, thus 100% our server...
I'll see if I can find out more about that.

**Comment by Zayelion** [comment]
Whats the date on your servers ocgcore.dll?

**Comment by destdev** [comment]
ocgcore.dll is updated every patch, last time from about 16 hours ago

**Comment by Zayelion** [comment]
using devpro internal ocgcore lib, or ygopro-core as the source?

**Comment by destdev** [comment]
I'm not 100% sure about this one, at least buttys said yesterday that we are using 100% flos core regarding game mechanics

**Comment by Zayelion** [comment]
The devpro ocgcore is "locked down", the updates are done manually to prevent any catastrophes. compare via diff https://github.com/sidschingis/Dev_ygopro/tree/master/ocgcore to the code in this repo.

Salv and dev are building from that folder not this repo at the current time.

**Comment by Buttys** [comment]
devpro are now using Fluo's core becuase shuffle is now apart of the client, added a submodule to the git the other day https://github.com/Buttys/Dev_ygopro

**Comment by StormWulf** [comment]
For curiosity, I've changed the setcode of the cards to many things such as `0x2f0` and it still doesn't fix the bug on the server. It's a weird phenomenon.

**Comment by Zayelion** [comment]
Is devpro using the Buttys repo and not the sidshingis repo?

**Comment by destdev** [comment]
Buttys, at least since our patch 2 days ago.
Not sure if that changes again in one way or another, at least he started working again on Devpro last week ... no idea what sid is doing^^

**Comment by destdev** [comment]
I have found a solution for this.
The server seems to have a problem with the fact, that the Legendary Dragon cards have an alternative code that is not entered in the Database. To solve this, just create 3 Dummy cards with the alternative codes granted from the Scripts and everything should work fine.
