### ISSUE TITLE
Bug or Ruling? Mahad the Protector Priest[71703785]

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1793]
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c71703785.lua

When you Draw Mahad during your opening Hand of 5 cards , can you Special Summon it ? I dont know if it Misses Timing or not , since no other Effects are being Resolved , just both Players Drawing their opening Hand.

I cannot find ruling forums for an answer

Thank You!

**Comment by mercury233** [comment]
https://ygorganization.com/perfectrulebook/
Page 26
The 5 cards were drawn before the game starts, so no effect can be activated then.

**Comment by Hello23-Ygopro** [comment]
I didnt know that, I think still Continuous Effects can work that dont start a Chain , also for some people's mod cards , that reads "At the start of your Draw Phase, activate this card",
`SetCode(EVENT_PHASE_START+PHASE_DRAW)`

but in TCG&OCG no Effect like that exist, so your right in terms of that

I'll be using that page as reference in the future

Thank You!
