### ISSUE TITLE
Bug or Ruling : Toon Kingdom ?

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1802]
hi ,
i have no card in my Deck , i try to Activate Toon Kingdom but cant , is this a Bug or a Ruling ?

The ruling is grayed out on Wikia , so i dont know , and the words look like part of the Effect and not an actual Cost cuz it appears after the Activation : 
> When this card is activated: Banish 3 cards from the top of your Deck, face-down.

Thank You!

**Comment by mercury233** [comment]
You can't active Raigeki if there isn't any monster on field. It is a basic rule.

**Comment by fervi** [comment]
@Hello23-Ygopro
I'm not a Yu-gi-oh master, but to summon Toon Kingdom you must ban 3 cards. So this is why you cannot summon it.

**Comment by Hello23-Ygopro** [comment]
so its not Cost-related , just a basic rule , like trying to Activate Pot of Greed with cards left ,
its important cuz it happens at Activation , so if it cant meet the requirements , it cant Activate

Thank You
