### ISSUE TITLE
Request: Filter for announce card

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1803]
The new Ancient Gear Gadget has an effect that requires to announce a card out of a specific setname (Gadget). I'm not sure if there is any way to properly solve this with the current functions, at least I failed to find any.

I think we either need another announce function or an option to filter cards by more specific things for the AnnounceCard function.

**Comment by mercury233** [comment]
@salix5 @VanillaSalt @DailyShana This card will be released in this weekend, so this issue need to be considered.
