### ISSUE TITLE
Code explanation

### ISSUE THREAD

**Issue by anshkumar** [Fluorohydride/ygopro#1805]
Why is `std::set<>` used instead of `std::vector<>` for data member `selectsum_cards` in [gframe/client_field.h](https://github.com/Fluorohydride/ygopro/blob/master/gframe/client_field.h#L64) ?

**Comment by DailyShana** [comment]
std::set guarantee the same card appears only one time.
when selecting cards, we clearly don't want to select one card multiple times.
