### ISSUE TITLE
utilit.lua bug

### ISSUE THREAD

**Issue by ghost** [Fluorohydride/ygopro#1815]
![notepad _2016-08-07_00-46-54](https://cloud.githubusercontent.com/assets/20883386/17460770/1db11c24-5c39-11e6-967e-a6d852fa2064.png)

**Comment by mercury233** [comment]
you need to update your core

**Comment by ygopro** [comment]
Update the lua files?

**Comment by ygopro** [comment]
![ygopro_vs_2016-08-08_00-54-45](https://cloud.githubusercontent.com/assets/20883386/17470550/d59ab862-5d02-11e6-8419-b1b70ee2595c.png)
updated core got this error.

**Comment by mercury233** [comment]
It seems that you are using wrong scripts, you need to use suitable card scripts, constants.lua, utility.lua, and core.

**Comment by ygopro** [comment]
Where can i get that?

**Comment by mercury233** [comment]
Any full package of ygopro will be ok.

**Comment by ygopro** [comment]
I took the scripts from devpro then tried percy scripts.

**Comment by ygopro** [comment]
Full pacakge? like devpro percy mycard?

**Comment by mercury233** [comment]
yes

**Comment by ygopro** [comment]
About the core

**Comment by mercury233** [comment]
if you use core of 10336, and script newer than 10338, you will get errors about `IsFusionCode`
if you use latest card script, but util and constant of old version,  you will get errors about `EVENT_CUSTOM`

so just make sure all things are same version.

**Comment by ygopro** [comment]
To update the core i update the ocgcore?
