### ISSUE TITLE
Mac version not working unless upgraded from v1.033.3

### ISSUE THREAD

**Issue by fandy** [Fluorohydride/ygopro#1816]
When opened, it flashes black and crashes without an error. [The only fix is to upgrade from an older version](https://www.ygopro.co/Forum/tabid/95/g/posts/t/31696/YGOPRO-not-working-for-Mac--OSX-Yosemite-10-10-5--v1-033-7-v2#post152987) which I'm unable to find.

**Comment by salix5** [comment]
Since Percival's version has updated, this problem may no longer exist.
