### ISSUE TITLE
BUG: If Buster Blader, the Dragon Destroyer Swordsman battle destroy an attack pos dragon, the dragon will be sent to the error graveyard

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1817]
1. Player1 spsummon _Buster Blader, the Dragon Destroyer Swordsman_
2. Player2 spsummon _Destiny HERO - Plasma_
3. Use _Buster Dragon_ or _Dragonic Attack_ to make Plasma become a dragon
4. Buster Blader attack Plasma, Plasma will be destroyed, become defense position and be sent to player1's graveyard.

**Comment by salix5** [comment]
Do you have a replay file?
Thank you!

**Comment by mercury233** [comment]
https://puu.sh/qGKKP/19cc8e24e3.yrp

**Comment by salix5** [comment]
(Investigating)

**Comment by edo9300** [comment]
the same thing happens with jinzo+dna transplant
