### ISSUE TITLE
Bug : Spacebar in strings.conf

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1821]
hi , not alot of people know this , or they just use the right text edit programs :

i normally use notepad++ to modify the contents of strings.conf , but if there is a space after a word , only the words before the space will show up in ygopro (english)

for example : 
**!counter 0x40 Counter(Number 51: Finisher the Strong Arm)**
in ygopro , only "Number 51:" will show up
"Finisher the Strong Arm" doesnt show up because there are spaces after "Number 51:" which are not compatable
i can fix this by just copy-pasting the compatable spaces in between other lines that do work , but thats not the right way to do things

i want to know , is there a better program to edit the strings.conf , that will allow words after spaces to show up in ygopro (english) ?

thank u

**Comment by DailyShana** [comment]
your problem dosen't exist here
you should contact the author of ygopro (english)

**Comment by Hello23-Ygopro** [comment]
white-knighting wont help solve the issue

also your wrong , it does exist here
strings.conf is part of ygopro (any ygopro)

i submitted my report in the right section
you cant contact the author , especially for something so small , he rarely replies , you should know that by now

thank u
