### ISSUE TITLE
Bug : strings.conf

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1822]
hi , not alot of people know this , or they just use the right text edit programs :

i normally use notepad++ to modify the contents of strings.conf , but if there is a space after a word , only the words before the space will show up in ygopro (english)

for example :
`!counter 0x40 Counter(Number 51: Finisher the Strong Arm)`
in ygopro , only "Number 51:" will show up
"Finisher the Strong Arm" doesnt show up because there are spaces after "Number 51:" which are not compatable
i can fix this by just copy-pasting the compatable spaces in between other lines that do work , but thats not the right way to do things

i want to know , is there a better program to edit the strings.conf , that will allow words after spaces to show up in ygopro (english) ?

thank u

**Comment by mercury233** [comment]
This issue do ever exist, but it is fixed in https://github.com/Fluorohydride/ygopro/pull/1600
so you really need to contact the admin of the ygopro variant you are using.

**Comment by Hello23-Ygopro** [comment]
so spaces has been a problem before
thats what i was looking for , ill look into that conversation

thank u for being helpful : )

**Comment by Hello23-Ygopro** [comment]
Date : 2017-01-27
You can get it to show up in English Ygopro systems by just not using whitespace and copying the space between the words instead
