### ISSUE TITLE
BUG: If the attack target of Number S39: Utopia the Lightning is destroyed before damage cal, the attack won't reset.

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1823]
![20160823141123](https://cloud.githubusercontent.com/assets/13391795/17881969/087cb006-693c-11e6-9fa4-4855fbe96d39.jpg)

_Number S39: Utopia the Lightning_ attack a monster, use effect, deattach _Shiranui Spiritmaster_, _Shiranui Spiritmaster_ destroy the target, and then the attack of _Number S39: Utopia the Lightning_ will be kept 5000.

**Comment by DailyShana** [comment]
fixed in Fluorohydride/ygopro-core@9b9a984
