### ISSUE TITLE
Building Error on duelclient.cpp

### ISSUE THREAD

**Issue by nogard230** [Fluorohydride/ygopro#1827]
Hi, somebody help me, please. Heve problems to build on ubuntu linux.
==== Building ygopro (debug) ====
duelclient.cpp
../gframe/duelclient.cpp: In static member function ‘static int ygo::DuelClient::ClientAnalyze(char*, unsigned int)’:
../gframe/duelclient.cpp:1910:8: error: ‘PHASE_BATTLE_START’ was not declared in this scope
   case PHASE_BATTLE_START:
        ^
../gframe/duelclient.cpp:2980:7: error: ‘MSG_PLAYER_HINT’ was not declared in this scope
  case MSG_PLAYER_HINT: {
       ^
../gframe/duelclient.cpp:2985:16: error: ‘PHINT_DESC_ADD’ was not declared in this scope
   if(chtype == PHINT_DESC_ADD) {
                ^
../gframe/duelclient.cpp:2987:23: error: ‘PHINT_DESC_REMOVE’ was not declared in this scope
   } else if(chtype == PHINT_DESC_REMOVE) {
                       ^
make[1]: ** [../obj/Debug/ygopro/duelclient.o] Erro 1
make: ** [ygopro] Erro 2

**Comment by Buttys** [comment]
these are all declared in ocgcore, you can find the latest here: https://github.com/Fluorohydride/ygopro-core
