### ISSUE TITLE
BUG: Pendulum monsters equipped by Fullmetalfoes Alkahest can't be used to fusion Metalfoes Mythriel

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1828]
![image](https://cloud.githubusercontent.com/assets/13391795/18165129/22f358f4-7076-11e6-9886-08180ddbc8e9.png)

**Comment by salix5** [comment]
It can work in Fluorohydride/ygopro-core@d7814

Test replay:
https://www.sendspace.com/file/mtapz3
Please start from Turn 2.

https://www.sendspace.com/file/khns6o
It still works when all fusion summon are in the same turn.

**Comment by mercury233** [comment]
5星的那只融合是可以的，但6星的不行

**Comment by salix5** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=19550&keyword=&tag=-1
萬能溶劑裝備了變成效果怪獸的陷阱時，不能把裝備的陷阱卡拿來當素材

以這點來看，如果用萬能溶劑的效果融合，檢查素材的條件應該改成看卡片原始狀態

**Comment by DailyShana** [comment]
还是去问问比较好
It‘s better to ask Konami this question
