### ISSUE TITLE
BUG: The "special summon success" effect of monster spsummoned by Crystron Quon should be disabled

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1829]
> Question
「水晶機巧－クオン」の『①：相手のメインフェイズ及びバトルフェイズに発動できる。手札からチューナー以外のモンスター１体を効果を無効にして特殊召喚し、そのモンスターとこのカードのみを素材として機械族Sモンスター１体をS召喚する』モンスター効果によって、手札の「電磁石の戦士β」を特殊召喚し、「水晶機巧－クオンダム」をシンクロ召喚しました。
この場合、「電磁石の戦士β」の『①：このカードが召喚・特殊召喚に成功した場合に発動できる。デッキから「電磁石の戦士β」以外のレベル４以下の「マグネット・ウォリアー」モンスター１体を手札に加える』モンスター効果の処理はどうなりますか？
Answer
「水晶機巧－クオン」のモンスター効果によって特殊召喚されたモンスターは効果が無効化された状態で特殊召喚され、その後、機械族のシンクロモンスターをシンクロ召喚する際のシンクロ素材として使用され墓地へ送られる事になります。
質問の状況の場合、「水晶機巧－クオンダム」のシンクロ召喚に成功した際に、「電磁石の戦士β」のモンスター効果を発動する事はできますが、フィールドにて発動するその効果は無効化され、『デッキから「電磁石の戦士β」以外のレベル４以下の「マグネット・ウォリアー」モンスター１体を手札に加える』処理は適用されません。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=19582&keyword=&tag=-1

but now that effect don't get disabled.

**Comment by DailyShana** [comment]
fixed in Fluorohydride/ygopro-core@3fd6720
