### ISSUE TITLE
BUG: Divine Serpent Geh won't disable its attack target's effect if no effect is activated during the damage step

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1830]
Replay: https://puu.sh/r0iQk/965c0f37fc.yrp

1. Spsummon _Aria the Melodious Diva_
2. Spsummon _Divine Serpent Geh_
3. Increase the atk of _Divine Serpent Geh_ to more than 1200
4. _Divine Serpent Geh_ attack _Aria the Melodious Diva_ , don't activate any effect,
_Aria the Melodious Diva_'s attack will become 800, but won't get destroyed.
5. _Divine Serpent Geh_ attack _Aria the Melodious Diva_ , activate its effect, _Aria the Melodious Diva_ will be destroyed.

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@e236320
