### ISSUE TITLE
BUG: Illusion Balloons will throw error if Performapal Momoncarpet destroy itself when Necrovalley is in effect

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1831]
Replay: https://puu.sh/r0AAU/da2deb2d53.yrp
1. Activate _Necrovalley_
2. Activate _Performapal Momoncarpet_, it self destroy.
3. The Illusion Balloons in hand will show this error.
   ![image](https://cloud.githubusercontent.com/assets/13391795/18244566/4f68f90a-7393-11e6-96d2-5540d49cfecc.png)

**Comment by DailyShana** [comment]
It seems that Fluorohydride/ygopro-core@8520696 resolve this issue but potential problem still exists.
