### ISSUE TITLE
BUG: The return control "activation" of card in deck won't show hint to activate

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1833]
![img](https://cloud.githubusercontent.com/assets/13391795/18282753/16a76c84-7495-11e6-9563-4f765bd086dd.jpg)

1. Use _Darklords' Temptation_ to get control of one monster
2. Use a Darklord monster to copy this _Darklords' Temptation_, return it to deck and get control of another monster
3. End the turn, you will be asked to "activate" return control, but the _Darklords' Temptation_ in deck won't show hint to activate

**Comment by DailyShana** [comment]
3e0740b77c33cb0b4ec67e078f3532a21690771c
also solve #1749
