### ISSUE TITLE
Request: Make attacking and pendulum summon can be canceled

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1837]
Attacking was able to be canceled ever, but it was disabled in the recent version, can this feature be added back?
Pendulum summon needs cancel too.

**Comment by salix5** [comment]
攻擊宣言的順序嚴格來說是：
選擇攻擊怪獸->攻擊宣言之際的效果->選擇攻擊對象
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8726&keyword=&tag=-1
從選擇了攻擊怪獸開始那隻怪獸就算是攻擊過了
即使攻擊宣言沒有正式成立，這回合也不能再用那隻怪獸攻擊
以這點來看，選擇了攻擊怪獸之後就算是違背了「不能攻擊」的誓約

目前的判斷是
從選擇攻擊怪獸並執行攻擊指令開始就視為違背了「不能攻擊」的誓約
也就是說到了選擇攻擊對象這步之後，玩家不能倒回到執行攻擊指令之前的狀態比較合理

至於靈擺召喚的部分我不清楚

**Comment by DailyShana** [comment]
简单一点就像以前那样，有attack cost的时候才不能取消攻击

实际上选攻击对象必然是攻击宣言的一部分
实际操作中，肯定是这样说：“我用霞之谷猎鹰攻击你的青眼白龙，由于霞之谷猎鹰的效果，将蔷薇的刻印返回手牌。。。”
不大可能是这样：“我用霞之谷猎鹰攻击，由于霞之谷猎鹰的效果，将蔷薇的刻印返回手牌，霞之谷猎鹰的控制权返回，然后选青眼白龙为攻击对象”
所以其实应该把attack cost放在选攻击对象之后

**Comment by salix5** [comment]
http://yugioh-wiki.net/index.php?%A1%D4%B2%E2%A4%CE%C3%AB%A4%CE%A5%D5%A5%A1%A5%EB%A5%B3%A5%F3%A1%D5
Ｑ：このカードの攻撃宣言を行うためにカードを手札に戻す行為と攻撃対象を選択する行為はどちらが先に行われますか？
　　（《ビッグバン・シュート》との兼ね合い。）
Ａ：カードを手札に戻してから攻撃対象を選択し攻撃宣言を行います。(10/11/18)
　　よって相手モンスターに装備された《ビッグバン・シュート》を手札に戻して攻撃宣言を行う場合装備されていたモンスターは攻撃対象に選択できません。(11/07/06)

WIKI的記錄是先處理攻擊宣言之際的效果，之後才選擇攻擊對象

**Comment by shadowfox87** [comment]
![attackdeclare](https://user-images.githubusercontent.com/12994748/30060030-9868851c-920f-11e7-9034-7c120f96f563.jpg)
This is the scan of the official OCG Rulebook 2017. In the second paragraph, it states here that selecting an attack target is part of completing the attack declaration process. If the attack target has not been selected, then the attack declaration is incomplete.

In the case of Mist Valley Falcon, the cost should not be paid BEFORE selecting the attack target. In fact, the cost of returning a card from field to hand is paid as soon as the attack target is selected. You can reference this ruling:
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=8109&request_locale=ja

> このカードは、このカード以外の自分フィールド上のカード１枚を手札に戻さなければ攻撃宣言できない。
> ■「霞の谷のファルコン」のモンスター効果は永続効果です。
> ■「霞の谷のファルコン」自身が攻撃宣言を行う際に、自分フィールドのカード１枚を手札に戻します。 自分フィールドに他のカードが1枚も存在しない場合、「霞の谷のファルコン」は攻撃宣言を行う事自体ができません。
> ■「霞の谷のファルコン」自身が攻撃宣言を行う際に、自分のフィールドの裏側表示のカードを手札に戻す事もできます。
> ■「霞の谷のファルコン」自身が攻撃宣言を行う際に手札に戻すカードとして、モンスタートークンや、融合・シンクロ・エクシーズモンスターを選ぶ事はできません。

In addition, the official online automatic simulator by Konami - Legacy of the Duelist does the same thing. In this game, players are allowed to "right-click" to cancel an attack if the attack target has not been chosen.

Another example would be similar to Chess where a player is picking up a Chess piece. Picking up this chess piece does not commit that player to that chess piece until he has placed that Chess piece on the board and removed his/her hand from the Chess piece.

Hence, @salix5 , I hope you can please reconsider your decision after all this information I have given you to make a more accurate simulator.

**Comment by MichaelLawrenceDee** [comment]
@salix5 you still owe us Duel.ChangeAttacker, I don't care if rulings support you, but remember you also fucked a function up.
