### ISSUE TITLE
BUG: If Royal Prison is in effect, Paleozoic cards can't spsummon from graveyard

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1839]
> 墓地の「幻影騎士団シャドーベイル」は罠カードです。
「王宮の牢獄」の『このカードがフィールド上に存在する限り、お互いのプレイヤーは墓地のモンスターを特殊召喚できない』効果が適用されている場合でも、墓地の「幻影騎士団シャドーベイル」の効果を発動する事はできます。
（その効果処理によって、特殊召喚された「幻影騎士団シャドーベイル」は通常モンスター扱いとなります。）
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=7518&keyword=&tag=-1

Now it can be activated, but the summon won't be done.

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/84bd42fcfe037e89ce89693c1a8628e0322b7143#diff-b634e0b2032bae84bdfaffa2eaef1720
