### ISSUE TITLE
Request (1/2) : Top view in ygopro

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1842]

**Comment by nogard230** [comment]
i need too. Options on GUI to enable/disable top view horizontal and vertical and battle of monster animation(like gba) is perfect to cool spectat championships.

**Comment by Hello23-Ygopro** [comment]
Date : 2017-01-27 - Reopened

Edit: @salix5 @VanillaSalt @Fluorohydride
Maybe not as important as avatars , but something to consider for the future to expand Ygopro further , and can give some coders new ideas to improve Ygopro more
