### ISSUE TITLE
Request (2/2) : Avatars in ygopro

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1843]

**Comment by mercury233** [comment]
mycard team it trying to do this
it will need a launcher to get the avatars of players and place them in one folder.

**Comment by Hello23-Ygopro** [comment]
@mercury233 hi ,

i was hoping there wudnt be a launcher necessary , and just like cover1 and cover2  , there wud be avatar1 and avatar2 ..
if u exit ygopro , u quickly put in ur avatar1 & avatar2 (they can be any size the source code says) ,
like 80x80 for example , but prefferably with same width and height cuz their squares
then if ygopro starts in a duel , those avatars will load like sleeves , without the need of a launcher

lets hope , maybe in ygopro it wud be inherently available , but for the time being we can use a duel background with photo-edited avatars , so its not that big of a request ..

thanks for the reply

**Comment by Hello23-Ygopro** [comment]
Date : 2017-01-27 - Reopened 

It seems rather weird to see a Ygopro game without avatars..
some modified Ygopros have them , but it seems right to add them to the official source code here along with the backgrounds and card covers

Ill leave this open for the future
