### ISSUE TITLE
BUG: Qliphort monsters will ignore the effect of Dupe Frog

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1845]
![qq 20160918202946](https://cloud.githubusercontent.com/assets/13391795/18615652/b2957030-7dde-11e6-8f57-1acf8d6c0615.png)
Special summon _Dupe Frog_, normal summon one Qliphort monster, it will be able to attack any monster.

![image](https://cloud.githubusercontent.com/assets/13391795/18615721/3bc78860-7de0-11e6-8563-7f0088747db5.png)
The other monsters will work as expected, can only attack _Dupe Frog_.

Replay: https://puu.sh/rfobE/c2f0167569.yrp

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@cf73af5
