### ISSUE TITLE
[Proposal] Better card labels suggestion for .cdb file

### ISSUE THREAD

**Issue by MobiusMei** [Fluorohydride/ygopro#1849]
Up to now, ygopro do have a number of labels for cards, which help both players and programmers to mark the cards. However, sometimes the labels could be confusing, and make the maintenance for new cards becoming hard.

According to the existing situation, I would like to propose some changes for .cdb files.
1. [Category List]
   --Add [Special Summon/特殊召唤] or [Special Summon-only] 
   This change would be applied to cards like [フォトン・スラッシャー/Photon Thrasher]
   Hence, they could be distinguished better with cards like [サイバー・ドラゴン/Cyber Dragon]
   According to this list https://ocg.xpg.jp/search/search.fcgi?Category0=45&Mode=2
   The number of Special Summon Monsters are above 260, not a big number.
2. [Effect Labels List]
   --Change [Back to Hand/返回手卡] to [Return to hand/弹回手卡]
   --Change [Back to Deck/返回卡组] to [Return to Deck/弹回卡组]
   --Change [Recovery] to [Recycle] *English-version only
   These changes will match the label [Recycle/回收] better.
   Now ygopro have labels which are pretty confusing here.
   e.g.1. Cards with effects like [return 1 card from graveyard to hand] have no [Recycle] label
   e.g.2. Cards with effects like [return 1 card from graveyard to deck] have the [Recycle] label

After all, there's no reason for these confusion to happen at all.
And up to now, we only have above 300 cards with each of these labels, and most of them are crossing over 2 or more.
Therefore, this change will not be painful or heavy loading, and will eventually helps ygopro to grow.

**Comment by Hello23-Ygopro** [comment]
@MobiusMei 
I'm also for your label idea to simplify and update them , but i'm afraid you and i are part of the minority who still care about this

It would be nice to have "Special Summon" card type included , it is an official card type after all
I haven't seen any Ygopro system have it as a Constant , but maybe if the English TCG implements it in Series 10 , all Ygopro systems will start to use it

Unfortunately , most other people don't care about Categorys anymore , "Who still actually uses the category to search for cards?" i do , i make alot of custom cards , and i use it all the time to look for specific effects , if i don't remember the cards name , and should the card pool become 10,000+ cards , u can't expect everyone to remember every single effect and searching key-words won't always be enough 

I think i remember seeing Ygopro Devpro not even using the Category feature anymore , and it being used incorrectly in other Ygopro English versions , such as "Back to Hand" being used on all "Search" effects , so i can agree with "Return" being better , so those people don't get confused

But luckily the more official Ygopro ADS/Core/MyCard/etc. still use it , and i'm thankful for it , however :
-"Type & Property-Related" is definitely not used any more as much for "Monster Types and Attribute-related" effects that specifically state them , i think people just forget to add them
-"Destroy" for "Cannot be destroyed by battle [or card effects] , and "Select" for "Cannot be targeted by card effects" are also kinda left out on most Ygopro systems
-Lastly the one almost everyone doesn't use any more is "Search" , for any effect that causes a player to look in their Main or Extra Deck ,
e.g. "At the end of the Battle Phase, if this card attacked or was attacked: You can shuffle it into the Deck; Special Summon 1 "Gladiator Beast" monster from your Deck"
e.g. "Send 1 card from your Deck to the Graveyard."
you're "searching" your deck to select a monster to special summon, and "Searching" it to select a card to send to the grave , so "Search" has to be checked in this case

I've also been addressing this issue to other English Ygopro leaders , but they simply don't care , or are too lazy to edit them which is understandable , but at the same time it's better to address this issue sooner than later , the card pool is already over 8000+ cards , and it will be an enormous task in the future as more cards are added

**Comment by DailyShana** [comment]
The idea of effect labels is taken from TF series in PSP, on which type text is very complicated, so use effect labels to search card efficiently.
But on ygopro, one can search card by card name or card effect text, which is more straight and efficient. Effect labels is essentially duplicate to the effect text.

I think effect labels should be depreciated.
