### ISSUE TITLE
BUG: The select zone process of get control a trap monster don't work properly

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1850]
![image](https://cloud.githubusercontent.com/assets/13391795/19339103/dedd7948-9153-11e6-9f40-0aeb2f94334c.png)
Get control of a trap monster (which is also still a trap card), you will be able to select the field zone and pendulum zone to use.

Selecting a wrong zone will cause further glitches.
![image](https://cloud.githubusercontent.com/assets/13391795/19339212/acc498c8-9154-11e6-8e55-549d2772993c.png)

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@91dc62a
9aea518
