### ISSUE TITLE
BUG: If two monsters is banished temporarily, and the field don't have enough space, the player can't select which monster to return.

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1851]
Use _Timebreaker Magician_ to banish itself and another monster, when them return to field, I don't have enough space, I won't be able to select which monster to return.
![image](https://cloud.githubusercontent.com/assets/13391795/19339408/c73f1ace-9155-11e6-9bbf-ed5aa758e0b7.png)
![image](https://cloud.githubusercontent.com/assets/13391795/19339436/f1f161be-9155-11e6-9dea-37c5a44d911c.png)

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-scripts@447fc6f
