### ISSUE TITLE
BUG: Erebus the Underworld Monarch can be summoned infinitely in certain stituation

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1852]
Replay: https://puu.sh/rIWCm/60274ddc7f.yrp

your opponent have one tribute summoned monster, 
you have 5 zones full, and you activated _The Monarchs Stormforth_, 
you summon _Erebus the Underworld Monarch_, and you can select _release 1 tribute summoned monster_, which shouldn't happen because you don't have enough space,
and the effect of _Erebus the Underworld Monarch_ can be activated, but it won't be summoned to field, and you can summon it again.

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-scripts@8a44562
