### ISSUE TITLE
Bug: destroy replace

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1855]
EFFECT_DESTROY_REPLACE seems to take place before STATUS_BATTLE_DESTROYED, this shouldn't happen
example: If you have Kozmo Landwalker alone on the field you can still activate the effect to destroy another Kozmo if he would be destroyed by battle (works fine if he would be destroyed by effect)
you can also destroy another battle destroyed kozmo instead of letting it die by battle
![kozmo](https://cloud.githubusercontent.com/assets/12686731/19628814/69459c40-9966-11e6-8351-ed6129c1cfde.jpg)

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/5694c8b5774c6554e669db793007a5441450b4b1
