### ISSUE TITLE
BUG: Vylon Omega sync procedure bug

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1856]
It will fail to select the material under some condition.
![image](https://cloud.githubusercontent.com/assets/13391795/19686364/5abec618-9af3-11e6-8aff-a50581f6c605.png)

Replay: https://puu.sh/rV1Ti/febb2e8c92.yrp (Turn 4)

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/1ec840ff62443f2f073081b89537b4bd9e4a8b4a
