### ISSUE TITLE
Bug: Counters can't be removed manually

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1860]
I'm not sure since when exactly this issue takes place. I think it started about 1.5-2 weeks ago.
If you have an effect that requires you to remove any type of counter manually from a card you can't do that anymore.
Example: Have any Kaiju effect that requires you to remove x amount of kaiju counters from anywhere on the field. You can activate the effect, then the game waits for you to pic counters. However there is no card available to select in order to remove the counters. The system seems to recognize that the required counters are present on the field, however when you have to remove them no card is highlighted or clickable. The player then has to time out or quit.
![k1](https://cloud.githubusercontent.com/assets/12686731/19752335/c557fdbe-9bfc-11e6-8dc6-6fd68ea6c43a.jpg)
![k2](https://cloud.githubusercontent.com/assets/12686731/19752338/c8d70fac-9bfc-11e6-8e13-a9bbe3717d6b.jpg)

Cards that remove counters automaticly from a place (example: Royal Magical Library automaticly removes 3 counters from itself without needing the player to click on that) still work perfectly fine. This bug affects all kinds of counters.

**Comment by mercury233** [comment]
Are you sure that you updated those commits?
https://github.com/Fluorohydride/ygopro/commit/4cc3b3bf7b5b8a29af9e0c294a66945b355c25fb
https://github.com/Fluorohydride/ygopro-core/commit/7f4e96536a73d8d06b1cc6dbfda206d5d65c4aff

**Comment by Cristichi** [comment]
28 aug 2017: this problem keeps happening

**Comment by destdev** [comment]
then the client you are using is propably not updated, refer to the 2 commits linked above
