### ISSUE TITLE
BUG: Sprite's Blessing can spsummon Nekroz of Sophia with any material

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1865]
![image](https://cloud.githubusercontent.com/assets/13391795/20038695/1f27c9b8-a473-11e6-9ba5-40bd8e6d3dcb.png)
![image](https://cloud.githubusercontent.com/assets/13391795/20038717/700fa972-a473-11e6-8340-3d4e5cb9f4b0.png)

The `ritual_custom` of _Nekroz of Sophia_ won't work.

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/84a9dc227cbc6ac5549b703c9beba635915269e8

**Comment by mercury233** [comment]
为什么不在aux那里加呢……

**Comment by DailyShana** [comment]
唔，好像是可以放在aux里面
