### ISSUE TITLE
Request: Some effects of new official cards is hard or impossible to implement in ygopro

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1867]
- [x] 1. _RATE-JP009 [Parasite Fusioner](http://yugioh.wikia.com/wiki/Parasite_Fusioner) パラサイト・フュージョナー_
   Its "Cannot be used as a Fusion Material unless used as fusion substitute" limit may need changes to utility.
- [x] 2. _RATE Zoodiac/Juunishishi/十二獣 monsters_
   Their "Xyz Monster with this card as Xyz Material gains effect" effect is different from _Star Drawing_. It should be able to be registered if a Xyz monster was summoned with other monsters and then get Zoodiac monster as Xyz Material. Now, as workaround, the effect is registered to all Beast-Warrior Xyz Monster when them spsumon, and enabled when those Xyz Monster has Zoodiac monster as Xyz Material.
- [x] 3. _SPFE-JP005 [Predaplant Sundew Kingii](http://yugioh.wikia.com/wiki/Predaplant_Sundew_Kingii) 捕食植物サンデウ・キンジー_
   Its "If you use a monster with a Predator Counter as a Fusion Material, treat it as a DARK monster." effect needs something like `Card.IsFusionAttribute`. Note only the owner player of this card is affected by this effect.
- [x] 4. _DBLE-JP002 [Tune Magician](http://yugioh.wikia.com/wiki/Tune_Magician) 調弦の魔術師_
   It has Synchro Material limit like _Royal Swamp Eel_ but apply on Xyz and Fusion too. Now only syn limit(`EFFECT_SYNCHRO_MATERIAL_CUSTOM`) can be implemented.
- [x] 5. _PP19-JP004 [Pendulum Fusion](http://yugioh.wikia.com/wiki/Pendulum_Fusion) ペンデュラム・フュージョン_
   It can take cards in pendulum zone as fusion material, but `Card.IsCanBeFusionMaterial` prevent it as default. And `Card.IsType` won't return `TYPE_NORMAL` on Normal/Pendulum monster in pendulum zone. Btw, _Starving Venom Fusion Dragon_ need change to use cards in pendulum zone.
- [x] 6. _PP19-JP014 [Synchro Call](http://yugioh.wikia.com/wiki/Synchro_Call) シンクロコール_
   It might have issues with special tuners, such as _Blackwing - Kochi the Daybreak_, _Tatsunoko_.
- [x] 7. _SD31-JP041 [Startime Magician](http://yugioh.wikia.com/wiki/Startime_Magician) 	星刻の魔術師_
   It might have issue with _Wonder Xyz_. See https://github.com/Fluorohydride/ygopro-pre-script/pull/71 .
- [x] 8. _COTD-JP053 [Trickster Lightstage](http://yugioh.wikia.com/wiki/Trickster_Lightstage)_ トリックスター・ライトステージ
   Its "activate effect" effect seems cannot select target using `Duel.SelectTarget` because the end phace act don't have a chain.

**Comment by mercury233** [comment]
updated two cards

@EerieCode I think you can add your fusion procedure here
@destdev I think you can add your Necrovalley here

**Comment by EerieCode** [comment]
Ok. I'll take some time to test it with more complicated combinations and make sure there are no issues before adding it.

**Comment by EerieCode** [comment]
Alright @mercury233 , [I've made a branch with the finalized procedure](https://github.com/Fluorohydride/ygopro-scripts/pull/712). As I said in the comment, I've tested it with all circumstances I could think of: "Chain Material", "Miracle Synchro Fusion", "Super Polymerization", Pendulum hybrids, it always worked without any problems.

**Comment by destdev** [comment]
I thought you've already put necrovalley in your pull requests along the other cards?
But ok, I can make one too for that^^

**Comment by mercury233** [comment]
updated one card

**Comment by Hello23-Ygopro** [comment]
Thank you , now just Tune Magician is left !

**Comment by mercury233** [comment]
updated _Trickster Lightstage_
