### ISSUE TITLE
BUG: The battle damage between Number C96: Dark Storm and Odd-Eyes Pendulum Dragon is wrong

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1871]
![image](https://cloud.githubusercontent.com/assets/13391795/20460711/fb7eab1c-af26-11e6-9095-97effed54556.png) 
_Odd-Eyes Pendulum Dragon_ attacks _Number C96: Dark Storm_, the player of _Number C96: Dark Storm_ get 3000 damage, but the player of _Odd-Eyes Pendulum Dragon_ only get 1500.

**Comment by edo9300** [comment]
i think this happend because both use EVENT_PRE_BATTLE_DAMAGE, and c96 resolves first, i think a new effect should be added, like the REVERSE_RECOVER one

**Comment by DailyShana** [comment]
In fact, this behavior is not a bug now
