### ISSUE TITLE
BUG: Void Imagination can fusion Infernoid Tierra with only 2 cards under some condition

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1873]
Replay: https://puu.sh/sqP3t/acd26e3c9f.yrp

The bug appeared in turn 2.

**Comment by edo9300** [comment]
hmm so if you don't have any infernoid in the hand/mzone you can use only devyaty and onuncu

**Comment by mercury233** [comment]
This problem still exists.

**Comment by edo9300** [comment]
@mercury233 i made that fix but no one approved it...
