### ISSUE TITLE
BUG: Necroface always gains ATK

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1877]
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c28297833.lua#L28

Necroface still gets an ATK boost , even if the cards aren't shuffled to the deck , inside the : e1:SetValue(g:GetCount()*100)

The only solutions i can think of is , A) using a Duel.GetOperatedGroup
or B) Duel.SendtoDeck(g,nil,2,REASON_EFFECT)~=0

i don't know how the OCG rules it , but i just thought to go to through the official channels and bring it to your attention

thank u

**Comment by salix5** [comment]
ygopro-scripts@eed9034a4ed68fad7253aad17ce22f2ca65ba0fc
fixed
Thank you.

**Comment by Hello23-Ygopro** [comment]
Ah so you used FilterCount to make sure its in the deck when counting
It works perfectly,
Thank you
