### ISSUE TITLE
BUG: Gagagarevenge throw error if it is disabled by D/D/D Cursed King Siegfried etc.

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1881]
![image](https://cloud.githubusercontent.com/assets/13391795/20910846/05429d3c-bb9f-11e6-9908-5b467fc5b767.png)
Activate Gagagarevenge, use Siegfried to disable it, it will be sent to grave and show this error.

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/a090e2aa519938c38926a79f47056112995bf246
