### ISSUE TITLE
BUG: Dawn of the Herald and Cyber Tutubon will conflict when activating effect at same time

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1883]
Tribute _Cyber Tutubon_ with _Dawn of the Herald_, you can activate both effect at same time, 
but if _Dawn of the Herald_ is the only Ritual Spell in grave, and it banish itself, _Cyber Tutubon_ shouldn't be able to activate with no target.

**Comment by DailyShana** [comment]
If there is only one monster in grave, you can activate two _Call of the Haunted_, targeting the same monster.

**Comment by mercury233** [comment]
if you let _Dawn of the Herald_ chain 1, the chain 2 of _Cyber Tutubon_ will fail to select target, which shouldn't happen

**Comment by DailyShana** [comment]
solved in e6c44f6
