### ISSUE TITLE
Bug: Effect affecting cards moved to the field within a chain

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1884]
Quite difficult to explain, thus here a replay: (turn 3)
[2016-12-08 06-55-06.zip](https://github.com/Fluorohydride/ygopro/files/638550/2016-12-08.06-55-06.zip)
(uses 1 prereleased card, https://github.com/Fluorohydride/ygopro-pre-script/blob/master/scripts/MACR-JP/c100912075.lua )
Situation:
Chain link 1: Activate Raigeki
Chain link 2: (doesn't matter in this case I think...)
Chain link 3: (doesn't matter in this case I think...)
Chain link 4: Twin Twister on face down Destruction Swordsman Fusion and face down Destruction Sword Memories
Chain link 5: Destruction Sword Memories
Chain link 6: Destruction Swordsman's Cradle grave effect

On resolution Destruction Sword Memories gets protected by Cradle properly, however the Destruction Swordmaster summoned after the resolution of Cradle doesn't get protected by that from Raigeki. It should however, since Cradle is supposed to protect every face up destruction sword card after its resolution and also does so properly with the already face up Memories, just not the card summoned after its resolution.

**Comment by DailyShana** [comment]
>This card's name becomes "Buster Blader" while it is on the field or in the Graveyard. 

so _Buster Blader, the Destruction Swordmaster_ is not a "Destruction Sword" card when it is on field.

**Comment by destdev** [comment]
I feel dump >.<
thanks^^
