### ISSUE TITLE
BUG: Super Polymerization can be activated to fusion summon Starving Venom Fusion Dragon if my field is full of token

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1885]
![image](https://cloud.githubusercontent.com/assets/13391795/21071633/9d7a60fe-bee1-11e6-9df1-08c2824eda1c.png)
I shouldn't be able to fusion summon _Starving Venom Fusion Dragon_ because I don't have enough space,  but _Super Polymerization_ can be activated.

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/d0ec12fab15eebda0e934701533c6c27267463f1
