### ISSUE TITLE
BUG: Number 38 can activate effect if one xyz monster is destroyed and spsummoned by Toadally Awesome

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1886]
mail say it shouldn't activate:
> Q. 
自分のモンスターゾーンに表側表示で存在する「ダイガスタ・エメラル」が、相手の「餅カエル」の『②』の効果で破壊し、相手フィールドにセット。 
その際に、自分の「No.38 希望魁竜タイタニック・ギャラクシー」の『③』効果を発動する事はできますか？ 
A. 
ご質問の場合、「餅カエル」の効果によって、破壊した「ダイガスタ・エメラル」をセットした場合、「No.38 希望魁竜タイタニック・ギャラクシー」の『③』の効果を発動する事はできません。 

Now it can activate, but the effect cant resolve because `c:IsPreviousLocation(LOCATION_MZONE)` become false.
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c63767246.lua#L76

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/24089d2b7f0a4dc5098dd5523b2f0ca951f124a8#diff-2eaa4b4b13a91b086a7e7b4e7ee554aa
