### ISSUE TITLE
issue with monster that can be tribute summoned with less tributes

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro#1887]
The monsters in this list: http://yugioh.wikia.com/wiki/Normal_Summon_with_1_Tribute
 become bugged allowing you to "tribute summon" them in
this situation:
Your monster zones are full, with not valid tributes (e.g. Summoner Monk)
Your opponent has a valid tribute on their field
You activate The Monarch Stormforth or Soul Exchange
Now you're able to make a pseudo-tribute summon, but the monster will remain in the hand and it can be summoned again and, the most important thing, you can activate its effects when summoned.
I think this happens because the game doesn't check properly the zones when there are monsters with EFFECT_EXTRA_RELEASE_SUM and EFFECT_EXTRA_RELEASE effects
this happens both with custom procedures https://github.com/Fluorohydride/ygopro-scripts/pull/705 and the EFFECT_DECREASE_TRIBUTE in the case of Fog King

**Comment by DailyShana** [comment]
partially solve this in Fluorohydride/ygopro-core@28156c4 and set up a framework for checking tributes in summon proc
the next step is to make field::check_tribute perfect.
