### ISSUE TITLE
Bug: EFFECT_RITUAL_LEVEL + greater function

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1894]
I'll use Crab Turtle + Turtle Oath in this example. I've also tested this with the equal function (Nekroz Mirror + Shurit), this seems to work fine.
Have the monster + spell in hand + 3 levels of any other material + Gishki Shadow -> you correctly have to use the effect of Shadow and can properly use only that card as material, that works fine.
Have the monster +spell in hand + 4 or more levels of any other material + Gishki Shadow ->You can select any other material with a total value of 3 or less, then select Shadow and use the effect.
![unbenannt](https://cloud.githubusercontent.com/assets/12686731/21452346/81382e7e-c906-11e6-9889-44f602fb58c8.jpg)
You should not be allowed to use shadows effect if there is already anything else selected, this contradicts the rule that you are not allowed to use extra tributes.

edit:
Just noticed something else: If Shurit is in Grave and I want to summon Brionac with Mirror I'm not able to use only Shurit if I have at least 3 Rats in hand. I'm only able to use Shurit if I can't get any level combination of exactly 6 else. While Shurit is in the hand it seems to work fine.

**Comment by DailyShana** [comment]
fixed in d15cdb164cb9cecd4f46f7b76e7b6f5b77b9000d
