### ISSUE TITLE
BUG: Fullmetalfoes Alkahest will show error if ABC-Dragon Buster is in extra

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1896]
![image](https://cloud.githubusercontent.com/assets/13391795/21499648/ad216b8a-cc72-11e6-97a0-be4c305206ec.png)
Use the effect of _Fullmetalfoes Alkahest_ to equip a monster, and when _ABC-Dragon Buster_ is trying to check if it can spsummon, this error will show up.

**Comment by DailyShana** [comment]
Because Card.IsCanBeFusionMaterial ignores the second parameter in many scripts

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/8065944147a8d40b5ba0ae37f3019ab175f25e21 fixed, thanks
