### ISSUE TITLE
BUG: The extra attack of Frightfur Wolf cannot be copied by Starving Venom Fusion Dragon

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1897]
mail:
> Q. 
融合召喚に成功した「スターヴ・ヴェノム・フュージョン・ドラゴン」のモンスター効果の対象として、「デストーイ・シザー・ウルフ」を選んだ場合、1度のバトルフェイズ中に2回攻撃できますか？ 
A. 
「スターヴ・ヴェノム・フュージョン・ドラゴン」が「デストーイ・シザー・ウルフ」の効果を得た場合、1度のバトルフェイズにおいて、この「スターヴ・ヴェノム・フュージョン・ドラゴン」の融合素材としたモンスターの数まで攻撃をする事ができるようになります。 
したがって、「スターヴ・ヴェノム・フュージョン・ドラゴン」を融合召喚する際に、融合素材を2体使用していたのであれば、2回攻撃する事ができます。 

Now the extra attack effect of _Frightfur Wolf_ is registered when the card summon, so _Starving Venom Fusion Dragon_ can't copy it.

If we use 
```lua
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetCode(EFFECT_EXTRA_ATTACK)
	e3:SetValue(c11039171.atkval)
	c:RegisterEffect(e3)
...
function c11039171.atkval(e)
	local c=e:GetHandler()
	return math.max(c:GetMaterialCount()-1,0)
end
```

the effect can be copied, but the extra attack won't reset when the card become face-down.

So should we let the `MaterialCount` of a card reset when it become face-down?

**Comment by DailyShana** [comment]
What about the ① effect of _Rune-Eyes Pendulum Dragon_?

**Comment by TheOnePharaoh** [comment]
if we add a condition with is Summon type fusion it will reset if it gets set

**Comment by nekrozar** [comment]
Maybe this rule is changed.
> Q. 
> 「覇王眷竜ダークヴルム」1体と「覇王眷竜オッドアイズ」1体を融合素材として、「融合」の効果で「覇王眷竜スターヴ・ヴェノム」が融合召喚されています。 
> 
> 「キメラテック・メガフリート・ドラゴン」を対象にその「覇王眷竜スターヴ・ヴェノム」の①の効果を発動した場合、「キメラテック・メガフリート・ドラゴン」の『このカードの元々の攻撃力は、このカードの融合素材としたモンスターの数×１２００になる。』効果は適用されますか？ 
> A. 
> ご質問の場合、「キメラテック・メガフリート・ドラゴン」の効果を得た「覇王眷竜スターヴ・ヴェノム」には『①：このカードの元々の攻撃力は、このカードの融合素材としたモンスターの数×１２００になる』効果は適用されず、「覇王眷竜スターヴ・ヴェノム」の最終的な攻撃力は【2800】となります。

> Q. 
> 「覇王眷竜ダークヴルム」1体と「覇王眷竜オッドアイズ」1体をリリースして、自身の方法で「覇王眷竜スターヴ・ヴェノム」が特殊召喚されています。 
> 
> 「キメラテック・メガフリート・ドラゴン」を対象にその「覇王眷竜スターヴ・ヴェノム」の①の効果を発動した場合、「キメラテック・メガフリート・ドラゴン」の『このカードの元々の攻撃力は、このカードの融合素材としたモンスターの数×１２００になる。』効果は適用されますか？ 
> A. 
> ご質問の場合、「覇王眷竜スターヴ・ヴェノム」の最終的な攻撃力は【2800】となります。
