### ISSUE TITLE
BUG: Future Fusion can send the material of ABC-Dragon Buster to grave

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1898]
> 「未来融合－フューチャー・フュージョン」の効果で融合召喚を行う場合、『①：このカードの発動後１回目の自分スタンバイフェイズに発動する。自分のエクストラデッキの融合モンスター１体をお互いに確認し、そのモンスターによって決められた融合素材モンスターを自分のデッキから墓地へ送る』効果処理によって、融合素材モンスターをデッキから墓地へ送る必要があります。
「ABC－ドラゴン・バスター」の場合、テキストに記された『自分のフィールド・墓地の上記カードを除外した場合のみ、エクストラデッキから特殊召喚できる（「融合」は必要としない）』方法によってのみ特殊召喚する事ができるモンスターとなりますので、融合召喚によって特殊召喚する事自体ができません。
したがって、「未来融合－フューチャー・フュージョン」の効果によって、「ABC－ドラゴン・バスター」を融合召喚する事はできず、その素材となるモンスターをデッキから墓地へ送る事もできません。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20323&keyword=&tag=-1

But now it can send the material of ABC-Dragon Buster to grave.

**Comment by DailyShana** [comment]
If the card name of ABC-Dragon Buster is changed to Neo by Hero Mask, is Contact Out able to spsummon A, B and C from deck?

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-core@1345016
Fluorohydride/ygopro-scripts@b7b6484
