### ISSUE TITLE
Complete list of Cards Not Working

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1901]
Does some one keep a updated documented record of all cards that Ygopro cannot correctly play at this time ?

As the card pool gets bigger , more effects become harder to script and need more source code updates , not to mention of a possable 6th gen new mechanic revealed soon , so i think its more important now to keep track of all unimplementible cards , and in an updated method , like a google spreadsheet or some thing

Aside from the beta and pre-scripts , i know of a few older ones ..
Some Ygopro forums also listed these , but i dont know if it applies to all different Ygopro systems , and maybe some of them has been fixed since i was here : 
- https://github.com/Fluorohydride/ygopro-scripts/blob/master/c38723936.lua#L2
- https://github.com/Fluorohydride/ygopro-scripts/blob/master/c94568601.lua#L2
- Bait Doll vs Fiendish Chain / Fog Blade

> Use Bait Doll on a card like Fiendish Chain or Fog Blade. If there is a legal target for the trap on the field and the trap ISN'T chained the effect of the trap targets the card but doesn't apply the effect. To avoid that, just chain the trap targeted by Bait Doll.

- Nightmare Wheel
> Have a successfully resolved Nightmare Wheel on the field, targeting a monster. This card is one of very few that shouldn't loose its target if that monster is flipped face down. However, the core automaticly makes the card loose the target if that target is flipped face down. Currently I don't have any solution for that.
- Graydle control change vs Trap Monsters

> If you have only 1 free s/t zone and destroy a greydle you can activate the effect to take control of a monster. You are also able to target a trapmonster, which shouldn't be possible since you don't have another free s/t zone that is able to be occupied by that.

My computer cant handle putting all 8000+ scripts into notepad , so i cant search for the key words : "Not fully implemented"

Thank You!

**Comment by destdev** [comment]
I'll just drop that here now, for your info
https://github.com/Fluorohydride/ygopro/issues/1723

**Comment by Hello23-Ygopro** [comment]
@destdev Thank you , that helps

Regarding "Nightmare Wheel" : 
it makes sense since its similar like a Call of the Haunted targeting situation : 
if you Book of Moon the Summoned monster , it is no longer affected by the negative effects of Call of the Haunted ( if i remember right )

**Comment by destdev** [comment]
this is a different case, the problem with nightmare wheel was that both are a legal target, face up AND face down monsters (unlike 99% of all other continuous s/t cards that can only target one OR the other, not both)
I couldn't find any ruling for that situation before. It's good that we have one now.

**Comment by Hello23-Ygopro** [comment]
Im sure someone has a list somewhere , if they dont its not important cus the cards mentioned are hardly ever played , even casually , so its a "less priority" you like to say

Besides there are more important issues

Closed
