### ISSUE TITLE
BUG: Inferno Reckless Summon will send all monsters to grave under some condition

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1911]
It seems recent changes to `Duel.SpecialSummonStep` make the monsters in summon progress don't treated as on field, so them won't be removed from the group which will be sent to grave.
https://github.com/Fluorohydride/ygopro-scripts/blob/d35f4628e0e72dfe78e839d9d889d3c12c8e0362/c12247206.lua#L59

Replay: https://puu.sh/tfc6d/3dc074cc6f.yrp (Turn 4)

**Comment by DailyShana** [comment]
Fluorohydride/ygopro-scripts@fb2b81e
