### ISSUE TITLE
BUG: Metalfoes Counter can't trigger if Kozmo monster is destroyed and banish itself as cost

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1917]
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c33327029.lua#L26
`c:IsReason(REASON_BATTLE+REASON_EFFECT)` and `c:IsPreviousLocation(LOCATION_ONFIELD)` will become false if Kozmo monster banish itself as cost.

**Comment by mercury233** [comment]
@VanillaSalt https://github.com/Fluorohydride/ygopro-scripts/commit/d8701b13d4e65b9cead19c94af9cf6d46d5839df `Duel.RaiseEvent` will throw error if `re` is nil, such as monster destroyed by battle.

**Comment by salix5** [comment]
想問一下
為什麼メタルフォーゼ・カウンター不能直接使用EVENT_DESTROYED?

**Comment by mercury233** [comment]
Kozmo上级怪兽被破坏，发动自己效果把自己除外，这时才轮到炼装反击检查`EVENT_DESTROYED`，但那只Kozmo的`c:IsReason(REASON_BATTLE+REASON_EFFECT)` `c:IsPreviousLocation(LOCATION_ONFIELD)`已经因为被除外而变成了false，所以不能正确发动

**Comment by salix5** [comment]
@mercury233 謝謝
