### ISSUE TITLE
BUG: Two issues about Double Tuning

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1920]
1. ~~_Tatsunoko_ can't use monsters in hand to sync summon _水晶機巧－グリオンガンド/Crystron Gliongandr_.~~
2. _Synchro Call_ can't sync summon _Hot Red Dragon Archfiend King Calamity_.

**Comment by destdev** [comment]
related issues:
https://github.com/Fluorohydride/ygopro-scripts/issues/639
https://github.com/Fluorohydride/ygopro/issues/1810

**Comment by MichaelLawrenceDee** [comment]
I'm trying to work on it but solution has lead my duel to not start and once gave me "not enough memory" error.

**Comment by mercury233** [comment]
_Synchro Call_ still don't seems to work..
