### ISSUE TITLE
BUG: Astrograph Sorcerer can't select card banished by D.D. Crow to add to hand

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1921]
> Question
相手の発動した「激流葬」の効果によって、自分が召喚に成功した「調律の魔術師」が破壊され墓地へ送られた時、自分は手札の「アストログラフ・マジシャン」の『①：自分フィールドのカードが戦闘・効果で破壊された場合に発動できる。このカードを手札から特殊召喚する。その後、このターンに破壊されたモンスター１体を選び、その同名モンスター１体をデッキから手札に加える事ができる』モンスター効果を発動しました。
この時、相手がチェーンして「D.D.クロウ」のモンスター効果を発動し、墓地へ送られた「調律の魔術師」を除外した場合、その「調律の魔術師」を『このターンに破壊されたモンスター１体』として選ぶ事はできますか？
Answer
質問の状況の場合、「激流葬」の効果によって破壊され墓地へ送られた「調律の魔術師」は、「アストログラフ・マジシャン」のモンスター効果の処理時には、「D.D.クロウ」のモンスター効果によって除外されています。
この場合でも、その「調律の魔術師」は『このターンに破壊されたモンスター１体』として扱われていますので、『その後、このターンに破壊されたモンスター１体を選び、その同名モンスター１体をデッキから手札に加える事ができる』処理を適用する場合、その除外されている「調律の魔術師」を選び、デッキから2枚目の「調律の魔術師」を手札に加える事もできます。
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20425&keyword=&tag=-1

According to this ruling, _Astrograph Sorcerer_ should be able to select monster which was destroyed and then banished by _D.D. Crow_ to add monster with same name to hand.

> Question
相手の発動した「激流葬」の効果によって、自分が召喚に成功した「クロノグラフ・マジシャン」が破壊されエクストラデッキに表側表示で加わった時、自分は手札の「アストログラフ・マジシャン」の『①：自分フィールドのカードが戦闘・効果で破壊された場合に発動できる。このカードを手札から特殊召喚する。その後、このターンに破壊されたモンスター１体を選び、その同名モンスター１体をデッキから手札に加える事ができる』モンスター効果を発動しました。
この時、相手がチェーンして「エクストラゲート」を発動し、レベル6を宣言した事によって、『相手はエクストラデッキに存在する宣言されたレベルを持つモンスター１体をゲームから除外する』処理が行われ、自分のエクストラデッキに表側表示で加わった「クロノグラフ・マジシャン」が除外された場合、その「クロノグラフ・マジシャン」を『このターンに破壊されたモンスター１体』として選ぶ事はできますか？
Answer
質問の状況の場合、「激流葬」の効果によって破壊されエクストラデッキに表側表示で加わった「クロノグラフ・マジシャン」は、「アストログラフ・マジシャン」のモンスター効果の処理時には、「エクストラゲート」の効果によって除外されています。
この場合、その「クロノグラフ・マジシャン」は『このターンに破壊されたモンスター１体』として扱われませんので、『その後、このターンに破壊されたモンスター１体を選び、その同名モンスター１体をデッキから手札に加える事ができる』処理を適用する場合、その除外されている「クロノグラフ・マジシャン」を選ぶ事はできません。
（このターンに他に破壊されたモンスターが存在しない場合には、『その後、』の処理を適用する事はできません。）
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=10418&keyword=&tag=-1

But, according to this ruling, _Astrograph Sorcerer_ can't select monster which was destroyed and then banished by _Extra Gate_.

So I don't know how can we fix this.

**Comment by TheOnePharaoh** [comment]
We should wait for the 3rd ruling in the matter
third time's a charm, right?
otherwise we should just burn it.
but seriously though if I had to choose I would say that the D.D. Crow Ruling follows reason and other similar issues.
Astrograph doesn't require the location of the card also even if the card was removed that doesn't mean that it wasn't destroyed before.
