### ISSUE TITLE
cannot summon malefic paradox dragon

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro#1926]
![image](https://cloud.githubusercontent.com/assets/18705342/22480598/3e5aea8c-e7f2-11e6-8ecf-f6685c0e9824.png)
I cannot summon malefic paradox dragon even if i have the correct materials, te gear on the field and the malefic stardust in the hand, the stardust on the field shouldn't give any problem since its name is Elemental HERO Neos now

**Comment by VanillaSalt** [comment]
I don't think it's a bug.

Malefic Stardust Dragon treated as Elemental HERO Neos prevents you from summoning Malefic Paradox Dragon because Malefic Parallel Gear is already on the field.
