### ISSUE TITLE
[Source Code] Adjust tooltip's width for longer descriptions

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1927]
Some Extra Deck monsters gains effects when they used certain materials , like [Dragoncaller Magician[45667991]](https://github.com/Fluorohydride/ygopro-scripts/blob/master/c45667991.lua#L78) , and if there is a `EFFECT_FLAG_CLIENT_HINT` a little tooltip will show up near the card, but there is a problem with longer descriptions as you can see here : 
![](http://i.imgur.com/bwSX9eJ.png)

It looks like the description is showing in just 1 line and wont cut off to a second line , so i have to make Ygopros resolution bigger just to view the whole desc , but this isnt a problem with Chinese or Japanese text cus their characters are usually smaller and theres usually no spaces

What i can do is make the string shorter , but then it wont make sense or there wont be enough information to let both players know what the entire effect is about
- I can also use "Gained effects from Dragoncaller Magician" to make it even shorter , but then players wont know exactly what effects were gained , and they have to look for _Dragoncaller Magician_ and read its effects , but they shouldnt have to do that in the first place

I was wondering if someone who works with the official source code can adjust the tooltip's source code to add support for longer descriptions ?
- All i can think of is giving the tooltip's width a max. value so if description reaches that max. value it will continue on a new line

**Comment by mercury233** [comment]
I think we can add something like `EFFECT_FLAG_CLIENT_ADD_DESC` to add those description to the effect of the card, for example:
![image](https://cloud.githubusercontent.com/assets/13391795/22496039/5f1de0a0-e881-11e6-9941-a7deb7905e8a.png)

**Comment by Hello23-Ygopro** [comment]
Interesting , i didnt think about adding something entirely new to support it : 
+That seems to be a better option , cus not everyone knows about the tooltips and if its in the description tab , it cant be missed and more people will notice 
-The only downside i can see is that it will cause the scroll bar to appear on more cards , and for as long as i can remember Ygopro's scrollbar has always been kind of glitchy , but this should again only be an issue for English users cus their descriptions are longer

**Comment by Hello23-Ygopro** [comment]
Interesting , i didnt think about adding something entirely new to support it : 
+That seems to be a better option , cus not everyone knows about the tooltips and if its in the description tab , it cant be missed and more people will notice 
-The only downside i can see is that it will cause the scroll bar to appear on more cards , and for as long as i can remember Ygopro's scroll bar has always been kind of glitchy with "justified" text alignments

But this should again only be an issue for English users cus their descriptions are longer , and on Chinese and Japanese Ygopros this glitch doesnt appear cus their text alignments is inherently non-"justified"
# 
The glitchy scroll bar only appears when the text alignment is "justified" as you can see here : 
![image1](http://i.imgur.com/XCqG4SH.png)

As you can see here the glitch doesnt show : 
![image2](http://i.imgur.com/56EAW4C.png)

Ygopro's source code for the scroll bar seems to only be compatable with non-"justified" text alignments, but that causes the words to get cut off and makes it harder to read , at least in English :
