### ISSUE TITLE
BUG? Ghostrick Museum[7617062]

### ISSUE THREAD

**Issue by Hello23-Ygopro** [Fluorohydride/ygopro#1929]
Is the change position effect is supposed to be Continuous ? 
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c7617062.lua#L40

OCG effect says : 

> In addition, monsters who battle damage to players become backside defense display at the end of the damage step.

The effect looks like pre-PSCT , and i dont know if its supposed to trigger in the OCG

TCG effect says : 

> At the end of the Damage Step, change any monster that inflicted battle damage to a player during this battle to face-down Defense Position.

It doesnt trigger in the TCG , so maybe this is another English translation error ?

**Comment by nekrozar** [comment]
In OCG, _Ghostrick Museum_ create Chain Link.
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=10950
■『プレイヤーに戦闘ダメージを与えたモンスターは、ダメージステップ終了時に裏側守備表示になる』効果は**チェーンブロックの作られる効果**です。（対象を取る効果ではありません。）

**Comment by Hello23-Ygopro** [comment]
So it was translation error after all..
