### ISSUE TITLE
Counter Problem

### ISSUE THREAD

**Issue by Tic-Tac-Toc** [Fluorohydride/ygopro#1937]
I've a problem with counters on my fork of ygopro, when an user remove a counter : it crashed, have you changed something with counters ?

I've a problem with Fusions too... user can summon fusion monster with spell/trap card of the family (setname).

**Comment by mercury233** [comment]
yes, both the select counter message and fusion material check are changed. we need to keep update to latest core and script and gframe to make sure them work fine.

**Comment by Tic-Tac-Toc** [comment]
Ok thank you.

Do you have a date approximately for the fix ?
