### ISSUE TITLE
BUG: Get control of 1 monster temporarily, banish it with REASON_TEMPORARY, it will try to return control

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1943]
![image](https://cloud.githubusercontent.com/assets/13391795/23992446/f2dfd52e-0a77-11e7-8e7f-35f3e3946b77.png)

Use _Mind Control_ to get control one monster, and use _D.D. Sprite_ to banish it, this will cause the game require to return control at the end phase of the turn.
![image](https://cloud.githubusercontent.com/assets/13391795/23992466/02d7f772-0a78-11e7-8900-3107ee3a0a08.png)
![image](https://cloud.githubusercontent.com/assets/13391795/23992537/3cdfe43e-0a78-11e7-97ca-3ce98e8b50cb.png)

The banished zone of me can't be clicked, and the banished zone of opponent has _effect reset_, but list nothing.

If we change the script of _D.D. Sprite_, remove `REASON_TEMPORARY` of `Duel.Remove`, this issue won't show up.

**Comment by fallenstardust** [comment]
![image](https://cloud.githubusercontent.com/assets/10228030/24860372/d876e5ac-1e26-11e7-8a7a-5c1017d472b0.png)
As the pic shows, when Psy omega battle break the Graydle monster and be equied by Graydle mon. then changed control right to my side. then in M2 end step i  catched the timing and bannished Psy Omega by its effect. after all, in End Phase, the act shows in my Bannish and the Button is on opponent’s. But the dialog Shows nothing after clicked the "Reset Effect" as above.

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/a3479dc7d476b9de769ac37f3c4600db793f3b96
