### ISSUE TITLE
Issue New Master Rule

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#1951]
In this YGOPRO's version, YGOPRO has many problems.

- ~~User cannot play New Mater Rule in puzzle mode.~~
- ~~Player cannot create "Extra Link".~~
> ~~http://www.yugioh-card.com/japan/howto/data/rulebook_new_master_rule_ver1.0.pdf~~
> ~~メインモンスターゾーンのリンクモンスターと相互リンクの状態の自分のリンクモンスターがエクストラモンスターゾーンに存在する場合、もう片方のエクストラモンスターゾーンが空いているのであれば、**「エクストラリンク」を完成させる事ができるリンクモンスターを、その空いているエクストラモンスターゾーンに特殊召喚する事ができます**。~~
> ~~（この場合にのみ、2ヶ所のエクストラモンスターゾーンの両方を自分が使用してる状態になり、その間はどちらのエクストラモンスターゾーンも自分フィールドとして扱われます。）~~

- ~~If banished card would return by _PSY-Framelord Zeta_, player cannot select any Monster Zone by _PSY-Framelord Zeta_.~~
~~In OCG, if banished card would return by _PSY-Framelord Zeta_, player can select any Monster Zone by _PSY-Framelord Zeta_.~~
> ~~https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8113&keyword=&tag=-1~~
> ~~Q.自分が「PSYフレームロード・Ζ」の『①：１ターンに１度、相手フィールドの特殊召喚された表側攻撃表示モンスター１体を対象として発動できる。そのモンスターとフィールドのこのカードを次の自分スタンバイフェイズまで除外する。この効果は相手ターンでも発動できる』のモンスター効果によって、相手のモンスターゾーンに表側攻撃表示で存在している「HSR魔剣ダーマ」を除外しました。~~
> 
> ~~その後、次の自分のスタンバイフェイズに、除外されたモンスターがそれぞれのモンスターゾーンに戻る際に、戻すモンスターゾーンは同じモンスターゾーンでなければなりませんか？~~
> ~~A.「PSYフレームロード・Ζ」のモンスター効果によって除外されたモンスターが、その次の自分ターンのスタンバイフェイズにフィールドに戻る際には、**戻すモンスターゾーンは除外された時のゾーンと同じゾーンである必要はありません**。~~
> 
> ~~それぞれのプレイヤーが、**自身の空いているモンスターゾーンを選んで除外されたモンスターを戻す事になります**。~~
> ~~（質問の状況の場合、自分の「PSYフレームロード・Ζ」は自分が、相手の「HSR魔剣ダーマ」は相手が選びます。）~~

- ~~If banished Fusion, Synchro, Xyz or Link Monster would return by _Farfa, Malebranche of the Burning Abyss_, that banished monster return to Extra Monster Zone.~~
~~In OCG, if banished Fusion, Synchro, Xyz or Link Monster would return by _Farfa, Malebranche of the Burning Abyss_, that banished monster return to Main Monster Zone.~~
> ~~https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20754&keyword=&tag=-1~~
> ~~Q.リンクモンスターや融合モンスターなど、エクストラモンスターゾーンに特殊召喚されたモンスターが、その後に「彼岸の悪鬼 ファーファレル」の『③：このカードが墓地へ送られた場合、フィールドのモンスター１体を対象として発動できる。そのモンスターをエンドフェイズまで除外する』モンスター効果によって除外されました。~~
> 
> ~~その除外されたリンクモンスター・融合モンスター等がエンドフェイズにフィールドに戻る場合、どのモンスターゾーンに戻りますか？~~
> ~~A.エクストラモンスターゾーンに存在するリンクモンスターや融合モンスター等が「彼岸の悪鬼 ファーファレル」のモンスター効果によって除外された場合、フィールドに戻る際は、**エクストラモンスターゾーンではなく、メインモンスターゾーンに置かれる事になります**。~~
> ~~（このフィールドに戻る際に、メインモンスターゾーンに空きがなかった場合には戻す事ができず、墓地へ送られる事になります。）~~

- ~~If banished Fusion, Synchro, Xyz or Link Monster would return by _Ninjitsu Art of Shadow Sealing_, that banished monster return to Extra Monster Zone.~~
~~In OCG, if banished Fusion, Synchro, Xyz or Link Monster would return by _Ninjitsu Art of Shadow Sealing_, that banished monster send to graveyard.~~

> ~~https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20776&keyword=&tag=-1~~
>  ~~Q.「忍法 影縫いの術」の『自分フィールド上の「忍者」と名のついたモンスター１体をリリースして発動できる。相手フィールド上のモンスター１体を選択してゲームから除外する。そのモンスターがゲームから除外されている限り、そのモンスターカードゾーンは使用できない』効果の対象として、エクストラモンスターゾーンの相手モンスターを対象に選択する事はできますか？~~
> ~~A.エクストラモンスターゾーンに存在するモンスターを対象として「忍法 影縫いの術」を発動する事はできます。~~
> 
> ~~その場合、対象となったエクストラモンスターゾーンのモンスターは除外され、除外されている間は、そのエクストラモンスターゾーンは使用できない状態となります。~~
> ~~（その使用できなくなったエクストラモンスターゾーンは自分フィールドとも相手フィールドとも扱われない状態に戻りますので、もう片方のエクストラモンスターゾーンが空いていれば、どちらのプレイヤーも使用できる状態になっています。）~~
> 
> ~~その後、「忍法 影縫いの術」がフィールドを離れた際には、使用できない状態となっていたエクストラモンスターゾーンは使用できる状態に戻り、『このカードがフィールド上から離れた時、この効果で除外したモンスターを同じ表示形式で元のモンスターカードゾーンに戻す』効果が発動します。~~
> 
> ~~その際には、その「忍法 影縫いの術」の効果で使用できなくなっていたゾーンに除外していたモンスターを戻す処理を行われますが、**除外されたモンスターをエクストラモンスターゾーンに戻す事はできませんので、その除外したモンスターは墓地へ送られる事になります**。~~

- ~~If monster in Extra Monster Zone would switch by _Creature Swap_, those monster move Extra Monster Zone.~~
~~In OCG, if monster in Extra Monster Zone would switch by _Creature Swap_, those monster move Main Monster Zone.~~
> ~~https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20734&keyword=&tag=-1~~
> ~~Q.エクストラモンスターゾーンに自分のモンスターが1体、相手のモンスターが1体存在しています。~~
> 
> ~~この状況で「強制転移」の『お互いはそれぞれ自分フィールド上のモンスター１体を選び、そのモンスターのコントロールを入れ替える。そのモンスターはこのターン表示形式を変更できない』効果が適用された場合、処理はどうなりますか？~~
> ~~A.その場合、**どちらのエクストラモンスターゾーンのモンスターも、相手プレイヤーのメインモンスターゾーンへとコントロールを入れ替える事になります**。~~
> ~~（結果的に、両方のエクストラモンスターゾーンが空いた状態になります。）~~

Maybe YGOPRO has many other problems.

**Comment by mercury233** [comment]
> player cannot select any Monster Zone by PSY-Framelord Zeta.
I guess you mean player cannot select which Monster Zone to place the returned monsters?

**Comment by nekrozar** [comment]
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8113&keyword=&tag=-1
> A.「PSYフレームロード・Ζ」のモンスター効果によって除外されたモンスターが、その次の自分ターンのスタンバイフェイズにフィールドに戻る際には、**戻すモンスターゾーンは除外された時のゾーンと同じゾーンである必要はありません**。

I say, player cannot select any Monster Zone (In this version, that monster return to the same Monster Zone).

**Comment by edo9300** [comment]
Another problem, monsters in the extra monster zone cannot be selected as battle target

**Comment by edo9300** [comment]
another problem too, if you disable a spell/pendulum zone with a card like Zany Zebra, then you'll be able to activate a pendulum even if that zone is disabled
![image](https://cloud.githubusercontent.com/assets/18705342/24428586/3c6ee716-140f-11e7-9fd1-0a0c58acf7eb.png)

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/24512475/41582132-15a1-11e7-8dd1-62202ce3207a.png)
I can try to spsummon from extra even though I don't have zone linked.
![image](https://cloud.githubusercontent.com/assets/13391795/24512518/5c685c08-15a1-11e7-8fa4-d44ae24b2058.png)
If I try to spsummon a xyz monster in this situation, its xyz materials would be kept on field.

**Comment by Gideon9212** [comment]
Decode talker when linked to something doesn't show the atk boost in yellow like other attack boosts do. Not sure if its a display function missing or something but thought I would share that.

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/24533597/71404a50-15fb-11e7-972d-2533483f87b9.png)
![image](https://cloud.githubusercontent.com/assets/13391795/24533612/7f9ec644-15fb-11e7-8b64-4ce4da4b71f7.png)

@Gideon9212 I don't have this problem. 

But I found _T.G. Warwolf_ can spsummon when _Decode Talker_ is spsummoned.

**Comment by Gideon9212** [comment]
I must of build it wrong. My bad. Sorry about that.

**Comment by mercury233** [comment]
_Masked Chameleon_ can spsummon Link monsters.

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/24594447/e1eb1684-185f-11e7-8224-e29be6f49790.png)
_Night Dragolich_ and Link monster will cause infinite loop.

**Comment by ClementLouis** [comment]
Pendulum cards in the pendulum zone are not treated as being in the S&T zone  (tested with D/D/D beowulf, D/D savant Newton and D/D savant Copernicus)

-A Pendulum Monster placed in the Pendulum Zone is not treated as a monster, by rather as a Spell Card, and also as a card in the Spell & Trap Zone.
EX: A card in the Pendulum Zone is still treated as a card in the Spell & Trap Zone, so “D/D/D Dragonbane King Beowulf’s” effect of “Destroy all cards in the Spell & Trap Zones” can destroy them.
https://ygorganization.com/themiraclecarvedbypendulums/

also, Is it not possible to place Pcard in the S&T zone if the S&T zone if you use Master Rule 4? I think it can misleading for some users

**Comment by mercury233** [comment]
> Ｑ：新マスタールールにおいて、このカードの効果でペンデュラムゾーンの表側表示のカードを破壊できますか？ 
Ａ：ペンデュラムモンスターを魔法カードとして発動している状況においては、このカードの効果では破壊する事ができません。 (17/04/03)
http://yugioh-wiki.net/index.php?%A1%D4%B9%D3%CC%EE%A4%CE%C2%E7%CE%B5%B4%AC%A1%D5

@ClementLouis The wiki say _Wild Tornado_ can't destroy pendulum cards activated.

**Comment by nekrozar** [comment]
@mercury233 @ClementLouis 
Konami's answer, _Wild Tornado_ can target cards in Pendulum Zone.
Mail:
遊戯王OCG事務局です。 

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。 

Q. 
相手が魔法カード扱いとして手札から発動した「メタルフォーゼ・シルバード」の発動にチェーンして自分はその「メタルフォーゼ・シルバード」を対象に「荒野の大竜巻」を発動できますか？ 
A. 
新マスタールールからペンデュラムゾーンのカードも魔法＆罠ゾーンのカードとして扱います。 
ご質問の場合、「荒野の大竜巻」を発動することはできます。

**Comment by ClementLouis** [comment]
@nekrozar we also got a similar answer: 
Q. 
荒野の大竜巻 ~~~ ＤＤＤ剋竜王ベオウルフ 
これらのカードはスペル/トラップカードゾーンの振り子カードで動作しますか？ 
A. 
「荒野の大竜巻」の効果で、魔法＆罠ゾーンのカードとしても扱うペンデュラムゾーンのカードを破壊する事もできます。 
また、「DDD剋竜王ベオウルフ」の効果も同様で、魔法＆罠ゾーンのカードとしても扱うペンデュラムゾーンのカードを破壊する事もできます。 
Q.
Major tornado in the wilderness ~ DDD King Beulwolf King Dragon
Do these cards work with the pendulum card in the spell / trap card zone?
A.
You can also destroy a card in the pendulum zone that treats it as card of magic & trapping zone by the effect of "tornado of the wilderness".
Moreover, the effect of "DDD King Dragon King Beowulf" is also the same, you can also destroy a card in the Pendulum Zone which also treats it as a card of Magic & Trap Zone.

So I guess some ruling are outdated in the database and not up to date with MR4
also, like I mentioned, the pendulum should be affected by card affecting spell card(s) in the spell & trap zone

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/24761575/616d0262-1b1e-11e7-9659-f59b03e65ace.png)
![image](https://cloud.githubusercontent.com/assets/13391795/24761609/7bc100f0-1b1e-11e7-96fb-f825c638492c.png)
Metalfoes monsters can't activate effect to destroy another card in pendulum zone if the other 3 s&t zones are full.

**Comment by nekrozar** [comment]
If player has no monster in Extra Monster Zone, _Blasting Fuse_ in Extra Monster Zone's column can activate.
In OCG, if player has no monster in Extra Monster Zone, _Blasting Fuse_ in Extra Monster Zone's column cannot activate.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20730&keyword=&tag=-1
> Q.「爆導索」をエクストラモンスターゾーンがある列と同じ縦列に「爆導索」がセットされている場合、エクストラモンスターゾーンにもカードがないと発動する事はできませんか？
> A.エクストラモンスターゾーンのある縦列に「爆導索」をセットしている場合、4枚のカード（相手の魔法＆罠ゾーン、相手のメインモンスターゾーン、自分のメインモンスターゾーン、エクストラモンスターゾーン）が破壊される事になります。
> 
> **エクストラモンスターゾーンを含む、その縦列全てにカードが存在していなければ発動する事はできません**。 
----
If player has only _Ultimaya Tzolkin_ in Extra Monster Zone, _Ultimaya Tzolkin_ can activate Special Summon effect (but selected monster send to grave).
In OCG, if player has only _Ultimaya Tzolkin_ in Extra Monster Zone, _Ultimaya Tzolkin_ cannot activate Special Summon effect.

> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20781&keyword=&tag=-1
>  Q.「アルティマヤ・ツィオルキン」の『①：１ターンに１度、自分フィールドに魔法・罠カードがセットされた時に発動できる。「パワー・ツール」Sモンスターまたはレベル７・８のドラゴン族Sモンスター１体をエクストラデッキから特殊召喚する』モンスター効果によって特殊召喚を行う場合、メインモンスターゾーンに特殊召喚する事はできますか？
> A.「アルティマヤ・ツィオルキン」のモンスター効果によるシンクロモンスターの特殊召喚もエクストラデッキからの特殊召喚になりますので、**基本的にはエクストラモンスターゾーンに特殊召喚する事になります**。
> 
> しかし、**モンスターゾーンに存在するリンクモンスターのリンクマーカーが、自分のメインモンスターゾーンを指している場合、そのメインモンスターゾーンにもエクストラデッキのモンスターを特殊召喚する事が可能になります**ので、その場合は、「アルティマヤ・ツィオルキン」のモンスター効果によって、シンクロモンスターを自分のメインモンスターゾーンに特殊召喚する事ができます。

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/24839754/01004e8a-1d93-11e7-8a72-311f860a8309.png)

![image](https://cloud.githubusercontent.com/assets/13391795/24839748/f00f62e6-1d92-11e7-83ca-0511554b38fa.png)

_Star Grail Swordsman Aurum_'s 2nd effect can't be activated if both linked zone of it is used. In old days we can check `Duel.GetLocationCount(tp,LOCATION_MZONE)>-1` but now we need to specify the zone.

**Comment by mercury233** [comment]
_Instant Fusion_ and _D/D Swirl Slime_ can't be activated if my monster zone is full of 5 monsters but my extra zone is empty.

**Comment by mercury233** [comment]
_D/D/D Oblivion King Abyss Ragnarok_ and _Violet Poison Magician_ etc. an't trigger their pzone effect.

**Comment by mercury233** [comment]
_Zefraath_ 's extra pendulum summon effect don't work.

**Comment by mercury233** [comment]
`Duel.GetLocationCount(tp,LOCATION_MZONE)` seems always return 1 in the operation of _Baobaboon_, but not in target.

**Comment by ClementLouis** [comment]
I can target Link monsters with effect that change the battle position

Q: Can I activate the effect of Enemy Controller that changes the battle position of a face-up monster, by targeting a Link Monster?
A: Link Monsters cannot exist in Defense Position, so you cannot target a Link Monster with the effect of Enemy Controller that changes a monster’s battle position.

Source: https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20753&keyword=&tag=22

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/25382274/6dc3c698-29e9-11e7-9f8e-27867b5b5b69.png)
kaiju can tribute monster in extra zone even if main monster zone is full.

**Comment by TheOnePharaoh** [comment]
![image](https://cloud.githubusercontent.com/assets/22715864/25440015/baa92c30-2a63-11e7-846d-4542511c834d.png)
New Bug: when a player is using the extra link the other player gets promoted to summon extra deck monsters
also when attempting to summon it freezes on the select zone to summon in

also simular issue happens when using castle link's first effect targeting a monster with both it's linked zones occupied

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/26089223/9ca5b9ee-3a2e-11e7-81eb-d09ddddaaf7e.png)

if the player have linked zone in main monster zone, when pendulum spsummoning, he can place the monster in hand to the linked zone, and the monster in extra will fail to summon.

**Comment by edo9300** [comment]
@mercury233 that could be solved by summoning pendulums from the extra first

**Comment by mercury233** [comment]
@edo9300 sure, but i don't know how to change the order of cards in a group.

**Comment by edo9300** [comment]
@mercury233 you filter the cards in the extra, then the others

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/26342208/b7e6f470-3fc9-11e7-96c2-9f870e3a2106.png)
I can select both fusion material from hand even if i don't have extra zone avail.

**Comment by mercury233** [comment]
_Ultra Polymerization_ can't use its grave effect if there isn't zone avail for extra summon.

**Comment by mercury233** [comment]
_The Claw of Hermos_ can't use monster from hand as fusion material.

**Comment by mercury233** [comment]
> その後、『①：このカードの発動後１回目の自分スタンバイフェイズに発動する。自分のエクストラデッキの融合モンスター１体をお互いに確認し、そのモンスターによって決められた融合素材モンスターを自分のデッキから墓地へ送る』効果が発動し、処理を行う際に自分のモンスターゾーンに空きがない場合でも、自分のデッキから融合素材モンスターを墓地へ送る処理は通常通り適用されます。
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=11291&keyword=&tag=-1

_Future Fusion_ have similar issue with _Ultra Polymerization_, can't send materials to grave if the fusion monster seems can't be summoned in the first standby phase.
