### ISSUE TITLE
searching 'star' in deck editor causes ygopro to crash

### ISSUE THREAD

**Issue by bminahan73** [Fluorohydride/ygopro#1965]
very weird bug, but I promise I'm not crazy. This happens consistently. 

to replicate: 
-go to deck editor
-type "star" without quotes in search bar on the right.
-game proceeds to crash.

you can type 'star' at any time in the search bar EXCEPT for if it is at the very beginning of the search. only when it is at the beginning of the search string does the game close unexpectedly.

YGOPRO version: 1.033.D(a) Percy
Operating System: Mac OSX El Capitan 10.11.4

**Comment by Gideon9212** [comment]
Mac's have a issue that if there is a bad image on something, it will crash. Please refer to ygopro percys github of liveimages and download that to fix your issue.
