### ISSUE TITLE
BUG: Destroy replace

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1966]
> 「海竜神の加護」の効果によって、レベル3以下の水属性モンスターが破壊されない場合、「アームズ・シーハンター」の他のモンスターを代わりに破壊する効果は適用できません。
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8815&keyword=&tag=-1

If a card can't be destroyed, it can't be used to replace destroy. But now in ygopro it can.

**Comment by MichaelLawrenceDee** [comment]
Doesn't IsDestructable(e) work?

**Comment by MichaelLawrenceDee** [comment]
@Hello23-Ygopro stop being an ass. Since apparently, the only thing you can do is give thumbs downs to Salvation and Percy. Get a life bro.
