### ISSUE TITLE
Normal summon destroys "Pole Position" instead of being forbidden

### ISSUE THREAD

**Issue by zhykzhykzhyk** [Fluorohydride/ygopro#1975]
According to the OCG FAQ, player cannot play a card that can cause an infinite loop, but the program allows, and then destroys the cards involved in the infinite loop instead.

**Comment by MichaelLawrenceDee** [comment]
To be fair, in Tag Force 6 (which follows OCG rules), infinite loops are allowed, but one of which stops at 3 cycles.

**Comment by Gideon9212** [comment]
There is other issues with pole position I like to address while this is open. Below is a puzzle. Using snatch then pole will cause game to end. Made puzzle print everytime a event is adjusted and a simple script log to say "string" to show that no other errors will pop up.
[Pole_Snatch_Break.zip](https://github.com/Fluorohydride/ygopro/files/954353/Pole_Snatch_Break.zip)

**Comment by DailyShana** [comment]
won't fix
