### ISSUE TITLE
请求协作者权限 / Request for collaborator access permission

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1976]
我是一名游戏王爱好者，以代码贡献者的身份参与了一段时间的pro开发，但现在我希望能做更多的事情，背更多的锅。
比如：

- 优化GUI
- 改善代码可读性
- 增强与其他贡献者的沟通

------

I'm a yu-gi-oh fan, had been contributing to ygopro for a while, but now I want to do more things, undertake more responsibility.
For example:

- Update GUI
- Improve code readability
- More communication with other contributors

------

So I want to get the collaborator access to `Fluorohydride/ygopro` `Fluorohydride/ygopro-scripts` `Fluorohydride/ygopro-core` repositories.

@Fluorohydride @VanillaSalt @salix5 @DailyShana @woodee @IceYGO What do you think?

**Comment by shadowfox87** [comment]
Yes, please give him access.

**Comment by fallenstardust** [comment]
Yes, please give him access.

**Comment by mercury233** [comment]
@Fluorohydride Thank you!

**Comment by heiitu** [comment]
一直以为233是元老级人物。。。

**Comment by sebastianleecn** [comment]
yes support 233
