### ISSUE TITLE
Bug: Decrease Tribute from Hazy Pillar allows setting the monster

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1977]
Hazy Pillar currently allows the Hazy Flame monsters to be set with 1 less tribute, this is not allowed:

https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=10419&request_locale=ja
■「陽炎獣」と名のついたモンスターを裏側守備表示でセットする際に、『自分は「陽炎獣」と名のついたモンスターを召喚する場合に必要なリリースを１体少なくする事ができる』効果を適用する事はできません。

I'm not sure if are other similar decrease tribute effects that also need to be fixed

**Comment by DailyShana** [comment]
fixed in https://github.com/Fluorohydride/ygopro-core/commit/6383ab2e70005eec41d0df6156bda24e7c8a1a14
