### ISSUE TITLE
Change RACE_CYBERS to RACE_CYBERSE

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1980]
> ![image](https://cloud.githubusercontent.com/assets/13391795/26184769/54b9885e-3bb9-11e7-964c-2de2e21c5f25.png)
http://www.yugioh-card.com/en/products/starter-ys17.html

The official news have confirmed the TCG name of the new race "サイバース" is "Cyberse".
So should we change the name of constants in ygopro now?

**Comment by Ice-Pendragon** [comment]
Does it matter? Don't we already have ATTRIBUTE_DEVINE and RACE_DEVINE?

**Comment by mercury233** [comment]
so now i don't think it should bother like `defense` vs `defence`.

**Comment by DailyShana** [comment]
just adding one line `RACE_CYBERS=RACE_CYBERSE` will avoid compatibility problem.
else we will never get the right name of new races
