### ISSUE TITLE
Window Control (Maximize)

### ISSUE THREAD

**Issue by fervi** [Fluorohydride/ygopro#1981]
Hello.

I think YGOPro should be able to maximize windows. Other YGOPro clients have, however, based on the clear YGOPro. Of course I understand if this is not a priority, but I think this is a very useful feature.

**Comment by Ice-Pendragon** [comment]
I agree. I don't think maximizing is needed, but minimizing is a different problem.

**Comment by fervi** [comment]
@Ice-Pendragon 
I have minimize, but not maximize ;)

**Comment by Ice-Pendragon** [comment]
Oh, I totally misunderstood. Sorry.

If maximizing will be supported, isn't it better just supporting resizing?
