### ISSUE TITLE
New user frontend

### ISSUE THREAD

**Issue by anshkumar** [Fluorohydride/ygopro#1983]
Let me put it straight, with the coming of "yugioh duel generation", "yugioh duel links" and "yugioh legacy of the duelist", ygopro stands no chance against Konami. What I'm trying to say here is that we need to construct a new frontend and a game plot, if we want to see ygopro in the future. Here is my idea, I'm working on creating new frontend for ygopro with Qt (cross-platform application framework); reasons for using Qt is that it is cross platform and user interface much more fluid than the one provided by Konami. Also, Qt uses both markup (QML) and C++ for programming, so programming is much faster and easy to customize. I'm requesting all the developers here to just work on ygopro-core and start working with new frontend. I'm providing my project link in the description bellow. The repository also contains a screenshot of the interface. Anyone interested please let me know.

github repository: [Yu-Gi-Oh Glaze](https://github.com/anshkumar/yugioh-glaze)

@Fluorohydride @soarqin @zh99998 @luffySAMA @woodee @VanillaSalt @salix5

**Comment by mercury233** [comment]
We can consider https://github.com/lllyasviel/YGOProUnity_V2 too

**Comment by fervi** [comment]
@anshkumar
If this project continues, I will gladly adapt my project to it. At what level is he, you can already play on it?

@mercury233 
Yep, but this project isn't libre (fully libre)

**Comment by anshkumar** [comment]
@fervi 
At this time I'm working on single player duel (puzzles). NO, it's not playable yet. At this time we are able to select different puzzles; cards are loaded and there details are shown in the description window. All these are fluid. Since, I'm the only one working on it and without any documentation of the code, I've to first understand the code in Irrlicht engine and then implement it's equivalent in Qt( @mercury233 you must feel my pain). And yes this project will continue in future. I want know us to decide which framework we should be now using for ygopro frontend (up untill know we just came across two; one provided by me and one by @mercury233 ). Once decided which framework to use, we should start working on it as quick as possible (more the developer we have faster the speed of development will be; also more the error we will encounter). Let's put our cases in front of everyone and vote for the one whose case was strongest. Also, I don't think @Fluorohydride is working anymore on this project. Am I right?

**Comment by fervi** [comment]
@anshkumar 
Unfortunately I do not know programming, so I will not help you. How will you need the tester to write it :)

New engine would be useful. Unfortunately, YGOPro developers are more concerned with making the game more up-to-date with new card rules than any other enhancements for the user. The game in 2017 runs in the window ... At 800x600, it has graphics in very low quality. I would like someone willing, but I can not. By contrast, by creating an OpenYGO project I have to adapt to a specific engine, however large the defect would be.

**Comment by Zayelion** [comment]
> We can consider https://github.com/lllyasviel/YGOProUnity_V2 too

I suggest moving in this direction and dropping the current UI with an organization made that is inclusive to developers.

**Comment by fervi** [comment]
@Zayelion
Maybe, but it's not free project (libre), so maybe YGOPro may fail

**Comment by anshkumar** [comment]
@fervi you have a point. 
@fervi how could you help us ? 
@mercury233 could you explain the type of licenses Unity come with?
 
Also, we need to know the developers who are ready to move foreword in this direction. For that we should know the type of contribution each one of us could make. But first thing comes first. We need to come to a common ground on the programming language to use for front end design.

**Comment by fervi** [comment]
@anshkumar 
Don't know how can i help you.
Your game use this?
https://v-play.net/

**Comment by anshkumar** [comment]
@fervi yes because it has got better full screen support.

**Comment by anshkumar** [comment]
@mercury233 and @Zayelion If we can get enough developers support in this direction, we should rethink about using Unity. But Unity is not free (we have to consider that also). Moreover the frontend we will be designing will be using graphics currently copyrighted by Konami. We have to think of some way to use creative common license graphics but still cards images will be copyrighted.

**Comment by Zayelion** [comment]
Well the images are transformative works changing use, language, and resolution of already published physical art or reporting upon future releases. YGOPro objectively improves the market value of Yugioh. The question would be if the software enacted the policy of not releasing a card in its system till it was physically printed vs it being there for review by consumers before purchase before hand.

http://download.unity3d.com/unity/licenses

At that point its a question of how much of an "knock off", ygopro would be vs a Konami product which it wouldnt be considering they refuse to develop anything remotely like this. If features are developed properly to emulate tournament level play it quickly becomes a very clear educational tool. Adding a few more API's makes it a powerful market research tool.

Images URL's can be data mined from the wikia, a store that can linked to, etc,

There is no reason for the UI itself to feature anything from other copyrighted sources. Doing all those I think this falls within "Kelly v. Arriba Soft Corp".

All that aside, doing development in this community has been emotionally taxing for me because its like talking to a wall. I'll help where I can providing architectural review and support along with proper use cases that are not related to rulings.

**Comment by anshkumar** [comment]
@Zayelion and @mercury233  Unity is free and you have to pay only for pro version. Most of the work could be done in Unity but I was thinking of creating 2D interface and for that Unity will just increase the complexity of the code. For instance for creating a color rectangle in Unity following will be the code:
```

    private static Texture2D _staticRectTexture;
    private static GUIStyle _staticRectStyle;
 
    // Note that this function is only meant to be called from OnGUI() functions.
    public static void GUIDrawRect( Rect position, Color color )
    {
        if( _staticRectTexture == null )
        {
            _staticRectTexture = new Texture2D( 1, 1 );
        }
 
        if( _staticRectStyle == null )
        {
            _staticRectStyle = new GUIStyle();
        }
 
        _staticRectTexture.SetPixel( 0, 0, color );
        _staticRectTexture.Apply();
 
        _staticRectStyle.normal.background = _staticRectTexture;
 
        GUI.Box( position, GUIContent.none, _staticRectStyle );
 
 
    }
```

In Qt for creating the rectangle would be short:

```
import QtQuick 2.0

Rectangle {
    width: 100
    height: 100
    color: "red"
    border.color: "black"
    border.width: 5
    radius: 10
}
```

Also most of the C++ part of the code remains same. Also Qt for Application Development is dual-licensed under commercial and open source licenses.

@Zayelion  we welcome your help. Once we have convinced enough developers to start a new front end project, your help will be needed.

**Comment by mercury233** [comment]
personally i don't want to develop a new program in pure c++, and i don't have time for it.

**Comment by Zayelion** [comment]
I already have a working UI in JS, my team is more focused on rewriting the core itself and then the scripts. We came to the conclusion to do that about a year ago. There are more developers and its easy to make new developers.

**Comment by anshkumar** [comment]
@Zayelion Could you post me the link to UI. I think the main problem is that we are all working independently on creation of UI for the same game, hence a game is never able to hit the market. As you have said that your UI is using JS, my project also uses JS for designing (it uses C++, QML and JS), if we collaborate we will be able to speed up the speed of development and could be able to release our first version within a couple of months.

**Comment by DailyShana** [comment]
close inactive discussion
