### ISSUE TITLE
BUG: Control change of attack target in damage phase don't stop the damage cal

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1984]
https://github.com/Fluorohydride/ygopro-pre-script/blob/cfdc5cce5fbae2ddcf222a667b68aed976c7e366/scripts/CIBR-JP/c101002042.lua
[Varrel Load Dragon](http://yugioh.wikia.com/wiki/Varrel_Lord_Dragon) changed the control of attack target, but the attack still continue. `Duel.NegateAttack()` won't stop it too.

**Comment by edo9300** [comment]
@mercury233 this is a ruling issue, the problemi is that ad the ruling says, an attack van ne negated only during the battle step, once in the damage step, then the only way to make that attack end is making the attacker/attack target leave the field. I think we'll have to wait for some extra rulings, because as now, the came stops checking it the attack is negated once in the damage step

**Comment by mercury233** [comment]
anyway it don't seem that this dragon is designed to continue the battle `_(:з」∠)_`

**Comment by mercury233** [comment]
@nekrozar can you help to confirm this from KONAMI?

**Comment by nekrozar** [comment]
Konami's answer, if _Varrel Load Dragon_ changed the control of attack target, _Varrel Load Dragon_'s attack is cancel.

Mail:
> 遊戯王OCG事務局です。 
> 
> いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
> ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。 
> 
> Q. 
> 「ヴァレルロード・ドラゴン」の③の効果で「ヴェルズ・オ・ウィスプ」のコントロールを得た場合、そのダメージ計算後に「ヴァレルロード・ドラゴン」の効果は無効化されますか？ 
> A. 
> 攻撃した「ヴァレルロード・ドラゴン」が『③』の効果を『ダメージステップ開始時に発動』してコントロールを得た場合、**「ヴァレルロード・ドラゴン」と「ヴェルズ・オ・ウィスプ」はダメージ計算を行っていません**。 
> したがって、ダメージ計算を行っていない「ヴェルズ・オ・ウィスプ」の効果が発動する事はありません。

**Comment by mercury233** [comment]
@nekrozar another problem. I use _Mark of the Rose_ to get the control of _Power Tool Dragon_, attack _Ally of Justice Catastor_, and use _Mark of the Rose_ as destroy replace. Can you confirm what should happen after the control of PTD is returned?

**Comment by nekrozar** [comment]
Konami's answer, if _Mark of the Rose_ destroyed by _Power Tool Dragon_, _Power Tool Dragon_'s control is returned.

Mail:

> 遊戯王OCG事務局です。 
> 
> いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。 
> ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。 
> 
> Q. 
> 「薔薇の刻印」の効果で相手にコントロールが移っている、元々の持ち主が自分の「パワー・ツール・ドラゴン」と自分の「レプティアの武者騎兵」が戦闘を行う場合に、自分の「レプティアの武者騎兵」の効果が発動し、その効果で破壊される際に相手が「パワー・ツール・ドラゴン」の効果で装備されている「薔薇の刻印」を破壊した場合、その「パワー・ツール・ドラゴン」のコントロール及び戦闘はどうなりますか？ 
> A. 
> ご質問の場合、**「パワー・ツール・ドラゴン」のコントロールはただちに自分に戻り、「レプティアの武者騎兵」の戦闘は終了します**。

**Comment by mercury233** [comment]
@nekrozar Thank you!
