### ISSUE TITLE
BUG: The Monarchs Stormforth can't release cards affected by Miscellaneousaurus

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1988]
> したがって、「幻創のミセラサウルス」のモンスター効果が適用されている場合でも、相手がこのターンに「帝王の烈旋」の効果を適用し、モンスターをリリースする際に、自分の恐竜族モンスターをリリースする事ができます。
https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=11275

![image](https://cloud.githubusercontent.com/assets/13391795/26831134/e2c87454-4afd-11e7-945c-4b2841ae6b7e.png)
But now the dinosaurs can't be released.

**Comment by DailyShana** [comment]
Ｑ：《ガガガガンマン》の『●：攻撃表示』の効果を発動しているターンです。
　　『その相手モンスターの攻撃力は５００ダウンする』効果は、このカードと戦闘を行う場合でも適用されますか？
Ａ：通常通り適用されます。(17/05/13)
