### ISSUE TITLE
About Master Rule 4 function Duel.GetLocationCountFromEx(number)

### ISSUE THREAD

**Issue by Ice-Pendragon** [Fluorohydride/ygopro#1989]
I think this function should be able to get an optional secondary argument nil|Card|Group, so that this function can be called both by f(tp) and f(tp,g).

For example, let's assume a player has "Chimeratech Fortress Dragon" in a EX Monster Zone, and "Gaiasaber, the Virtual Knight" in his/her fourth Main Monster Zone from left (in ygopro, LOCATION_MZONE 3), and four "Elemental HERO" Monsters in all other Main Monster Zones.

![ygopro fps_ 59 2017-06-08 19_25_40](https://user-images.githubusercontent.com/20840352/26924521-2c082a86-4c81-11e7-8bf1-32232bf71752.png)

If he/she activate "Polymerization"...

- He/She should contain third or fifth Monster from left (or right), since unless he/she do so, the Fusion Monster cannot be placed.
- He/She CANNOT use "Gaiasaber" as a Fusion Material (if he/she is going to Fusion Summon "Elemental HERO Gaia"), since it makes his/her Linked Zone disappear.

That's why I suggest this opinion : if the secondary argument Card|Group is stated, the function should work assuming "the card, or the cards in group didn't exist on Monster Zone, and their Zone was empty".

On the first case, usually Duel.GetLocationCountFromEx(tp) will be 0; but Duel.GetLocationCountFromEx(tp,mg) will be 1 or 2, if the linked Monster of "Gaiasaber" is contained in Group mg.

On the second case, Duel.GetLocationCountFromEx(tp,mg) will be 0 if Group mg contains "Gaiasaber", even though mg also contains the linked Monster of "Gaiasaber".

I hope this replacement be done soon.

**Comment by Ice-Pendragon** [comment]
Oh, maybe I posted on wrong branch. How can I move this post to ygopro-core branch?

**Comment by edo9300** [comment]
@Ice-Pendragon well, this function already does, it accepts 4 parameters (tp,tp,sg,c) now I don't remember the difference between the 2 tps, but SG is the group used for that action, in this case the monsters that will be used for the summon, and c is the card that will be summoned

**Comment by Ice-Pendragon** [comment]
Thanks. Maybe I've seen a outdated version. I wish you luck.
