### ISSUE TITLE
How to code a new card?

### ISSUE THREAD

**Issue by JRigoCR** [Fluorohydride/ygopro#2]
Hi everyone, I have some programming knowledge and I would like to contribute with some cards. But I see, for example this:

function c10000000.tgtg(e,tp,eg,ep,ev,re,r,rp,chk)
if chk==0 then return true end
Duel.SetOperationInfo(0,CATEGORY_TOGRAVE,e:GetHandler(),1,0,0)
end

What does e,tp,eg,ep,ev,re,r,rp,chk mean? What are those paremeters for?

Could be a page of the wiki dedicated to this?

Thank you in advance.

**Comment by shynome** [comment]
哪里有如何编辑新卡的资料啊
Where can I get the information about how to edit the new card?
