### ISSUE TITLE
BUG: Some fusion check shouldn't check the zone availability

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2004]
> その後、『①：このカードの発動後１回目の自分スタンバイフェイズに発動する。自分のエクストラデッキの融合モンスター１体をお互いに確認し、そのモンスターによって決められた融合素材モンスターを自分のデッキから墓地へ送る』効果が発動し、処理を行う際に自分のモンスターゾーンに空きがない場合でも、自分のデッキから融合素材モンスターを墓地へ送る処理は通常通り適用されます。
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=11291&keyword=&tag=-1

_Future Fusion_ shouldn't check the zone availability in the 1st turn.

--------

_De-Fusion_ and _Ultra Polymerization_ should check the fusion materials, but shouldn't check the zone availability too.

**Comment by edo9300** [comment]
@mercury233 this issue has already been solved. Now those cards work as they should.
