### ISSUE TITLE
About making new constant TYPES_EXTRA and TYPES_EXTRA_P

### ISSUE THREAD

**Issue by Ice-Pendragon** [Fluorohydride/ygopro#2009]
Although new special summon type "Link Summon" has been added, some old and abandoned cards' script still considers TYPE_FUSION+TYPE_SYNCHRO+TYPE_XYZ as list of Extra Deck monsters.

I don't mean we need to change "Supreme King Z-ARC"('s Pendulum Effect) or "Dimensional Barrier", what exactly designate Fusion/Synchro/Xyz in their text; In fact, there is only 4 cards I've found currently.

- G.B. Hunter (04132790)
It prevents Extra Deck monsters to be returned to hand (and as a result to Extra Deck).

- Alsei, the Sylvan High Protector (10406322)
- Abyss Warrior (88409165)
- Sylvan Blessing (91650245)
They return a card to "either the top or bottom of the Deck".

You can make another function to check it, but just making new constant will be easy, and it will also be easily maintainable afterwards, when Master Rule 5, 6, ... and many new Special Summons have come.

TYPES_EXTRA = 0x4802040 (TYPE_FUSION+TYPE_SYNCHRO+TYPE_XYZ+TYPE_LINK) - types that can be placed on Extra Deck, and cannot on Hand or Deck
TYPES_EXTRA_P = 0x5802040 (TYPES_EXTRA+TYPE_PENDULUM) - types that can be placed on Extra Deck

**Comment by mercury233** [comment]
Good idea.

**Comment by edo9300** [comment]
What if, instead of making this type as a constant that will be the sum, we don't make it as a "new type", then, for example, the game could use it as reference for putting a card in the extra or main deck too.

**Comment by Ice-Pendragon** [comment]
@mercury233 That will be better. Let's do it.

**Comment by MichaelLawrenceDee** [comment]
I bump since I was discussing this with my team.
