### ISSUE TITLE
Normal summoning during the battle phase doesn't make a replay to happen

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro#2020]
When the oppopnent Normal Summons a monster via an effect, like with "Ultimate Offering" or "Rival Arrival" the game ends the attack, without asking for a battle replay

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/7fb46ee7dc12f37332889a0f4132cd78dc36b793
https://github.com/Fluorohydride/ygopro-core/commit/04362c8018151a1bab44dbdb5ade507d76d10f9e
