### ISSUE TITLE
BUG: Necrovalley will disable Trickstar Reincarnation if one hand is discarded

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2022]
Replay: 
[BUG_Necrovalley.zip](https://github.com/Fluorohydride/ygopro/files/1167342/BUG_Necrovalley.zip)
[BUG_Necrovalley 2.zip](https://github.com/Fluorohydride/ygopro/files/1167358/BUG_Necrovalley.2.zip)

Steps to reproduce:
1. Activate _Necrovalley_
2. Activate _Trickstar Reincarnation_ 
3. Chain _Maxx "C"_, or _Twin Twisters_
4. Because one target of _Trickstar Reincarnation_ is in grave, _Necrovalley_ will disable it.

**Comment by DailyShana** [comment]
It's not appropriate to use `Duel.GetOperationInfo` in `EVENT_CHAIN_SOLVING` because operation info only indecate the information of the chain when activating but not solving the effect.

**Comment by salix5** [comment]
Fluorohydride/ygopro-scripts@297649debca8293d6e58d3820552884af358834d
fixed

**Comment by salix5** [comment]
Fluorohydride/ygopro-scripts@297649debca8293d6e58d3820552884af358834d
1. fixed
2. testing

**Comment by mercury233** [comment]
I guess c64697431 have the same problem

**Comment by mercury233** [comment]
I prefer solution like https://github.com/Fluorohydride/ygopro-scripts/pull/1131
