### ISSUE TITLE
Black Garden's owner always chooses which monster zone to summon the Rose Token to

### ISSUE THREAD

**Issue by raphael-costa** [Fluorohydride/ygopro#2026]
\"The owner of the "Rose Token" is the controller of the Summoned monster when the effect of "Black Garden" activates. That player chooses the Monster Zone to which the "Rose Token" is Special Summoned.\"
Source: https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=7625&request_locale=ja
Source: http://yugioh.wikia.com/wiki/Card_Rulings:Black_Garden

Right now on YGOPRO, if the opponent summons a monster and I control Black Garden, I choose which monster zone to summon the Rose Token, this is relevant now with Links.

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/10c12289152723faac8a791386dd79ac94536c15#commitcomment-18550285
https://github.com/Fluorohydride/ygopro-scripts/commit/10c12289152723faac8a791386dd79ac94536c15#commitcomment-18550453

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/5a462b3e916282f0c0120040fa6fc65163ba8915
