### ISSUE TITLE
Crystal Beast Topaz Tiger crash

### ISSUE THREAD

**Issue by tspivey** [Fluorohydride/ygopro#2031]
I think this is causing my server to crash.

1. Create a deck with Crystal Beast Topaz Tiger (95600067) padding it with other monsters to prevent deck out.
2. Player 0 summons Crystal Beast Topaz Tiger in defense position, and ends the turn.
3. Player 1 summons Crystal Beast Topaz Tiger in attack position.
4. Player 1 Attacks player 0. Answer no to the prompt asking to use the effect.

Using Fluorohydride/ygopro-core@e777299920f37489670a7ae3df396664b50ba0f6 and Fluorohydride/ygopro-scripts@0658fa0ccabcbc9c31c4b9cdc712f7309525a4d7, this causes field::send_to to call move_card with a playerid of 16, which then tries to access player[16], which is invalid.

**Comment by DailyShana** [comment]
fixed in https://github.com/Fluorohydride/ygopro-core/commit/e3fe8cb4c7c9ac6705b8763379c66dedbcb72b01
