### ISSUE TITLE
How to run "Percy version" with self-compiled script engine?

### ISSUE THREAD

**Issue by M-Reimer** [Fluorohydride/ygopro#2034]
Hello,

after some patching, I managed to compile this repo on Arch Linux. The software seems to run without major problems.

Now I fetched a current "Percy version" of ygopro and dropped my self-compiled "bin" into there. It runs well but I miss the "Multiplayer" option.

How to fix this? Can someone point me to some instructions on how to run the "Percy" LUA scripts in a self-compiled client?

**Comment by mercury233** [comment]
The Percy version added "Multiplayer" (built-in server room list) as a feature, and this original version don't have it. You should create a room in LAN mode and run another ygopro to join it.

BTW, the core of those version have some differences, so the scripts may be incompatible. And the expansions load logic is different too.

**Comment by M-Reimer** [comment]
But, as the main project is GPL2 licensed, the sourcecode of the Percy version should be available somewhere, right? Can someone point me to the right direction?

**Comment by mercury233** [comment]
At some time in the past, ygopro is in MIT license, and the Percy version is based on that, but not open-source.

You can try to contact @Ygoproco to get the code.

**Comment by M-Reimer** [comment]
Is access to the multiplayer feature somewhere on the todo list for the "original" project?

**Comment by mercury233** [comment]
No. But personally i'm interested in it.

And both checkmate and mycard made "server" that make player only need to enter ip and port to connect to the server and duel online.

**Comment by M-Reimer** [comment]
Thanks for the hint with the servers. I'll try that.
I've opened a separate bug about the multiplayer feature:
https://github.com/Fluorohydride/ygopro/issues/2035
