### ISSUE TITLE
Add "Multiplayer mode"

### ISSUE THREAD

**Issue by M-Reimer** [Fluorohydride/ygopro#2035]
In the "Percy version", there is a dedicated "Multiplayer" mode in the menu.
Similar things seem to be possible with contributed servers, but you have to know an IP to connect with the LAN mode.
It would be nice if there would be a dedicated "Multiplayer" mode to start with.
Maybe it even is possible to connect to the system used by the "Percy version" of ygopro.

**Comment by Zayelion** [comment]
This would require a change to the `STOC` protocol to send a room list for that server, and a way of maintaining a live connection to it.
