### ISSUE TITLE
How to make working build?

### ISSUE THREAD

**Issue by M-Reimer** [Fluorohydride/ygopro#2036]
Hello,

I managed to compile but the contents of this repo don't seem to be a working game.

Some stuff seems to be missing and nowhere documented from where to get it.

Like a "cards.cdb" file and the "strings.conf". Maybe even more.

Is there some tutorial on how to "finish" the contents of the repo to make it actually work?

Thanks in advance.

Edit: I'm compiling on Arch Linux using the documentation found on the Wiki.

**Comment by fervi** [comment]
https://github.com/fervi/OpenYGO/tree/master/ygopro-build

And database of cards

**Comment by M-Reimer** [comment]
Good start but why do you comment out cloning the "script" directory? If this is not added to the repo, the final result still doesn't work.

**Comment by Zayelion** [comment]
- https://github.com/Fluorohydride/ygopro-core/blob/master/README.md
- https://github.com/moecube/ygopro/blob/master/.travis.yml

A few other build instructions. Compare notes.

**Comment by mercury233** [comment]
[The wiki of ygopro on github](https://github.com/Fluorohydride/ygopro/wiki/build) is open to anyone to edit, and I'm planning to rewrite it after irrklang is introduced.

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro/wiki#running
