### ISSUE TITLE
Segmentation fault when trying to edit deck

### ISSUE THREAD

**Issue by M-Reimer** [Fluorohydride/ygopro#2038]
I get the attached segfault when clicking on "Edit Deck".
[backtrace.txt](https://github.com/Fluorohydride/ygopro/files/1285356/backtrace.txt)

**Comment by fervi** [comment]
Do you have deck directory?

**Comment by M-Reimer** [comment]
Yes. They are both existent. But empty.

**Comment by fervi** [comment]
Do you have database? (cards.cdb)

**Comment by M-Reimer** [comment]
For some reason I don't get the segfault with my "improvised" build where I dumped the self-compiled binaries into a "Percy version" (after killing the closed-source binary). No segfault there. But I would prefer to run 100% self-compiled. Does the fact, that it works with the "Percy scripts" mean, that this is potentially a script but which triggers the crash on C++ side?

**Comment by M-Reimer** [comment]
Yes, I just copied the database from the "Percy version" as I don't have any other database.

**Comment by mercury233** [comment]
Could you try a linux build here: 
https://github.com/moecube/ygopro/releases

**Comment by fervi** [comment]
@M-Reimer 
I tests, and you probably don't have fonts (directory + fonts in config)

**Comment by edo9300** [comment]
Do you have the fonts? Usually it crashes in deck edit when it doesn't find the fonts

**Comment by M-Reimer** [comment]
Yes, that was the problem. Still missing pictures for the cards now...
Is this a "wanted feature" that the game crashes without fonts?
In my opinion some useful error messages would help here. Especially as the directory is missing on the repository, too.

**Comment by DailyShana** [comment]
84200fa1cb9e869e1517d608c326f47c0061c40a
