### ISSUE TITLE
Last Will

### ISSUE THREAD

**Issue by AndreOliveiraMendes** [Fluorohydride/ygopro#2040]
last will states:
>If a monster on your side of the field was sent to your Graveyard this turn, you can Special Summon 1 monster with an ATK of 1500 points or less from your Deck once during this turn. Then shuffle your Deck.

According to the rulings I should be able to summon with its effect at any time during the turn it's active, but atm in ygopro, you can only use its effect if a chain is created, without the possibility to use it in idle states of the turn, like the main phases or the battle phase, thing that you should be able to do. So i think it would be better to make a new handling for this kind of effect, a "global continuous effect that can be activated manually".
@VanillaSalt

**Comment by mercury233** [comment]
fixed
