### ISSUE TITLE
BUG: Effect of continuous cards may "disappear randomly"

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2066]
After updating my server yesterday, I got many report about can't pendulum summon or continuous s&t can't use effect.
Them have same feature that the effect only disappear in once duel, and the bug can't be reproduced.

Here are one bugged replay. The negative pend effect of _Satellarknight Zefrathuban_ disappeared so the player pendulum summoned all hands.
[神数自肃bug.zip](https://github.com/Fluorohydride/ygopro/files/1508754/bug.zip)
I tried 50 times on my PC but I can't reproduce it. ~~Maybe it only happens on linux?~~

**Comment by DailyShana** [comment]
I guess https://github.com/Fluorohydride/ygopro-core/commit/c8cab7c3d4d3443b4116e6c6ba567ef8e4807ecc can solve it
