### ISSUE TITLE
Connection has been lost before winning / losing

### ISSUE THREAD

**Issue by fervi** [Fluorohydride/ygopro#2067]
Hello, it suddenly stopped working :P And I do not know what caused the error.

When a player has to win / lose a duel (lose LP), players are disconnected without a final result. Maybe someone knows the solution to this? Unfortunately, I have no information what causes this problem.

Thank you for your answer

**Comment by fervi** [comment]
Surrender also kicking out players ...

**Comment by mercury233** [comment]
The connection end event is parsed before duel end event is parsed. 
https://github.com/Fluorohydride/ygopro/blob/master/gframe/duelclient.cpp#L147-L175
I don't know how to fix it too.

It can be reproduced by: create a room, go to observer, join two windbot, watch them duel. At most times, the connection lost dialogue will show up before you watch the duel to end.

**Comment by OhnkytaBlabdey** [comment]
yes
楼上说的对∑(ﾟдﾟ*)

**Comment by fervi** [comment]
Ufff, now just ygopro crash :)
[28397.567812] ygopro[22425]: segfault at 170320 ip 0000000000170320 sp 00007f0bf75e4c88 error 14 in ygopro[5593ff9aa000+25e000]
[28397.567856] ygopro[22280]: segfault at 170320 ip 0000000000170320 sp 00007feb98a9cc88 error 14 in ygopro[564d1e689000+25e000]

**Comment by purerosefallen** [comment]
Use the version 2.0.22 of libevent. This problem may cause if used other versions.

**Comment by fervi** [comment]
@purerosefallen I understand it, but it's an old library.

**Comment by DailyShana** [comment]
According to the explanation in libevent/libevent#839, why this problem occurs when using libevent 2.1 is when calling `NetServer::StopServer()` after duel end, `event_base_loopexit(net_evbase, 0)` has a little delay in 2.0 but active immediately in 2.1 when the second parameter is `0`, this a little delay seems enough for client receiving massages including `STOC_DUEL_END`.

So a workaround is to change [this line](https://github.com/Fluorohydride/ygopro/blob/master/gframe/netserver.cpp#L63) to
```
timeval etv = { 0, 1 };
event_base_loopexit(net_evbase, &etv);
```
but
>you should not write such code, that assume that the events will be triggered after you stopped the event loop with event_base_loopexit()
So I'm strongly suggesting you to rewrite your code to avoid such patterns

maybe this is why 
>It can be reproduced by: create a room, go to observer, join two windbot, watch them duel. At most times, the "disconnected" dialog will show up before you watch the duel to end.

occurs, although I cannot reproduce it when using libevent 2.0.22

**Comment by edo9300** [comment]
Wouldn't it better to do like in the other example where the loop is actually broken by disabling the listener and putting a callback on it?

**Comment by DailyShana** [comment]
@edo9300 
Yes. In fact, the listener is disabled after duel start by `NetServer::StopListening()`, so after duel end, even do not calling `NetServer::StopServer()`, the server will automatically end when all players leave the game.

**Comment by edo9300** [comment]
Hmm iirc on my client the listening is never disabled, probably that's why I never encountered this issue
