### ISSUE TITLE
Two cards with same name won't let user select which card to trigger mandatory effect

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2069]
_Star Pendulumgraph_ and _Heavymetalfoes Electrumite_ have effect that "You can only use this effect of [] once per turn."
If two of those cards are on your field, one of them is disabled, and the effect of them will be triggered, you may want to select which card to trigger, but now the program will activate effect automatically, and the disabled card may be selected.

**Comment by DailyShana** [comment]
#1656 can solve this, but...

`MSG_SELECT_TRIGGER` seems like a simplified version of `MSG_SELECT_CHAIN`, maybe we can use `MSG_SELECT_CHAIN` to implement `PROCESSOR_SELECT_TRIGGER`.

**Comment by DailyShana** [comment]
solved in e6c44f6d4b9dad011d44cfba6b81f32bd6654ce3
