### ISSUE TITLE
trying to build the client and im stuck

### ISSUE THREAD

**Issue by chatango-kotarou** [Fluorohydride/ygopro#2074]
where do I put the include and lib folders in the sln can you provide screenshots im not a vs dev im coming from python

**Comment by purerosefallen** [comment]
https://github.com/moecube/ygopro/blob/master/appveyor.yml
Follow those steps one by one and you will succeed

**Comment by chatango-kotarou** [comment]
wow does appveyor come in handy

**Comment by chatango-kotarou** [comment]
thanks

**Comment by chatango-kotarou** [comment]
don't mean to reopen after I close but I get No artifacts found matching 'ygopro-$(APPVEYOR_REPO_TAG_NAME)-win32-zh-CN.tar.gz' path
"GitHub" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")

**Comment by mercury233** [comment]
it need `APPVEYOR_REPO_TAG_NAME`, so you should git tag your commit and push again

**Comment by chatango-kotarou** [comment]
how do I do that? I don't mean to sound unknowledgeable but git is fairly new to me

**Comment by mercury233** [comment]
```bash
git tag v1.0
git push --tags
```

or use github release to create it
