### ISSUE TITLE
BUG: Trickstar Candina can't trigger its second effect if Unending Nightmare activate and use its effect.

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2080]
If _Unending Nightmare_ don't use its effect(destroy card) when activating, _Trickstar Candina_ can trigger effect.
But `re:IsHasType(EFFECT_TYPE_ACTIVATE)` will be false if the continuous trap activate and use effect.

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/5b4a078f2b7844db9f88823a71011e5bf7277006#diff-4d3e75d312bd06042b71854fa0c82846R4739

@VanillaSalt I guess it is because `EFFECT_TYPE_ACTIVATE` was reset here.

temp fix: https://github.com/Fluorohydride/ygopro-pre-script/pull/170/files

**Comment by DailyShana** [comment]
I think `EFFECT_TYPE_ACTIVATE` should be removed in step 10 of `solve_chain`
