### ISSUE TITLE
BUG: Some Issues of EFFECT_TYPE_CONTINUOUS / EVENT_FREE_CHAIN

### ISSUE THREAD

**Issue by purerosefallen** [Fluorohydride/ygopro#2082]
![n x1nu kmc5 1k6h0c46go](https://user-images.githubusercontent.com/19840160/35850336-6d4f649e-0b5f-11e8-910a-ea0365676f0c.png)
1. after activated Last Will, and returned it from the grave to the hand, a Do Effect button will display. but it's same as Activate.
2. when activated Last Will and spsummoned a monster with an EFFECT_TYPE_TRIGGER_O effect of EVENT_SPSUMMON_SUCCESS immediately, that effect COULD be triggered.
but, when activated Last Will and spsummoned a monster with an EFFECT_TYPE_TRIGGER_O effect of EVENT_SPSUMMON_SUCCESS later using the EFFECT_TYPE_CONTINUOUS / EVENT_FREE_CHAIN effect, that effect COULD NOT be triggered, but will trigger after spsummoning a monster from the extra deck, or going to the end phase(not battle phase)

**Comment by DailyShana** [comment]
2nd problem is fixed in https://github.com/Fluorohydride/ygopro-core/commit/74e7ec534f565133450cec34b2e2e901cd27134f
