### ISSUE TITLE
BUG about Effect.GetActivateLocation

### ISSUE THREAD

**Issue by purerosefallen** [Fluorohydride/ygopro#2086]
![9 msda11gsc ejqjacawfd](https://user-images.githubusercontent.com/19840160/36152586-7b96804e-1106-11e8-9fd5-04727dc204bf.jpg)
during player's main phase, Astrograph Sorcerer which has just been sent to hand from extra deck by the effect of Heavymetalfoes Electrumite, can still activatee its effect though Mind Drain is still available.
however, the Astrograph Sorcerer which has already in hand could not activate.
I looked carefully through the related scripts and the ocgcore, and thought it should be a bug of Effect.GetActivateLocation. perhaps a timing of set_activate_location is missing.

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/773555f69fcfb47292917c6a2ebefbabb0e13acd#diff-b6f4a9a4b26648c624030a6bf8e8d73c

**Comment by purerosefallen** [comment]
This problem remains.
