### ISSUE TITLE
EFFECT_UNRELEASABLE_NONSUM don't takes value

### ISSUE THREAD

**Issue by AndreOliveiraMendes** [Fluorohydride/ygopro#2087]
unlike EFFECT_UNRELEASABLE_SUM, EFFECT_UNRELEASABLE_NONSUM is not affected by any way for setvalues, which makes it almost impossible to specify what or who can't tribute it.
it necessary for new card, "Darkest Diabolos, Lord of the Lair", because it should only block opponent from tributing.

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/4b3176d1d7b74f3274e48e13a0f2de9456dbc7c1
I guess this will make this card work, so the change of `EFFECT_UNRELEASABLE_SUM` isn't necessary now.
