### ISSUE TITLE
Issue Necrovalley, Ghost Belle & Haunted Mansion

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#2112]
Konami's answer, _Ghost Belle & Haunted Mansion_ can negate _Xyz Soul_'s effect.

> http://yugioh-wiki.net/index.php?%A1%D4%A5%A8%A5%AF%A5%B7%A1%BC%A5%BA%A1%A6%A5%BD%A5%A6%A5%EB%A1%D5#faq
> Ｑ：このカードの発動にチェーンして自分は《屋敷わらし》の効果を発動できますか？
> Ａ：はい、発動できます。(18/05/10)

However, if _Xyz Soul_ add `Duel.SetOperationInfo(0,CATEGORY_TOEXTRA,g,1,0,0)`, _Necrovalley_ negate _Xyz Soul_'s effect.
Konami's answer, _Necrovalley_ don't negate _Xyz Soul_'s effect.

> http://yugioh-wiki.net/index.php?%A1%D4%A5%A8%A5%AF%A5%B7%A1%BC%A5%BA%A1%A6%A5%BD%A5%A6%A5%EB%A1%D5#faq
> Ｑ：フィールドに《王家の眠る谷－ネクロバレー》が表側表示で存在する場合にこのカードを発動した場合、その『自分フィールド上に存在する全てのモンスターの攻撃力は、エンドフェイズ時まで選択したモンスターのランク×２００ポイントアップする。』と『その後、選択したモンスターをエクストラデッキに戻す事ができる。』の処理は行われますか？
> Ａ：『自分フィールド上に存在する全てのモンスターの攻撃力は、エンドフェイズ時まで選択したモンスターのランク×２００ポイントアップする。』処理は**通常通り適用されます**。
> 　　なお、『その後、選択したモンスターをエクストラデッキに戻す事ができる。』の処理を行わずに効果処理を完了します。(18/05/10)

So, I think we should add new categories.
what do you think about it?

This problem maybe has _Ash Blossom & Joyous Spring_.

**Comment by DailyShana** [comment]
Since whether _Xyz Soul_ returns the Xyz monster is not definitely, we can use 
`Duel.SetOperationInfo(0,CATEGORY_TOEXTRA,nil,0,0,0)` (similar to _Macro Cosmos_)
to indecate there maybe a monster would return to extra deck
and modify _Necrovalley_ to check the count of operation info
