### ISSUE TITLE
Add function rearrange face-down and face-up spell / trap cards on the field

### ISSUE THREAD

**Issue by Septimoangel12** [Fluorohydride/ygopro#2114]
Fluorohydride it would be possible to add to the game in the constant "ShuffleSetCard" cards in the Spell / trap zone?, for example the effect of Mirror Force Launcher or Brandish Mechanism Multi-Roll or Darkness card (100000590) has this effect, however it is not included in your script:

http://yugioh.wikia.com/wiki/Darkness

Thank you for your attention.

**Comment by Septimoangel12** [comment]
I understand, but it is possible shuffle Set Cards in Spell/Trap Zone with "ShuffleSetCard"?

**Comment by mercury233** [comment]
```lua
	local sg=Duel.GetMatchingGroup(Card.IsFacedown,tp,LOCATION_SZONE,0,aux.ExceptThisCard(e))
	Duel.ShuffleSetCard(sg)
```

**Comment by Septimoangel12** [comment]
**mercury233** thank, I try to add this to the script of Anime cards.
