### ISSUE TITLE
申请添加一个新功能

### ISSUE THREAD

**Issue by yybbwc** [Fluorohydride/ygopro#2115]
现状:在残局模式中选择某个残局后，“主要信息”处不会显示残局相关信息。

申请功能:让残局文件可以自带“主要信息”处的文字。

益处:残局作者可以给残局添加简介了。

**Comment by fallenstardust** [comment]
noted with thanks

**Comment by purerosefallen** [comment]
We wanted to, but no solution yet.

**Comment by purerosefallen** [comment]
https://github.com/Fluorohydride/ygopro/pull/2136

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro/commit/553330c7f633b043cbe269c4aafddc14fd6f17da
