### ISSUE TITLE
Make improvements to the following filters for Ygopro

### ISSUE THREAD

**Issue by Septimoangel12** [Fluorohydride/ygopro#2119]
Is possible to improve the following filters to be able to interact
with other cards in the game when they replace an action during the duel the filters are:

**●void Card.SetStatus(Card c, int state, bool enable)**
**●void Duel.RaiseSingleEvent(Card ec, int code, Effect re, int r, int rp, int ep, int ev)**
**●void Duel.RaiseEvent(Group|Card eg, int code, Effect re, int r, int rp, int ep, int ev)**

For example to simulate a battle outside the Battle Phase:

If it were used in a code to simulate a destruction by battle, and the following filter:

Duel.SendtoGrave(tc,**REASON_BATTLE**)
tc:SetStatus(**STATUS_BATTLE_DESTROYED**,true)
Duel.RaiseSingleEvent(tc,**EVENT_BATTLE_DESTROYED**,e,**REASON_BATTLE**,tc:GetControler(),tc:GetControler(),0)
Duel.RaiseEvent(tc,**EVENT_BATTLE_DESTROYED**,e,**REASON_BATTLE**,tc:GetControler(),tc:GetControler(),0)

You can trigger other cards in the game to react to these events as "If a monster is destroyed in battle ..." and can be chained in response to the filter also can calculate damage as a Battle Damage if the ATK of that destroyed in battle was a monster. For example:

Duel.RaiseSingleEvent(tc,**EVENT_BATTLE_DAMAGE**,e,**REASON_BATTLE**,tc:GetControler(),tc:GetControler(),"damage equal to the difference of the ATK of that attacks monster and the attack target“)

something similar happens with the constant "●**void Duel.CalculateDamage(Card c1, Card c2)**" where it would also be possible to calculate the damage as battle and to order the destruction by battle so that other cards can be linked in response to it for example with the constant: "**●void Duel.ChangeAttackTarget(Card c|nil)**"  And the game recognizes these two types of effect as attacks.

Thank you for your attention.

**Comment by DailyShana** [comment]
Cannot understand what you are saying.
Please summarize in a few sentences.

**Comment by Septimoangel12** [comment]
Hi **DailyShana** my request is that you can simulate a battle outside the **Battle Phase** and that the cards can be chained or activated in response to this and I believe that to achieve this it is possible through the following filters:

●void Card.SetStatus(Card c, int state, bool enable)
●void Duel.RaiseSingleEvent(Card ec, int code, Effect re, int r, int rp, int ep, int ev)
●void Duel.RaiseEvent(Group|Card eg, int code, Effect re, int r, int rp, int ep, int ev)
●Duel.Damage(int player, int value, int reason)

If these filters are improved it would be possible to simulate this type of effects and even many others, for example:

Duel.SendtoGrave(tc,**REASON_BATTLE**)
tc:SetStatus(**STATUS_BATTLE_DESTROYED**,true)
Duel.RaiseSingleEvent(tc,**EVENT_BATTLE_DESTROYED**,e,**REASON_BATTLE**,tc:GetControler(),tc:GetControler(),0)
Duel.RaiseEvent(tc,**EVENT_BATTLE_DESTROYED**,e,**REASON_BATTLE**,tc:GetControler(),tc:GetControler(),0)
Duel.Damage(1-tp, int value,**REASON_BATTLE**)

It would be possible for example in the previous case to make these filters try to emulate a battle event when a card has been destroyed or sent to the Graveyard, however, it is not possible to chain cards that negate that attack, change the attack target. Do a battle damage calculation by means of the filter ● **int Duel.Damage (int player, int value, int reason)** where it is possible to chain cards for example that negate battle damage, change battle damage, and may be compatible with many similar effects with respect to battle damage.

Along with **[Ygopro Percy](https://www.ygopro.co/Forum/tabid/95/g/posts/t/8185/My-Missing-Anime-Cards-Project)** about 3 years ago with many users of the game **Ygopro** we started a project to add the Anime cards and video games to add them to **Ygopro**, the project has been very good and many users have helped this could be possible, however, many anime cards need to emulate a battle phase and to do so it is necessary that the previous filters can be improved, and that the cards can respond to these filters. Cards like the **[Egyptian Gods (Anime)](http://yugioh.wikia.com/wiki/Egyptian_God)**, **[Chaos Phantasm Armityle (Anime)](http://yugioh.wikia.com/wiki/Chaos_Phantasm_Armityle)**, **[ZW - Leo Arms (Anime)](http://yugioh.wikia.com/wiki/ZW_-_Leo_Arms_(anime))**, **[Impact Revive](http://yugioh.wikia.com/wiki/Impact_Revive)**, **[Chaos Barrier Field](http://yugioh.wikia.com/wiki/Chaos_Barrier_Field)**, **[One-on-One Fight](http://yugioh.wikia.com/wiki/One-on-One_Fight)** and many more others like these can be added to the project. To see the project of Anime cards you can go to the following link on my page so you can find out more about the project. Thank you very much:

[https://www.deviantart.com/septimoangel12](url)

**Comment by DailyShana** [comment]
Sorry, we do not consider animate cards in this project. As far as I know, there are several projects using modified ocgcore for diy cards.

**Comment by Septimoangel12** [comment]
Well, I understand that it is difficult for you to take into account the opinion of the "amateurs" and / or users of the game, that is something that can be seen now, it would be possible for them to add these characteristics to the filters that I mentioned before to be able to add to play many of these cards that Ygopro users have been asking us since we started these projects, would be of great help to us and we would always appreciate it, please be grateful for the Ygopro users, thanks.

**Comment by DailyShana** [comment]
It is anime cards is not in the range of this project that your request is refused, not other things.
