### ISSUE TITLE
Vehicroid Connection Zone problem

### ISSUE THREAD

**Issue by AndreOliveiraMendes** [Fluorohydride/ygopro#2122]
There's a problem with the interaction between Vehicroid Connection Zone and cards like Breakthrough Skill. Let's take the following scenario.
Your opponent has a monster and a set Breakthrough Skill, and you use Vehicroid Connection Zone to fusion Summon Super Vehicroid - Mobile Base, using Pair Cycroid and Cycroid as material. You use its effect, targeting your opponent's monster, and the opponent chains Breakthrough Skill. According to Vehicroid Connection Zone, Mobile Base's effect should resolve instead of being negated, but at the moment it is negated. This seems to be an issue with EFFECT_CANNOT_DISEFFECT on effects of type EFFECT_TYPE_SINGLE, because it works fine with cards like Altergeist Protocol that use EFFECT_TYPE_FIELD in the same scenario.

**Comment by AndreOliveiraMendes** [comment]
i think that the bellow code (on field.cpp) works, not sure trought, probaly need some deep tests on it.
```C++
int32 field::is_chain_disablable(uint8 chaincount) {
	effect_set eset;
	if(chaincount > core.current_chain.size())
		return FALSE;
	effect* peffect;
	if(chaincount == 0)
		peffect = core.current_chain.back().triggering_effect;
	else
		peffect = core.current_chain[chaincount - 1].triggering_effect;
	if(!peffect->get_handler()->get_status(STATUS_FORBIDDEN)) {
		if(peffect->is_flag(EFFECT_FLAG_CANNOT_DISABLE))
			return FALSE;
		if (peffect->get_handler()->is_affected_by_effect(EFFECT_CANNOT_DISEFFECT))
			return FALSE;
		filter_field_effect(EFFECT_CANNOT_DISEFFECT, &eset);
		for(int32 i = 0; i < eset.size(); ++i) {
			pduel->lua->add_param(chaincount, PARAM_TYPE_INT);
			if(eset[i]->check_value_condition(1))
				return FALSE;
		}
	}
	return TRUE;
}
```

**Comment by DailyShana** [comment]
you can open a pull request
