### ISSUE TITLE
BUG: Armored Kappa can't use 2nd effect by different player in same turn

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2157]
My opponent have one _Armored Kappa_, I attack it, it use 2nd effect, I use _Rebellion_ to get its control, and I can't use its 2nd effect.

I think it is because the `count_limit` is decreased in
https://github.com/Fluorohydride/ygopro-core/blob/3737bd18ed135b6c95afb7e11070229940da3317/effect.cpp#L594
so it directly return false in
https://github.com/Fluorohydride/ygopro-core/blob/3737bd18ed135b6c95afb7e11070229940da3317/effect.cpp#L153

**Comment by edo9300** [comment]
I'm believing that it affects every effect, not that one only
