### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by OliOpf** [Fluorohydride/ygopro#2161]
Hi there!

I don't know if you guys already know this, cause I didn't read every thread. I wanted to ask, if it is possible to implement some new things in the core. It would be really great to have an option, that monsters could only be summoned to the Extra Monster Zone. Furthermore would it be possible to implement a function, so that the opponent could not look in his/mine/either graveyard? 

Best regards!

**Comment by mercury233** [comment]
Sorry, but now we only consider OCG rule and cards here. 
Some fork may have support for this: https://github.com/purerosefallen/ygopro
