### ISSUE TITLE
Heap Corrupt

### ISSUE THREAD

**Issue by ytlDL** [Fluorohydride/ygopro#2171]
Heap corrupted on first Duel.SpecialSummon() is called in LUA script.

[Build Environment] Visual Studio 15.9.4 + Windows 10
[Configuration] Release, Win32 (Debug Okay)
[Exception] 0xC0000374: A heap has been corrupted
[Traceback] int32 scriptlib::duel_special_summon(lua_State *L) : return lua_yield(L, 0);

**Comment by ytlDL** [comment]
It works, thank you for the quick reply.
But shouldn't the destructor of set<card *, cardsort>(the local variable cset) be called when exiting the if block?

**Comment by DailyShana** [comment]
I can't explain...if that were the case, it should be no problem.
