### ISSUE TITLE
How to run it on linux?

### ISSUE THREAD

**Issue by Max-Snow** [Fluorohydride/ygopro#2172]
I am using debian and I have successfully built it. Now how do I run the game?

**Comment by purerosefallen** [comment]
Do you mean to run it as server or client?

**Comment by Max-Snow** [comment]
I want to run it as client, mainly because I can't find a linux ygo client. But I still don't understand how to figure it out. I have downloaded a windows distribution, but how do I combine it with the binary? And how can I open the exe file on linux?

**Comment by purerosefallen** [comment]
@Max-Snow Check `./bin/release` of your source folder and see if there's a binary named `ygopro`. Then copy this file into your downloaded windows ygopro folder. If not, see if you built it correctly
Then `vim system.conf` and change the font options to your fonts, which should be at `/usr/share/fonts` in your operating system.
After this, each time you play, open a new terminal and `./ygopro`, and enjoy.

**Comment by Max-Snow** [comment]
@purerosefallen Thanks so much for your help. I can find ygopro in ./build/bin. After following the steps you wrote, I still can't run it and the computer told me:
`Irrlicht Engine version 1.8.4
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64
Using plain X visual
This driver is not available in Linux. Try OpenGL or Software renderer.
`
Do you know how to handle it?

**Comment by edo9300** [comment]
Probably the game is trying to use the directx3d driver, change its setting in settings.conf to 0 so that the game will use the opengl render
