### ISSUE TITLE
Issue Malefic Territory and Malefic Parallel Gear

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#2180]
Konami's answer, "if _Malefic Territory_ and Malefic monster has on the field, player can only control 1 _Malefic Parallel Gear_."

> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22507
> Q.自分のフィールドゾーンに「Sin World」、自分の魔法＆罠ゾーンに「Sin Territory」がそれぞれ表側表示で存在し、自分のモンスターゾーンに「Sin パラレルギア」2体が表側表示で存在しています。
> 
> この状況で、自分は手札の「Sin 真紅眼の黒竜」を『デッキから「真紅眼の黒竜」１体を除外した場合に特殊召喚できる』方法によって特殊召喚する事はできますか？
> A.質問の状況の場合でも、自分は手札から「Sin 真紅眼の黒竜」を特殊召喚する事ができます。
> 
> 「Sin Territory」の『②：「Sin」モンスターの持つ、「「Sin」モンスターはフィールドに１体しか表側表示で存在できない」効果は、「「Sin」モンスターは１種類につきフィールドに１体しか表側表示で存在できない」として適用される』によって、特殊召喚された「Sin 真紅眼の黒竜」の『①：「Sin」モンスターはフィールドに１体しか表側表示で存在できない』モンスター効果は、『「Sin」モンスターは１種類につきフィールドに１体しか表側表示で存在できない』効果として適用されます。
> 
> この時、**自分のモンスターゾーンには「Sin パラレルギア」2体が存在していますので、いずれか1体の「Sin パラレルギア」が破壊される事になります**。 

However, if _Malefic Territory_ and Malefic monster has on the field, player can control 2 or more _Malefic Parallel Gear_ s.

**Comment by salix5** [comment]
8257410ccc7cf6d31b1ac35484b0a123e2c0fedd@Fluorohydride/ygopro-scripts

**Comment by edo9300** [comment]
@salix5 a better solution to this, would be to have the possibility to use global unique on fields, rather than using those workarounds adding efects on card that shouldn't have them. What if a malefic monster was a normal monster? how would have it been handled?

**Comment by salix5** [comment]
I will try to do so when I have enough time.
Thank you for your advice.

**Comment by edo9300** [comment]
Thanks for your reply. Anyways, looking at malefic territory's text, i'm thinking that maybe its effect should be interpretated more like There Can Be Only One "Each player can only control 1 monster of each Type. If a player controls 2 or more monsters of the same type, they must send some to the GY so they control no more than 1 monster of that Type. "
as teh card is behaving completely replacing the effect, so seeing it in gameplay terms, a replaced effect could be of any type (so not forcefully an unique on field effect). In fact its wording suggest that "There cannot be face-up "Malefic" monsters on the field with the same name". So a proper implementation would be a grant effect that gives an effect like There Can Be Only One to all the malefics with the unique effect (even if a global unique on field would still be itneresting).

**Comment by edo9300** [comment]
Gozen match is more similar for wording too "Each player can only control 1 Attribute of monster. Send all other face-up monsters they control to the Graveyard."

**Comment by edo9300** [comment]
@salix5 if you want to give a look, this is my implementation of malefic territory that works with that ruling https://github.com/Ygoproco/Live2017Links/pull/1955/files
