### ISSUE TITLE
Request for a collaborator access permission

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#2186]
@Fluorohydride 
I had been contributing to ygopro via pull requests.
However, ygopro has many old ruling scripts.
So  I need the collaborator access to `ygopro`, `ygopro-core` and `ygopro-scripts` repositories.
Would you get me access to these repositories?
Thank you.

**Comment by nekrozar** [comment]
@Fluorohydride Thank you!

**Comment by purerosefallen** [comment]
Well, congratulations!
But what I have to tell you is, please leave large changes in Pull Request, for further discussions.
In addition, could you leave your contact information? We developers could discuss together.

**Comment by nekrozar** [comment]
Sorry, I updated my bio.

**Comment by purerosefallen** [comment]
.. What do you mean?

**Comment by nekrozar** [comment]
I mean "In addition, could you leave your contact information?" is "Counld you show contact information?".
