### ISSUE TITLE
[Question / Scripting Request] Calling refresh_location_info_instant() from lua script

### ISSUE THREAD

**Issue by GoodByeWorld** [Fluorohydride/ygopro#2188]
I would like to renew location status, says field::player[playerid].disabled_location instantly, in lua script.
However, it appears that currently there is no way to achieve this directly.

By the way, a temporary solution was something like this:
<pre><code>
    -- Set c::reason to REASON_TEMPORARY to bypass duel_return_to_field check.
    -- REASON_RULE prevent this operation fails.
    Duel.SendtoDeck(c, p1, 0x0, REASON_RULE | REASON_TEMPORARY)

    -- Call refresh_location_info_instant() internally right before actual operation.
    -- The operation result does not matter.
    Duel.ReturnToField(c)

    -- Refreshed field::player[playerid].disabled_location.
</code></pre>
which is inefficient.

Any better approach?

**Comment by purerosefallen** [comment]
Use `Duel.AdjustInstantly()`.

**Comment by GoodByeWorld** [comment]
Thanks for the reply.

duel_adjust_instantly() is a wrapper of field::adjust_instant() for LUA scripts.
But according to the source code:
<pre><code>
void field::adjust_instant() {
	adjust_disable_check_list();
	adjust_self_destroy_set();
}
</code></pre>
, in which:
	adjust_disable_check_list() updates card disabled status
	adjust_self_destroy_set() updates self-destroy list 
and none of them actually refreshes field::player[playerid].disabled_location.

Therefore, I am afraid that the solution would not work.
This is why I would like to add wrapper of field::refresh_location_info_instant(), just like field::adjust_instant().

**Comment by DailyShana** [comment]
we only add lua functions when it is really necessary for **ocg** cards

**Comment by GoodByeWorld** [comment]
Well, this will never be necessary, as one can always refresh it by some other methods; they are just inefficient.
I thought it would be not difficult to do this, but if that is the case, let us just close the issue.

Many thanks for your help : )

**Comment by purerosefallen** [comment]
But sometimes lua functions are added for pre-release cards... which isn't considered as OCG cards....
