### ISSUE TITLE
Build error on Visual Studio

### ISSUE THREAD

**Issue by Portalcake** [Fluorohydride/ygopro#2189]
I've followed all steps on the Wiki so far, I can compile almost all projects except 'ygopro' (exe).
I'm getting the following errors when I try to compile the ygopro.exe:

[game.cpp :: line 937]
E0144	a value of type "const irr::c8 *" cannot be used to initialize an entity of type "const wchar_t *"
C2440	'initializing': cannot convert from 'const T *' to 'const wchar_t *'

[menu_handler.cpp :: line 297]
C2664	'BOOL CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION)': cannot convert argument 9 from 'STARTUPINFO *' to 'LPSTARTUPINFOW'

Is there something that I'm doing wrong?

p.s. I'm using Visual Studio 2019 on Windows 10.

**Comment by DailyShana** [comment]
for the first error, you need define `_IRR_WCHAR_FILESYSTEM` before compiling irrlicht, as an example, see https://github.com/DailyShana/ygopro/commit/971a683e88866451ea57b6701aaf8d8b097edf6c#diff-403ca672e354fc20b0c0a04d4fcb7feb
for the second, it's probably that the macros `UNICODE` and `_UNICODE` are not defined.

**Comment by Portalcake** [comment]
> for the first error, you need define `_IRR_WCHAR_FILESYSTEM` before compiling irrlicht, as an example, see [DailyShana@971a683#diff-403ca672e354fc20b0c0a04d4fcb7feb](https://github.com/DailyShana/ygopro/commit/971a683e88866451ea57b6701aaf8d8b097edf6c#diff-403ca672e354fc20b0c0a04d4fcb7feb)
> for the second, it's probably that the macros `UNICODE` and `_UNICODE` are not defined.

Okay, thanks; I've fixed these errors, now I'm getting:
LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in CGUIImageButton.obj

This error happens when I try to build ygopro.exe
Previously I've build Irrlicht.lib as Static lib, accordingly to the post on Wiki.

**Comment by mercury233** [comment]
you can try this script: https://github.com/moecube/ygopro/blob/master/appveyor.yml

**Comment by purerosefallen** [comment]
*Is this script supporting `premake4.lua`?*

However, I could compile this repo properly with premake5 alpha 13 on my Ubuntu 18.04.2 LTS, with making extra changes.

**Comment by Portalcake** [comment]
> you can try this script: https://github.com/moecube/ygopro/blob/master/appveyor.yml

I'll try it, thanks.
