### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by jo-nathan1999** [Fluorohydride/ygopro#2192]
I'm sure someone has asked this before, but how could I take this code and host it on a website?

**Comment by mercury233** [comment]
You mean playing ygopro in browser?

**Comment by jo-nathan1999** [comment]
Yeah.

**Comment by mercury233** [comment]
Sure it is possible, you need to choose a HTML5 game engine and rewrite the client part of ygopro with it. Then it can connect to any server online.

**Comment by jo-nathan1999** [comment]
Would you happen to know of any open source code already in HTML5?

**Comment by mercury233** [comment]
No.

**Comment by jo-nathan1999** [comment]
alright
