### ISSUE TITLE
Client crashes when clicking a monster during the resolution of an attack

### ISSUE THREAD

**Issue by ketsuban** [Fluorohydride/ygopro#2195]
I can pretty reliably reproduce this crash, but the timing is apparently a little tight.

1. Save the provided Lua script to `single/[WCT2006] 01 Warriors of Darkness.lua`. (It's the same as the default `[WCS2006]01_ankokukai.lua`, but it's possible the filename is relevant.)
1. Run the client.
2. Click "Puzzle Mode".
3. Select `[WCT2006] 01 Warriors of Darkness.lua`.
3. Click "OK".
4. Complete the puzzle to the point where you're swinging with the remaining monsters into an empty board:
    1. Activate The Cheerful Coffin and discard Beiige, Broww and Sillva.
    2. Add their effects to the chain in any order. Special Summon Sillva and Beiige in Attack Position.
    3. Normal Summon Zure.
    4. Enter the Battle Phase.
    5. Attack White Magical Hat with Scarr.
    6. Destroy both Blue-Eyes White Dragons with Goldd's effect and Special Summon it in Attack Position.
5. While the opponent's Life Point bar is ticking down after an attack, click on a monster which has yet to attack. I find this happens most often with Goldd or Sillva, but I don't know if it's exclusively these two.

```lua
Debug.SetAIName("Warriors of Darkness")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)

Debug.SetPlayerInfo(0,600,0,0)
Debug.SetPlayerInfo(1,7000,0,0)

Debug.AddCard(07459013,0,0,LOCATION_DECK,0,POS_FACEDOWN)

Debug.AddCard(32619583,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(33731070,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(78004197,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(79126789,0,0,LOCATION_HAND,0,POS_FACEDOWN)

Debug.AddCard(05498296,0,0,LOCATION_MZONE,2,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,1,1,LOCATION_MZONE,1,POS_FACEUP_ATTACK)
Debug.AddCard(15150365,1,1,LOCATION_MZONE,2,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,1,1,LOCATION_MZONE,3,POS_FACEUP_ATTACK)

Debug.AddCard(41142615,0,0,LOCATION_SZONE,2,POS_FACEDOWN)

Debug.ReloadFieldEnd()
Debug.ShowHint("Win in this turn!")
aux.BeginPuzzle()
```

**Comment by DailyShana** [comment]
can't reproduce
you should report to the provider of your game download first
