### ISSUE TITLE
'startproject' (a nil value)

### ISSUE THREAD

**Issue by brithbutter** [Fluorohydride/ygopro#2197]
I am trying to play this game with Ubuntu 18.04. I've followed the instruction in wiki/build, but can not finish premake4 gmake and fetch the following error message.
```bash
premake4.lua:5: attempt to call global 'startproject' (a nil value)
```

**Comment by mercury233** [comment]
you can try premake5 or just delete the line

**Comment by purerosefallen** [comment]
Use Premake5 alpha13 and you will succeed.
In addition, you may also use cmake.
