### ISSUE TITLE
BUG: Elborz, Sacred Peak of Simorgh + Simorgh, Bird of Ancestry can't reduce the tribute requirement to 0

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2204]
while _Amarylease_ + _Geartown_ can do this in ygopro.

**Comment by nekrozar** [comment]
Konami's answer, _Simorgh, Bird of Ancestry_'s effect apply once only.
So, this issue isn't bug.

> Q. 
> 「始祖神鳥シムルグ」が自分フィールドに2体存在する場合、自分は「烈風の覇者シムルグ」をリリースなしで召喚できますか？ 
> A. 
> 「始祖神鳥シムルグ」が自分フィールドに2体以上存在する場合でも、『風属性モンスターの生け贄召喚に必要な生け贄は１体少なくなる』効果は**重複しません**ので、2体の「始祖神鳥シムルグ」の効果を適用して「烈風の覇者シムルグ」をリリースなしで召喚することはできません。
>

**Comment by mercury233** [comment]
didn't the title say that there are different cards ?

**Comment by nekrozar** [comment]
> Q. 
> 自分フィールドに「始祖神鳥シムルグ」1体のみが存在する場合、自分は「神鳥の霊峰エルブルズ」の②の効果を発動できますか？できる場合、②の効果処理後に自分は「烈風の覇者シムルグ」をリリースなしで召喚できますか？ 
> A. 
> 「始祖神鳥シムルグ」の『風属性モンスターの生け贄召喚に必要な生け贄は１体少なくなる』効果が適用されている場合に、「神鳥の霊峰エルブルズ」の『②』の効果を適用し、「烈風の覇者シムルグ」をリリースなしで召喚することはできます。
> 
> Q. 
> お互いのフィールドゾーンに「歯車街」が存在する場合、自分は「古代の機械熱核竜」をリリースなしで召喚できますか？ 
> A. 
> 「歯車街」の効果は重複しませんので、リリース無しで「古代の機械熱核竜」をアドバンス召喚することはできません。

Maybe `EFFECT_DECREASE_TRIBUTE` should check card code.
