### ISSUE TITLE
International Board

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#2206]
@Fluorohydride @DailyShana @zh99998 @nekrozar @VanillaSalt 

The majority of the teams, and simulators that are dependent on this repo have gathered on Discord-App in an attempt to better coordinate fixes and changes to the software so that everyone's needs are met. Your presence is requested  so that we can resolve various ongoing problems quickly and privately.

https://discord.gg/yrzwtav 

If you are having issues connecting please respond on this thread and we will make other arrangements.

**Comment by kevinlul** [comment]
big money BMW if true we make game crack

**Comment by President-Makarov** [comment]
Friend I thank you for your assistance. I am able to compile game now and we move onto the step 2.
