### ISSUE TITLE
BUG: The pendulum effect of Servant of Endymion will set ACTIVITY_SPSUMMON wrongly

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2211]
[BUG-ACTIVITY_SPSUMMON.zip](https://github.com/Fluorohydride/ygopro/files/3292663/BUG-ACTIVITY_SPSUMMON.zip)
In this replay, _Altergeist Multifaker_ can't activate its 2nd effect.
Its `ACTIVITY_SPSUMMON` become 1 when the Servant of opponent summon itself.

I think it is caused by this line:
https://github.com/Fluorohydride/ygopro-core/commit/b94f0ed98d1507406ed499b7b8ae7bc6565eec36#diff-4d3e75d312bd06042b71854fa0c82846L4610
```
if(optarget.op_player == 1)
	sumplayer = 1 - sumplayer;
```
I don't know what this line do, but it is added years ago, seems a fix to _Spear Cretin_:
https://github.com/Fluorohydride/ygopro/commit/12a966457ddf1e709dc34d82919c4fcd41f628e9#diff-f0d8bf36b9bf85ff7cbd533305acfab8R4744

**Comment by DailyShana** [comment]
fixed in https://github.com/Fluorohydride/ygopro-core/commit/a0c052357d60f8a6dcc0f6bd9d109174295bcc95
