### ISSUE TITLE
BUG: Burning Abyss monster won't trigger self destroy effect infinitely if the destroy is replaced

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2215]
![image](https://user-images.githubusercontent.com/13391795/59565140-0543fa00-9082-11e9-81dc-d13fa92aa1ce.png)
_Archfiend Empress_ should be able to banish any count of monsters from grave before the BA is destroyed, but now it only repeat twice.

**Comment by nekrozar** [comment]
> http://yugioh-wiki.net/index.php?%A1%D4%A5%D8%A5%EB%A1%A6%A5%A8%A5%F3%A5%D7%A5%EC%A5%B9%A1%A6%A5%C7%A1%BC%A5%E2%A5%F3%A1%D5#faq
> Ｑ：自分フィールド上に《ヘル・エンプレス・デーモン》と《ジェネラルデーモン》が存在します。
> 　　《ジェネラルデーモン》が自身の効果で破壊される場合、このカードの効果によって破壊を免れられますか？
> 　　(１度守ったらそれ以降自壊しなくなりますか？それとも、墓地のモンスターを全て除外するまで繰り返した後で自壊が発生しますか？)
> Ａ：《ヘル・エンプレス・デーモン》の効果を適用することはできますが、**再び《ジェネラルデーモン》の効果が適用され自壊します**。
> 　　(墓地のモンスターを全て除外するまで繰り返した後でも自壊する) (13/04/15)

> http://yugioh-wiki.net/index.php?%A1%D4%A5%A8%A5%AF%A5%BE%A5%C7%A5%A3%A5%A2%A1%A6%A5%CD%A5%AF%A5%ED%A5%B9%A1%D5#faq
> Ｑ：エクゾディアパーツが存在しなくなった時、このカードが破壊される代わりに《魔導騎士 ディフェンダー》の効果で破壊を免れた場合、このカードは再び自身の効果で破壊する処理を行ないますか？
> 　　それとも、フィールド上に残り続けますか？
> Ａ：《魔導騎士 ディフェンダー》の効果で魔力カウンターを取り除くことはできますが、その処理を行った直後、**再びこのカードは自身の効果により破壊されます**。(14/11/07)
