### ISSUE TITLE
Issue Miracle Contact, Neos Fusion and United Gladiator Beasts

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro#2228]
These cards don't treat fusion summon and fusion material.

e.g.1) _Miracle Contact_ cannot apply _Fusion Tag_.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=17047
> 「ミラクル・コンタクト」の『①：自分の手札・フィールド・墓地から、融合モンスターカードによって決められた融合素材モンスターを持ち主のデッキに戻し、「E・HERO ネオス」を融合素材とするその「E・HERO」融合モンスター１体を召喚条件を無視してEXデッキから特殊召喚する』効果によってデッキに戻すモンスターは、融合素材モンスターとして適切なモンスター一組である必要がありますが、「ミラクル・コンタクト」の効果によってデッキに戻るモンスターは**融合素材としては扱われません**。

e.g.2) _Miracle Contact_ cannot apply _King of the Swamp_.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12371
> 「ミラクル・コンタクト」の効果による特殊召喚は**融合召喚として扱われない為**、「沼地の魔神王」等の『このカードを融合素材モンスター１体の代わりにする事ができる』効果を適用する事はできません。

e.g.3) _Miracle Contact_, _Neos Fusion_ and _United Gladiator Beasts_ can use "cannot use fusion material" monster.
> http://yugioh-wiki.net/index.php?%A1%D4%A5%DF%A5%E9%A5%AF%A5%EB%A1%A6%A5%B3%A5%F3%A5%BF%A5%AF%A5%C8%A1%D5#faq
> Ｑ：《ヒーロー・マスク》を発動し、《Ｅ・ＨＥＲＯ ネオス》となった融合素材にできない効果を持つモンスターをデッキに戻す事はできますか？
> Ａ：はい、できます。(19/07/08)
> http://yugioh-wiki.net/index.php?%A1%D4%A5%CD%A5%AA%A5%B9%A1%A6%A5%D5%A5%E5%A1%BC%A5%B8%A5%E7%A5%F3%A1%D5#faq
> Ｑ：《Ｅ・ＨＥＲＯ ネオス》と融合素材にできない《剣闘獣ティゲル》を墓地へ送って《Ｅ・ＨＥＲＯ ブレイヴ・ネオス》を特殊召喚することはできますか？
> Ａ：はい、できます。(19/07/15)
> http://yugioh-wiki.net/index.php?%A1%D4%C3%C4%B7%EB%A4%B9%A4%EB%B7%F5%C6%AE%BD%C3%A1%D5#faq1
> Ｑ：融合素材にできない《剣闘獣ティゲル》をデッキに戻すことはできますか？
> Ａ：はい、できます。(19/07/13)

But, in current version, these scripts different from these ruling. (https://github.com/Fluorohydride/ygopro-scripts/commit/5fc1678bb060869e2eb915472c18102073a36cba I fixed some in this commit.)

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/blob/5fc1678bb060869e2eb915472c18102073a36cba/utility.lua#L1062-L1063
we should remove this material check and filter IsCanBeFusionMaterial before calling Duel.CheckFusionMaterial in scripts that need select fusion material

**Comment by nekrozar** [comment]
but
> したがって、質問の状況の場合、「ミラクル・コンタクト」の効果によってデッキに戻すモンスターに「融合識別」の効果が適用されていたとしても、『その見せたモンスターの同名カードとして融合素材にできる』効果を適用する事はできませんので、エクストラデッキから特殊召喚されるモンスターは、「E・HERO ネオス」と「N・グラン・モール」 で特殊召喚される「E・HERO グラン・ネオス」になります。
this rule don't solve.
