### ISSUE TITLE
BUG: The timing of resolving effect that do not form a chain at After damage calculation in the damage calculation in effect is wrong

### ISSUE THREAD

**Issue by mallu11** [Fluorohydride/ygopro#2234]
This function only makes a monster attack another monster without calculating the damage.
For example：if an effect is chain 1，<i>Last Turn</i> is chain 2，the battle damage will be calculted after the chain 1 resolved.

**Comment by DailyShana** [comment]
The battle damage is calculated during chain solving. I guess you want to say sending battle destroyed monster to grave is taken after chain 1 solved, but this is not a bug.

ガガガザムライ:
>Ｑ：(2)の効果をチェーン２で発動し、《ＢＦ－蒼炎のシュラ》に戦闘破壊されました。
　　この場合、《ＢＦ－蒼炎のシュラ》の効果（モンスターを破壊し墓地へ送った時に発動）はチェーン２で発動条件を満たしたため、タイミングを逃す事となりますか？
Ａ：タイミングを逃しません。
　　チェーン１の効果の処理が終了した後、《ＢＦ－蒼炎のシュラ》の効果が発動します。(14/10/19)
http://yugioh-wiki.net/index.php?%A1%D4%A5%AC%A5%AC%A5%AC%A5%B6%A5%E0%A5%E9%A5%A4%A1%D5#faq

**Comment by mallu11** [comment]
> The battle damage is calculated during chain solving. I guess you want to say sending battle destroyed monster to grave is taken after chain 1 solved, but this is not a bug.
> 
> ガガガザムライ:
> 
> > Ｑ：(2)の効果をチェーン２で発動し、《ＢＦ－蒼炎のシュラ》に戦闘破壊されました。
> > 　　この場合、《ＢＦ－蒼炎のシュラ》の効果（モンスターを破壊し墓地へ送った時に発動）はチェーン２で発動条件を満たしたため、タイミングを逃す事となりますか？
> > Ａ：タイミングを逃しません。
> > 　　チェーン１の効果の処理が終了した後、《ＢＦ－蒼炎のシュラ》の効果が発動します。(14/10/19)
> > http://yugioh-wiki.net/index.php?%A1%D4%A5%AC%A5%AC%A5%AC%A5%B6%A5%E0%A5%E9%A5%A4%A1%D5#faq

What I say is damage calculation.In my example,the chain 2 will calculate the battle damage,then you can apply the effect destroy-instead and mark the status STATUS_BATTLE_DESTROYED,but the monster will not send to the grave.After that is <b>After damage calculation</b>,after resolving the operation of destroy-instead is the resolution of chain 1.At last,the batte-destroyed monster will be send to the grave in the <b>End of the Damage Step</b>.
The bug what I say is the damage calculation won't calculate in chain 2,it will calculate after chain 1 resolve in program.

**Comment by mallu11** [comment]
> The battle damage is calculated during chain solving. I guess you want to say sending battle destroyed monster to grave is taken after chain 1 solved, but this is not a bug.
> 
> ガガガザムライ:
> 
> > Ｑ：(2)の効果をチェーン２で発動し、《ＢＦ－蒼炎のシュラ》に戦闘破壊されました。
> > 　　この場合、《ＢＦ－蒼炎のシュラ》の効果（モンスターを破壊し墓地へ送った時に発動）はチェーン２で発動条件を満たしたため、タイミングを逃す事となりますか？
> > Ａ：タイミングを逃しません。
> > 　　チェーン１の効果の処理が終了した後、《ＢＦ－蒼炎のシュラ》の効果が発動します。(14/10/19)
> > http://yugioh-wiki.net/index.php?%A1%D4%A5%AC%A5%AC%A5%AC%A5%B6%A5%E0%A5%E9%A5%A4%A1%D5#faq

Another bug/problem I found in Duel.CalculateDamage() is:
If the chain 1 is the effect uses function Duel.SynchroSummon(),Duel.XyzSummon(),Duel.LinkSummon() or Duel.Summon(),the program may not work normally.
But in fact,according KONAMI's answer,the effect of Ritual Summon/Fusion Summon/Synchro Summon/Xyz Summon/Link Summon with using materials or Normal Summon/Set a monster can not activate and resolve in damage step.

**Comment by DailyShana** [comment]
>自己场上存在「螺旋枪杀」，自己的「天翔之龙骑士 盖亚」攻击宣言时，对方在连锁2以上发动「我我我侍」等的效果的场合，**在这组连锁处理完毕时**，进入这次战斗的伤害计算后，「螺旋枪杀」的效果在这个时点发动。
被战斗破坏时代替破坏的场合，和正常的伤害步骤一样，代替破坏适用在效果处理中的伤害计算时，而进行的动作发生这个效果处理完毕时的伤害计算后。
https://ocg-rule.readthedocs.io/zh_CN/latest/c02/%E6%88%98%E6%96%97%E9%98%B6%E6%AE%B5%E6%B5%81%E7%A8%8B.html#id23

**Comment by mallu11** [comment]
> > 自己场上存在「螺旋枪杀」，自己的「天翔之龙骑士 盖亚」攻击宣言时，对方在连锁2以上发动「我我我侍」等的效果的场合，**在这组连锁处理完毕时**，进入这次战斗的伤害计算后，「螺旋枪杀」的效果在这个时点发动。
> > 被战斗破坏时代替破坏的场合，和正常的伤害步骤一样，代替破坏适用在效果处理中的伤害计算时，而进行的动作发生这个效果处理完毕时的伤害计算后。
> > https://ocg-rule.readthedocs.io/zh_CN/latest/c02/%E6%88%98%E6%96%97%E9%98%B6%E6%AE%B5%E6%B5%81%E7%A8%8B.html#id23

Sorry,I was wrong.The chain 1 is also in the Damage calculation too(Maybe bad understanding causes this.).
But another problem is existing.

**Comment by DailyShana** [comment]
open different problem in different issue

**Comment by DailyShana** [comment]
>这类效果处理完毕时，进入伤害计算后，进行各种伤害计算后不入连锁的处理，并开始处理剩余的连锁，整个连锁处理完毕后，伤害计算后发动的效果和满足条件的诱发类效果组成连锁发动并处理，再进入伤害步骤结束时。
https://ocg-rule.readthedocs.io/zh_CN/latest/c02/%E6%88%98%E6%96%97%E9%98%B6%E6%AE%B5%E6%B5%81%E7%A8%8B.html#id23

after chain solving of `Duel.CalculateDamage` in chain 2, first resolve effects **that do not form a chain** at _After damage calculation_, then resolve chain 1, after all chains resolved, **activate** the effects at _After damage calculation_ and go to _End of the Damage Step_.

In the current version, no matter a effect form a chain or not, it will resolved after all chains resolved.
