### ISSUE TITLE
BUG: The effect activated by disabled monster won't be disabled if the monster become Xyz material

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2235]
1. Disable _Wind-Up Kitten_ with _Effect Veiler_
2. Activate the effect of _Wind-Up Kitten_
3. Chain _Zenmaiday_, attach _Wind-Up Kitten_ to another Xyz monster
4. The effect of _Wind-Up Kitten_ should be disabled, but it is able to process

I guess it is because the `EFFECT_DISABLE_CHAIN` registered in https://github.com/Fluorohydride/ygopro-core/blob/3ef2b61b6bc10bd6b9211b19e18b548da367441d/processor.cpp#L3844 become not `is_available` because the Xyz material `current.controler == PLAYER_NONE`

**Comment by AndreOliveiraMendes** [comment]
fixing it will be troublesome since changing xyz controler requires Changes on how swap cards works.

**Comment by DailyShana** [comment]
since `chain_id` is unique and has nothing to do with the handler, we can register `EFFECT_DISABLE_CHAIN` to the `game_field` instead of to the handler
