### ISSUE TITLE
BUG: Wrong action when two Crackdown of both player take effect at same time

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2238]
Let's consider this situation: 
![image](https://user-images.githubusercontent.com/13391795/67612112-67500100-f7d2-11e9-9c6e-c38464eb8d27.png)
One player has a monster in extra mzone, another one has a monster in main mzone, both monsters are targeted by _Crackdown_, but _Crackdown_ is disabled by _Royal Decree_
![image](https://user-images.githubusercontent.com/13391795/67612122-8058b200-f7d2-11e9-9723-1c1f64404cb7.png)
If we destroy _Royal Decree_, the control of the two monsters will swap automatically, instead of letting the player select the zone.

**Comment by edo9300** [comment]
The issue here is in the adjust step when "restoring" contorl effects, here https://github.com/Fluorohydride/ygopro-core/blob/master/operations.cpp#L1224 it's using swap as soon as the cound of both player cards that have to be swapped is equal, thus not checking for emzone
