### ISSUE TITLE
How Can I Help?

### ISSUE THREAD

**Issue by AustinMCrane** [Fluorohydride/ygopro#2239]
Hello,

i am curious on how i might be able to help some with development and upkeep with the game. i dont have a lot of industry c++ experience but i did use it a lot in college. i am a fullstack web developer 9-5 but like what your doing and i can imagine help is appreciated?

my discord username is ygosoftwareguy#1514 if you want to chat

**Comment by Zayelion** [comment]
Is the email on your profile correct? I can send you a link to where some of the various groups have gathered and do planning and recruitment. We can explain everything there.

**Comment by AustinMCrane** [comment]
@Zayelion no i would use austin.crane.robotics@gmail.com for personal use
