### ISSUE TITLE
BUG: Duel.SSet return wrong value when you have Left Arm Offering

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2250]
`Duel.SSet` should return the count of operated cards,
but _Left Arm Offering_ will corrupt `game_field->returns.ivalue[0]` , make the return value become 0.

**Comment by DailyShana** [comment]
fixed in Fluorohydride/ygopro-core@cbec781c430c6ea80b418f0908cf8b65c1d77810
