### ISSUE TITLE
remove EFFECT_FLAG_CONTINUOUS_TARGET

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro#2254]
taking equip/continuous target to cards on field of equip/continuous cards cannot be disabled is because it is not part of effect solving
EFFECT_FLAG_CONTINUOUS_TARGET will make operations other than taking target become un-disableable

related: #2201 #1869
Fluorohydride/ygopro-scripts#1270 
Fluorohydride/ygopro-scripts#1234 
Fluorohydride/ygopro-scripts#764 
Fluorohydride/ygopro-scripts#706

**Comment by salix5** [comment]
EFFECT_FLAG_CANNOT_INACTIVATE
效果敘述包含"這個效果的發動不會被無效"
無視一切發動無效

EFFECT_FLAG_CANNOT_DISABLE
效果敘述包含"這個效果不會被無效"
無視一切效果無效

EFFECT_FLAG_CONTINUOUS_TARGET
持續成為對象的魔法陷阱卡發動
可以分成
1. operation內只有建立對象
即使無效時也應該照常執行operation
2. operation內包含其他動作
operation內可以分成正常及無效時的狀況執行不同動作

**Comment by DailyShana** [comment]
one idea:
## new process of chain solving during activation of  equip/continuous card
### signiture of operation function
```lua
function op(e,tp,eg,ep,ev,re,r,rp,remain)
    if remain then
        Duel.Equip(...)
        return
    end
    --other operation, if exists
end
```
in practice, for most case, just written in this way
```lua
function op(e,tp,eg,ep,ev,re,r,rp,remain)
    if not remain then return end
    Duel.Equip(...)
    --same as before
end
```
### the process of excute operation
first execute operation with `op(e,tp,eg,ep,ev,re,r,rp,true)`
then if effect not disabled, execute operation with `op(e,tp,eg,ep,ev,re,r,rp,nil)`

### compatibility
use lua debug interface to check the parameter count of operation function, solve chain as normal when the parameter count is 8

**Comment by mercury233** [comment]
it is a good idea to use aux to do this

**Comment by DailyShana** [comment]
Taking equip target should not be executed during EVENT_CHAIN_SOLVING, `enable_field_effect(true)` is called for the equip spell. This will cause some problems in certain situation.
