### ISSUE TITLE
cards that can be only special summoned by specific cards

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro#2259]
_Serial Spell_ can not be chained to _Dark Fusion_ to special summon _Evil HERO_ monsters, because they can only be special summoned by _Dark Fusion_ and the card name of _Serial Spell_ is not _Dark Fusion_.
It seem that we can add a card code check in the scripts of _Evil HERO_ cards, but there is a card called _Dark Calling_ which can fusion summon monsters as if they are summoned by _Dark Fusion_.

**Comment by edo9300** [comment]
Better add a Duel.GetReasonEffect and then check that in the condition of those monsters, in the case of cards summoned with dark fusion, they'd check for the reason effect handler to have dark fusion code. Anyways, are there any specific rulings regarding this scenario?

**Comment by DailyShana** [comment]
> Better add a Duel.GetReasonEffect and then check that in the condition of those monsters, in the case of cards summoned with dark fusion, they'd check for the reason effect handler to have dark fusion code.

This can be done easily, see script of CNo.88

**Comment by edo9300** [comment]
Hmm, i think that making it more generic might be better in the long run (GetReasonEffect is still a function that might be useful in some scenarios tho)

**Comment by DailyShana** [comment]
I think this problem can be solved in this way:
_Evil HERO_ fusion monster: replace `st==SUMMON_TYPE_FUSION+0x10` by `se:GetHandler():IsCode(94820406)`
_Dark Fusion_: `c:IsCanBeSpecialSummoned(e,SUMMON_TYPE_FUSION,tp,false,false)`
_Dark Calling_: `c:IsCanBeSpecialSummoned(e,SUMMON_TYPE_FUSION,tp,true,false)`

**Comment by DailyShana** [comment]
I think we can just ignore the illogical ruling and fix the main problem first
