### ISSUE TITLE
BUG: Duel.SpecialSummonStep won't send card to grave immediately if there is no zone 

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2260]
replay: [ss.zip](https://github.com/Fluorohydride/ygopro/files/4018256/ss.zip)

**Comment by DailyShana** [comment]
scripts with
```lua
if Duel.SpecialSummonStep(...) then
    ...
    Duel.SpecialSummonComplete()
end
```
need update to
```lua
if Duel.SpecialSummonStep(...) then
    ...
end
Duel.SpecialSummonComplete()
```

**Comment by DailyShana** [comment]
Maybe we can send `core.ss_tograve_set` to grave after this line
https://github.com/Fluorohydride/ygopro-core/blob/9e4732f6dd0cb0227565459194c61c16f9242a06/processor.cpp#L4297
to avoid mass script change?
