### ISSUE TITLE
Need an XML tag for hover box background

### ISSUE THREAD

**Issue by griimnak** [Fluorohydride/ygopro#2261]
This is an old issue that has been expressed a few times on the forums
https://www.ygopro.co/Forum/tabid/95/g/posts/t/8864/Hover-Text-hard-to-read#post53556
https://www.ygopro.co/Forum/tabid/95/g/posts/t/24804/Question-about-skins#post124325

A simple solution would be an XML tag for the hover box background / tooltip hover background.

Changing <EGDC_BUTTON_TEXT a="255" r="30" g="30" b="30" /> is not a good solution because it changes the text color globally

**Comment by DailyShana** [comment]
I think you come to the wrong place. We have no skin support here.
Maybe you can go to https://github.com/edo9300/ygopro

**Comment by griimnak** [comment]
Oops! sorry about that, moving report to edopro
