### ISSUE TITLE
build: use vcpkg to resolve dependencies

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro#2268]
### background
The main hard part of building ygopro is to resolve dependencies, especially on windows platform. Now we can use vcpkg to install dependencies and use them via cmake.

I hope we can depreciate building via premake
### build flow
install dependencies
```
vcpkg install libevent[thread] freetype[core] lua[cpp] sqlite3 irrlicht[unicode]
# add --triplet x86-windows-static on windows
# use --overlay-ports=<path> to use modified version of irrlicht
# cache [vcpkg root]/installed folder on CI
```
use tool chain file to build via cmake
```
# out-of-source build
mkdir build && cd build 

# Linux
# generate make file
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=[vcpkg root]/scripts/buildsystems/vcpkg.cmake -G "Unix Makefiles" ..  
# build
cmake --build .

# Windows
# generate visual studio project
# to target WinXP, add -T "v141_xp"
cmake -DCMAKE_TOOLCHAIN_FILE=[vcpkg root]\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 15 2017" ..
# build
cmake --build . --config Release
# or open \build\ygopro.sln to build
```

**Comment by kevinlul** [comment]
Are you looking to use a similar approach to EDOPro?

**Comment by DailyShana** [comment]
> Are you looking to use a similar approach to EDOPro?

installing packages in vcpkg is similar but use cmake to build the project

**Comment by kevinlul** [comment]
I have some half-done CMakeLists on a branch for the client and the core is already CMake and independent.

**Comment by ChuanJianHua** [comment]
how do I use it?  It seems that needs some folders, but not in the branch
