### ISSUE TITLE
BUG: The extra deck will always be public after using Duel.ConfirmCards

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2269]
Example: You can see what cards are be banished by _Pot of Indulgence_ if you used _Ghost Reaper & Winter Cherries_ to confirm the extra deck of opponent.

Should we add `Duel.ShuffleExtra` to all cards which confirms extra deck, or do this automatically in ocgcore?

**Comment by DailyShana** [comment]
As `Duel.ShuffleHand` is added for effects that comfirming cards in hand, just adding `Duel.ShuffleExtra` is enough
