### ISSUE TITLE
Build error  LNK2038

### ISSUE THREAD

**Issue by ChuanJianHua** [Fluorohydride/ygopro#2276]
error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in CGUIImageButton.obj.
In the last step of the build, I encountered this problem, how can I solve it

**Comment by DailyShana** [comment]
_ITERATOR_DEBUG_LEVEL is wrongly defined somewhere

**Comment by ChuanJianHua** [comment]
I have not defined _ITERATOR_DEBUG_LEVEL anywhere， I follow the build instructions

**Comment by mercury233** [comment]
you will have to build ygopro in Release mode, or build irrlicht from source code in Debug mode

**Comment by ChuanJianHua** [comment]
yes , I build ygopro in Debug mode , and also build irrlicht by Static Lib Debug mode

**Comment by DailyShana** [comment]
Have you update to the latest commit? see 7680c3c33b00cbdf60097d41432d5fae8474bd37

**Comment by ChuanJianHua** [comment]
yes

**Comment by DailyShana** [comment]
information too little, you need to describe how did you build the project in detail

**Comment by ChuanJianHua** [comment]
I used this tutorial to build https://github.com/Fluorohydride/ygopro/wiki/build

**Comment by DailyShana** [comment]
that page is not written by maintainers of this repository and out of date.

I updated the build process on https://github.com/Fluorohydride/ygopro/wiki#windowsmsvc

If you feel it is complicated, you can try https://github.com/DailyShana/ygopro/tree/rebuild, it is buildable via cmake or premake, but the source code is not up to date

**Comment by ChuanJianHua** [comment]
thank you！It will be helpful to me

**Comment by DailyShana** [comment]
I find that the vcxproj in the irrlicht source define `_ITERATOR_DEBUG_LEVEL=0` even in debug configuration, 
but generally `_ITERATOR_DEBUG_LEVEL` is implicitly defined as `2` in vs projects

If you want to build irrlicht from source, you can remove `_ITERATOR_DEBUG_LEVEL=0` in the debug configuration.
