### ISSUE TITLE
[help me] How to use the APIs in ocgcore to process the game

### ISSUE THREAD

**Issue by OhnkytaBlabdey** [Fluorohydride/ygopro#2291]
I implemented proper card reader and script reader and so on, referring to the single mode source code. And I loaded a puzzle file in `single/` folder successfully. 

But could anyone tell me how to process the game? or how to interact with the APIs.

```
        bool use_default_script_reader = true;
	long pduel = 0;
	byte duel_buff[0x1000] = {0};
	pduel = create_duel(0x12345678u);
	logger->info("duel created");
	set_player_info(pduel, 0, 8000, 0, 0);
	set_player_info(pduel, 1, 8000, 5, 1);
	logger->info("player info set");
	if (!use_default_script_reader)
	{
		set_script_reader((script_reader)hello::script_Reader);
		logger->info("script reader set");
	}
	else
	{
		logger->info("use default script reader");
	}
	initdb();
	set_card_reader((card_reader)card_Reader);
	logger->info("card reader set");
	set_message_handler((message_handler)MessageHandler);
	logger->info("message handler set");

	if (!preload_script(pduel, "single/xx.lua", 0))
	{
		logger->warn("load script failed.");
		end_duel(pduel);
		return 1;
	}
	new_card(pduel, 23571046, 1, 1, 1, 1, 1);
	new_card(pduel, 23571046, 1, 1, 1, 2, 1);
	new_card(pduel, 23571046, 0, 0, 1, 1, 1);
	bool is_continue = true;
	int len = get_message(pduel, (byte *)duel_buff);
	if (len > 0)
	{
		for (int i = 0; i < 256; i++)
		{
			printf("%x ", duel_buff[i]);
		}
	}
	start_duel(pduel, 0);
	process(pduel);
	int ct = query_field_count(pduel, 1, 0xff);
	end_duel(pduel);
	closedb();
	return 0;
```

above is some of my codes.

> a3 14 0 e6 96 b0 e6 89 8b e9 99 aa e7 bb 83 e4 b8 93 e7 94 a8 41 49 0 a2 4 64 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 6 4 1 0 1 0 b0 36 0 0 0 
> 1 4 0 1 4 0 1 4 0 0 0 0 0 0 1 2 0 0 0 0 0 0 1 0 0 0 0 0 a4 12 0 e9 bb 98 e8 ae a4 e4 b8 8d e6 b4 97 e7 89 8c ef bc 81 0 0 0 0 0

here's some of the bits in the buffer, I could figure out that it stored the AI's name, but I couldn't analyze more referring to `SingleMode::SinglePlayAnalyze`.

thanks for help. 🤣

**Comment by DailyShana** [comment]
see https://github.com/Fluorohydride/ygopro/blob/2acbb94664d8e1abbb2acd45ea0fe654e84f61da/gframe/single_mode.cpp#L118-L126

**Comment by DailyShana** [comment]
when `process(pduel)` returns, the return value result has two parts:

- `result & 0xffff` is the length of buffer sent by ocgcore, then use `get_message` to get it. 

- `flag = result >> 16` is to indicate whether to continue to call process(pduel), 
if `flag == 2`, it means the duel is end. 
if `flag == 1`, it means ocgcore is waiting for player's response to continue to duel. eg, `MSG_SELECT_CARD`. use `set_responseb` to send response buffer to ocgcore. The structure of response buffer depends on the type of `MSG_*`

**Comment by OhnkytaBlabdey** [comment]
thanks for help 😄
