### ISSUE TITLE
Archlinux build error, undefined reference to lua_*

### ISSUE THREAD

**Issue by BlindingDark** [Fluorohydride/ygopro#2298]
Some error messages
```
/usr/bin/ld: ../lib/libocgcore.a(scriptlib.cpp.o): in function `scriptlib::check_param_count(lua_State*, int)':
scriptlib.cpp:(.text+0x2ae): undefined reference to `lua_gettop(lua_State*)'
/usr/bin/ld: scriptlib.cpp:(.text+0x2d8): undefined reference to `luaL_error(lua_State*, char const*, ...)'
/usr/bin/ld: ../lib/libocgcore.a(scriptlib.cpp.o): in function `scriptlib::check_action_permission(lua_State*)':
scriptlib.cpp:(.text+0x325): undefined reference to `luaL_error(lua_State*, char const*, ...)'
```

```
➜ readelf -Ws /usr/lib/liblua5.3-c++.so | grep lua_gettop               
   192: 0000000000008010    27 FUNC    GLOBAL DEFAULT   15 lua_gettop@@LUA_5.3
```

I tried using .so file from ubuntu deb package, tried to compile lua by myself, and also tried changing to lua5.2 (according to #2078), and I get the same error message.

**Comment by DailyShana** [comment]
seems not find the place of the lua library

try to use cmake, following https://github.com/Fluorohydride/ygopro/wiki#linux
it will raise error if some library is not found during configuration.

also lua library must be built as c++, with name liblua5.3-c++ or liblua-c++

**Comment by BlindingDark** [comment]
> try to use cmake

The above error was printed by cmake

> must be built as c++

I tried both lua and lua-c++ and got the same error result.

**Comment by DailyShana** [comment]
to build lua as c++, try the following
```
wget -O - https://www.lua.org/ftp/lua-5.3.5.tar.gz | tar zfx -
cd lua-5.3.5
sed -i '9c CC= g++' src/Makefile
sed -i '22c MYCFLAGS=-x c++' src/Makefile
sed -i '31c LUA_A=	liblua5.3-c++.a' src/Makefile
sed -i '44c TO_LIB= liblua5.3-c++.a' Makefile
sudo make linux install
```
tested on Ubuntu

**Comment by BlindingDark** [comment]
Thanks! After compiling lua according to your method, this way can succeed
```
premake4 gmake
make -Cbuild
```
but use `cmake` will cause the following error
```
/usr/bin/ld: CMakeFiles/ygopro.dir/CGUIImageButton.cpp.o:(.data.rel.ro._ZTIN3irr3gui15CGUIImageButtonE[_ZTIN3irr3gui15CGUIImageButtonE]+0x10): undefined reference to `typeinfo for irr::gui::CGUIButton'
/usr/bin/ld: CMakeFiles/ygopro.dir/CGUIImageButton.cpp.o:(.data.rel.ro._ZTCN3irr3gui15CGUIImageButtonE0_NS0_10CGUIButtonE[_ZTVN3irr3gui15CGUIImageButtonE]+0x18): undefined reference to `typeinfo for irr::gui::CGUIButton'
/usr/bin/ld: CMakeFiles/ygopro.dir/CGUIImageButton.cpp.o:(.data.rel.ro._ZTCN3irr3gui15CGUIImageButtonE0_NS0_10CGUIButtonE[_ZTVN3irr3gui15CGUIImageButtonE]+0x1f0): undefined reference to `typeinfo for irr::gui::CGUIButton'
/usr/bin/ld: CMakeFiles/ygopro.dir/CGUIImageButton.cpp.o:(.data.rel.ro._ZTCN3irr3gui15CGUIImageButtonE0_NS0_10CGUIButtonE[_ZTVN3irr3gui15CGUIImageButtonE]+0x228): undefined reference to `typeinfo for irr::gui::CGUIButton'
```

Thanks for your guidance! 😄️

**Comment by DailyShana** [comment]
> but use `cmake` will cause the following error
> 
> ```
> /usr/bin/ld: CMakeFiles/ygopro.dir/CGUIImageButton.cpp.o:(.data.rel.ro._ZTIN3irr3gui15CGUIImageButtonE[_ZTIN3irr3gui15CGUIImageButtonE]+0x10): undefined reference to `typeinfo for irr::gui::CGUIButton'
> /usr/bin/ld: CMakeFiles/ygopro.dir/CGUIImageButton.cpp.o:(.data.rel.ro._ZTCN3irr3gui15CGUIImageButtonE0_NS0_10CGUIButtonE[_ZTVN3irr3gui15CGUIImageButtonE]+0x18): undefined reference to `typeinfo for irr::gui::CGUIButton'
> /usr/bin/ld: CMakeFiles/ygopro.dir/CGUIImageButton.cpp.o:(.data.rel.ro._ZTCN3irr3gui15CGUIImageButtonE0_NS0_10CGUIButtonE[_ZTVN3irr3gui15CGUIImageButtonE]+0x1f0): undefined reference to `typeinfo for irr::gui::CGUIButton'
> /usr/bin/ld: CMakeFiles/ygopro.dir/CGUIImageButton.cpp.o:(.data.rel.ro._ZTCN3irr3gui15CGUIImageButtonE0_NS0_10CGUIButtonE[_ZTVN3irr3gui15CGUIImageButtonE]+0x228): undefined reference to `typeinfo for irr::gui::CGUIButton'
> ```

this is probably `-fno-rtti` is missing in cmake

**Comment by IntinteDAO** [comment]
@DailyShana I have this problem also and -fno-rtti don't fix it

```
cmake -fno-rtti -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
```

**Comment by Frefreak** [comment]
For future visitors, this is what's working for me:

1. First build lua-5.3.5 as comment above

2. change path accordingly:
```sh
cmake -DLUA_INCLUDE_DIR=../lua-5.3.5/src -DLUA_LIBRARY=../lua-5.3.5/src/liblua5.3-c++.a -DCMAKE_CXX_FLAGS="-fno-rtti" -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
```
3. copy ygopro to root, grab a cards.cdb, change **system.conf** etc... (read error.log)

**Comment by IntinteDAO** [comment]
@Frefreak Thanks, I fix it already
https://github.com/IntinteDAO/Summoned-Monsters/blob/master/build/ygopro.build
