### ISSUE TITLE
Should we deprecate this code and switch to maintaining Edopro

### ISSUE THREAD

**Issue by QXqLash** [Fluorohydride/ygopro#2316]
当前不可修复和不可维护的代码库的最佳解决方案是合并edopro并从那里开始。 Current code base is unfixable and non maintainable best solution is to merge edpro and start from there . I have a team of 5- 10 people who want to contribute as extra credit for college but only if we drop the current code base and switch to edopro.

**Comment by mercury233** [comment]
Nobody here can stop you to contribute to edopro

**Comment by QXqLash** [comment]
[![](https://api.gh-polls.com/poll/01EFXSVHKX9Y3QP28THC88AT89/Yes)](https://api.gh-polls.com/poll/01EFXSVHKX9Y3QP28THC88AT89/Yes/vote)

**Comment by QXqLash** [comment]
[![](https://api.gh-polls.com/poll/01EFXSVHKX9Y3QP28THC88AT89/Yes)](https://api.gh-polls.com/poll/01EFXSVHKX9Y3QP28THC88AT89/Yes/vote)
[![](https://api.gh-polls.com/poll/01EFXSVHKX9Y3QP28THC88AT89/No)](https://api.gh-polls.com/poll/01EFXSVHKX9Y3QP28THC88AT89/No/vote)

**Comment by QXqLash** [comment]
https://medium.com/madhash/what-to-do-when-youve-inherited-dysfunctional-code-e09822656b3a

**Comment by QXqLash** [comment]
@edo9300

**Comment by DyXel** [comment]
As @edo9300 and I have said several times, in order for that to happen upstream would need to change the license to AGPL, something which i think is very unlikely to happen (at least for the core it is). Contributors upstream have their own issues to deal with while we focus on minor inconveniences and hardly work on new features (who would want to with this ball of spaghetti? being honest), we have done several changes that are incompatible with upstream and i think that even if everybody agreed to merge to upstream, it would probably cause more issues than what it would actually solve (not for our side, but i heard upstream and koishipro are actually very popular in china).

I agree that ygopro in its current state is very "dysfunctional" and ugly and i would love for our code to be used as a baseline for a refactoring, but realistically speaking i think its not happening, in fact, i think its beyond help at this point. Thats why i decided long ago to rewrite most of it from scratch, which is what i have been doing for months now, very slowly, but im not in a race with anybody so i dont really care that much.

As a parting message, like mercury said, you are always welcome to open PRs in our fork, dunno if they will count or not towards your college score, but the option is there.
