### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by egycno** [Fluorohydride/ygopro#2324]
I am a beginner in programming especially in C ++, however I liked this project very much and wanted to know how its files work and the tasks that link them together, such as the dueling system, and to develop a new version such as ygopro2 and edopro, unfortunately I did not find any useful resources for that, and I could not Understand the codes written in most files.

**Comment by 1912193931** [comment]
do you know how to build it？

**Comment by OhnkytaBlabdey** [comment]
maybe you can refer to the wiki page of this repo, there is a tutorial. [Wiki-build](https://github.com/Fluorohydride/ygopro/wiki/build)
