### ISSUE TITLE
BUG: Advanced Heraldry Art vs There Can Be Only One

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2338]
If _Advanced Heraldry Art_ summon 2 monsters but 1 monster is sent to grave by _There Can Be Only One_, the Xyz summon still process and the Xyz material will be used from grave.
What is more, if _Pendulum XYZ_ is used and the monsters are originally different level, the Xyz summon won't be proceed but `core.limit_xyz` wont be reset, which will affect the next rule summon.

**Comment by mallu11** [comment]
There is one more like this:
If a Xyz Monster equipped with _**Stoic Challenge**_ is used to Xyz Summon _**Negalogia AA-Zeus**_, the Xyz Monster will be destroyed by _**Stoic Challenge**_ and Xyz Summon _**Negalogia AA-Zeus**_ and the Xyz Material will be used from grave.

**Comment by chronogenexx** [comment]
ref:
> https://yugioh-wiki.net/index.php?%A1%D4%B9%E2%C5%F9%CC%E6%BE%CF%BD%D1%A1%D5#faq
> Ｑ：フィールドに《コトダマ》が存在し、このカードの効果で同名の紋章獣を特殊召喚した場合、《コトダマ》の効果でその２体の紋章獣は破壊されますか？
> Ａ：はい、２体の紋章獣は《コトダマ》の効果で破壊され、**エクシーズ召喚を行う事ができません**。(15/05/30)

> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22901&keyword=&tag=-1
> 例えば、手札から鳥獣族の「武神器－ハバキリ」と、墓地から獣族の「武神器－ヘツカ」を選んだ場合であれば、それらを特殊召喚し、『その２体のみを素材としてXモンスター１体をX召喚する』によって、エクシーズ召喚を行う事ができますが、手札と墓地から鳥獣族の「武神器－ハバキリ」を選んだ場合は、その２体は特殊召喚されますが、「センサー万別」の効果が適用されていますので、どちらか1体の「武神器－ハバキリ」は墓地へ送らなければならず、『その２体のみを素材としてXモンスター１体をX召喚する』によって、**エクシーズ召喚を行う事はできません**。

https://github.com/Fluorohydride/ygopro-core/blob/master/processor.cpp#L5000
Because of `EVENT_ADJUST` doesn't raise.
So, we would call `EVENT_ADJUST` or `adjust_all`.
