### ISSUE TITLE
The engine has not been updated

### ISSUE THREAD

**Issue by wrenchonline** [Fluorohydride/ygopro#2340]
Using the new script, I found that the [IsSummonCancelable](https://github.com/Fluorohydride/ygopro-core/commit/1ebab3c0b6e118a3194617c0a60ad0e8a65143b9) function was missing

**Comment by mercury233** [comment]
Please report at where you download your ygopro, or build ygopro on yourself, or follow a redistributable version which is keep up to date with upstream.
