### ISSUE TITLE
BUG: AI mode freezes when declaring card names

### ISSUE THREAD

**Issue by salix5** [Fluorohydride/ygopro#2347]
@mercury233 
![unknown](https://user-images.githubusercontent.com/2851577/119136307-149fff00-ba72-11eb-995b-164c76c42d17.png)
When AI_Witchcraft activates 抹殺の指名者, the process freezes instantly.
Maybe there are some problems in declaring card names.

Tested in the executable build with current version of ygopro and ocgcore.

**Comment by mercury233** [comment]
Which version of windbot are you using? Is it after https://github.com/IceYGO/windbot/commit/f6eae0a7b337725e82b98f3801221a92f87bc204 ?

**Comment by salix5** [comment]
The latest version from
http://ygocore.ys168.com/

>  Is it after IceYGO/windbot@f6eae0a ?  

I am not sure

**Comment by mercury233** [comment]
Is the bot updated to the version with self pick deck feature?

**Comment by salix5** [comment]
Yes

**Comment by salix5** [comment]
It is my problem.
It works in the latest version.
