### ISSUE TITLE
Migrate to GPL-2.0-or-later

### ISSUE THREAD

**Issue by nfitzen** [Fluorohydride/ygopro#2351]
I opened a related issue at [edo9300#209](https://github.com/edo9300/edopro/issues/209), relating to potential licensing issues of the project, and wanted to open an issue here regarding GNU GPL versions. The gist is that, as it stands, this project appears to be licensed under [`GPL-2.0-only`], but this is incompatible with EDOPro, which requires the cross-compatibility between [`GPL-2.0-or-later`] and [`AGPL-3.0-or-later`].

Would it be possible to relicense the project under [`GPL-2.0-or-later`]? (Or at least clarify that is the case.) It'd ensure better compatibility with other projects that have different needs.

Disclaimer: <span title="I am not a lawyer">IANAL</span>, and this is not legal advice.

[`GPL-2.0-only`]: https://spdx.org/licenses/GPL-2.0-only.html "GNU General Public License v2.0 only"
[`GPL-2.0-or-later`]: https://spdx.org/licenses/GPL-2.0-or-later.html "GNU General Public License v2.0 or later"
[`AGPL-3.0-or-later`]: https://spdx.org/licenses/AGPL-3.0-or-later.html "GNU Affero General Public License v3.0 or later"

**Comment by mercury233** [comment]
`¯\_(ツ)_/¯` @Fluorohydride

**Comment by Yuzurisa** [comment]
A bit disagree.
Their EDOPro should move the license to fit us, rather than we change the license to fit them.

**Comment by nfitzen** [comment]
@Yuzurisa if ocgcore wasn't intended to be used in software with proprietary/more restrictive licenses, then why was it licensed under the Expat/MIT license? I believe the intent of EDOPro's licensing is to ensure server software remains free. However, they probably should've licensed the client under [`GPL-2.0-or-later`] and only licensed ocgcore under [`AGPL-3.0-or-later`], taking advantage of the combination clause in &sect; 14 of both licenses. So, I agree, they absolutely should change their license; however, this does not change the incompatibility between both client programs. 

Ultimately, changing to [`GPL-2.0-or-later`] could also help with a license upgrade in the future, should this project wish to do so.

[`GPL-2.0-or-later`]: https://spdx.org/licenses/GPL-2.0-or-later.html
[`AGPL-3.0-or-later`]: https://spdx.org/licenses/AGPL-3.0-or-later.html
