### ISSUE TITLE
Propose: Change the format of new scripts

### ISSUE THREAD

**Issue by salix5** [Fluorohydride/ygopro#2367]
@mercury233 
(Inspired by the format of edopro)
In order to make the conversion of pre-released id to official id easier, maybe we can change the format of pre-released scripts into something like this.

```lua
local s,id=GetID()
local offset=100
function s.initial_effect(c)
	--
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetCountLimit(1,id)
	--
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(id,1))
	e2:SetCountLimit(1,id+offset)
	--
	local e3=Effect.CreateEffect(c)
	e3:SetDescription(aux.Stringid(id,2))
	e3:SetCountLimit(1,id+2*offset)
end
```

When the card releases, we only need to change:
1. the value of `offset`

**Comment by pyrQ** [comment]
Why not just make it a function (like us) and eliminate having to change the local value of `id` as well?

**Comment by edo9300** [comment]
You could use the GetID function we were using before I integrated this behaviour in the core
```lua
function GetID()
    local str=string.match(debug.getinfo(2,'S')['source'],"c%d+%.lua")
    str=string.sub(str,1,string.len(str)-4)
    local scard=_G[str]
    local s_id=tonumber(string.sub(str,2))
    return scard,s_id
end
```
This will remove the need to manually set the id as it'll take it from the filename instead. (It will work on the assumptions that all the card scripts are in the format cXXXXX.lua.)

**Comment by purerosefallen** [comment]
Hey, did you learn the format from those custom card community?
Those people submit PRs of pre-release scripts in this format, and all rejected.

**Comment by edo9300** [comment]
Yes, (we don't have it in the aux library tho, as it is easier to use as plain global function)

**Comment by salix5** [comment]
How about:
```lua
local s,id=GetID()
local offset=100
function s.initial_effect(c)
	--
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetCountLimit(1,id)
	--
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(id,1))
	e2:SetCountLimit(1,id+offset)
	--
	local e3=Effect.CreateEffect(c)
	e3:SetDescription(aux.Stringid(id,2))
	e3:SetCountLimit(1,id+2*offset)
end
```
pre-released: offset=100
released: offset=1

**Comment by purerosefallen** [comment]
> ```lua
> _G[str]={}
> ```

Why `_G[str]={}` ?
It would break the metatable relation of "CTable" and Card object.

**Comment by salix5** [comment]
I didn't notice that the metatable is already set.
Sorry.

**Comment by mercury233** [comment]
why not use `o` instead of `offset` to make it shorter

**Comment by salix5** [comment]
> why not use `o` instead of `offset` to make it shorter

Done.
Thank you.
