### ISSUE TITLE
Error: 'mt19937' does not name a type

### ISSUE THREAD

**Issue by YuquanW** [Fluorohydride/ygopro#2369]
This error appeared when I was running the command ```cmake --build .```given in Wiki on my Ubuntu 20.04.3 LTS. The details are as follows:

```
[ 52%] Building CXX object gframe/CMakeFiles/ygopro.dir/client_card.cpp.o
In file included from /path/to/ygopro/gframe/game.h:6,
                 from /path/to/ygopro/gframe/client_card.cpp:4:
/path/to/ygopro/gframe/deck_con.h:81:2: error: ‘mt19937’ does not name a type
   81 |  mt19937 rnd;
      |  ^~~~~~~
make[2]: *** [gframe/CMakeFiles/ygopro.dir/build.make:102：gframe/CMakeFiles/ygopro.dir/client_card.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:163：gframe/CMakeFiles/ygopro.dir/all] Error 2
make: *** [Makefile:84：all] Error 2
```

I have tried to add

```
#include <iostream>
#include <random>
using namespace std;
```

in the header of /path/to/ygopro/gframe/deck_con.h and add

```
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
```

in /path/to/ygopro/CMakeLists.txt, but cmake reports another error.

Could anyone help me with this problem? Thanks.

**Comment by mercury233** [comment]
did you run git pull & git checkout master in the ocgcore submodule?

**Comment by YuquanW** [comment]
> did you run git checkout master & git pull in the ocgcore submodule?

No, I didn't. I just tried these commands. Git checkout master showed my branch was consistent with "origin/master" and git pull showed already up-to-date.

```
$ git checkout master
之前的 HEAD 位置是 b75bb91 add Card.GetCurrentScale (#360)
切换到分支 'master'
您的分支与上游分支 'origin/master' 一致。
$ git pull
已经是最新的。
```

**Comment by mercury233** [comment]
那就可以继续编译了
then you can make it again

**Comment by YuquanW** [comment]
> 那就可以继续编译了
> then you can make it again

Thank you, the problem have been solved.
