### ISSUE TITLE
Feature: Make Duel.SendtoDeck send cards to bottom when no shuffle mode is on

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2371]
Now it send cards to deck top, and mark the deck need to be shuffled. Some players complain about that behavior because them want to create some "drafted" duel video but can't control the draw after sending cards to deck. In addition, cards like _Magical Mallet_ won't work.

If we change the behavior, it may break some puzzles, so we may need to add a switch to the puzzle mode.

**Comment by purerosefallen** [comment]
Why not sending cards to bottom at all times?
