### ISSUE TITLE
SECURITY ISSUE: vulnerables about `package.loadlib` and other `package` functions

### ISSUE THREAD

**Issue by Yuzurisa** [Fluorohydride/ygopro#2378]
The following code in either card script or puzzle script can access `os` or other disabled libs.

```lua
Debug.Message(os)
package.loadlib('/usr/lib/x86_64-linux-gnu/liblua5.3-c++.so', 'luaL_openlibs')
Debug.Message(l)
l()
Debug.Message(os)
Debug.Message(os.date())
```
The above example runs on YGOPro compiled on Debian. with `liblua5.3-dev` from Debian official source, giving the following output.

![图片](https://user-images.githubusercontent.com/48149916/133918573-04378533-0963-41b0-9694-d49daf451432.png)

In fact, the following code gives similar result, but without use of `package.loadlib`.

```lua
package.cpath="/usr/lib/x86_64-linux-gnu/liblua5.3-c++.so"
Debug.Message(os)
my_os=require('os')
Debug.Message(my_os)
Debug.Message(my_os.date())
```

This may lead to card scripts attacking the server, as well as other security issues. Should we, disable most libs unrelated to YGOPro cards functioning, and keep the Lua lib as tiny as possible?

**Comment by Yuzurisa** [comment]
I think the following Lua libs should all be disabled, for not required by YGOPro card scripting, and leading to security problems.

* `os`
* `io`
* `package` for loading untrusted binaries from anywhere of the system.
* `coroutine` which may interrupt threading of ocgcore. Some people build *server crasher* by this lib.
* `debug` not very useful on card scripting, but still security-problematic for accessing data which shouldn't be accessible by card script.

In addition, to avoid those people using script loader to read sensitive files from system, we can disable the following as well.

* `require` reads both Lua scripts and dynamic libs.
* `dofile` `loadfile` reads Lua scripts.

And we may provide a specific script-reading function `Duel.LoadScript`, for safe script loading. It would also make use of `script_reader` for better script loading as well.

**Comment by salix5** [comment]
@Yuzurisa 
How to disable specific Lua libraries?

**Comment by salix5** [comment]
fixed in
Fluorohydride/ygopro-core@ee3f6ebe429c044d2bf644d88d3857d8c028314a
Fluorohydride/ygopro-core@fa5440d1055513785b6f188ddc0c3abc5d4aa125
Thank you!

Should `coroutine` be disabeld as well?

**Comment by salix5** [comment]
@Yuzurisa 
https://github.com/Fluorohydride/ygopro-core/commit/b419ee8ef49ab143a152f715abcac3b03d9ea09e
Totally fixed
Thank you!
