### ISSUE TITLE
Feature: search cards with ADVANCED searching options by code

### ISSUE THREAD

**Issue by luoxueyasha** [Fluorohydride/ygopro#2381]
Koishipro supports searching with regular expressions, but I don't think that's enough for morden yugioh.  
Want some advanced searching options in game, as I can find the TYPE/ATTRIBUTE/TRIBE/.... by sql/pesudocode. (or if already supports, document link plz)  
  
eg.   
search legal condition cards for **天威之龙拳圣/天威の龍拳聖/Draco Masters of the Tenyi/23935886**, effect ② : 
`where having TYPE_MONSTERS and not having TYPE_EFFECT` (pesudo-sql, guess `TYPE_MONSTERS - TYPE_EFFECT` will be better?)

search legal target cards for **光界王战 玛多尔女王/光の王 マルデル/Mardel, Generaider Boss of Light/13903402**, effect ② :
`(c:IsSetCard(0x134) or c:IsRace(RACE_PLANT)) and not c:IsCode(13903402)` (lua)

Though real coding languages may cause security problems...

**Comment by purerosefallen** [comment]
~~Use sqlite and do them by yourself~~
