### ISSUE TITLE
BUG: STATUS_FORBIDDEN is applied before the announced name of Prohibition is updated

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2383]
1. Activate Prohibition, announce `name1`, the card name1 will be forbidden
2. Return Prohibition to hand, the card name1 will be usable
3. Activate Prohibition again, announce `name2`, both name1 and name2 will be forbidden

<details><summary>test puzzle</summary>

```lua

Debug.SetAIName("Prohibition")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,5)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

Debug.AddCard(64734921,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(91188343,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(43711255,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(42703248,0,0,LOCATION_HAND,0,POS_FACEDOWN)

Debug.ReloadFieldEnd()
aux.BeginPuzzle()
```

</details>

If you make `c43711255.bantg` to log `fcode`, you will find the program will try to update disabled status of cards before `fcode` is updated to `name2`.

**Comment by salix5** [comment]
Is this issue fixed now?

**Comment by mercury233** [comment]
fixed by workaround

**Comment by salix5** [comment]
fixed in https://github.com/Fluorohydride/ygopro-scripts/pull/1838
