### ISSUE TITLE
BUG: Zexal Alliance cannot activate if Dinoruffia Stealthbegia has on the field

### ISSUE THREAD

**Issue by chronogenexx** [Fluorohydride/ygopro#2397]
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=23448&keyword=&tag=-1
> その場合でも「ダイノルフィア・ステルスベギア」の『①』の『自分のLPが２０００以下である限り、自分は「ダイノルフィア」モンスターの効果及び、罠カードを発動するために払うLPが必要なくなる』効果によって、ライフポイントを払わずに「ゼアル・アライアンス」を発動できます。

in database, if Dinoruffia Stealthbegia has on the field, Zexal Alliance can activate.
but, if Dinoruffia Stealthbegia has on the field, Zexal Alliance cannot activate.
this problem happen because of https://github.com/Fluorohydride/ygopro-core/commit/16be11adb9cc82390d57d98f669e096c04f145f1#diff-9c303fc29f7374041f51201c6208b8672f77cf296e89986d7ae02da80c451f86R2285.

**Comment by mercury233** [comment]
let us assume _Number S39: Utopia Prime_ vs _Brain Research Lab_ or _Telekinetic Charging Cell_ should have same ruling
