### ISSUE TITLE
BUG: Puppet King and Puppet Queen can activate effect if monster sent to hand by Bingo Machine, Go!!!

### ISSUE THREAD

**Issue by chronogenexx** [Fluorohydride/ygopro#2400]
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=23463&keyword=&tag=-1
> Question
> 「ビンゴマシーンGO！GO！」の効果によって相手が「青眼の白龍」３枚を見せ、ランダムに１枚を手札に加えた場合、自分は「パペット・クィーン」の『①』の『相手がドロー以外の方法でデッキからモンスターを手札に加えた時に発動できる』効果を発動できますか？
> Answer
> **発動できません**。 

in database, if monster sent to hand by Bingo Machine, Go!!!, Puppet King and Puppet Queen cannot activate effect.
but, if monster sent to hand by Bingo Machine, Go!!!, Puppet King and Puppet Queen can activate effect.

**Comment by mercury233** [comment]
Maybe we can add something like `STATUS_TO_HAND_WITHOUT_CONFIRM` to the card before it is sent to hand, in the script of Bingo Machine, and check that status in the script of Puppet King, and remove that status any time any card leaves hand (in `field::remove_card`)

**Comment by mercury233** [comment]
need ruling about _Respect Play_ in this situation

**Comment by chronogenexx** [comment]
> Q.
> 「相視相殺」の効果でお互いの手札が公開されているターンに、「ビンゴマシーンGO！GO！」の効果によって相手が「青眼の白龍」３枚を見せ、ランダムに１枚を手札に加えた場合、自分は手札の「パペット・キング」の効果を発動できますか？
> A.
> ご質問の場合、「パペット・キング」の『①』の効果を発動できません。
