### ISSUE TITLE
BUG: Deck top don't get updated in replay mode after Duel.SortDecktop

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2401]
Replay: [deck top not updated.zip](https://github.com/Fluorohydride/ygopro/files/7653282/deck.top.not.updated.zip)

I have 5 cards in my deck:
![image](https://user-images.githubusercontent.com/13391795/144695993-c830b868-a63f-4b18-be12-788fb1fd0896.png)

I activate _Card Advance_, place _Left Arm of the Forbidden One_ on the top of my deck, then I click the deck in replay mode again, but the deck didn't get updated:
![image](https://user-images.githubusercontent.com/13391795/144696039-9e44d9ff-161d-4062-92d2-9af08987e1fb.png)

After the next draw, the card in hand is correct, but the cards in deck is still wrong (If no other shuffle deck event is triggered).
The _One for One_ disappeared, and I got 2 left arms.
![image](https://user-images.githubusercontent.com/13391795/144696064-d11970fd-ba8f-46b2-bc28-1b340cd497b5.png)

**Comment by mercury233** [comment]
If we add `MSG_SHUFFLE_DECK` to
https://github.com/Fluorohydride/ygopro-core/blob/fa5440d1055513785b6f188ddc0c3abc5d4aa125/processor.cpp#L678-L686

the client will ask for update, but the user will see false shuffling deck.

Should we add a new message such as `MSG_SHUFFLE_DECKTOP` with the count of affected cards in it?

**Comment by edo9300** [comment]
With this approach of sending each move individually, the issue is solved nicely and with a proper animation https://github.com/edo9300/ygopro-core/commit/03e2b2546119e9d35bf0617d84a4e50005369f3e

**Comment by mercury233** [comment]
@edo9300 I think the new sequence of the cards shouldn't be sent to the client, otherwise the player can know whether the card returned by _Raiza the Storm Monarch_ is still on deck top.

**Comment by edo9300** [comment]
@mercury233 that's intentional on my end
