### ISSUE TITLE
Can't pass LUA_USE_APICHECK

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2406]
Build lua with `LUA_USE_APICHECK`, it will fail on
- [x] `api_check(L, idx != 0 && -idx <= L->top - (ci->func + 1), "invalid index");`
when calling `*yield_value = lua_isboolean(rthread, -1) ...` in `interpreter::call_coroutine`

and fail on
- [x] `api_check(L, L->status == LUA_OK, "cannot do calls on non-normal thread");`
when calling `lua_pcall(current_state, param_count, ret_count, 0)` in `interpreter::call_function`

It happen in both lua 5.3 and 5.4.

**Comment by mercury233** [comment]
for the 2nd problem, we are calling lua functions from `current_state` which maybe a yielded lua thread, and lua don't allow this actually: https://www.lua.org/manual/5.4/manual.html#lua_status

**Comment by salix5** [comment]
fixed by https://github.com/Fluorohydride/ygopro-core/pull/582
