### ISSUE TITLE
what means "TP"?

### ISSUE THREAD

**Issue by Reisen1969** [Fluorohydride/ygopro#2411]
There are a lot of "TP" in the source code.
such as 
"TPResult"

**Comment by mercury233** [comment]
For `STOC_SELECT_TP`, it means let the player who won the hand guess (rock paper scissors) to select first to go or second to go.
_I don't know what is the original word too._

For `tp` in `e,tp,eg,ep,ev,re,r,rp`, it means the triggering player of the effect.

**Comment by sjm1327605995** [comment]
I'm guessing it's server to client select turn priority. "Turn Priority" means the right to choose the first or second go. Rounds take precedence. It should mean first strike. Translated into English
