### ISSUE TITLE
BUG: Cyberdark End Dragon will be affected by the effect of Ghost Rabbit at certain condition

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2412]
The opponent used _Monster Reborn_ and summoned _Ghost Ogre & Snow Rabbit_ from my grave.
I activated _Cyberdark End Dragon_, the opponent chained that ghost rabbit.
Then my _Cyberdark End Dragon_ is destroyed, because `re:GetHandlerPlayer()` become **me** when ghost rabbit was sent to my grave.

Should we add `effect->active_player` and `Effect.GetActivatePlayer()` to fix this?

**Comment by salix5** [comment]
Can we use `Effect.GetOwnerPlayer` instead?

**Comment by mercury233** [comment]
It may work but maybe confusing
