### ISSUE TITLE
Ocgcore: Possible Link Zone Bug?

### ISSUE THREAD

**Issue by mrboots123** [Fluorohydride/ygopro#2416]
hello everyone. I'm testing the standalone ocgcore and ran into a possible issue. Scenario: Turn 1 xyz summons to location 0x04 sequence 5. Turn 2 attempts to xyz summon, MSG_SELECT_PLACE returns possible location of sequence 5.  At this point the only way to advance the ocgcore state is to send  buffer(1,0x04,5), any attempt to send the correct zone of buffer(1,0x04,6) results in MSG_RETRY. is this correct?

**Comment by mrboots123** [comment]
including recording of scenario https://jumpshare.com/v/GkBHBFDSHVP9W3K5oynM

**Comment by mercury233** [comment]
The player of white dragon used the left extra monster zone in his view, so the another player must use another extra monster zone, in his view is left zone too.
In other word, the zone you placed _Number 46_ is seq 5 to the white dragon player, seq 6 to the harpie player.

BTW, did you use the old rule on purpose?

**Comment by mrboots123** [comment]
Hi Mercury,I also had that doubt but I was confused since the ocgcore will only accept the buffer of seq 5 for player 2 when it should only accept sequence 6, does this mean it is flipped?.
Also i am using master rule 4:     lib.start_duel(pduel, 0x040000);

**Comment by mrboots123** [comment]
Okay, i think im understanding it now, thank you for clarifying. So if player 2 summons in seq 6 then player one must also summon in his view seq 6
