### ISSUE TITLE
BUG: Can't move card from Pendulum zone to Spell zone

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2421]
`Duel.MoveSequence` won't change the `pzone` status, and `Duel.MoveToField` can't move card to same place.

![image](https://user-images.githubusercontent.com/13391795/155907956-a44a1d89-231b-4359-8948-f94f55d78c81.png)

**Comment by salix5** [comment]
Do you have a replay file or a single mode script?
Thank you!

**Comment by mercury233** [comment]
```lua
Debug.SetAIName("AI")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_PSEUDO_SHUFFLE+DUEL_SIMPLE_AI,5)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

Debug.AddCard(100418201,0,0,LOCATION_HAND,0,POS_FACEUP)
Debug.AddCard(100418205,0,0,LOCATION_HAND,0,POS_FACEUP)
Debug.AddCard(69351984,0,0,LOCATION_HAND,0,POS_FACEUP)
Debug.AddCard(63394872,0,0,LOCATION_HAND,0,POS_FACEUP)
Debug.AddCard(20721928,0,0,LOCATION_HAND,0,POS_FACEUP)

Debug.ReloadFieldEnd()
aux.BeginPuzzle()
```

1. Activate _Shinonome, Priestess of the Valiants_ in the left P zone
2. Activate _Metalfoes Volflame_ in the right P zone
3. Summon _Valiants' Buster - Baron_ to the center M zone
4. Activate _Senet Switch_ in the center S zone, use its effect to move Baron to right.
5. Activate the effect of Baron to move Shinonome to S zone.

Then you can still pendulum summon with Shinonome, or use its P effect to summon it to the M zone.
