### ISSUE TITLE
Cannot compile at arch linux 

### ISSUE THREAD

**Issue by fecet** [Fluorohydride/ygopro#2423]
I follow the guild at wiki but got
```
$ premake5 gmake


** Warning: `configuration` has been deprecated; use `filter` instead (https://premake.github.io/docs/Filters/)
** Warning: the flags value EnableSSE2 has been deprecated and will be removed.
   Use `vectorextensions "SSE2"` instead.
   @C function

** Warning: the flags value Symbols has been deprecated and will be removed.
   Use `symbols "On"` instead
   @C function

** Warning: the flags value OptimizeSpeed has been deprecated and will be removed.
   Use `optimize "Speed"` instead.
   @/home/rok/ygopro/premake4.lua(45)

Error: cannot open ocgcore: No such file or directory
```

**Comment by mercury233** [comment]
https://github.com/mercury233/ygopro/blob/test/.circleci/config.yml

**Comment by fecet** [comment]
> https://github.com/mercury233/ygopro/blob/test/.circleci/config.yml

Thanks your quick reply! I fixed this by `git submodule update --init`, but `make-Cbuild`  got another error:

```
make: Entering directory '/home/rok/ygopro/build'
==== Building ocgcore (debug) ====
==== Building clzma (debug) ====
==== Building cspmemvfs (debug) ====
==== Building ygopro (debug) ====
Linking ygopro
/usr/bin/ld: cannot find -llua5.3-c++: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [ygopro.make:102: ../bin/debug/ygopro] Error 1
make: *** [Makefile:51: ygopro] Error 2
```

**Comment by mercury233** [comment]
just ignore the wiki and cmake and premake4 things, them are outdated, use premake5: https://github.com/Fluorohydride/ygopro/pull/2399 or my fork

**Comment by fecet** [comment]
> just ignore the wiki and cmake and premake4 things, them are outdated, use premake5: #2399 or my fork

Yeah, I'm using premake5 and finish the premake thing(I guess), but encounter error at 'make -Cbuild' or ' make config=release -j$(nproc)', which tell me cannot find 'llua5.3-c++'

I find 'https://github.com/mercury233/ygopro/issues/28' this in your fork, what's the meaning of "install lua of apt" and how to do this?

**Comment by mercury233** [comment]
there is no `lua5.3-c++` in the premake5.lua of my pull request or fork. ~~don't use premake4.lua unless you can handle the `lua5.3-c++` yourself~~

**Comment by fecet** [comment]
> there is no `lua5.3-c++` in the premake5.lua of my pull request or fork. ~don't use premake4.lua unless you can handle the `lua5.3-c++` yourself by building lua in c++ mode and change the lib file name~

I switch to your fork but failed at `premake5` step(In current repo I failed at `make -Cbuild` step), here is my routes:

1. `git clone https://github.com/mercury233/ygopro.git`
2. `git submodule update --init`
3. `premake5 gmake`

And I got `Error: /usr/bin/lua:1: unexpected symbol near '<\127>'`, am I done anything wrong?

**Comment by mercury233** [comment]
https://github.com/premake/premake-core/issues/1783

**Comment by fecet** [comment]
> [premake/premake-core#1783](https://github.com/premake/premake-core/issues/1783)

So this is an upstream error and I can't fix this by myself? Sorry I'm new to all the make stuffs(cmake gcc build make, they are same to me).

**Comment by mercury233** [comment]
there are 2 ways of fix in that link.

**Comment by fecet** [comment]
> there are 2 ways of fix in that link.

OK, I finally fix this by
```
yay -S dos2unix premake
git clone https://github.com/mercury233/ygopro.git
git submodule update --init
curl --retry 5 --connect-timeout 30 --location https://downloads.sourceforge.net/irrlicht/irrlicht-1.8.5.zip | bsdtar -xf-
mv irrlicht-1.8.5 irrlicht
curl --retry 5 --connect-timeout 30 --location https://www.ambiera.at/downloads/irrKlang-64bit-1.6.0.zip | bsdtar -xf-
mv irrKlang-64bit-1.6.0 irrklang
curl --retry 5 --connect-timeout 30 --location https://www.lua.org/ftp/lua-5.4.3.tar.gz | bsdtar -xf-
mv lua-5.4.3 lua
cd irrlicht
unix2dos ../premake/irrlicht/irrlicht.patch
patch --binary -p1 < ../premake/irrlicht/irrlicht.patch
cd ..
cp -r ./premake/* .
cp /usr/bin/premake5 .
./premake5 gmake
cd build
make config=release -j$(nproc)
```
However, I got a crash when I'm trying to run it:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/irrklang/bin/linux-gcc-64/
./bin/release/ygopro
```

The window is just show up a second and closed, here is the output:
```
Irrlicht Engine version 1.8.5
Linux 5.16.11-arch1-1-surface #1 SMP PREEMPT Thu, 24 Feb 2022 13:45:20 +0000 x86_64
Using renderer: OpenGL 4.6.0
NVIDIA GeForce GTX 1060/PCIe/SSE2: NVIDIA Corporation
OpenGL driver version is 1.2 or better.
GLSL version: 4.6
```

**Comment by mercury233** [comment]
download some release of ygopro and get the cards.cdb and pics from there

**Comment by fecet** [comment]
For whom may concerned, one can check `error.log` for missing files and modify `system.conf` font options.

**Comment by marek22k** [comment]
Mhh, I get another error on Arch Linux:
```
$ make config=release
==== Building clzma (release) ====
==== Building cspmemvfs (release) ====
==== Building lua (release) ====
==== Building irrlicht (release) ====
==== Building ocgcore (release) ====
make[1]: *** No rule to make target '../premake/irrlicht/source/Irrlicht/C3DSMeshFileLoader.cpp', needed by '../obj/Release/irrlicht/C3DSMeshFileLoader.o'.  Stop.
make: *** [Makefile:67: irrlicht] Error 2
```

**Comment by marek22k** [comment]
The instructions from fecet seem to work, but only with the fork from mercury233.

**Comment by marek22k** [comment]
@fecet Did you find a fix for `The window is just show up a second and closed, here is the output:`. I have the same bug.

**Comment by mercury233** [comment]
> The instructions from fecet seem to work, but only with the fork from mercury233.

now you can refer to this wiki: https://github.com/Fluorohydride/ygopro/wiki
