### ISSUE TITLE
BUG: The additional effect of Infinite Impermanence apply even if selected monster summoned by Vehicroid Connection Zone

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2432]
Should we add `Card.IsCanBeDisabledByEffect` to fix this and replace `not tc:IsDisabled() and not tc:IsImmuneToEffect(e)`?

**Comment by salix5** [comment]
Yes.
If the target has `EFFECT_CANNOT_DISABLE`, `EFFECT_DISABLE` should not be added to that card.

Example:
魔力の泉
「魔力の泉」は１ターンに１枚しか発動できない。①：相手フィールドの表側表示の魔法・罠カードの数だけ自分はデッキからドローする。その後、自分フィールドの表側表示の魔法・罠カードの数だけ自分の手札からカードを選んで捨てる。このカードの発動後、次の相手ターンの終了時まで、相手フィールドの魔法・罠カードは破壊されず、発動と効果を無効化されない。 

エルシャドール・アプカローネ 
①：このカードが特殊召喚に成功した場合、フィールドの表側表示のカード１枚を対象として発動できる。そのカードの効果を無効にする。

[negate1.zip](https://github.com/Fluorohydride/ygopro/files/8377728/negate1.zip)
Turn 2
1. activate 魔力の泉 
2. activate the 1st effect of エルシャドール・アプカローネ 

Correct: The Field Spell should not be negated.
Now: The Field Spell becomes negated after the effect of 魔力の泉 ends.
