### ISSUE TITLE
请问有没有rush duel的数据库下载地址

### ISSUE THREAD

**Issue by kooriookami** [Fluorohydride/ygopro#2445]
我自己在做一个RD的在线制卡器，https://tools.kooriookami.top/#/rush-duel
想要添加搜索功能，不知道有没有大佬了解rd有没有通用的cdb数据库哈

**Comment by purerosefallen** [comment]
https://code.mycard.moe/mycard/ygopro-rush-duel

**Comment by kooriookami** [comment]
> https://code.mycard.moe/mycard/ygopro-rush-duel

好的感谢大佬~，我看了数据库有简体中文的卡片信息，别的语言像日语这种是没有的嘛

**Comment by purerosefallen** [comment]
暂时是没有维护的，你有兴趣的话是可以自己维护一个贡献给大家呢
