### ISSUE TITLE
VS Compile issue: error LNK2001

### ISSUE THREAD

**Issue by midstreeeam** [Fluorohydride/ygopro#2464]
I was trying to compile it using VS2022, but something went wrong when compling freetype, which gives `LNK2001: unresolved external symbol _ft_svg_renderer_class`.
My freetype version is 2.11.1, which is the recommended version.
I think it might be some problems on my VS setting but I can not find it.
I don't know have anyone met this problem before, or do I have some other options to compile the game on windows.
![image](https://user-images.githubusercontent.com/105056239/195037109-cdea583a-ad4a-4af5-ab11-8b770367cbdb.png)
I will be very appreciate if someone can help me on this.

**Comment by mercury233** [comment]
你的工程文件是怎么生成的，是不是没有全部用premake

**Comment by mercury233** [comment]
freetype 2.11.1 里根本没有这个符号，是2.12新加的，重新编译一下freetype吧

**Comment by midstreeeam** [comment]
编译通过了，感谢大佬！
