### ISSUE TITLE
CMake Error 第一次整这个不是很明白

### ISSUE THREAD

**Issue by yehuoshun** [Fluorohydride/ygopro#2473]
CMake Error at E:/Tool/developTool/CLion 2022.2.4/bin/cmake/win/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibEvent (missing: LIBEVENT_LIBRARIES LIBEVENT_INCLUDE_DIR)
Call Stack (most recent call first):
  E:/Tool/developTool/CLion 2022.2.4/bin/cmake/win/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/macros/FindLibEvent.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:33 (find_package)

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro/wiki/Windows%E4%B8%8A%E7%BC%96%E8%AF%91
