### ISSUE TITLE
编译的时候出现了一些问题

### ISSUE THREAD

**Issue by yehuoshun** [Fluorohydride/ygopro#2474]
![image](https://user-images.githubusercontent.com/69134831/205004957-584f1dec-e4ba-400b-bc64-fc50c5031be5.png)

**Comment by yehuoshun** [comment]
![image](https://user-images.githubusercontent.com/69134831/205005065-c28ef86c-5b04-4e81-9745-813632b66450.png)

**Comment by mercury233** [comment]
FreeType必须使用2.11.1或更早的版本，更近的版本是坏的，见 https://gitlab.freedesktop.org/freetype/freetype/-/issues/1146
