### ISSUE TITLE
ygopro core chain issue 

### ISSUE THREAD

**Issue by mrboots123** [Fluorohydride/ygopro#2483]
Not sure if this is the correct behavior but when using the ygopro core directly triamid chain effects are not shown when msg_select_chain resolves.  All other chain effects except the triamid effects seem to be included in msg_select_chain. im not sure if this is due to the ygo core sending incorrect information or the way im consuming the data. here is a video showing other chains resolving but not triamid.

https://user-images.githubusercontent.com/3998349/212788689-9021a046-a6e5-4d1e-b47e-5ac800c5a984.mp4

**Comment by mercury233** [comment]
But I can't see any field spell with other name in your screen record

**Comment by mrboots123** [comment]
> But I can't see any field spell with other name in your screen record

I think you are right! i could not replicate the issue with the other triamid cards. thank you :)
