### ISSUE TITLE
申请添加一个新功能，请过目。

### ISSUE THREAD

**Issue by yybbwc** [Fluorohydride/ygopro#2488]
现状：在残局模式中选择某个残局后，“主要信息”处不会显示残局里有多少张效果卡。

申请功能：让在残局模式中选择某个残局后，“主要信息”处可以自动统计并显示残局里有多少张效果卡。

益处：残局作者在做残局时，可以借此参数来帮助调整残局里的效果卡的数量，再也不用人工数数了。而残局玩家可以靠此参数初步判断残局难度。

补充：印卡残局也只需要统计残局开始时残局里的效果卡数量。本质上，印卡残局相当于多了一张能印卡的效果卡。在印卡残局中会多次发动印卡的效果，但它其实还只是来源于一张卡的效果。

**Comment by mercury233** [comment]
效果卡指的是什么？

**Comment by yybbwc** [comment]
> 

就是“有效果的卡”。像“青眼究极龙”就没有效果。纯粹的通常怪兽也没有效果。

**Comment by yybbwc** [comment]
> 

就是“有效果的卡”。像“青眼究极龙”就没有效果。纯粹的通常怪兽也没有效果。

**Comment by purerosefallen** [comment]
Could you explain why this feature is useful to players?

**Comment by yybbwc** [comment]
> 

“做游戏王残局，效果卡的张数有两个门槛，一个是15张，一个是30张。

15张效果卡以下，也有一批优秀的残局，这证明了在15张效果卡以下也能制作优秀的残局。但15张效果卡以下的残局一般只能把大部分卡放在我方，少数卡放在对方，相当于无形中削弱了对方。于是这一制作残局的方法也被称为自闭流。

30张效果卡以下的局能把更多的卡片分配给对方，形成棋逢对手的局面。相比于15卡门槛，30卡得到了更多的卡片补充，不仅全方位的提升了残局的可玩性，还保留了较好的可读性。

而超过30张效果卡的残局，不是不能有，但一定得是高水平的残局。”

所以，如果能自动统计并显示残局里的效果卡数量，残局作者将能更好的设计不同层次的残局。

残局玩家也可以借这个参数来初步判断这个残局的难度。比如，效果卡数超过30张的残局就是难局，新手将不会轻易去碰触它。比如，效果卡数在15张以下，新手将更喜欢玩这种可读性较好的残局。

**Comment by yybbwc** [comment]
> 

“做游戏王残局，效果卡的张数有两个门槛，一个是15张，一个是30张。

15张效果卡以下，也有一批优秀的残局，这证明了在15张效果卡以下也能制作优秀的残局。但15张效果卡以下的残局一般只能把大部分卡放在我方，少数卡放在对方，相当于无形中削弱了对方。于是这一制作残局的方法也被称为自闭流。

30张效果卡以下的局能把更多的卡片分配给对方，形成棋逢对手的局面。相比于15卡门槛，30卡得到了更多的卡片补充，不仅全方位的提升了残局的可玩性，还保留了较好的可读性。

而超过30张效果卡的残局，不是不能有，但一定得是高水平的残局。”

所以，如果能自动统计并显示残局里的效果卡数量，残局作者将能更好的设计不同层次的残局。

残局玩家也可以借这个参数来初步判断这个残局的难度。比如，效果卡数超过30张的残局就是难局，新手将不会轻易去碰触它。比如，效果卡数在15张以下，新手将更喜欢玩这种可读性较好的残局。

**Comment by mercury233** [comment]
先不说这种根据“效果卡”数量给残局分类的理论的合理性
一个残局里有多少张卡，点开就能看到，何必非要显示在外面
要显示的话，更应该显示在发布残局的地方，因为下载安装残局是相对麻烦的过程，点开残局是非常简单的过程
所以我觉得如果你要推广这套理论，应该先想办法让残局作者把“效果卡”数量标在残局名和简介里
而这样标注之后，软件再单独做一套读取卡片数量的功能就是毫无必要的了
