### ISSUE TITLE
改写暴君龙94568601的特殊召唤代价引发的bug

### ISSUE THREAD

**Issue by lostname3210** [Fluorohydride/ygopro#2497]
1.叠放R4
2.时间潜行cost一个超量素材A，特招自身
3.黑洞
4.死者苏生拉R4，R4特殊召唤代价选墓地1张卡作为超量素材（特殊召唤代价见：暴君龙 94568601）
   此时，若选择A，客户端看不见A作为超量素材。若此时一体叠放R5，客户端闪退。若此时发动墓地的，时间潜行者表圈潜艇的效果：去除超量素材特招，也会闪退。
   若选择A以外的卡叠放，则不会出现这种情况。
[pro闪退.zip](https://github.com/Fluorohydride/ygopro/files/11779497/pro.zip)
--R4
function c20230620.initial_effect(c)
	--xyz summon
	aux.AddXyzProcedure(c,nil,4,2)
	c:EnableReviveLimit()
	--spsummon cost
	local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_SINGLE)
	e0:SetCode(EFFECT_SPSUMMON_COST)
	e0:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_SINGLE_RANGE)
	e0:SetRange(0xff)
	e0:SetCost(c20230620.spcost)
	e0:SetOperation(c20230620.spcop)
	c:RegisterEffect(e0)
end
function c20230620.spcost(e,c,tp)
	return Duel.IsExistingMatchingCard(nil,tp,LOCATION_GRAVE,0,1,e:GetHandler())
end
function c20230620.spcop(e,tp,eg,ep,ev,re,r,rp)
	local g=Duel.SelectMatchingCard(tp,nil,tp,LOCATION_GRAVE,0,1,1,e:GetHandler())
	Duel.Overlay(e:GetHandler(),g)
end

**Comment by salix5** [comment]
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=5333&request_locale=ja
■『このカードを他のカードの効果によって墓地から特殊召喚する場合、そのプレイヤーは自分フィールド上に存在するドラゴン族モンスター１体をリリースしなければならない』は効果の扱いではありません。（「タイラント・ドラゴン」自身をカードの効果によって墓地から特殊召喚する際に必要な手順となります。自分のモンスターゾーンにリリースできるドラゴン族モンスターが存在しない場合、「タイラント・ドラゴン」をカードの効果によって墓地から特殊召喚する事はできません。）

https://yugioh-wiki.net/index.php?%A1%D4%A5%BF%A5%A4%A5%E9%A5%F3%A5%C8%A1%A6%A5%C9%A5%E9%A5%B4%A5%F3%A1%D5
Ｑ：裏側守備表示で墓地から特殊召喚した場合にもリリースは必要ですか？
Ａ：必要です。
　　墓地から特殊召喚する直前にリリースするため召喚後が表向きか裏向きかは関係ありません。

EFFECT_SPSUMMON_COST
主要用於特殊召喚執行之前的行動
（暴君龍等等

因此
> 4.死者苏生拉R4，R4特殊召唤代价选墓地1张卡作为超量素材（特殊召唤代价见：暴君龙 94568601）

這步是不合理的行動
此時R4還在墓地
不能添加超量素材

**Comment by lostname3210** [comment]
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=5333&request_locale=ja ■『このカードを他のカードの効果によって墓地から特殊召喚する場合、そのプレイヤーは自分フィールド上に存在するドラゴン族モンスター１体をリリースしなければならない』は効果の扱いではありません。（「タイラント・ドラゴン」自身をカードの効果によって墓地から特殊召喚する際に必要な手順となります。自分のモンスターゾーンにリリースできるドラゴン族モンスターが存在しない場合、「タイラント・ドラゴン」をカードの効果によって墓地から特殊召喚する事はできません。）
> 
> https://yugioh-wiki.net/index.php?%A1%D4%A5%BF%A5%A4%A5%E9%A5%F3%A5%C8%A1%A6%A5%C9%A5%E9%A5%B4%A5%F3%A1%D5 Q：如果我在背面防御展示上从墓地特殊召唤，需要释放它吗？ 答：是的。 召唤是面朝上还是面朝下都没有关系，因为它是在墓地的特殊召唤之前释放的。
> 
> EFFECT_SPSUMMON_COST 主要用於特殊召喚執行之前的行動 （暴君龍等等
> 
> 因此
> 
> > 4.死者苏生拉R4，R4特殊召唤代价选墓地1张卡作为超量素材（特殊召唤代价见：暴君龙 94568601）
> 
> 這步是不合理的行動 此時R4還在墓地 不能添加超量素材

我想看相关的源码 请问我该怎么做

**Comment by salix5** [comment]
https://github.com/Fluorohydride/ygopro-core/blob/303ddff9bc3bd33957c295acc3688f7f86b3517a/effect.h#LL301C14-L301C14
Github的追蹤或是Visual Studio的Fina all references
可以找到ocgcore裡面所有出現EFFECT_SPSUMMON_COST的地方

**Comment by lostname3210** [comment]
> https://github.com/Fluorohydride/ygopro-core/blob/303ddff9bc3bd33957c295acc3688f7f86b3517a/effect.h#LL301C14-L301C14 Github的追蹤或是Visual Studio的Fina all references 可以找到ocgcore裡面所有出現EFFECT_SPSUMMON_COST的地方

谢谢你
