### ISSUE TITLE
Vanquish Soul Jiaolong cannot summon itself via it's own effect.

### ISSUE THREAD

**Issue by VforViolin** [Fluorohydride/ygopro#2502]
The effect: "If you reveal a card(s) in the hand to activate a "Vanquish Soul" card's effect (except during the Damage Step): You can Special Summon this card from your hand." does not seem to allow activation after its conditions have been met.

**Comment by mercury233** [comment]
Replay file please

btw, make sure you are using scripts in https://github.com/Fluorohydride/ygopro-pre-script/tree/master/scripts/AGOV-JP , and have scripts in https://github.com/Fluorohydride/ygopro-pre-script/tree/master/scripts/AGOV-JP/old%20cards/018 updated

**Comment by VforViolin** [comment]
Sorry, this was encountered on Dueling Nexus, and since YGO Omega resolved the issue on their simulator on Aug 18, but the issue still persists on Dueling Nexus, they suggested it may be an issue here. I haven't tested it outside of YGO Omega and Dueling Nexus, but the gif of the interaction is below.

https://media3.giphy.com/media/U8ZMM10N745YSxSy7I/giphy.gif
