### ISSUE TITLE
"CallCardFunction"(c101003059.initial_effect): attempt to call an error function, and other similar errors c100221001 c100222001 c100240003 c100407001 c100407002 c100407003 c100407004 c100407030 c100407031 c100407032

### ISSUE THREAD

**Issue by codingnewcode** [Fluorohydride/ygopro#2512]
hello,

i have an error in game replay similar to previous messages in the chinese website.

<img width="1153" alt="ygopro error 101003059" src="https://github.com/salix5/ygopro/assets/155306405/6efc406f-0d36-4569-8a2f-281f5a01fd73">

[2024-02-04 16:42:52][Script Error]: "CallCardFunction"(c101003059.initial_effect): attempt to call an error function

all the replays here: (password: ads-test) https://drive.google.com/file/d/1pW8Z3ytrXsNX1SNnBB9qzCtBrw9XkzfV/view
i also have same error in total with the following:
c100221001.initial_effect): attempt to call an error function
c100222001.initial_effect): attempt to call an error function

c100240003.initial_effect): attempt to call an error function

c100407001.initial_effect): attempt to call an error function
c100407002.initial_effect): attempt to call an error function
c100407003.initial_effect): attempt to call an error function
c100407004.initial_effect): attempt to call an error function

c100407030.initial_effect): attempt to call an error function
c100407031.initial_effect): attempt to call an error function
c100407032.initial_effect): attempt to call an error function

c101003059.initial_effect): attempt to call an error function

i very much like your software and would like to watch my old replays if possible

info: i tried to post on the chinese website but i could not verify phone number in my country so unable to post

thanks,

edit2: fixed replays download link
edit3: fix too
edit4: fix too

**Comment by mercury233** [comment]
You can't watch replays which contain cards you don't have in your data. Even through you have got those data, there is very high chance that something go wrong and error occurs again, because you can't find the compatible scripts and ocgcore.

**Comment by codingnewcode** [comment]
thanks for your quick reply, after looking in one old hard drive and also after much help from the ygopro discord separately

i now found the script file, it was ine the live2017 expansion

i also found that to use expansions they need to be put at the root of expansions folder and not in some subfolder (for example expansions/live2017/script doesnt work but expansions/script should work, this is explained here: https://www.deviantart.com/lorisc93/art/How-to-use-custom-cards-in-YgoPro-822191487

thanks to the help on the discord i found how to use data editor x to create cards, i could create the card in the cdb file but testing is still unfinished (again i dont know much about ygopro specifically but is fun to learn anyways)

then i found the ygopro expansion manager github that is very useful https://github.com/Eronan/YGOPro-Expansion-Manager for searching

i think i have all the data to recreate a functioning with this expansion ygopro, but i have yet to make this work, thanks for all help and if you ahve tips i would lie to know too i mean, thanks,

the script is here for info btw 

<img width="1654" alt="found the lua file" src="https://github.com/Fluorohydride/ygopro/assets/155306405/b6f22946-0840-42c5-875d-e8cc936848d9">

and the expansin description

<img width="743" alt="live2017 info" src="https://github.com/Fluorohydride/ygopro/assets/155306405/5bd514f6-9cce-410e-94bd-fcb7d6e2f8a4">

it seems my config is bit weird caus ei was using an odler verison of the live2017 expansion that is lcoated in the 1.033.A folder of ygopro i had too, but somehow i wa using this in the 1.033.D folder, soemthign lie this possibly, i ahve yet to debug this, so any help or idea appreciated, thanks, to be conitnued

**Comment by codingnewcode** [comment]
edit: updated the message above

**Comment by codingnewcode** [comment]
i have now new erros, the card is recognized without having to add it in the cdb file, but i have yet to understand how this all works, to be continued..

<img width="890" alt="card detected now" src="https://github.com/Fluorohydride/ygopro/assets/155306405/b5f2d1fe-acbd-4d9c-8ece-29f061c39030">
<img width="890" alt="errors2" src="https://github.com/Fluorohydride/ygopro/assets/155306405/d5a23f6c-bbd1-4af1-8a27-ebbac7d3b472">

**Comment by codingnewcode** [comment]
<img width="1137" alt="errorlog2 1" src="https://github.com/Fluorohydride/ygopro/assets/155306405/2a36e615-7793-44ab-9267-4cd27b915069">
<img width="1135" alt="errorlog2 2" src="https://github.com/Fluorohydride/ygopro/assets/155306405/dd6814c9-bf40-4f9d-9365-3390247e7f49">
<img width="1362" alt="one error vs code after live2017 add scripts" src="https://github.com/Fluorohydride/ygopro/assets/155306405/95d7a076-9047-415d-ba5b-db7984fabffd">
