### ISSUE TITLE
Laval Warrior's effect activation

### ISSUE THREAD

**Issue by buh6173** [Fluorohydride/ygopro#259]
His effect can only be activated and resolved if there are 4 or more Laval monsters in the Graveyard. If this is not the case, though, his effect is still activated, just negated. It should not activate at all.

**Comment by DailyShana** [comment]
The ruling is different in OCG
>Ｑ：相手モンスターを戦闘破壊した時、自分の墓地にラヴァルが４種類以上存在しない場合でもチェーンブロックを作りますか？
Ａ：はい、作ります。（10/08/16）
http://yugioh-wiki.net/?%A1%D4%A5%E9%A5%F4%A5%A1%A5%EB%A1%A6%A5%A6%A5%A9%A5%EA%A5%A2%A1%BC%A1%D5
