### ISSUE TITLE
please do this, sorry because i don't know where the forum of this 

### ISSUE THREAD

**Issue by xyzzone** [Fluorohydride/ygopro#288]
i just give my comment for this game.. i suggest that 1) change this game to website like Dueling Network because DN only have one duel channel for players to find players easily ! 2) add invite friend into room or friend list,chat ! 3) card animation to attract more players ! 4) no more and thank you for this game

**Comment by IceYGO** [comment]
1) This is not possible, we cannot change a C++ application into a web application without reprogramming everything.
2) YGOPro is an application, not an online server or a community.
3) Animations require animators and a lot of scripting. If you can find someone willing to do this, feel free to ask him to open a pull request.

**Comment by Zayelion** [comment]
1.) As I discussed with everyone working on the project before, to go to a web application the network system needs to be refined and separation of concerns added to `duelclient.cpp`.
2.) You are avoiding his "why", @xyzzone, DevPro, Percy, Dawn, and Salvation each have server side variants to work with YGOPro to provide those extra features you are asking for, use one of those variants or as their developers to add the features you need.
3.) I believe animations can be added in the future via launchers, I'll add a feature request explaining it in the future.
