### ISSUE TITLE
Official Ruling ::Manual Hand Shuffling

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro#292]
"Players may shuffle the cards in their hands, unless a condition exist due to a card effect, etc. that would prohibit  them from doing so." - Julia

https://dl.dropbox.com/u/90837170/hand_shuffling.PNG

and a letter

Subject: Re: [Ticket#2012100910000174] TCG Ruling Question
Date: Tue, 9 Oct 2012 13:54:44 +0200
To: -------------------.com
From: yugioh@konami-europe.net

Dear -----------,

Thank you very much for contacting the Konami Support Team.

Shuffling your hand is legal. It can be done as many times per turn as you want, but you should keep in mind that you still need to play at a reasonable pace. If you are doing nothing to advance the game and instead spend an unreasonable amount of time shuffling and reshuffling your hand, this might be considered Slow Play or Stalling. In an official tournament, such behaviour might lead to penalties.

Best regards,

Your Konami Support Team

Konami Digital Entertainment GmbH
Berner Str. 103-105
60437 Frankfurt am Main
Germany

Local Court of Frankfurt am Main: HRB Nr. 24990 
Managing Director: Shinji Hirano, Fumiaki Tanaka

 <--------------.com> schrieb:
Dear Konami,

Me and my friends have had some debates lately regarding manual hand shuffles (shuffling the card order in your hand). It is done by many players worldwide, but it is not mentioned in the Official Rulebook that this is actually a legal action.

So I am sending you this e-mail with the question: "Are manual hand shuffles allowed during a duel or not? If so, how many times are they allowed to shuffle their hands per turn?"

I added the 2nd part of the question, since in the official Yu-Gi-Oh! Online DUEL ACCELERATOR game, you were only allowed to shuffle your hand once per turn.

I hope you could shed some light on this issue for me and my friends.

Yours sincerely,

x----------

There was a heated debate in the TDOANE main chat over the course of the last few days about the rulings on hand shuffling, and after speaking with the top official TCG judge Julia the above response was acquired, and the following concluded.

A control be it a key press or button should be available during the Main Phase 1 or 2 that allows the hand to be shuffled. This 'action' should not reset the timer. 

Personally I do not care; passing the word along, I understand that you have stopped work on the GUI, but it is still used by over 6000 people.

**Comment by IceYGO** [comment]
Since the feature is now implemented, I am closing this.
