### ISSUE TITLE
Abyssphere and Trap Stun

### ISSUE THREAD

**Issue by Seikah** [Fluorohydride/ygopro#359]
It was recently ruled that Abyssphere, under Trap Stun, will not destroy itself, and stay face-up until it is destroyed through other means, (preventing the owner of Abyssphere from using spells).

Currently, Abyssphere destroys itself regardless of negation. Trap Stun does not expire in the end phase, so it should not behave like this.

**Comment by DailyShana** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12602&keyword=&tag=-1
