### ISSUE TITLE
SWAP FROG NEEDS FIXING. IT IS BROKEN.

### ISSUE THREAD

**Issue by Starstrike** [Fluorohydride/ygopro#387]
"The third effect is back monster because there is no limitation to, Summoned at triggering the effect with a monster that I do well with."

There is no limitation to returning the monster to hand for the third effect.

This needs to be fixed, Fluorohydride. You are breaking the game and causing problems for a lot of people who want to use this card on any of the YGOPro systems. There is nothing on that japanese page that says you cannot keep returning Swap Frog to the hand. You can only gain 1 additional summon per turn, but you can keep paying the cost to return it to the hand as much as you want.

You really need to fix this.

I really dont want to have to keep opening an issue about this, but the card needs to be fixed. There is no ruling change that you can't keep bouncing it to the hand. You can only gain 1 additional normal summon if you use Double Summon but you can play 3 of them in the same turn if you really want to. You just only gain 1 summon.

So, please. Fix this card so people can stop complaining that it's broken.

**Comment by DailyShana** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=43&keyword=&tag=-1
