### ISSUE TITLE
Tailor of the Fickle not working w/ Dark Necrofear

### ISSUE THREAD

**Issue by NoroiKisaragi** [Fluorohydride/ygopro#390]
Official Ruling:

Dark Necrofear: "Tailor of the Fickle" or "Collected Power" can be used to move "Dark Necrofear" from one monster to another after it is an Equip Spell Card. "Fairy's Hand Mirror" or "Shift" cannot be used when "Dark Necrofear" first becomes an Equip Spell Card and is equipped to your opponent's monster.

It's a legal, legit play. However, when I had Tailor of the Tickle set, it was not letting me activate it at all during the match even as I had Dark Necrofear in play attached to a monster. It was a ranked match and the glitch greatly affected the outcome of the duel.

Did not give me the option to activate Tailor of the Fickle to reattach dark necrofear at any point. Not even an activation prompt appeared.

Replay, happens at the very end (costs us the duel): https://dl.dropbox.com/u/77596770/tailor%20of%20the%20fickle.yrp

**Comment by DailyShana** [comment]
>Ｑ：《ダーク・ネクロフィア》が効果により相手モンスターＡに装備されており、Ａが自分フィールド上にいる際にＡを対象に《サンダー・ブレイク》や《雷の裁き》等が発動され、それにチェーンをし《移り気な仕立屋》や《力の集約》等を発動しＡに装備された《ダーク・ネクロフィア》を相手モンスターＢに移し替えた時、どのような処理が行われますか？
Ａ：《ダーク・ネクロフィア》を対象にして《移り気な仕立屋》を発動する事はできません、また《力の集約》の効果で《ダーク・ネクロフィア》を他のモンスターに移し替えた場合、対象が正しくない装備カードとして破壊されます。(15/06/08)
http://yugioh-wiki.net/index.php?%A1%D4%A5%C0%A1%BC%A5%AF%A1%A6%A5%CD%A5%AF%A5%ED%A5%D5%A5%A3%A5%A2%A1%D5=
