### ISSUE TITLE
有关irr的linux的中文支持问题

### ISSUE THREAD

**Issue by ssfdust** [Fluorohydride/ygopro#683]
Fluorohydride（不知道怎么叫）
我在网络上看见了一个实现支持xim的补丁版的irr1.7.1，不过我不知道你在哪个文件里面写的irr中文支持，我想试试看修改那个文件来仿照补丁版的irr1,.7实现linux的中文输入问题。

**Comment by behind1231** [comment]
我想问一下,linux下如何安装这程序？
