### ISSUE TITLE
Do a Barrel Roll bug

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#728]
1. The only monster i control was "Mecha Phantom Beast Token" and "Do a Barrel Roll" was set. "Brotherhood of the Fire Fist - Bear" attacked my "Mecha Phantom Beast Token" and try to use it's search effect during battle step, but i can still activate "Do a Barrel Roll" (my only "Mecha Phantom Beast Token" was destroyed by "Brotherhood of the Fire Fist - Bear")

2. If both players have all five pieces of "Exodia the Forbidden One" in their hands at the start of the Duel, then the Duel ends in a DRAW.

**Comment by salix5** [comment]
fixed
Thank you.
