### ISSUE TITLE
Luminous Dragon Ritual

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#884]
If you activate "Cost Down" and make "Paladin of Photon Dragon" in your hand level 2, you can banish "Luminous Dragon Ritual" and monsters whose total Levels equal 2 to Ritual Summon "Paladin of Photon Dragon" in your hand. (But the card text says "banish monsters from your Graveyard whose total Levels equal exactly 4")

**Comment by salix5** [comment]
a13462df9ce892a116e85ec3cafc3b8f0e1edc5d
fixed
