### ISSUE TITLE
Do a Barrel Roll bug again

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#897]
The only monster i control was "Mecha Phantom Beast Token" and "Do a Barrel Roll" was set. "Airknight Parshath" attack my "Mecha Phantom Beast Token" and try to use it's drawing effect during battle step, but i can still activate "Do a Barrel Roll" (my only "Mecha Phantom Beast Token" was destroyed by "Brotherhood of the Fire Fist - Bear") to negate it.

遊戯王OCG事務局です。

いつも遊戯王オフィシャルカードゲームをお楽しみいただき誠にありがとうございます。
ゲームルールについてお問い合わせいただいた件、下記のとおりご案内申し上げます。

Q.
《天空騎士パーシアス》との戦闘で「幻獣機トークン」が破壊された場合、その後の《天空騎士パーシアス》の効果にチェーンをしてその戦闘で破壊された「幻獣機トークン」をリリースして《弾幕回避》を発動できますか？
A.
戦闘で破壊が決まっている「幻獣機トークン」を「弾幕回避」のコストにリリースする事はできません。
したがって、他に「幻獣機トークン」が存在しない場合、「弾幕回避」を発動する事はできません。

**Comment by salix5** [comment]
be9409d599efafafbcb4d30d9b28e478159abf78
fixed
Thank you.
