### ISSUE TITLE
Last Turn 2nd Battle Phase implementation

### ISSUE THREAD

**Issue by MichaelLawrenceDee** [Fluorohydride/ygopro#926]
Just tested this yesterday with the AI and checked the rulings today and the tips page.
http://yugioh.wikia.com/...i/Card_Rulings:Last_Turn
http://yugioh.wikia.com/wiki/Card_Tips:Last_Turn

I used Invader "A" in a Duel with the AI. I wasn't able to take control of my opponent's monster. In Tag Force series, it enters a Battle Phase, activate Invader "A", end of Battle Phase, take control, opponent normally continues its turn, (can even enter the Battle Phase again) but here, it's not working.

Please implement a 2nd Battle Phase. An Unfortunate Report's 2nd Battle Phase implementation doesn't work on this, btw.

**Comment by shadowfox87** [comment]
Hey MLD, it's me AM. Why not Mischief of the Time Goddess to skip your opponent's turn to repeat the 2nd Battle Phase? Nothing is lost really since neither player drew a card in the draw phase.

**Comment by MichaelLawrenceDee** [comment]
Skipping the opponent's turn for a 2nd Battle Phase would mean an additional summon as well as cards that may apply "except the turn it is sent to the Graveyard" and many more..
