### ISSUE TITLE
Able to bypass effect cost

### ISSUE THREAD

**Issue by sidschingis** [Fluorohydride/ygopro#932]
It is currently possible to bypass the cost of an effect if multiple effects with the same cost are triggered at the same time while only being able to pay for one  (See the duel puzzle in the link).

https://www.dropbox.com/s/dtjn5393ekc86rd/test.lua?dl=0

How to Repro:

1. Activate Soul Charge targeting both Mermail Monsters
2. Activate both effects

The second effect will activate and resolve even though there will be no card to discard left.

**Comment by salix5** [comment]
acb48d40ce97a92c91492249664dedac016c07b9
fixed
Thank you.
