### ISSUE TITLE
"Noble Knight Medraut" bug

### ISSUE THREAD

**Issue by treepiece** [Fluorohydride/ygopro#939]
When "Noble Knight Medraut" equipping "Noble Arms" use special summoning effect, and chain the "Call of the Haunted" to summon "Fossil Dyna Pachycephalo". "Noble Knight Medraut" cannot special summon "Noble Kinght" monster but u still have to destroy the "Noble Arms".

Ｑ：このカードの効果の発動にチェーンして《リビングデッドの呼び声》を発動され《フォッシル・ダイナ パキケファロ》を特殊召喚されました。
　この場合装備魔法を破壊する処理は行われますか？
Ａ：いいえ、行われません。(13/05/22)

**Comment by salix5** [comment]
fixed
