### ISSUE TITLE
Lack of License

### ISSUE THREAD

**Issue by fhnstephen** [Fluorohydride/ygopro#952]
I am currently starting to build a duel system for weiβ schwarz (another TCG). I found that this project is awesome and I want to build my system based on it. But there isn't any license attached to it. I wonder if you can provide a license for it.

**Comment by adrianojn** [comment]
cc @Fluorohydride @VanillaSalt @salix5 @woodee 

Since the repository has over 190 forks is important to have a license.

[choosealicense.com](http://choosealicense.com/)

**Comment by Zayelion** [comment]
I know @zh99998  brought this issue up before. An answer would be nice, people are calling the software illegal.

If it is MIT, nothing changes as we put idiots to rest.
If it is GPL then the other software like Percy and Percy's version are required to become opensource, opponents of the projects believe it is GPL

Apache would work for the current external development teams.
